### ISSUE TITLE
Endpoint management in CH4

### ISSUE THREAD

**Issue by halimamer** [pmodels/mpich#2391]
#3356 handles the creation and management of VCIs inside the netmods and exposing it to CH4.  This issue handles the remaining pieces as listed below (updated based on discussion on #3356):

 - [ ] Have one or more communicators/windows/files map to a single WorkQ.  More serialization affects enqueue rate.
 - [ ] Multiple WorkQ setup, where one or more WorkQs can map to a single VCI.  More concurrency affects progress/completion rate.

**Comment by mblockso** [comment]
Just want to point out that if we start with "symmetric" send-recv endpoints then we are *forced* to only support 1 endpoint per communicator. If a communicator is associated with more than one endpoint (read: rx context) then to which endpoint would a tagged receive be posted? Posting to different endpoints when ANY_SOURCE is enabled would mess up hardware tag matching.

**Comment by mblockso** [comment]
Er .. I should clarify that we could have more than one endpoint per communicator, but we could only have one endpoint that is used for tagged receive operations. We could still split out the different data flows (rma, am, etc) into multiple endpoints.

**Comment by hfujita** [comment]
Right... when I did a simple experiment using multiple contexts, I wrote in a way that tagged send went to receive context with index zero, and the tagged receive was posted to it. We could do it inside OFI netmod as well (tagged send always goes to zero or any predefined index, and CH4 is supposed to post a receive to that index), but it sounds like ad-hoc a little bit.

**Comment by halimamer** [comment]
Agreed, that's the limitations of this initial design.

**Comment by raffenet** [comment]
See #2405

**Comment by hajimefu** [comment]
Not sure what the best way to initiate a discussion is, but I think CH4 init should be able to say "give me as many endpoints as you can" when calling netmod init. Perhaps by passing zero or negative value.

**Comment by halimamer** [comment]
We can define a macro for that. The name will carry meaning and the value can be changed without breaking the code in the future. For the value, a negative value, zero, or INT_MAX, I am fine with any of them.

**Comment by Bayyapu** [comment]
Issue #3356 supersedes this issue and hence closing this.

**Comment by pavanbalaji** [comment]
No, we decided to leave both open and split them to handle specific pieces.
