### ISSUE TITLE
bug: MPIIO test failure with static build of 3.3a2 on OSX

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#2436]
I see the following failure on OSX with static build of mpich-3.3a2 - but not shared library build

```
balay@ipro^~/petsc(next) $ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.12.1
BuildVersion:   16B2555
balay@ipro^~/petsc(next) $ xcodebuild -version
Xcode 8.1
Build version 8B62
balay@ipro^~/petsc(next) $ cat conftest.c 
#include <mpi.h>
int main() {
  MPI_File fh;
  MPI_Info info;
  if (MPI_File_close(&fh));
  return 0;
}
balay@ipro^~/petsc(next) $ ./arch-mpich-alpha-shared/bin/mpicc conftest.c 
conftest.c:5:27: warning: if statement has empty body [-Wempty-body]
  if (MPI_File_close(&fh));
                          ^
conftest.c:5:27: note: put the semicolon on a separate line to silence this warning
1 warning generated.
balay@ipro^~/petsc(next) $ echo $?
0
balay@ipro^~/petsc(next) $ ./arch-mpich-alpha/bin/mpicc conftest.c 
conftest.c:5:27: warning: if statement has empty body [-Wempty-body]
  if (MPI_File_close(&fh));
                          ^
conftest.c:5:27: note: put the semicolon on a separate line to silence this warning
1 warning generated.
Undefined symbols for architecture x86_64:
  "_romio_onesided_always_rmw", referenced from:
      _ADIOI_OneSidedWriteAggregation in libmpi.a(onesided_aggregation.o)
  "_romio_onesided_no_rmw", referenced from:
      _ADIOI_OneSidedWriteAggregation in libmpi.a(onesided_aggregation.o)
  "_romio_read_aggmethod", referenced from:
      _ADIOI_OneSidedReadAggregation in libmpi.a(onesided_aggregation.o)
  "_romio_write_aggmethod", referenced from:
      _ADIOI_OneSidedWriteAggregation in libmpi.a(onesided_aggregation.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
balay@ipro^~/petsc(next) $ echo $?
1
balay@ipro^~/petsc(next) $ 

```

**Comment by balay** [comment]
Attaching config.log for the corresponding static and shared builds.
[config-static.log.txt](https://github.com/pmodels/mpich/files/602344/config-static.log.txt)
[config-shared.log.txt](https://github.com/pmodels/mpich/files/602345/config-shared.log.txt)

**Comment by raffenet** [comment]
@balay do you know when this last worked? I also notice issues with `--disable-weak-symbols --disable-shared` on Linux.

**Comment by balay** [comment]
We default to mpich-3.2 on OSX and have not upgraded to 3.3a2 - due to this issue ( petscbot message above points to the relavent change in petsc)

**Comment by balay** [comment]
BTW: This issue still exists in mpich master a5abbc0

**Comment by hzhou** [comment]
@balay Could reconfirm this issue with MPICH 4.0?

**Comment by balay** [comment]
Sorry - I'm unable to build build mpich-4.0 to test - due to https://github.com/pmodels/mpich/issues/5791

**Comment by hzhou** [comment]
> Sorry - I'm unable to build build mpich-4.0 to test - due to #5791

Of course. https://github.com/pmodels/mpich/pull/5795 should fix it. Maybe you can try that patch?

**Comment by balay** [comment]
Can you point me to instructions to build MPICH from git? Or do you a patch that I can apply to relase tarball?

**Comment by hzhou** [comment]
https://patch-diff.githubusercontent.com/raw/pmodels/mpich/pull/5795.patch should give you the patch. I think it should apply cleanly to the 4.0 tarball. You may need manually delete the meta data at the beginning of the patch file.

**Comment by balay** [comment]
Thanks! I still get build errors:
```
  CCLD     src/env/mpivars/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/.libs/libmpifort.a(mpi_base.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/.libs/libmpifort.a(mpi_base.o) has no symbols
Undefined symbols for architecture x86_64:
  "_MPIR_CVAR_CHOP_ERROR_STACK", referenced from:
      _MPIR_Err_stack_init in libpmpi.a(lib_libpmpi_la-errutil.o)
      _MPIR_Err_print_stack_string in libpmpi.a(lib_libpmpi_la-errutil.o)
  "_MPIR_CVAR_COREDUMP_ON_ABORT", referenced from:
      _MPID_Abort in libpmpi.a(lib_libpmpi_la-mpid_abort.o)
  "_MPIR_CVAR_DATALOOP_FAST_SEEK", referenced from:
      _segment_seek in libpmpi.a(lib_libpmpi_la-segment.o)
  "_MPIR_CVAR_PRINT_ERROR_STACK", referenced from:
      _ErrGetInstanceString in libpmpi.a(lib_libpmpi_la-errutil.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by hzhou** [comment]
> Thanks! I still get build errors:
> 
> ```
>   CCLD     src/env/mpivars/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/.libs/libmpifort.a(mpi_base.o) has no symbols
> /Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/.libs/libmpifort.a(mpi_base.o) has no symbols
> Undefined symbols for architecture x86_64:
>   "_MPIR_CVAR_CHOP_ERROR_STACK", referenced from:
>       _MPIR_Err_stack_init in libpmpi.a(lib_libpmpi_la-errutil.o)
>       _MPIR_Err_print_stack_string in libpmpi.a(lib_libpmpi_la-errutil.o)
>   "_MPIR_CVAR_COREDUMP_ON_ABORT", referenced from:
>       _MPID_Abort in libpmpi.a(lib_libpmpi_la-mpid_abort.o)
>   "_MPIR_CVAR_DATALOOP_FAST_SEEK", referenced from:
>       _segment_seek in libpmpi.a(lib_libpmpi_la-segment.o)
>   "_MPIR_CVAR_PRINT_ERROR_STACK", referenced from:
>       _ErrGetInstanceString in libpmpi.a(lib_libpmpi_la-errutil.o)
> ld: symbol(s) not found for architecture x86_64
> ```

Thanks! I'll investigate it. However, this is a different error (albeit the same linking error) from the original ticket.

**Comment by hzhou** [comment]
@balay Add `-fno-common` should fix all this static linking issue. Fundamentally I believe it is either broken `clang`, or broken `ar`, or broken `ld` on osX. I'll see if we can easily detect this issue in configure.

**Comment by hzhou** [comment]
A quick test shows both `gcc` on linux and `clang` on mac produce common symbols, so that is not fundamentally broken. It must be `ranlib` or the linker then.

**Comment by balay** [comment]
yeah - we [petsc] use `ranlib -c` on mac

**Comment by hzhou** [comment]
Do you patch libtool? Or maybe you guys don't use libtool at all?

**Comment by hzhou** [comment]
> yeah - we [PETsc] use `ranlib -c` on mac
> 
> But I guess MPICH didn't need this in earlier versions..

Well, this ticket has been open for 5 years. There was an early comment that MPICH patch individual global symbols to avoid common symobles, a very hacky fix.

**Comment by balay** [comment]
> Do you patch libtool? Or maybe you guys don't use libtool at all?

We don't use libtool. Our configure is in python - and does a check for 'ranlib -c' before using it.

> Well, this ticket has been open for 5 years

Ah yes. this issue was previously confined to MPI-IO usage. Now it breaks at build time.

**Comment by balay** [comment]
> Add -fno-common to CFLAGS should fix all this static linking issue.

This also worked.
