### ISSUE TITLE
BGQ: OFI Scalable Endpoints implementation associated with hang in MPI_Win_lock

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2438]
There seems to be a problem with the current state of the ofi scalable endpoints implementation on BGQ when doing passive RMA.  The simple 2-proc `osu_put_latency` test hangs (`MPI_Put` from proc 0 to window on proc 1) in the `MPI_Win_lock(MPI_LOCK_SHARED, 1, 0, win)` call.  After tracing the code It looks like `ch4` has implemented the `MPI_Win_lock` using active messages with callbacks.  This is the main loop from `ch4` when it waits with a progress loop on the remote lock to get set in `src/mpid/ch4/netmod/ofi/ofi_win.h`:

```
#define FCNAME MPL_QUOTE(FUNCNAME)
static inline int MPIDI_NM_mpi_win_lock(int lock_type, int rank, int assert, MPIR_Win * win)
{
    int mpi_errno = MPI_SUCCESS;

    MPIR_FUNC_VERBOSE_STATE_DECL(MPID_STATE_NETMOD_OFI_WIN_LOCK);
    MPIR_FUNC_VERBOSE_ENTER(MPID_STATE_NETMOD_OFI_WIN_LOCK);

    MPIDI_CH4U_win_sync_lock *slock = &MPIDI_CH4U_WIN(win, sync).lock;
    MPIDI_CH4U_EPOCH_CHECK_TYPE(win, mpi_errno, goto fn_fail);

    if (rank == MPI_PROC_NULL)
        goto fn_exit0;

    MPIDI_OFI_win_control_t msg;

    msg.type = MPIDI_OFI_CTRL_LOCKREQ;
    msg.lock_type = lock_type;

    mpi_errno = MPIDI_OFI_do_control_win(&msg, rank, win, 1, 1);

    if (mpi_errno != MPI_SUCCESS)
        MPIR_ERR_SETANDSTMT(mpi_errno, MPI_ERR_RMA_SYNC, goto fn_fail, "**rmasync");

    MPIDI_OFI_PROGRESS_WHILE(!slock->remote.locked);


The only code that will set it is in  src/mpid/ch4/netmod/ofi/util.c:

static inline void MPIDI_OFI_win_lock_ack_proc(const MPIDI_OFI_win_control_t * info,
                                               MPIR_Win * win, unsigned peer)
{
    if (info->type == MPIDI_OFI_CTRL_LOCKACK)
        MPIDI_CH4U_WIN(win, sync).lock.remote.locked = 1;
    else if (info->type == MPIDI_OFI_CTRL_LOCKALLACK)
        MPIDI_CH4U_WIN(win, sync).lock.remote.allLocked += 1;
}
```

Which is called by this MPIDI_OFI_control_handler set for the target callbacks here in the active message section of MPIDI_OFI_init_generic:

```
MPIDI_Global.target_msg_cbs[MPIDI_OFI_INTERNAL_HANDLER_CONTROL] = MPIDI_OFI_control_handler;
```

So the problem Is the callback is registered but never actually called hence the remote lock is never set.  Tracing the rfifo_poll's on the target it appears the message from the origin is never received hence there is no ack to run the callback on the origin and lock the window.

**Comment by raffenet** [comment]
@pkcoff Is this still an issue?

**Comment by pavanbalaji** [comment]
Closing this till we hear back from @pkcoff.
