### ISSUE TITLE
Document the lock handoff protocol in progress routines

### ISSUE THREAD

**Issue by halimamer** [pmodels/mpich#2441]
Device implementations, e.g., CH4, can implement differently thread safety depending on whether or not releasing a lock occurs in progress routines (e.g., `MPID_Progress_wait`, `MPID_Progress_test`). CH3 assumes **blocking** routines to potentially release a lock (to avoid blocking other threads) while **nonblocking** routines should not release a lock (`MPID_Progress_test`). We need to revisit the code and verify that this assumption is valid, document it properly, and **enforce it on each device implementation**.

**Comment by halimamer** [comment]
The second aspect of this problem are the semantics of `MPID_Progress_test` and `MPID_Progress_wait`. The intent is that the former behaves like `MPI_Testsome` and the latter as `MPI_Waitsome`. From a locking perspective, `MPID_Progress_wait` is required to yield the lock when no progress has been made. This is currently missing in CH4. @charlesarcher has a patch #2442 but it was applied at the wrong place, i.e. at the level of `Progress_test`. It ensures correct behavior but breaks the intent.

**Comment by hzhou** [comment]
Obsolete.
