### ISSUE TITLE
Jenkins build and test for BGQ CH4 OFI

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2445]
With our plans to support MPI3 on BGQ via the Libfabric OFI provider for the next 3 years I think there is merit here to have an  ofi-bgq build for nightly-master-ch4 on Jenkins to ensure that we aren’t broken with all the development going on.  Pavan is supportive of this idea but there are feasibility issues that need to be worked out with Ken.

**Comment by raffenet** [comment]
I had started down this path with @wscullin before pamid was abandoned. It is possible to configure a Jenkins worker inside that LCF firewall that connects back our master server, I think we even have the firewall holes configured already. What is left to do is integration with the job submission system to actually run tests on BG/Q. We should setup a meeting at some point where we can sit together and hack on something until it works.

**Comment by pkcoff** [comment]
That sounds good - I'll be at the lab either next week or the one after I will track down William and schedule something.  Thanks.

**Comment by yfguo** [comment]
The testing for BGQ has been setup.
