### ISSUE TITLE
Remote CQ data size (cq_data_size) from provider being ignored 

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2478]
According to the OFI manual:

>CQ Data Size (cq_data_size)
>Applications may include a small message with a data transfer that is placed directly into a remote completion queue as part of a completion event. This is referred to as remote CQ data (sometimes referred to as immediate data). This field indicates the number of bytes that the provider supports for remote CQ data. If supported (non−zero value is returned), the minimum size of remote CQ data must be at least 4−bytes.

For the `MPIDI_OFI_ENABLE_DATA` path in ch4 it looks like it is always using 8 bytes for the immediate data and is not looking at what the provider is setting in the `cq_data_size` domain attr.  For BGQ this breaks because we currently only have room for 4 bytes, we are therefore setting this `cq_data_size` domain attr to 4 bytes but ch4 is ignoring this and still sending 8.

**Comment by wesbland** [comment]
I'll look in to this. It looks like this is a problem for many providers, not just BGQ.

**Comment by wesbland** [comment]
I have a patch for this incoming, it's going through internal review right now.
