### ISSUE TITLE
CH4/UCX: Hangs in finalize

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2514]
From the looks of it, collective tests periodically hang during `MPI_Finalize` like so - https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ucx/compiler=gnu,jenkins_configure=default,label=ib64/lastCompletedBuild/testReport/(root)/summary_junit_xml/52_____coll_allgatherv2_10/. See that ` No Errors` is correctly output, meaning all processes have finished verifying the correct result of the test.

AM-only configurations of CH4/UCX do not appear to have this problem.

**Comment by LenaO** [comment]
Tracked it down to a deadlock in the final flush for the uct endpoints. For some reason, flushing the shared memory endpoints sometimes returns "UCS_ERR_NO_RESOURCE" forever, so it never finishes - although operations on this endpoint should be finished. 

Next step I try to figure out if it is an UCX bug or an MPICH bug

**Comment by LenaO** [comment]
Finally track it down to bug in ucx/uct shared memory processing.
I created an issue on the UCX repro
[#1304](https://github.com/openucx/ucx/issues/1304)

**Comment by LenaO** [comment]
They fixed the failure in UCX and created a pull request. We will wait until it's in
UCX Pull request: [#1312](https://github.com/openucx/ucx/pull/1312)

**Comment by raffenet** [comment]
https://github.com/openucx/ucx/pull/1312 was merged and our tests look good. Closing.
