### ISSUE TITLE
Reconcile all the enable-direct flags

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2518]
## Problem

There's currently at least two ways to build with support for direct providers:
* `--enable-direct=<prov>` is used when building with an embedded library
* `--with-ch4-netmod-ofi-args=netmod-direct` is used when building with an external library

We should combine these so there is just one way of enabling direct providers to simplify things and avoid confusion.

@pkcoff first encountered this issue with his BG/Q testing.

## Solution

I propose that we combine the two flags into a new one. `--enable-direct` is not namespaced and therefore can be a little confusing. `--with-ch4-netmod-ofi-args` no longer has any other possible arguments other than `netmod-direct` since the capability sets patch got rid of the rest of them.

Given that this is only for the OFI provider, how about `--enable-ch4-ofi-direct-provider`?

### Update

I realized that we still need to have the option of naming the provider for embedded builds. So instead of creating a new flag, how about just renaming the `--enable-direct` flag to `--enable-ch4-ofi-direct-provider=<prov>` and drop the other flag?

**Comment by pkcoff** [comment]
Works for me.
