### ISSUE TITLE
Decouple progess mode setting from ofi_init discussion

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2523]
The BGQ provider supports auto and manual data_progress mode (just manual control progress) and we currently set that as a configure option in our subconfigure via --with-bgq-progress=auto | manual   (so it can compile out and avoid extra branching).    However this is being explicitly set to manual in the ofi_init.

hints->domain_attr->data_progress = FI_PROGRESS_MANUAL;

For now I'm simply ignoring the hint but we should discuss a general solution for decoupling and wrt other providers.

**Comment by raffenet** [comment]
Fixed in #2560.
