### ISSUE TITLE
coll: performance tuning for collectives

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#2529]
The thresholds used within MPICH are very old and need to be refreshed to match what the current state of the networks and processors is.

**Comment by pavanbalaji** [comment]
It will be useful to create a script that goes through the various algorithms and tunes them for a given platform.  That way, we can simply rerun this script every once in a while.  Supercomputer centers can also use this script to tune MPICH for their system specifically.

**Comment by hzhou** [comment]
There is this (very) simplified formula `T = C1 a + C2 b`, where `a` is the overhead cost per transport, and `b` is the transport cost per data size. We can have a discussion on how off is this simplification and what factors we can include to get a better estimate. But anyway, if we can have such empirical formula, then each algorithm can provide its estimated cost dynamically and all we need is a few parameters that characterize a given system and we can have a universal selection logic that works across all collectives.

**Comment by hzhou** [comment]
This is currently being actively researched, but not directly linked to this issue. I am closing this issue now. The project can re-open this issue if they need tracking, hopefully with more relevant background.
