### ISSUE TITLE
ch4/ofi: Limitation on the total number of processes

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#2544]
The current MPICH/CH4/OFI code seems to have a limit of 16 bits for the number of processes it can launch, i.e., around 65536 processes.  This is because we are trying to fit the source rank, tag and communicator context id into a 64-bit integer for fast matching.

There are some options that we can try out to increase the number of ranks that we can support:

1. We can take some bits away from the tag space for source ranks.

2. We can use `FI_DIRECTED_RECV` and immediate data support in OFI to carry the source rank and use the 64-bit space exclusively for the tag and context ID.

3. We can add additional endpoints, so the match bit space is per endpoint.  If each endpoint is responsible for a different set of communicators, we can reduce the number of bits for the context ID and use them for the source rank.

4. For software matching, it is still useful to have the match bits sit in a 64-bit space (so the matching can be done in a single operation), but is not critical.  We can increase this to 128 bits, if needed.

**Comment by mblockso** [comment]
Umm .. we already hit this with the ofi bgq provider and worked through these issues (maybe this was internal?).  The solution at that time was to require ofi providers to support `FI_DIRECTED_RECV` **and** `FI_REMOTE_CQ_DATA` if you want to scale above 64k ranks. You have to specify **both** capabilities for it to work.

`1`. was discouraged because we already have some aurora application that has a lot of tag space pressure.

`3`. sounds interesting, but you are now requiring that the ofi provider support a different feature - scalable endpoints and/or multiple endpoints - instead of `FI_DIRECTED_RECV` + `FI_REMOTE_CQ_DATA`.

**Comment by wesbland** [comment]
So the compromise fix that I'm working on now is to add the specification of context id/rank/tag bits to the capability sets so you can configure it per provider and/or at runtime. That way if you need more bits for ranks, you can decide where else to take them from.

I have a patch for this and am testing it now.

**Comment by pavanbalaji** [comment]
If (2) is available, that'd be the ideal solution.  Is this already coded in?

For the OFP machine, this will not work since it uses OPA and that doesn't support this capability.

**Comment by mblockso** [comment]
@pkcoff If this goes through then we will want to resurrect the `fi_[t]inject()` optimization and packet header type. This saves us about 0.2 usec for messages of size 0-16 bytes.

**Comment by mblockso** [comment]
(2) is already coded in the ch4/ofi netmod. This is the current default run mode on bgq.

**Comment by wesbland** [comment]
2 is already coded, but the PSM2 provider doesn't support the immediate data that's necessary for the OFP machine.

**Comment by mblockso** [comment]
According to https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.4.0 the psm2 provider already supports `FI_DIRECTED_RECV`. 

`FI_REMOTE_CQ_DATA` is not specified in the table, so not sure about that.

**Comment by wesbland** [comment]
Correct. It does not support `FI_REMOTE_CQ_DATA`.

**Comment by mblockso** [comment]
Why can't it support `FI_REMOTE_CQ_DATA`? PSM2 has a 96-bit tag space, the psm2 provider should be able to use 64 bits for the ofi tag and 32 bits for the immediate data.

**Comment by wesbland** [comment]
@ddurnov and I have been talking to Jianxin about that today. Apparently the other 32 bits are already being used for various other things.

**Comment by mblockso** [comment]
bah!

that's what I have to say about that.

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
This was actually part of the original capability sets pull request (https://github.com/pmodels/mpich/pull/2374). The only thing missing at that point was the PSM2 provider, which didn't support it at the time.

Support was added in the 1.6 series of libfabric (I believe) and I updated the PSM2 capability set to reflect that in a relatively recent patch (https://github.com/pmodels/mpich/pull/2985/commits/c88ad7d118bd6e6ba9df0c55590501c804e5cb42) where we made the requirement for `FI_DIRECTED_RECV` and completion queue data default (and you could enable the legacy behavior when using an old provider by compiling with `--enable-legacy-ofi`).

I think this issue can be closed.
