### ISSUE TITLE
Improve context ID allocation in unnecessary combinations

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2567]
We should review the reserved context id bits in case, we can re-use some of the reserved bits based on the type of communicator. Some combinations might be impossible, e.g. intercomms and RMA.

**Comment by hzhou** [comment]
@raffenet Could you clarify this ticket?

**Comment by raffenet** [comment]
I'm not entirely sure, to be honest. The description refers to how RMA windows cannot be created with inter-communicators, but I don't see how to distinguish an RMA context id at all in today's code. I'll look more closely to see if there's something I'm missing.

**Comment by hzhou** [comment]
This ticket lacks the imperative statement, e.g. what is broken and why the fix. Enhancements issues are okay, but it needs someone actively working on them. Otherwise, they just obscure more important issues. Therefore, I am closing this ticket for now.
