### ISSUE TITLE
CH4: Enhance MPID_Progress_wait

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2570]
The CH4 version of this routine does nothing with the input state.

**Comment by hajimefu** [comment]
Related: #2742

**Comment by hajimefu** [comment]
Has this been addressed in #3235? @danghvu @raffenet

**Comment by danghvu** [comment]
@hajimefu I hope so -- at least the state is now used in similar way as ch3. 
I am not sure if we want to do anything else with it.

**Comment by hajimefu** [comment]
@danghvu Thanks. Then I would suggest we close this issue. If anything else comes up, we can submit a new and more specific issue then.

**Comment by danghvu** [comment]
I can't close, ping @raffenet or @halimamer for comment/close
