### ISSUE TITLE
CH4: (comm, rank) locality function should return av table entry in addition to boolean

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2588]
It should be possible to avoid the AV rankmap calculation a second time in nm/shm if we instead pass an av table entry down. All the nm/shm APIs will need to change to accept the new parameter in order for this to work.

**Comment by yfguo** [comment]
I think PR #2681 solved this problem on the point-to-point path. The rest is to determine how are we going to change the RMA path to the same logic.
