### ISSUE TITLE
build: ch4/ofi: pmi.h not found for BGQ build

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2604]
I thnk this commit:

commit ec1e13b80e58191ce2c2a65d5567f9b2d24a063c
Author: Ken Raffenetti <raffenet@mcs.anl.gov>
Date:   Wed Feb 22 15:13:34 2017 -0600

    pmi: Move headers out of top-level include dir

    If we are building with an external pmi library, we should be using the
    external version of the pmi.h/pmi2.h. Move the MPICH copies into subdirs
    that will be conditionally added to CPPFLAGS based on configure options.

    Signed-off-by: Gengbin Zheng <gengbin.zheng@intel.com>

Has broken BGQ, I'm getting this compiler error:

C       src/mpi/attr/lib_libmpi_la-attr_delete.lo
In file included from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/src/ch4_impl.h:14:0,
                from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/src/ch4_request.h:14,
                from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/include/mpidch4.h:249,
                from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/include/mpidpost.h:15,
                from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/include/mpiimpl.h:234,
                from /home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpi/attr/attr_delete.c:8:
/home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/src/ch4_types.h:17:17: fatal error: pmi.h: No such file or directory
compilation terminated.

Note that I currently have these configure options set:
        with_pmi=no 
        MPID_NO_PMI=yes

**Comment by pkcoff** [comment]
I went ahead and reverted this commit and that does indeed fix the problem - so i'm not broken take your time to do the proper fix

**Comment by raffenet** [comment]
One question, how do processes discover the filename in `/dev/shm` for shared memory communication on BG/Q? The code in `src/mpid/common/shm` uses PMI. I don't see a workaround for non-PMI builds.
CC: @mblockso

**Comment by mblockso** [comment]
bgq just needs pmi to get the rank and job size .. after that all the fabric address information is set up by the provider during `fi_av_open()`.  Why do we need shared memory communication? I thought that was turned off for bgq...

**Comment by raffenet** [comment]
Ah, if it's turned off then that explains it.

**Comment by raffenet** [comment]
Well, that explains part of it. There are still calls to PMI in the OFI netmod that won't be compiled out. Is there some dummy PMI library on BG/Q to supplies the symbols at link time?

**Comment by mblockso** [comment]
Yes.

https://github.com/ofiwg/libfabric/blob/master/prov/bgq/src/fi_bgq_pmi.c

**Comment by raffenet** [comment]
More pieces to the puzzle! Should OFI/bgq be providing its own `pmi.h`? Should we move this PMI implementation into MPICH instead of OFI?

**Comment by raffenet** [comment]
Or just pre-install it on BG/Q systems and point to it at configure time ala `--with-pmi=cray`?

**Comment by mblockso** [comment]
**Or** ... MPICH could generate the libpmi.so client library and, depending on how MPICH was configured, we'd get a bgq-specific implementation (or cray or hydra).

This way other projects (Sandia OpenSHMEM, "ofi direct" applications, etc) could also just link in libpmi.so to get the job started.

If we did this, then we could move the bgq pmi implementation from the bgq ofi provider into MPICH pmi client library code.

**Comment by pkcoff** [comment]
Well of course now a user wants to build their own mpich at EPFL, what is the outlook for this fix?  In the meantime I'll just tell them to revert the commit

**Comment by raffenet** [comment]
I think the real solution here is to contribute the BG/Q PMI implementation into MPICH and select it at configure time. That way we can select/provide the right header. Specifying `--with-pmi=none` only worked because we always supplied the PMI headers in the past.

@mblockso's suggestion to distribute/build the PMI library independently is the right thing to do, but I don't have an estimate for when it will be done. Could be a future hackathon item.

**Comment by raffenet** [comment]
Just to reiterate, I don't want to go back to always providing the PMI headers, as it breaks existing external libraries such as Cray PMI.

**Comment by mblockso** [comment]
Sounds good .. Could we get a pmi "hydra" client library first? then Paul and I could hook in a bgq implementation fairly easily.

**Comment by pkcoff** [comment]
Hey Ken - could you reply to Mike's request?  in the mean time I guess i'll need to add official verbage to this in the README as doesn't appear we'll have a fix soon so users will have to keep reverting this.  thanks.

**Comment by raffenet** [comment]
Still no update on when the separate PMI library work will be taken on. @mblockso, when you say a "hydra" PMI library, do you mean a single library that implements the `PMI_<foo>` calls that will work with Hydra? Or do you mean a PMI library that contains multiple "providers" (for lack of a better term), the first of which supports Hydra?

**Comment by pkcoff** [comment]
Per the mpich telecon discussion on pmi today, Ken is going to implement a --with-pmi=bgq option so will be some subconfigure workaround plans to have it by Friday

**Comment by pkcoff** [comment]
The --with-pmi=bgq  workaround works for the bgq build - I guess we'll keep this issue open for the separate pmi lib final solution....

**Comment by hzhou** [comment]
@raffenet Can this ticket be updated -- is it still relevant? Clarify what needs to be done?

**Comment by raffenet** [comment]
`--with-pmi=bgq` fixed the issue they had. I don't think doing a Simple PMI client library module right now is the right use of effort since PMIx has much more traction.
