### ISSUE TITLE
Hanging behavior with derived types in a 'user-defined gatherv'

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#2609]
from discuss@ mailing list:

The code mimics a decomposition of a multi-field grid in 2 dimensions. Each grid has a halo region allocated, and this gather is only interested in transmitting the interior of each grid. 

The conditions, as far as I can tell, are related to:

1. nranks > 2
1. 'larger' messages: I haven't fully bisected it, but 256x128 grids work, and 256x256 don't.
1. Having halos. With the global integer halow = 2, the strides for the grids (and the resulting hvector derived types) exceed the lengths, and that seems to be important; if you set halow = 0 and run, it completes, independent of the other factors. 

The test program uses Waitsome to figure out which requests are completing, and it looks like rank 0 fails to complete a recv from rank 2, despite rank 2 completing its send.  

You can fiddle with the hacky 'mask' parameter to have a subset of the ranks send (line 326). -1ULL means all ranks are allowed in, but you get interesting results with 6ULL, which has just ranks 1 and 2 participate in sending, but rank 0 still hangs on the recv from rank 2. (Obviously the correctness test will fail here, since it expects results from all ranks).

I discovered this on Intel MPI, and thanks to my colleague Jeff Hammond's analysis, was able to reproduce the behavior on MPICH 3.2. OpenMPI 2.1.0 successfully completes every case I have tried.

Test code: https://gist.githubusercontent.com/jasonsewall/0d1fb12a93e157795786e560733cbf0c/raw/7548f85ef44a52204f76fd08294e29d0f6182428/mpi-gather.cpp

Execution:

    export  MPIR_CVAR_NOLOCAL=1
    mpiexec -np 3 ./mpi-gather 256 256

**Comment by pavanbalaji** [comment]
Here is a much simpler reproducer:

{{{
#include <stdio.h>
#include "mpi.h"

#define BLKLEN (1024)
#define NUM_BLKS (64)

double large_buf[(BLKLEN + 1) * NUM_BLKS];

int main(int argc, char *argv[])
{
    int rank;
    int nranks;

    MPI_Init(&argc, &argv);

    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &nranks);

    MPI_Request reqs[nranks];

    if (rank == 0) {
        for (int r = 0; r < nranks - 1; r++) {
            MPI_Datatype type;

            MPI_Type_create_hvector(NUM_BLKS, BLKLEN, (BLKLEN + 1) * sizeof(double), MPI_DOUBLE, &type);
            MPI_Type_commit(&type);

            MPI_Irecv(large_buf, 1, type, r + 1, 0, MPI_COMM_WORLD, &reqs[r]);
            MPI_Type_free(&type);
        }
        MPI_Waitall(nranks - 1, reqs, MPI_STATUSES_IGNORE);
    }
    else
        MPI_Send(large_buf, BLKLEN * NUM_BLKS, MPI_DOUBLE, 0, 0, MPI_COMM_WORLD);

    printf("R%d all finished\n", rank);

    MPI_Finalize();
    return 0;
}
}}}

Execution:

{{{
% mpiexec -genv MPIR_CVAR_NOLOCAL=1 -n 3 ./mpi-gather
}}}
