### ISSUE TITLE
Add Fortran interfaces to fault tolerance extensions

### ISSUE THREAD

**Issue by nathanweeks** [pmodels/mpich#2632]
Currently, the fault tolerance extensions (MPIX_Comm_failure_ack, MPIX_Comm_failure_get_acked, MPIX_Comm_revoke, MPIX_Comm_shrink, MPIX_Comm_agree) are available only in C. I'm involved in a project where we would like to make use of this API in Fortran. I can try creating Fortran procedure interfaces for these in our code, but it would be helpful if these were made available via the Fortran mpi and mpi_f08 modules.

**Comment by nathanweeks** [comment]
Since I need this for a project, I've implemented Fortran bindings for the FT interfaces, as well as regression tests:

https://github.com/nathanweeks/mpich-private/compare/master...feature/ft-fortran

If it's possible for this to be accepted into the upstream MPICH codebase, I'd like to start a conversation on what might need to be done before a proper pull request can be submitted.

A few comments regarding the added regression tests:

1. The fixed-format (F77) Fortran regression tests include the Fortran 2008 ERROR STOP statement, as the tests are expected to return a non-zero exit status; the runtests script will not consider a "1" valid output; and though the runtests script skips "FORTRAN STOP", 'stop "FORTRAN STOP"' returns an exit status of 0 (at least with the Intel Fortran compiler). The Intel Fortran 17 compiler accepts this, though I'm not sure about other Fortran compilers.
2. I left out the "(C) 2014 by Argonne National Laboratory." statements in the source code comments, leaving in the "See COPYRIGHT in top-level directory."
3. While the Fortran regression are mostly a translation of the C tests, dynamic memory allocation has been excluded due to the lack of support for the ALLOCATE statement in Fortran 77. The f90 tests are auto-generated from the f77 tests, and the f08 tests are consistent with the f77 tests, except for changing types as required by the mpi_f08 interfaces, and substituting variables of type MPI_Comm in place of MPI_STATUS_IGNORE to work around https://github.com/pmodels/mpich/issues/2703

**Comment by wesbland** [comment]
Go ahead and create the pull request and then we can have the conversation there. @raffenet / @yfguo can tell you what should and shouldn't be there, but in general, MPICH doesn't have merge commits so you'll need to squash your commits down to remove that. Probably all three commits can be squashed down to one commit since the last one just looks like a fix for the first one.

**Comment by nathanweeks** [comment]
Done: https://github.com/pmodels/mpich/pull/2719

**Comment by hzhou** [comment]
The mentioned FT functions are now generated in the `use mpi_f08` module.
