### ISSUE TITLE
CH4/OFI: Another hang in MPI_(I)Probe on BGQ

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2633]
I have run across another hang in the MPI_(I)Probe on BGQ that seems to have the origin of the problem in mpich this time.  Using the latest ofiwg master and doing  a git bisect  on the latest mpich master it seems  commit f3f409cd7570564d44b86e6b93bae2dcffd81b82 :

>Author: Yanfei Guo <yguo@anl.gov>
Date:   Thu Feb 23 10:16:52 2017 -0600
>
>    CH4/OFI: Enable Dynamic Process Support.
>
>    Adding the management of connection and functionality for dynamic
    process. The connection between two process groups is maintained between
    two roots. Each root will get a conn_id for any new communication, which
    in turn saved in fi_av and mapped to corresponding fi_addr_t. The
    mapped address is saved in a connection manager (part of MPIDI_Global).
    Note the connection is only used for management purpose, not the actual
    communication between groups.
>
>    The network addresses of the processes in each group will get exchanged
    during the connect/accept procedure. They will be inserted to fi_av and
    mapped to fi_addr_t(s). Any address that is not previously known will be
    associated with a new CH4 level AVT_ID. This is a part of the existing
    protocol for UPIDS to LUPIDS conversion. After the address exchange, all
    process will communicate in a "connection-less" manner.
>
>    Disconnection protocol. This patch uses a "eventually disconnect"
    protocol for handling disconnection. This means no disconnection message
    will be send during the invocation of 'MPI_Comm_disconnect'. The actual
    disconnection happens in the destroy of connection manager at finalize
    time. Within the connection manager, each connection will be marked as
    `CONNECTED_PARENT` and `CONNECTED_CHILD`. The "child" process (root of
    the connecting group) will send the "disconnect message" to the "parent"
    process (root of the accepting group). The message will be sent using
    `fi_tsendmsg` with `FI_TRANSMIT_COMPLETE` flag to avoid delivery problem
    when `FI_PROGRESS_MANUAL` is used.
>
>    Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>

Has somehow caused a hang in the pt2pt/isendselfprobe.  I actually have several permutations of the test using MPI_Iprobe, MPI_Probe and then sending to an actual neighbor (rank 0 to rank 1) and they all hang.  What makes this very difficult to debug is the hang does NOT happen if I build in debug mode with full object symbols, the problem only occurs if i build in optimized mode with everything stripped.  This is a huge commit and I'll look thru the code some more tomorrow, but any thoughts on the mechanism by which this dynamic processs code could be impacting the probe is appreciated....

**Comment by pkcoff** [comment]
i did some debugging today, the reason for the hang seems to be the src_addr in the target context posted for the trecvmsg that the probe is trying to match on is corrupted, so far I can't determine exactly when the corruption takes place, and when I turn my trace on i'm getting failures for both the optimized and debug builds but the src_addr is corrupted differently for debug vs optimized

**Comment by pkcoff** [comment]
looking thru the code changes for this dynamic process support commit I don't see anything explicitly that would be an issue, are you somehow assuming a 32-byte context whereas bluegene uses 64?

**Comment by pkcoff** [comment]
I was looking thru ofi_types and I see fi_context used in alot of structures, like this one for dynamic tasks:

typedef struct {
    char pad[MPIDI_REQUEST_HDR_SIZE];
    struct fi_context context;  /* fixed field, do not move */
    int event_id;               /* fixed field, do not move */
    int done;
    uint32_t tag;
    uint32_t source;
    uint64_t msglen;
} MPIDI_OFI_dynamic_process_request_t;

I know this was an issue in the past, trying to remember how it got resolved --- how does ofi_types know that fi_context is 64 bytes for bgq?  If the structure is laid out as only 32 bytes for fi_context the bgq context will get overlaid with the rest of the fields.....

**Comment by wesbland** [comment]
Does the BG/Q provider require `FI_CONTEXT2`? If so, I have a patch that enables it sitting in my repository, but I was holding it until more providers supported it. I didn't want to break any providers that do explicit checking of mode bits but haven't updated for `FI_CONTEXT2`.

**Comment by pkcoff** [comment]
No, now I remember bgq generates the fi_direct.h and has this:

#ifdef FABRIC_DIRECT
#define FABRIC_DIRECT_ 1

#include "rdma/fabric.h"

struct fi_context {
        void                    *internal[8];
};

#endif

So as long as a pointer is 8 bytes this gives us 64, and we're setting FABRIC_DIRECT...  But seems like there should be a better way to do this, that FI_CONTEXT2 seems like the better way....

**Comment by pkcoff** [comment]
Met with Ken and Mike --- the issue wasn't context corruption, rather a problem in the fi_trecvmsg implementation on BGQ, we needed to manually set the src_addr in the context to the fi_tagged_msg.addr that mpich is giving to us.  Now it works - ofi fix.  Closing.
