### ISSUE TITLE
bug: mpi_t/cvarwrite.c test case fails when cvars are constant or read-only scope

### ISSUE THREAD

**Issue by csadlo** [pmodels/mpich#2654]
The mpi_t_/cvarwrite.c test case is failing when cvars scope is either constant or read-only.

Currently the test case only checks the cvar's binding and datatype before trying to write to it, without regard for whether the scope allows for writing.

The error output when running the test on ill-suited cvars looks like this:

```
$ srun -n 1 ./cvarwrite
INTERNAL ERROR: invalid error code 44 (Ring ids do not match) in PMPI_T_cvar_write:135
Rank 0 [Wed Oct 26 14:46:31 2016] [c0-0c0s6n0] Fatal error in PMPI_T_cvar_write: Other MPI error, error stack:
PMPI_T_cvar_write(149):  MPI_T_cvar_write(handle=0x9aaac0, buf=0x7fffffff5880)
PMPI_T_cvar_write(135):
srun: error: nid00024: task 0: Aborted
srun: Terminating job step 87614.0
```

It looks like this is an opportunity to use a more descriptive error message when trying to write to a constant or read-only cvar.

**Comment by sudheer9** [comment]
@csadlo, can you provide an example for the CVAR that is CONSTANT or read-only? On the few systems that I've tried, there isn't any error generated with running ./cvarwrite.

**Comment by sudheer9** [comment]
The issue reported here is an Abort error when there is any CVAR that has the scope as `MPI_T_SCOPE_CONSTANT` or `MPI_T_SCOPE_READONLY` and when the test tries to write a value to it using `MPI_T_cvar_write`. The reported behavior was seen with v3.3.2 release. With the later releases and including the latest `master`, `MPI_T_cvar_write` on CVARs with readonly or constant scope, the test reports an error. @raffenet can we close this issue?

**Comment by raffenet** [comment]
I don't think we've solved the issue yet. The test case should either not try to write CVARs that are not writable, or if it does, it should expect an error and not fail the test because of it.

I think we should amend the test to not try to write read-only CVARs. We can add a separate test in the `test/mpi/errors/` directory to verify the error behavior, if desired.
