### ISSUE TITLE
MPI_Comm_connect crashed when using MXM channel

### ISSUE THREAD

**Issue by DjangoPeng** [pmodels/mpich#2656]
I am trying this example with MPICH: http://mpi.deino.net/mpi_functions/MPI_Open_port.html
When I use the ch3:nemesis channel over TCP/IP network, it works well.
However, when I use ch3:nemesis:mxm channel over InfiniBand network, it crashes:
```
Caught signal 11 (Segmentation fault)
==== backtrace ====
2 0x000000000006746c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3097/src/mxm/util/debug/debug.c:641
3 0x00000000000679bc mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3097/src/mxm/util/debug/debug.c:616
4 0x0000000000035a00 killpg()  ??:0
5 0x00000000001839e6 MPID_nem_mxm_vc_init()  :0
6 0x000000000017dd76 MPID_nem_vc_init()  :0
7 0x0000000000172088 MPIDI_CH3_VC_Init()  :0
8 0x000000000016ca5b MPIDI_VC_Init()  :0
9 0x0000000000172279 MPIDI_CH3_Connect_to_root()  :0
10 0x000000000012dd2c MPIDI_Comm_connect()  :0
11 0x0000000000166de3 MPID_Comm_connect()  :0
12 0x00000000000dae2c MPI_Comm_connect()  ??:0
13 0x0000000000400ef6 main()  ??:0
14 0x0000000000021af5 __libc_start_main()  ??:0
15 0x0000000000400ac9 _start()  ??:0
===================
```
I tried both MPICH 3.2 and 3.3a2, and the error can be reproduced by both versions.
The same error can also be reproduced by running the tests in “test/mpi/spawn” directory of MPICH.
My MPI configure is:  --prefix=XXX --with-device=ch3:nemesis:mxm --with-mxm=/opt/mellanox/mxm

Can you please take a look? I am wondering the right way to use the MPI_Comm_connect feature with InfiniBand. Thanks!

**Comment by raffenet** [comment]
Unfortunately this functionality is not supported with the MXM netmod at this time.

**Comment by DjangoPeng** [comment]
Thanks for the answer! If not supported, I think it is better to show some explicit information rather than crash directly.

**Comment by pavanbalaji** [comment]
`ch3` is in maintenance mode and new features will not be added.
