### ISSUE TITLE
Provide a way to easily bootstrap MPICH

### ISSUE THREAD

**Issue by gnzlbg** [pmodels/mpich#2698]
On systems with unsupported versions of autoconf, automake, and libtool it is _extremely painful_ to bootstrap MPICH. It would be nice if this could be solved, e.g., by providing a script (e.g. `bootstrap.sh`) that automatically fetches the correct versions of `autoconf`, `automake`, and `libtool`, ~~or by using a build system that can be bootstraped easily, like cmake~~ (EDIT: using cmake is probably not an option).

---

EDIT2: this is what I ended up doing:

`bootstrap_mpich.sh:`
```bash
#!/usr/bin/env bash
set -e
set -o pipefail

LIBTOOL=libtool-2.4.6
AUTOCONF=autoconf-2.69
AUTOMAKE=automake-1.15
wget http://ftpmirror.gnu.org/libtool/${LIBTOOL}.tar.gz
wget http://ftp.gnu.org/gnu/autoconf/${AUTOCONF}.tar.gz
wget http://ftp.gnu.org/gnu/automake/${AUTOMAKE}.tar.gz
tar -xzf ${LIBTOOL}.tar.gz
tar -xzf ${AUTOCONF}.tar.gz
tar -xzf ${AUTOMAKE}.tar.gz

TOOLS_PREFIX=${PWD}/tools
mkdir -p ${TOOLS_PREFIX}

cd ${LIBTOOL}
./configure --prefix=${TOOLS_PREFIX}
make -j
make install -j
cd ../${AUTOCONF}
./configure --prefix=${TOOLS_PREFIX}
make install -j 
make -j
cd ../${AUTOMAKE}
./configure --prefix=${TOOLS_PREFIX}
make -j
make install -j
cd ..

PATH=${TOOLS_PREFIX}/bin:${PATH}
```

**Comment by raffenet** [comment]
We could look at including this script in maint. Would you be able to provide a signed contributors agreement for MPICH before we accept this? http://www.mpich.org/documentation/contributor-docs/

**Comment by gnzlbg** [comment]
@raffenet I've just sent the signed agreement to the email address (says the message is awaiting moderator approval).

Shall I just send a PR with the script?

**Comment by raffenet** [comment]
Yes, a PR would speed up the acceptance process. Thanks!

**Comment by gnzlbg** [comment]
@raffenet I've sent a PR.
