### ISSUE TITLE
bug/jenkins: test/mpi/errors/datatype/getcnterr.c fails with #2697 PR

### ISSUE THREAD

**Issue by Bayyapu** [pmodels/mpich#2715]
test/mpi/errors/datatype/getcnterr.c fails and is being marked as getcnterr 1 xfail=ticket2697 in test/mpi/errors/datatype/testlist for consistency. This is observed when pull request #2697 is tested on Jenkins.

**Comment by wesbland** [comment]
To attach code, I'd recommend using a Gist instead of a PDF since it's a lot easier to view/edit. A pull request is good too.
