### ISSUE TITLE
Supporting Message Queue Dumping Interfaces for CH4

### ISSUE THREAD

**Issue by shawnccx** [pmodels/mpich#2721]
Message Queue Dumping (MQD) interfaces are not supported for CH4. Existing code of `mpi/debugger/` is hard-coded with `MPIR_Request` in CH3 implementation. For example, in https://github.com/pmodels/mpich/blob/master/src/mpi/debugger/dll_mpich.c, line 306-349, MQD interfaces use CH3-defined structures and fields to extract info of posted/unexp queues.

Also, existing code of MQD uses `MPIR_Request **` for the head of posted/unexp queues. This also doesn't work for CH4 as posted/unexp queues are `MPIDI_CH4U_rreq_t **`. Debugger cannot get the following info from CH4 message queues as `MPIDI_CH4U_rreq_t` doesn't have these fields, and debugger can only get the value of these fields by using offset in request structure (request structure is opaque to debugger).

```  mqs_tword_t desired_local_rank;       /* Rank of target/source -1 for ANY */
  mqs_tword_t desired_global_rank;      /* As above but in COMM_WORLD  */
  int tag_wild;                         /* Flag for wildcard receive  */
  mqs_tword_t desired_tag;              /* Only if !tag_wild */
  mqs_tword_t desired_length;           /* Length of the message buffer */
  int system_buffer;                    /* Is it a system or user buffer ? */
  mqs_taddr_t buffer;                   /* Where data is */
```

Currently a work-around method of adding MQD for CH4 is to use global macros to write code for CH4 and CH3 separately. While this method is not general, any other generic design/method can be proposed to make MQD work for both CH3 and CH4?

**Comment by hzhou** [comment]
I believe this issue is obsolete by https://github.com/pmodels/mpich/pull/5757
