### ISSUE TITLE
CH4/UCX: RMA tests timeout

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#2745]
Jenkins consistently reports timeout RMA tests. This might be related to recent UCX update.

**Comment by raffenet** [comment]
This is what is currently set to xfail.

```
ucx * * ch4:ucx * sed -i "s+\(^win_large_shm .*\)+\1 xfail=ticket0+g" test/mpi/rma/testlist                                        
ucx * * ch4:ucx * sed -i "s+\(^strided_putget_indexed_shared .*\)+\1 xfail=ticket0+g" test/mpi/rma/testlist   
```
All other RMA tests are passing consistently. I think this must have been resolved some time ago, so I'm going to close.
