### ISSUE TITLE
CH4 SHMMOD support for RMA operation

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#2752]
CH4 saves addresses of processes (network/shm) and passes them when calling the netmod or shmmod function. In order to avoid using extra space or translation when a process has both a network address and a shm address, we would like to allow the shm address to override the network address in the global address vector. However, this only works if the shmmod can do RMA operations.

**Comment by hzhou** [comment]
Since no one is working on this, I am closing it.
