### ISSUE TITLE
Fix race condition with Window and Communicator-based collectives

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2776]
Because `MPIR_Win` objects share a `comm_ptr` with the communicator from which they're created, there is a race condition that's possible when doing RMA collectives (like `MPI_WIN_FENCE`) overlap with regular collectives (like `MPI_BARRIER`).

There's a test for this case that came from #2506 in c55632e.

**Comment by pavanbalaji** [comment]
I prefer option 1.  Much more maintainable.

**Comment by wesbland** [comment]
BTW, digging a bit more, it seems that we're already duplicating the communicator in CH3:

https://github.com/pmodels/mpich/blob/2c5df4acccbc90d041e2c5f12927a0cc991706c9/src/mpid/ch3/src/mpid_rma.c#L274

So I guess we should stick with that.
