### ISSUE TITLE
Hydra slurm integration failure

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#2786]
Hydra's parsing of slurm node list is quite fragile.  It currently looks for node lists in the following formats:

```
[host001-host012]
host001-host012
host009
[host001-host012,host014-host020]
```

Some machines (such as Bebop) use the following format: `host-[001-002]` which is not recognized by Hydra, resulting in failure in detecting the allocated nodes.

**Comment by raffenet** [comment]
@gcongiu it is probably working looking for an external library that can do this parsing for us before we commit to coding it ourselves.

**Comment by gcongiu** [comment]
@raffenet ok I will look around
