### ISSUE TITLE
document info keys

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#2795]
The keys need to be documented.  It's a pain to document by hand: let's do something like what CVAR does, with comment blocks and such. 

Documentation needs to give 
 * the hint name, 
* any aliases
* general descriptoin
* specifically what functions it impacts

**Comment by hzhou** [comment]
We have `mpivars` dump all the cvars. Should we have `mpihints` to dump the info keys?

**Comment by roblatham00** [comment]
dumping all the info keys is easy:

``` 
#!/usr/bin/env python
from sys import argv
from mpi4py import MPI

fh = MPI.File.Open(MPI.COMM_WORLD, argv[1])

info = fh.Get_info()

for key in info.keys():
    print("key: ", key, "value: ", info.Get(key))

info.Free()
fh.Close()
```

but what does `romio_cb_fr_alignment` mean?  what are the expected values?  Furthermore, dumping the keys associated with an info object in this way will get you the default keys, but there are non-default keys such as `striping_unit` that users can also set.

**Comment by hzhou** [comment]
Right. I was thinking of adopting a similar comment block like the cvar block and have autogen generate `src/env/dumphints.c` with full information.

**Comment by hzhou** [comment]
On second thought, info keys are not global. They are rather per-function-based. So probably fit better in the man page. We still can use the CVAR-style comment block to document it, then have the binding generation script generate the info key section into the relevant function's man page.
