### ISSUE TITLE
comm/cmsplit_type 4 test failing on CH4

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2811]
Something that went into master between [Oct 21](https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ofi/174/) and [Oct 23](https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ofi/175/) broke `comm/cmsplit_type`. Haven't bisected yet to find the problem.

**Comment by pavanbalaji** [comment]
I believe this has been fixed.  Please reopen if that's not the case.
