### ISSUE TITLE
Remove MPIR_Barrier_group

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2862]
During the collectives work @pavanbalaji realized that we never use `MPIR_Barrier_group` and it doesn't need to be around anymore.

**Comment by akhillanger** [comment]
This has now been already taken care of in the prereqs pull request. The issue can be closed once that gets merged.

**Comment by wesbland** [comment]
https://github.com/pmodels/mpich/pull/2859

**Comment by akhillanger** [comment]
This issue can also be closed, since the PR has been merged. I don't seem to have the permission to close issues.

**Comment by wesbland** [comment]
Closed with fd9c0d7f636accb9c7dd056f1b971029d4d53cf1
