### ISSUE TITLE
Add Algorithm Protections for Collective Framework Algorithms

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2866]
Add checks for any algorithms with specific requirements like those that require a power of 2.

**Comment by akhillanger** [comment]
This is being taken care of in PR #2907.

**Comment by akhillanger** [comment]
The corresponding commit has been approved/signed-off and will be merged soon. This issue can now be closed.

**Comment by wesbland** [comment]
The commit message should say "closes pmodels/mpich#2866".
