### ISSUE TITLE
Problem with mpich building on autogen stage

### ISSUE THREAD

**Issue by FyodorK** [pmodels/mpich#2873]
Hi, 
I'm trying to build the mpich now. 
I performed: 
mybuildhost$ git clone --recursive https://github.com/pmodels/mpich.git
mybuildhost$ ./autogen.sh 

and got following error:

## Checking submodules

===> ERROR:   Submodule src/hwloc is not checked out
I looked to the folder but it's not empty

.gitmodules contains:
[submodule "src/hwloc"]
	path = src/hwloc
	url = https://github.com/pmodels/hwloc
	branch = 1.11.8-mpich

I proceeded to src/hwloc and check out the branch,  it was *(no branch) so I change branch to 1.11.8-mpich
mybuildhost$ git checkout 1.11.8-mpich
mybuildhost$ git submodule update

But the error is still here. 

Could you please give any advice?

**Comment by raffenet** [comment]
To properly initialize all submodules, you should do:

> git submodule update --init

Try that and see if `autogen.sh` will succeed.

**Comment by FyodorK** [comment]
Unfortunately it doesn't  succeed. 
My colleague gave me this hash - 2f32a1cd5, when I check out from it, all looking  good and workable just out-from-box. Mb it gives you some clues regarding the issue.

**Comment by raffenet** [comment]
If you used submodules in the past and updated with yesterday's changes, you might need to do a

> git submodule sync

to ensure git is getting submodules from the new location. Does that help?

**Comment by FyodorK** [comment]
No it doesn't work too.

**Comment by FyodorK** [comment]
I've made git pull, it is still building but autogen stage has succeeded. So I think the issue is solved. Somehow.
