### ISSUE TITLE
CH3/RMA: testall returns error with request-based RMA.

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#2880]
[mpi_testall.c.txt](https://github.com/pmodels/mpich/files/1510026/mpi_testall.c.txt)
MPI_Testall returns error code for request-based RMA but the request is actually successfully completed. This is a simple bug in request-based RMA. Attached program can reproduce the bug. Thanks for the report and the reproducer program contributed by Joseph.

**Comment by hajimefu** [comment]
@minsii Are you going to add this to the test suite?

**Comment by minsii** [comment]
@hajimefu : Yes. I will make a PR later today.

**Comment by hajimefu** [comment]
Good to hear that. Thanks! I'm curious if this also affects CH4.

**Comment by minsii** [comment]
I think so. This is actually a simple bug in the mpi layer. In function `MPIR_Request_get_error`, the case option for RMA type request is missing. I will add the fix within the PR.
