### ISSUE TITLE
aclocal_fc.m4: undefined reference to test_assumed_rank_async_impl

### ISSUE THREAD

**Issue by nathanweeks** [pmodels/mpich#2929]
Commit https://github.com/pmodels/mpich/commit/bf0db16be5c43ec5a5f19671f55bb701165dfc8d adds a test that contains a generic interface TEST_ASSUMED_RANK_ASYNC for subroutine TEST_ASSUMED_RANK_ASYNC_IMPL. Per the commit comments, this detects a compiler error in the Intel 18 compiler (I'll add that ifort 17.0.2 seems affected as well). However, this also results in an undefined reference error for the Cray 8.6.2 compiler:

```
configure:44641: ftn -o conftest   -g   conftest.f90 conftest1.o -lm    >&5   
/tmp/pe_33576/conftest_1.o: In function `main':
/global/u2/n/user/repos/mpich/conftest.f90:76: undefined reference to `test_assumed_rank_async_impl_'
``` 
I think this error is valid, as TEST_ASSUMED_RANK_ASYNC is invoked by the generated test, but TEST_ASSUMED_RANK_ASYNC_IMPL isn't defined.

The failure of this test ultimately causes the mpi_f08 interfaces to not be built for the Intel or Cray Fortran compilers (or gfortran, which lacks ISO_Fortran_binding.h).

**Comment by raffenet** [comment]
@yfguo can you look into this?

**Comment by yfguo** [comment]
@nathanweeks FYI, Intel has fixed this problem in their Fortran compiler (since version 2018.3.222 and 2019.0.070).
