### ISSUE TITLE
mpich-3.3a3 build error on opensolaris [while mpich-3.3a2 builds fine]

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#2937]
Attaching logs

[config.log](https://github.com/pmodels/mpich/files/1654236/config.log)
[build.log](https://github.com/pmodels/mpich/files/1654239/build.log)

**Comment by raffenet** [comment]
Thanks for the report. I've got a fix for this. Not sure how I left that awful code through in the first place :frowning_face:
