### ISSUE TITLE
coll: Cleanup pof2/log~2~ calculations

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2946]
There's a bunch of scattered instances of code to calculate the closest power-of-2 to a communicator size. Recently a fields was added to the `MPIR_Comm` struct (https://github.com/pmodels/mpich/commit/5217cce0d4b53cc6857cec248d178199af2de9ca) to store this, so those calculations are redundant. What we don't have stored is the exponent. We should provided a method to retrieve it, as well. That way we can wipe out all these open-coded instances throughout `src/coll`.

**Comment by raffenet** [comment]
It looks like 5217cce0d4b53cc6857cec248d178199af2de9ca took care of most of this. Still, the log~2~ problem remains unless I'm missing something.

**Comment by raffenet** [comment]
This is a pretty straight-forward improvement to the code to use `MPL_pof2` and `MPL_ilog` at comm create time. Would be great for someone just starting on the project to understand using MPL and communicator metadata.

**Comment by hzhou** [comment]
I actually am leaning toward not caching these calculations and prefer to use `MPL_pof2` and `MPL_ilog` at run time.  The caching, no matter how trivial, adds complexity. On the other hand, the benefit is very small. In fact, `gcc` has `__builtin_clzll` that can compile it down to a single instruction for `MPL_ilog` and add 1 shift to get `pof2`. Even when `MPL_pof2` and `MPL_ilog` are less optimized, it is still likely several clocks and in the context of collective, shouldn't be a concern.

**Comment by hzhou** [comment]
Reference for the algorithm: https://stackoverflow.com/questions/23856596/how-to-count-leading-zeros-in-a-32-bit-unsigned-integer
