### ISSUE TITLE
bug/jenkins: tests failing with nb bcast algorithm

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2960]
`comm/comm_idup_comm` and `threads/comm/idup_comm_gen` are both failing with `MPIR_CVAR_BCAST_INTRA_ALGORITHM=nb` set at runtime. This probably started from the collective framework prereq branches.

These tests seem to happen with most configs except ch4/ofi.

**Comment by akhillanger** [comment]
`MPIR_CVAR_BCAST_DEVICE_COLLECTIVE=0 MPIR_CVAR_BCAST_INTRA_ALGORITHM=nb mpirun -n 6 ./comm_idup_comm`

**Comment by wesbland** [comment]
I'm not sure. In our xfail file, we have ch3 and ch4 marked.

**Comment by raffenet** [comment]
@akhillanger was this fixed in 81443c298f21fac780d58e98ee313e906f83a451?

**Comment by akhillanger** [comment]
I don't think so. This issue, when I last checked few weeks after it was opened, is not a problem with any particular algorithm. This issue arises because of bcast implemented as ibcast+wait (that is when nb is the chosen algo for bcast).

**Comment by hzhou** [comment]
Just tested. There is no issue.
