### ISSUE TITLE
bug/jenkins: ch4 lockall_dt_flushlocal timeout

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#2965]
`lockall_dt_flushlocal` takes much longer time with ch4 (about 4mins) than that with ch3 (about 2mins) on Jenkins.
[Link to the failure on jenkins](https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ofi/lastCompletedBuild/compiler=clang,fabric_prov=sockets,jenkins_configure=debug,label=ib64/testReport/(root)/summary_junit_xml/398_____rma_lockall_dt_flushlocal_4/)

**Comment by minsii** [comment]
This issue is not shown on Jenkins anymore after separating the test with **DTpool**. I think we can close it.

**Comment by tarudoodi** [comment]
@raffenet We recently saw some tests timeout locally and then noticed that they were xfailed in master. All of them are corresponding to this issue but the issue has been closed. I think this issue should be opened again since those tests are still failing.

**Comment by pavanbalaji** [comment]
@tarudoodi CH4 will continue to fail for many RMA tests because it doesn't pack/unpack data, but instead converts to IOVs.  Till we fix that issue, these tests will continue to timeout.

**Comment by tarudoodi** [comment]
@pavanbalaji I just think we should keep the issue open while we still have related xfails for tests. Thanks for opening it again and explaining the issue.

**Comment by hzhou** [comment]
We no longer observe these failures.
