### ISSUE TITLE
bug: MPI_Init() hangs on opensolaris

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#2969]
```
  $ ../mpich-3.3b1/configure --prefix=/export/home/balay/soft/mpich-3.3b1-4 CC=cc CXX=CC F77=f90 FC=f90
```
I see an hang in MPI_Init() on opensolaris with sun compilers.
```
balay@n-gage:~/junk$ ~/soft/mpich-3.3b1-4/bin/mpicc -show
cc -I/export/home/balay/soft/mpich-3.3b1-4/include -L/export/home/balay/soft/mpich-3.3b1-4/lib -R/export/home/balay/soft/mpich-3.3b1-4/lib -lmpi

balay@n-gage:~/junk$ ~/soft/mpich-3.3b1-4/bin/mpicc cpi.c -g -lm
balay@n-gage:~/junk$ dbx ./a.out 
For information about new features see `help changes'
To remove this message, put `dbxenv suppress_startup_message 7.7' in your .dbxrc
Reading a.out
Reading ld.so.1
Reading libm.so.2
Reading libmpi.so.0.0.0
Reading libc.so.1
Reading libkstat.so.1
Reading liblgrp.so.1
Reading libpciaccess.so.0.11.1
Reading libxml2.so.2.9.4
Reading libpthread.so.1
Reading libnsl.so.1
Reading libsocket.so.1
(dbx) run
Running: a.out 
(process id 29494)
^Cdbx: warning: Interrupt ignored but forwarded to child.
t@1 (l@1) signal INT (Interrupt) in hwloc_x86_cpuid at 0xfe8f0425
0xfe8f0425: hwloc_x86_cpuid+0x0015:     xchgl    %esi,%ebx
Current function is main
   27       MPI_Init(&argc, &argv);
(dbx) where
current thread: t@1
  [1] hwloc_x86_cpuid(0x80478a4, 0x80478a8, 0x80478a0, 0x80478ac), at 0xfe8f0425 
  [2] cpuid_or_from_dump(0x80478a4, 0x80478a8, 0x80478a0, 0x80478ac, 0x0, 0xa439795, 0xd), at 0xfe8f08b1 
  [3] look_proc(0x8082588, 0x8085b40, 0xd, 0xd, 0x80479c0, 0x0, 0x0, 0xfe8f2625), at 0xfe8f0fe0 
  [4] look_procs(0x8082588, 0x8085b40, 0x0, 0xd, 0xd, 0x80479c0, 0x0, 0xfe8edcd8, 0xfe8edb74, 0x0, 0x0, 0xfe8f292d), at 0xfe8f26ce 
  [5] hwloc_look_x86(0x8082588, 0x0, 0xf69890e4, 0xfe8f2d81), at 0xfe8f2ce1 
  [6] hwloc_x86_discover(0x8082588, 0xfea12290, 0x8047b08, 0xfe8cde24), at 0xfe8f2e28 
  [7] hwloc_discover(0x80821f8, 0x28, 0x80733b0, 0xfe8cec8b), at 0xfe8cde55 
  [8] hwloc_topology_load(0x80821f8, 0xfea12290, 0x8047b78, 0xfe70db30), at 0xfe8cee2c 
  [9] MPIR_Init_thread(0x8047ca0, 0x8047ca4, 0x0, 0x8047b9c), at 0xfe70db5a 
  [10] PMPI_Init(0x8047ca0, 0x8047ca4), at 0xfe70cd1f 
=>[11] main(argc = 1, argv = 0x8047ccc), line 27 in "cpi.c"
(dbx) 
```
I do not see this with gcc on the same box..
```
balay@n-gage:~/junk$ ~/soft/mpich-3.3b1-5/bin/mpicc -show
gcc -std=gnu99 -I/export/home/balay/soft/mpich-3.3b1-5/include -L/export/home/balay/soft/mpich-3.3b1-5/lib -R/export/home/balay/soft/mpich-3.3b1-5/lib -lmpi
balay@n-gage:~/junk$ ~/soft/mpich-3.3b1-5/bin/mpicc cpi.c -g
balay@n-gage:~/junk$ ./a.out 
Process 0 of 1 is on n-gage
pi is approximately 3.1415926544231341, Error is 0.0000000008333410
wall clock time = 0.017296

```
[config.log](https://github.com/pmodels/mpich/files/1696979/config.log)

**Comment by pavanbalaji** [comment]
This configuration is tested on our nightlies.  https://jenkins.mpich.org/job/mpich-master-ch3-solaris/

Is `cc` pointing to `suncc`?

**Comment by balay** [comment]
balay@n-gage:~/petsc$ which cc
/usr/bin/cc
balay@n-gage:~/petsc$ cc -V
cc: Sun C 5.10 SunOS_i386 2009/06/03
usage: cc [ options] files.  Use 'cc -flags' for details

**Comment by balay** [comment]
Should add: mpich-3.3a2 works fine for this test/config

**Comment by pavanbalaji** [comment]
The error seems to be coming from the new `hwloc` usage that was introduced in `3.3b1`.  Can you give @KavithaTipturMadhu access to the machine you are testing this on?  It's clearly working on our machines.

**Comment by KavithaTipturMadhu** [comment]
The log above seems to be indicating that hwloc_x86_cpuid call is hanging in an inline assembly instruction in hwloc topology query. I will debug this on the machine where it seems to be hanging and may have to report it to hwloc development team.

**Comment by balay** [comment]
sure

**Comment by KavithaTipturMadhu** [comment]
Quick update: MPI_Init() hangs due to an infinite loop in one of the hwloc methods but inconsistently so across mpich builds i.e., I don't see the problem occuring when I build a second time. I don't see the same problem in a hwloc standalone. I will keep this thread posted with updates about the fix.

**Comment by balay** [comment]
For me - the hang was consistant across multiple builds when using CC="cc".

However there is no hang when I don't specify the compiler [and configure pickup 'gcc' by default]

Its interesting that stand-alone hwloc does not have this problem. [assuming its built with '/usr/bin/cc']

**Comment by KavithaTipturMadhu** [comment]
We are following up on this issue with hwloc. Here's the [link](https://github.com/open-mpi/hwloc/issues/290) to the issue for you to follow up.

**Comment by hzhou** [comment]
This issue is stale. If it is still relevant, feel free to re-open.
