### ISSUE TITLE
build/jenkins: absoft compiling failure

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#2988]
[An example of Jenkins failure](https://jenkins.mpich.org/job/mpich-master-ch3-ubuntu/compiler=absoft,jenkins_configure=default,label=ib64/899/testReport/junit/(root)/summary_junit_xml/682_____f77_io_c2fmultio_/)

Issue: `libxml2` is a dependent library of libmpi.so (hwloc-2.0 adds it), but it is not linked with the program binary at linking time if uses `af77` for linking (MPICH uses the fortran compiler for linking). 
```
## /sandbox/jenkins.tmp.FCkJACiP/mpich-master/_inst/lib/libmpi.so: undefined reference to `xmlReadFile'
## /sandbox/jenkins.tmp.FCkJACiP/mpich-master/_inst/lib/libmpi.so: undefined reference to `xmlFreeDoc'
## /sandbox/jenkins.tmp.FCkJACiP/mpich-master/_inst/lib/libmpi.so: undefined reference to `xmlNewDoc'
## /sandbox/jenkins.tmp.FCkJACiP/mpich-master/_inst/lib/libmpi.so: undefined reference to `xmlSetGenericErrorFunc'
```

**Comment by minsii** [comment]
Tried the following experiments on bb68 with absoft:
1. create a static library `libbar.a` exposing `libbar()` function. This function calls a libxml2 function (mimic libhwloc_embedded.a).
```libtool --tag=CC --mode=link gcc -o libbar.la libbar.lo -lxml2```

2. create a dynamic library `libfoobar.so`. It calls `libbar()` function (mimic libmpi.so).
```libtool --tag=F77 --mode=link af77 -rpath $libinstalldir -o libfoobar_af77_libtool.la libfoobar.lo libbar.la -lxml2```

Breakdown Step 2:
2.1. `libtool` translates `-lxml2` to an absolute path `/usr/lib/x86_64-linux-gnu/libxml2.so`, because it founds the corresponding `libxml2.la`. Thus the final linking command becomes:
```
af77 -shared  -fPIC  .libs/libfoobar.o  -Wl,--whole-archive ./.libs/libbar.a  -Wl,--no-whole-archive /usr/lib/x86_64-linux-gnu/libxml2.so -o .libs/libfoobar_af77_libtool.so
```
2.2. `af77` translates the above command to (turn on verbose via `af77 -v`):
```
gcc .libs/libfoobar.o /usr/lib/x86_64-linux-gnu/libxml2.so -L/soft/com/packages/absoft11.0/shlib64 -Wl,--whole-archive -Wl,--no-whole-archive -shared -o .libs/libfoobar_af77.so ./.libs/libbar.a -laf90math -lafio -lamisc -laf77math -lm -lmv
```

**Comment by hzhou** [comment]
We no longer require libxml2 in embedded hwloc and we no longer use Fortran compiler link libmpi.so.
