### ISSUE TITLE
bug/jenkins: unusual lockall_dt_flushall failure

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#2989]
[An example of failure on Jenkins](https://jenkins.mpich.org/job/mpich-review-ch3-sock/917/compiler=gnu,jenkins_configure=default,label=freebsd32/testReport/junit/(root)/summary_junit_xml/393_____rma_lockall_dt_flushall_4/)

```
not ok 393 - ./rma/lockall_dt_flushall 4
  ---
  Directory: ./rma
  File: lockall_dt_flushall
  Num-procs: 4
  Timeout: 240
  Date: "Wed Feb  7 16:29:21 2018"
  ...
## Test output (expected 'No Errors'):
## Data expected = f but got p[1765360] = 63
## Data expected = e but got p[1765361] = 62
## Data expected = d but got p[1765362] = 61
## Data expected = c but got p[1765363] = 60
```

This error has been reported also on other configs / platforms.

**Comment by hzhou** [comment]
No longer exist.
