### ISSUE TITLE
int overflow in netpipe message size

### ISSUE THREAD

**Issue by yosefe** [pmodels/mpich#2996]
Looks like netpipe is using 'int' for message size parameter, it causes int overflow in https://github.com/pmodels/mpich/blob/master/test/mpi/basic/netmpi.c#L242, when length is increased and wraps to -1, which is still <MAX_INT. So "len <= end" doesn't stop the iteration and calls MPI_Send with negative message size.

**Comment by akhillanger** [comment]
I guess we just need to change `bufflen` and `bits` to be of type `MPI_Aint`?
