### ISSUE TITLE
MPI_OFFSET_KIND defined differently than in OpenMPI on 32bit architectures

### ISSUE THREAD

**Issue by rathann** [pmodels/mpich#3002]
### Description of problem:
MPI_OFFSET_KIND=4 in OpenMPI while it equals 8 in MPICH on 32bit arches. I don't know which is correct, but this difference has caused compilation issues in cp2k-5.1 with MPICH:
```
[...]
/builddir/build/BUILD/cp2k-5.1/src/mpiwrap/message_passing.F:3588:70:
                                     type_descriptor%type_handle, ierr)
                                                                      1
Error: Type mismatch in argument 'array_of_displacements' at (1); passed INTEGER(8) to INTEGER(4)
[...]
```

### Version-Release number of selected component (if applicable):
openmpi-2.1.1-5.fc28.i686
mpich-3.2.1-2.fc28.i686

### How reproducible:
Always

### Steps to Reproduce:
1. `grep MPI_OFFSET_KIND= mpich-i386/mpif.h mpich-i386/mpiof.h openmpi-i386/mpif-config.h`

### Actual results:
```
mpich-i386/mpif.h:       PARAMETER (MPI_OFFSET_KIND=8)
mpich-i386/mpiof.h:      PARAMETER (MPI_OFFSET_KIND=           8)
openmpi-i386/mpif-config.h:      parameter (MPI_OFFSET_KIND=4)
```

### Expected results:
The value should be the same across MPI implementations.

### Additional info:
https://lists.cp2k.org/private/cp2k-dev/2018-January/000856.html
https://bugzilla.redhat.com/show_bug.cgi?id=1535968

**Comment by wgropp** [comment]
The expected results are bogus.  MPI_OFFSET_KIND should create an integer suitable for file system offsets.  For most modern systems, this needs to be an 8-byte integer.

Note also that Fortran says nothing about how these values should be interpreted - a kind of “8” doesn’t guarantee an 8-byte object (in the Fortran standard), and there are Fortran compilers that use a different encoding.

Bill

William Gropp
Director and Chief Scientist, NCSA
Thomas M. Siebel Chair in Computer Science
University of Illinois Urbana-Champaign

**Comment by pavanbalaji** [comment]
@rathann Why do you need `MPI_OFFSET_KIND` to be 4 bytes?  I agree with Bill.  The reason it's an opaque handle is because different MPI implementations can define it differently.  If you are assuming that it's 4 bytes, then your program is not portable.

**Comment by pavanbalaji** [comment]
I think the right fix would be to change `cp2k-5.1` to use `MPI_Offset` type for declaring the `array_of_displacements`.  I'm closing this issue since it's not an MPICH issue.

**Comment by rathann** [comment]
@pavanbalaji I didn't actually say I need it to be 4 bytes. I was just asking why it's inconsistent between implementations. I think it should actually be the same as `off_t`, and depend on whether `-D_FILE_OFFSET_BITS=64` was present during compilation.

Unfortunately, your colleagues at OpenMPI project seem to disagree: https://github.com/open-mpi/ompi/issues/4846 .

I think it'd be best if both MPI implementations were consistent here.

**Comment by pavanbalaji** [comment]
@rathann I agree with the OMPI folks.  The MPI standard doesn't require all implementations to have the same value.  This really is a bug in `cp2k-5.1`, and a rather simple one to fix, IMO.  It could just as easily use the `MPI_Offset` type instead of `INTEGER`.  Is there a reason they don't want to fix this error?

**Comment by rathann** [comment]
Oh the bug is indeed in cp2k and fixed already (they were assuming `MPI_ADDRESS_KIND` == `MPI_OFFSET_KIND`). I just wanted to make sure you guys were aware of the inconsistency and that it was on purpose, not a bug. Thank you for your time and consideration.

**Comment by wkliao** [comment]
You might be interested in reading [this issue](https://github.com/open-mpi/ompi/issues/3195) opened at OpenMPI.

OpenMPI always configures MPI_Offset to be of size 4 bytes on 32-bit architectures, no matter the machines support LFS (large-file support) or not. MPICH on the other hand configures MPI_Offset to be of size 8 bytes when LFS is supported.
