### ISSUE TITLE
build: ch4 build problems on aarch64

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#3015]
mpich/ch4 fails to build on aarch64 with the following error messages:

```
/tmp/ccfMjWal.s: Assembler messages:
/tmp/ccfMjWal.s:101517: Error: pc-relative load offset out of range
/tmp/ccfMjWal.s:378640: Error: conditional branch out of range
```

Searching for this a bit seems to reveal that this is a limitation of GCC that gets triggered when a function has a lot of instructions: something that can happen when many functions/macros are inlined, such as what ch4 does.  More information on this can be found here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63304

This is a resource limit in GCC (and probably other compilers too) that we might run into on other platforms too, in the future.  The right solution for this would be to avoid excessive inlining for function paths that are not performance critical and to do that only for performance-critical functions.  A good step forward for this would be to move non-performance-critical functions to `.c` files instead of `.h` files.

**Comment by pavanbalaji** [comment]
Cc'ing @raffenet @yfguo @tpenya @moon6pence @Hopobcn.

**Comment by pavanbalaji** [comment]
Update: the same problem occurs with `-O2` optimization as well.  So my initial thesis that it goes away with `-O2` is not correct.

**Comment by raffenet** [comment]
@yfguo is working on removing the excessive inlining in #3464 (or #3220).

**Comment by hzhou** [comment]
I think this has been fixed since it seems no longer an issue today.
