### ISSUE TITLE
bug/jenkins: RMA fails with assertion when using struct datatypes

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3056]
When using `MPI_Accumulate` with datatypes built with `MPI_Type_create_struct` MPICH fails with: `Assertion failed in file src/mpid/ch3/src/ch3u_rma_ops.c at line 494: origin_dtp->basic_type != MPI_DATATYPE_NULL`.

**Comment by minsii** [comment]
I just noticed MPI standard (page 425 in 3.1 report) says:
```
Each datatype argument must be a predefined datatype or a derived datatype, where all basic components are of the same predefined datatype. Both datatype arguments must be constructed from the same predefined datatype. The operation op applies to elements of that predefined type.
```
The first sentence indicates that we cannot use a `struct` datatype in accumulate if the `struct` datatype contains two or more different basic datatypes.

Thus, I think we can close this PR and remove such tests in our test suite.

**Comment by minsii** [comment]
@gcongiu : @hajimefu and I have discussed this problem. We propose to add a special `struct` datatype in dtpool which contains single basic datatype (e.g., struct {int a; int b}). We can use this `single-basic-datatype struct` for RMA accumulate/get_accumulate tests. What do you think ?

**Comment by gcongiu** [comment]
@minsii this problem was concerning datatypes created with heterogeneous predefined datatypes (i.e., `DTP_pool_create_struct`) IIRC. If the standard says `accumulate` operation only expects homogeneous datatypes we can just remove the tests for `DTP_pool_create_struct` that use heterogeneous types, as you said in your previous comment. 

If you want to support `struct` of same datatype we don't need to add `single-basic-datatype struct` we already have the `DTP_pool_create_struct`. Even easier in this case because you can define your homogeneous structs in the configuration file. What is missing in `DTP_pool_create_struct` at the moment is the possibility to have a count for the struct. Indeed, this interface creates a pool containing a single element. What we may do (hopefully this won't require too many changes) is to extend such interface to take an additional parameter that defines how many struct elements we want for the pool. At this point we would create derived datatypes starting from the "basic" struct element as we do for predefined datatypes.

**Comment by gcongiu** [comment]
@minsii @hajimefu I will update the configuration file to include the required struct datatype (i.e., <int,int>) and remove the previous tests that violated the standard requirements.

**Comment by minsii** [comment]
Thanks !
