### ISSUE TITLE
bug/jenkins: ch4/ofi: bug in mixed datatypes handling

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3076]
*The way some mixed datatypes are handled in OFI is incorrect*:
• `MPI_FLOAT_INT`
• `MPI_2INT`
• `MPI_LONG_INT`

*OFI is causing problems with some of these datatypes, for example, in* `MPIDI_OFI_do_accumulate()`:
• Use `MPIDI_Datatype_check_size()` to get `origin_bytes`
  • This `MPIDI_Datatype_check_size()` considers these datatypes as non-predefined (`IS_BUILTIN`) and returns the proper size (e.g., 12 bytes for `MPI_LONG_INT`)
• Later OFI gets `basic_type = MPIDI_OFI_accumulate_get_basic_type()`
  • This internally converts target (mixed) datatypes to predefined:

```
MPIDI_OFI_GET_BASIC_TYPE(target_datatype, basic_type);
switch(basic_type) {
    /* 8 byte types */
    case MPI_FLOAT_INT:
    case MPI_2INT:
    case MPI_LONG_INT:
    {
        basic_type = MPI_LONG_LONG;
        *acc_check = 1;
        break;
    }
    /* types with pads or too large to handle */
    case MPI_DATATYPE_NULL:
    case MPI_SHORT_INT:
    case MPI_DOUBLE_INT:
    case MPI_LONG_DOUBLE_INT:
        goto unsupported;
}
...
unsupported:
    basic_type = MPI_DATATYPE_NULL;
    goto fn_exit;
```

*The previous code is incorrect*:
• `MPI_FLOAT_INT` and `MPI_2INT` are converted to `MPI_LONG_LONG` doing the implicit assumption that `sizeof(INT)=sizeof(FLOAT)=sizeof(LONG_LONG)/2`
• `MPI_LONG_INT` on 64-bit is 12 bytes and thus should be jump to unsupported instead of being converted to `MPI_LONG_LONG`

**Comment by hzhou** [comment]
This issue is obsolete.
