### ISSUE TITLE
bug/jenkins: ch4/ucx: message truncated error

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3078]
The `MPI_C_DOUBLE_COMPLEX` and `MPI_C_LONG_DOUBLE_COMPLEX` types are causing tests to fail because of a message truncated error.

**Comment by raffenet** [comment]
@gcongiu did we decide this wasn't actually a bug?

**Comment by gcongiu** [comment]
@raffenet to be honest I don't remember what exactly the problem was here. I should have a look at it again.

**Comment by hzhou** [comment]
This issue is unclear and I don't think we have similar issues now.
