### ISSUE TITLE
bug/jenkins: pair datatypes are causing issues in RMA

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3079]
Paired datatypes:

• `MPI_SHORT_INT`
• `MPI_FLOAT_INT`
• `MPI_DOUBLE_INT`
• `MPI_LONG_INT`
• `MPI_LONG_DOUBLE_INT`

are causing RMA problems in both CH3 and CH4.

• `MPI_SHORT_INT` + `test/mpi/rma/lock*` + CH4 crashes because of an assertion in `ch4r_rma_target_callbacks.h:738`. The problem seems that the code uses the `basic_sz` of the elementary datatype (i.e. `MPI_SHORT_INT`) to establish the number of bytes to transfer: `count = iov[i].iov_len / basic_sz`. `basic_sz` is 6 bytes while the first element in the `iov` has length 2. This is because `MPI_SHORT_INT` is built as an indexed type of `MPI_BYTE` with `2 blocks` + `2 holes` + `4 blocks`. When the layout of the buffer is built in `ch4r_rma.h:385`, the corresponding `dt_iov` (iovector) has a number of elements (offset, length) equal to count of `MPI_SHORT_INT` + 1 (the contiguous 4 and 2 blocks in the middle are merged into single blocks of 6 elements). The `dt_iov` layout then is: (0, 2) (4, 6) (12, 6) ... ((count-1)*extent + extent/2, 4).

**Comment by hjelmn** [comment]
Welcome to the club. We have the same issue in Open MPI (at least for the internally non-contiguous MPI_SHORT_INT). They are a pain to deal with. I am trying to get their use in RMA either deprecated (we will still all have to support them for awhile) or at least get it so there are no guarantees to the user on the state of the padding bits.

**Comment by gcongiu** [comment]
Yes, `MPI_SHORT_INT` is definitely the most problematic among all, although for some configuration all of them are causing problems.

**Comment by minsii** [comment]
@gcongiu: I agree with you that padding of `dt_iov` seems problematic. But why does `MPI_SHORT_INT ` fail only with some RMA tests ? If the `iovs` are overlapped, all RMA tests that use paired type with padding should fail.

**Comment by gcongiu** [comment]
@minsii this is the other part of the problem I need to check. `test/mpi/epochtest.c`, for example, is not failing with `MPI_SHORT_INT`. I need to check what is different for this test in terms of callpath in the mpich code.

**Comment by hzhou** [comment]
Those tests are not failing anymore, so we must have fixed them at some point.
