### ISSUE TITLE
build: BGQ build issues

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#3139]
1. VPATH build fails with embedded libfabric headers
2. Device timer does not work
3. clock_gettime not working

**Comment by KavithaTipturMadhu** [comment]
RMA programs throw error : MPIDI_OFI_win_init(429).......: OFI memory registration failed

**Comment by hajimefu** [comment]
@KavithaTipturMadhu I would love to know more like build configurations, base MPICH version (commit id), etc. CC: @shawnccx

**Comment by KavithaTipturMadhu** [comment]
> @KavithaTipturMadhu I would love to know more like build configurations, base MPICH version (commit id), etc. CC: @shawnccx

I'm building mpich master, and i'm attaching config log here. 
[config.log](https://github.com/pmodels/mpich/files/2634072/config.log)

**Comment by hajimefu** [comment]
Thanks. As a future reference, master as of now is e829fefd05a1840df46afd102941d1c127e8b3fa.

**Comment by hzhou** [comment]
I believe this is no longer of interest. If someone like this to be fixed, please re-open the issue.
