### ISSUE TITLE
bug: wrong alignments for structs with complex floating entries

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#3174]
I'm in the process of creating a couple of Python routines for mpi4py to convert datatypes between MPI and NumPy. After writing some extensive tests for them, I got some failures, and it seems the problem is within MPICH.

MPICH is not computing alignments the right way for complex floating entries in struct datatypes. Please run the self contained example at the end, you should reproduce the issue. However, if you comment out the line with `MPI_Type_dup()`, we are back to normal.

I tracked down the problem (though I might be wrong) to this line https://github.com/pmodels/mpich/blob/master/src/mpi/datatype/type_contiguous.c#L93 . This is OK for almost all builtin types, but not for C/C++ (and Fortran?) complex floating types.

I could contribute a patch but I'm not sure the best way to fix the issue. Would it be OK to use `MPIR_Datatype_get_ptr()` for  builtin datatypes and copy the alignment value from oldtype to newtype? An alternative would be to special case `MPI_C_XXX_COMPLEX` types and then `new_dtp->alignsize = el_sz/2;`, but it does not look so clean to me (Oh!, we should special case the complex types for C++ and Fortran, not just the C ones, so it is a bad idea). Thoughts?

```c
#include <stddef.h>
#include <stdio.h>
#include <complex.h>
#include <mpi.h>

typedef struct _S {
  signed char f0;
  double complex f1;
} S;

int main(int argc, char *argv[]) {
  int blocklengths[2];
  MPI_Aint displacements[2];
  MPI_Datatype types[2];
  MPI_Datatype newtype;
  MPI_Aint lb, extent;

  MPI_Init(&argc,&argv);
  blocklengths[0] = 1; displacements[0] = offsetof(S, f0); types[0] = MPI_SIGNED_CHAR;         
  blocklengths[1] = 1; displacements[1] = offsetof(S, f1); types[1] = MPI_C_DOUBLE_COMPLEX;
  MPI_Type_dup(types[1], &types[1]);
  MPI_Type_create_struct(2, blocklengths, displacements, types, &newtype);
  MPI_Type_get_extent(newtype, &lb, &extent);
  printf("c-sizeof=%d  extent=%d\n", (int)sizeof(S), (int)extent);
  if (types[1] != MPI_C_DOUBLE_COMPLEX) MPI_Type_free(&types[1]);
  MPI_Type_free(&newtype);
  MPI_Finalize();
  return 0;
}
```

**Comment by dalcinl** [comment]
@hzhou Looks like the previous issues I was experiencing are fixed in current `main`. However, I still see a few code leftovers, for example in function `MPIR_Typerep_create_resized()`:

```c
...
        newtype->alignsize = el_sz;     /* ??? */
...
        newtype->alignsize = oldsize;   /* FIXME ??? */
```

Perhaps the `alignsize` gets overwritten at a later stage? Most likely not, I guess my testing is not so comprehensive to trigger the issue.

Maybe a trivial fix for the leftover I mention above (and other similar ones in that source file) is is to just use the value from `MPIR_Datatype_builtintype_alignment()` rather than using the one from `MPIR_Datatype_get_basic_size()`. Although I'm not familiar at all with the code, looks like that may be enough.

**Comment by hzhou** [comment]
Thanks for reminding us. I'll look into it.

**Comment by hzhou** [comment]
> Looks like the previous issues I was experiencing are fixed in current `main`

@dalcinl Oh, it is fixed because we switched to a different datatype engine (`yaksa`) in `ch4`. If you try `ch3`, you will see your old familiar bug 😄

**Comment by hzhou** [comment]
> 
> 
> > Looks like the previous issues I was experiencing are fixed in current `main`
> 
> @dalcinl Oh, it is fixed because we switched to a different datatype engine (`yaksa`) in `ch4`. If you try `ch3`, you will see your old familiar bug 😄

**Comment by hzhou** [comment]
> Maybe a trivial fix for the leftover I mention above (and other similar ones in that source file) is is to just use the value from `MPIR_Datatype_builtintype_alignment()`

I am going to take your suggestion! In fact, I believe it was the intention when we added `MPIR_Datatype_builtintype_alignment()`, but at that time we were only looking at `struct`, thus neglected the other cases. 

Thanks for not giving up on your old issue :)

**Comment by dalcinl** [comment]
> If you try `ch3`, you will see your old familiar bug

Oh! Of course! Thanks for your prompt action.
