### ISSUE TITLE
build: the checking method of c11 _Static_assert does not work with icc

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3178]
The _Static_assert c11 function is not supported by Intel C compiler version 12.
See https://software.intel.com/en-us/articles/c11-support-in-intel-c-compiler

MPICH checks whether _Static_assert is supported at src/include/mpir_assert.h. The checking method does not work with icc.

**Comment by pavanbalaji** [comment]
@minsii Does this show up on jenkins?

**Comment by hzhou** [comment]
This issue should be closed. I have added compile check to configure and refactored all compile time assert macros. The original issue is when we do preprocessor check in `mpir_assert.h`. That has been refactored away now.
