### ISSUE TITLE
Issues with Intel 2018 and Fortran 2008 Support in MPICH 3.2.1

### ISSUE THREAD

**Issue by harisubramoni** [pmodels/mpich#3238]
Hi, All.

Recently, one of our users posted an issue they were facing Fortran 2008 support with MVAPICH2 when using Intel 2018 compilers.

When I looked at it, it looked like we inherited it directly from MPICH 3.2.1. I was able to observe the behavior with the MPICH 3.2.1 tarball.

This seems to be an issue with the [conftest.f90.txt](https://github.com/pmodels/mpich/files/2224878/conftest.f90.txt) being used to detect compatibility and the Intel 2018 compilers. Intel 2017 prints a warning, but does not cause an error allowing things to proceed (see the example below).

If we remove "ASYNCHRONOUS" from the attached conftest.f90, things pass. However, I am unsure whether this is the right fix. Can you please comment?

Intel 2018
=======
```
$ module list

Currently Loaded Modules:
  1) intel/18.0.1   2) mvapich2/2.2   3) texlive/2016   4) StdEnv

$ ifort -o conftest     conftest.f90
conftest.f90(74): warning #8100: The actual argument is an array section or assumed-shape array, corresponding dummy argument that has either the VOLATILE or ASYNCHRONOUS attribute shall be an assumed-shape array.   [IAR]
CALL TEST_ASSUMED_RANK_ASYNC(IAR(2:7))
-----------------------------^
conftest.f90(74): error #7505: If an actual argument is an array section with vector subscript and corresponding dummy argument does not have VALUE attribute, it must not have ASYNCHRONOUS / VOLATILE attribute.   [BUF]
CALL TEST_ASSUMED_RANK_ASYNC(IAR(2:7))
^
compilation aborted for conftest.f90 (code 1)
```

Intel 2017
======
```
$ module load intel/17.0.2

Due to MODULEPATH changes the following have been reloaded:
  1) mvapich2/2.2

The following have been reloaded with a version change:
  1) intel/18.0.1 => intel/17.0.2

$ ifort -o conftest     conftest.f90
conftest.f90(74): warning #8100: The actual argument is an array section or assumed-shape array, corresponding dummy argument that has either the VOLATILE or ASYNCHRONOUS attribute shall be an assumed-shape array.   [IAR]
CALL TEST_ASSUMED_RANK_ASYNC(IAR(2:7))
-----------------------------^
```

**Comment by raffenet** [comment]
Resolved in master and 3.2.x.
https://github.com/pmodels/mpich/pull/3282
https://github.com/pmodels/mpich/pull/3283

**Comment by raffenet** [comment]
@harisubramoni I think https://github.com/pmodels/mpich/pull/3243 should fix this issue. Tonight's nightly tarball should contain it.

**Comment by harisubramoni** [comment]
Thank you Ken. Let me try it out and get back to you.

**Comment by harisubramoni** [comment]
I confirm that the patch works :-).
