### ISSUE TITLE
coll: MPII_Treeutil_tree_knomial_2_init not returning a value

### ISSUE THREAD

**Issue by hajimefu** [pmodels/mpich#3270]
https://github.com/pmodels/mpich/blob/20cedcb02b6163523aa8653645616d42440c85ff/src/mpi/coll/algorithms/treealgo/treeutil.c#L203
This function is supposed to return `int`.

Taggning @akhillanger

**Comment by akhillanger** [comment]
Resolved in PR #3269

**Comment by hajimefu** [comment]
👍
