### ISSUE TITLE
mpicc doesn't know the 'double complex' type

### ISSUE THREAD

**Issue by yurivict** [pmodels/mpich#3313]
This type exists in C, see here for example: https://en.cppreference.com/w/c/numeric/complex/cexp

mpicc fails:
```
Cluster_DFT_ON2.c:30:18: error: expected ';' at end of declaration list
   double complex b;
                 ^
                 ;
```

```mpich-1.5_11``` installed from the package on FreeBSD 11.2.

**Comment by raffenet** [comment]
mpicc is just a wrapper around the system compiler. It has no special knowledge of types. The error here looks to me like a missing in the program:

> #Include <complex.h>

**Comment by yurivict** [comment]
No, ```#include <complex.h>``` is present. How does mpicc decide what is system compiler?

**Comment by raffenet** [comment]
It defaults the compiler used to build the library. You can see the full invocation with `mpicc- show`.

**Comment by raffenet** [comment]
It may be possible to override the default compiler by setting the `MPICH_CC` environment variable.

**Comment by yurivict** [comment]
Ok, thanks!
