### ISSUE TITLE
Better link for macOS (Homebrew) on mpich downloads page on website

### ISSUE THREAD

**Issue by zbeekman** [pmodels/mpich#3316]
I was just browsing https://www.mpich.org/downloads/ and it might be nice for the [stable] and [devel] links to point to https://formulae.brew.sh/formula/mpich rather than the homebrew formula definition at https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpich.rb

The formula page on https://brew.formulae.brew.sh/formula/mpich is probably more user friendly.

**Comment by zbeekman** [comment]
(P.S. I would be happy to create a PR if the website were hosted on GH, or some other public repository.)

**Comment by raffenet** [comment]
I agree those are better and updated the web page. We aren't hosting the page on GH, so no PRs for change at the moment :). Thanks!
