### ISSUE TITLE
Weak symbol handling is not complete for some routines

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3348]
`HAVE_WEAK_ATTRIBUTE` is not set for some routines, such as `MPI_Status_f2c` in fortran binding. We need to also systemically check if all MPI functions have added this option.

In FreeBSD 11.2, `weak attribute` is enabled but `weak pragma` is not, thus some `MPI_*` symbols cannot be found in library binaries.

**Comment by hzhou** [comment]
The profiling is not defined for the Fortran interface, so it's not clear that we need to support the profiling interface for `MPI_status_f2c`. I am going to close this issue for now.
