### ISSUE TITLE
bug/jenkins: RMA accumulate AM fallback breaks with short_int pairtype 

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3380]
In active message fallback, CH4 handles accumulate in the following steps:
1. Origin process checks if datatype is continuous
    - *Origin data type handle:*  If origin contig, send entire message; if origin noncontig, send iov structure with chunked data
        - OFI packs iovs  into a pack_buf and transfer
    - *Target data type handle:* If target noncontig, generate iov/n_iov info, and set in `am_hdrs`
    - OFI packet format: `| msg_hdr | am_hdrs | data |`
2. Target process receives the packet and performs callback function:
    1) In `MPIDI_{get_}acc_target_msg_cb`: 
        - Copy received `packed_data` into a temp buffer `MPIDI_CH4U_REQUEST(*req, req->areq.data)` (copy performed in `MPIDI_OFI_handle_short_am`)
        - Copy target iov/n_iov info from `am_hdrs` into `MPIDI_CH4U_REQUEST(rreq, req->areq.dt_iov)` and `MPIDI_CH4U_REQUEST(rreq, req->areq.n_iov)`
    2) In `MPIDI_handle_{get_}acc_cmpl`: 
        - For each iov chunk of target buffer, `compute_acc_op` with the count of elements from `MPIDI_CH4U_REQUEST(*req, req->areq.data)`
 
The above design works fine as long as each continuous chunk contains elements with the same basic datatype. However, for special predefined pairtype such as `short_int`, it is parsed as two noncontig chunks on the origin side (i.e., iov[0]: base=0, len=2; iov[1]: base=4, len=4), and packed as a 6-byte `packed_data` in netmod, but must be accumulated as a single element on the target side. Then, the above design does not work. In more complicated case, where derived datatype with `short_int` is used, one iov chunk may contain half component of `short_int`.

Possible solutions:
1. Transfer dataloop (similar to CH3):
   - Origin sets `target_dataloop` instead of iov/n_iov info in packet (extended pkt in CH3)
   - Target creates `target_datatype` by using `target_dataloop`.
   - Target unpacks received `packed_data` as contigunous `basic_datatype` (obtained from target_dataloop), stored in a temp buffer (`rreq->dev.user_buf` in CH3)
   - `compute_acc_op` with unpacked `rreq->dev.user_buf`(`basic_datatype`) and target buffer (`target_datatype`)
2. Define target iov/n_iov per `predefined_datatype`
   - Origin generates `iov/n_iov` where each iov contains full `predefined_datatype` (e.g., iov[0]: base=0, len=8 for `short_int`)
   - Origin sets `predefined_datatype` in am_hdrs
   - Target unpacks received `packed_data` into a temp buffer as contigunous `predefined_datatype`
   - Target computes each iov chunk with the same count of elements in unpacked buffer

**Comment by minsii** [comment]
This bug can be reproduced by test `atomic_get_short_int` which is added in PR #3342 .

**Comment by pavanbalaji** [comment]
@minsii Does this show up on Jenkins?  If yes, can you add a link to a failure?

**Comment by minsii** [comment]
@pavanbalaji This failure was reproduced in an old Jenkins build (Oct, 2018). But it looks like Jenkins deletes those old build records, so we do not have a link now.

The failure can be reproduced by `atomic_get_short_int ` test which is xfailed on Jenkins now.

**Comment by hzhou** [comment]
All `rma/atomic_get_[pair_types]` currently is passing on Jenkins in both ch3 and ch4 on all configurations. We must've fixed it at some point.
