### ISSUE TITLE
ch4/ofi: Regression in datatype initialization

### ISSUE THREAD

**Issue by hajimefu** [pmodels/mpich#3420]
#2671 introduced this patch:
> ch4: Initialize MPIR objects after nm/shm (c6b1a1c8c41c76a0c7fd98f6028976d8cb67c292)

This broke the datatype initialization of OFI netmod. In OFI init, there's a logic to record OFI-specific datatype index into predefined datatypes.
https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ofi/ofi_init.h#L1013, then
https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ofi/util.c#L527

Looks like this index is abandoned when `MPID_Init` later calls `MPIR_Datatype_init` as a result of c6b1a1c8c41c76a0c7fd98f6028976d8cb67c292.

This is causing segfaults with the following test cases, when `--enable-ch4-direct=netmod` and all the debug options are turned on. Argonne's Jenkins doesn't have this configuration, so it was not caught during the review of #2671.

```
./rma/atomic_get_long_int 3
./rma/atomic_get_float_int 3
./rma/atomic_get_double_int 3
./rma/atomic_get_long_double_int 3
```

**Comment by raffenet** [comment]
So I see 2 options here.
1. We move the call to `MPIDI_OFI_index_datatypes();` to `MPIDI_NM_mpi_type_commit_hook`. This ensures that datatypes are setup before ch4/ofi tries to map them to ofi types. However it has the drawback that it is re-run every time a new datatype is committed. Maybe we could add a hack to only run it as the last pre-defined datatype is committed...
2. Add a device (and nm/shm) hook to `MPIR_Datatype_init` and move this mapping out of device init.

**Comment by raffenet** [comment]
3. We could delay `MPIDI_OFI_index_datatypes();` to first window creation.

**Comment by raffenet** [comment]
I discussed this with @minsii and I think we both agree 2 is the cleanest solution. However my gut is leaning towards 3 to get this done quickly for 3.3.

**Comment by hajimefu** [comment]
I basically agree with your assessment. When another use case for `MPIR_Datatype_init` hook comes up in future, we can consider the second option.
