### ISSUE TITLE
allctypesf failing in all configurations

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#3421]
Starting on 2018-10-27, `f77/datatype/allctypesf 1` and `f90/datatype/allctypesf90 1` started failing with this output:

```
not ok 1139 - ./f77/datatype/allctypesf 1
  ---
  Directory: ./f77/datatype
  File: allctypesf
  Num-procs: 1
  Timeout: 180
  Date: "Sat Oct 27 01:10:48 2018"
  ...
## Test output (expected 'No Errors'):
##   For datatype MPI_FLOAT_INT found name 
##   For datatype MPI_DOUBLE_INT found name 
##   For datatype MPI_LONG_INT found name 
##   For datatype MPI_SHORT_INT found name 
##   For datatype MPI_LONG_DOUBLE_INT found name 
##   Found            5  errors
```

I can't be sure, but it seems that this started failing when #3342 was merged. That doesn't seem to be reflected in the pull request testing so it's possible that it was something else.

**Comment by hajimefu** [comment]
I'm not sure if #3342 was the cause. In my local testing 0b4b86e066ceaa0e8af27272e966fe11f578c23f works fine.

**Comment by minsii** [comment]
Let me do a quick investigation.

**Comment by minsii** [comment]
This failure is caused by the same commit as mentioned in issue #3420
