### ISSUE TITLE
build/jenkins: OS/X Intel compiler builds fail

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3437]
> ld: illegal thread local variable reference to regular symbol __tls___MPIR_Per_thread for architecture x86_64

**Comment by hajimefu** [comment]
Which ICC version?

**Comment by raffenet** [comment]
> mpich-mac1:~ raffenet$ icc -v
> icc version 18.0.0 (gcc version 4.9.0 compatibility)

**Comment by hajimefu** [comment]
Isee. I tested on `icc (ICC) 19.0.0.105 20180804` and it was fine.

**Comment by raffenet** [comment]
I'll note this in the release notes and we can fix it after the release candidate.

**Comment by dmey** [comment]
@raffenet I seem to have the same issue with `icc (ICC) 19.0.1.144 20181018` and `ifort (IFORT) 19.0.1.144 20181018`.

**Comment by dmey** [comment]
Has anyone been able to reproduce this issue? It looks like a blocker for Intel on macOS...

**Comment by raffenet** [comment]
@hajimefu are you still able to build MPICH with the version you listed above?

**Comment by hajimefu** [comment]
@raffenet Sorry, apparently I totally missed the context. I didn't realize this was about macOS. No, I haven't tried icc on macOS.

**Comment by kerrykey** [comment]
I see the same issue after upgrading to MacOS 10.14.4 and compiling with Intel 19.0.3.199.   Can't get mpich nor openmpi to compile on 10.14.4.

**Comment by cafaro** [comment]
Same issue:

ld: illegal thread local variable reference to regular symbol __tls___MPIR_Per_thread for architecture x86_64
make[2]: *** [lib/libpmpi.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

trying to compile MPICH-3.3 on macOS 10.14.5 with Intel icc, ICPC and fort version 19.0.4.233

Any fix/workaround ?

**Comment by kerrykey** [comment]
I down graded to previous x code and macOS 10.14.3.  Intel said they are working on a fix for their macOS compiler.

**Comment by raffenet** [comment]
I created a minimal reproducer of what I believe is the issue using ICC 18.0.0 on macOS 10.13.

Despite declaring `foo` as `extern __thread`, the compiler allocates is as a regular variable.
https://gist.github.com/raffenet/45d0a3840498602d4d272bf3c600a67d
> icc -c tls-broken.c
> nm tls-broken.o
> 0000000000000074 s EH_frame0
>                  U ___intel_new_feature_proc_init
> 0000000000000070 S _foo
> 0000000000000000 T _main
> 000000000000008c S _main.eh

However, if the variable is referenced in the same compilation unit, the compiler does allocate it as tls.
https://gist.github.com/raffenet/f2dc3dcfb01a1a69b9245e278a6a44d5

> icc -c tls-working.c
> nm tls-working.o
000000000000008c s EH_frame0
                 U ___intel_new_feature_proc_init
0000000000000050 S __tls___foo
                 U __tlv_bootstrap
0000000000000088 s _foo
0000000000000000 T _main
00000000000000a4 S _main.eh

**Comment by raffenet** [comment]
I tested this with icc version 19.0.4.233 and the problem still persists. A workaround we could add would be to always reference the `MPIR_Per_thread` structure somewhere in `src/mpi/init/initthread.c` in order to trick the compiler into doing the right thing. I will create a PR to do so.

**Comment by raffenet** [comment]
I found this Intel support forum thread from 2006 that explains the same issue: https://software.intel.com/en-us/forums/intel-c-compiler/topic/307175

**Comment by raffenet** [comment]
This was re-broken by d5991caeb6669e6c48e3f9af6bdbb43cf99ad4a1.

**Comment by raffenet** [comment]
Fixed in #4024
