### ISSUE TITLE
Too much duplication in test code

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#3441]
During patching https://github.com/pmodels/mpich/pull/3401, it become very tedious as many test code are duplicated and any patch need be duplicated as well. In this particular case, `dtpools`' `typelist` code is duplicated in 22 files and a common name change results in changes over all these files. As the duplicated code are not always exact, a manual check is often necessary or result in new breakage. 

Need a thorough refactor of many such test code to ease future maintenance.

**Comment by raffenet** [comment]
You may also want to look at https://github.com/pmodels/mpich/pull/3145. I haven't looked at it myself, but it would probably be good to combine or coordinate between the 2 efforts.

**Comment by gcongiu** [comment]
@hzhou I guess this can be closed
