### ISSUE TITLE
rma: MR key bit assignment

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [pmodels/mpich#3477]
1. MPI RMA issue with ofi : I have reported this issue earlier here. max_contexts_allowed is evaluated to 0 because max_rms_key_bits evaluates to 7 and MPIDI_Global.context_shift is 8, because of which the assert in line 531 of src/mpid/ch4/netmod/ofi/ofi_win.h fails. I removed the assert to make it work, I don’t have the exact hash with which this hack was working before, but this hack fails with the latest mpich master (segfaults in MPI_Get).

2. I checked out a much old version of mpich (357e17f3c917f6b37debf6395f01753bb8db1691), and my BSPMM RMA program seemed to work fine with smaller problems. However, when my allocation size exceeds 1024 matrix dimension (total memory in shared window in rank 0 is 16 MB, I get an error message with core dump. The error message states "DDR Correctable Error Summary : count=1 MCFIR error status: [MEMORY_CE] This bit is set when a memory CE is detected on a non-maintenance memory read op”. I used mallopt to allow larger memory blocks to be allocated and this still kept failing. 
Attaching my source file here: 
[bspmm_hierarchical-src.zip](https://github.com/pmodels/mpich/files/2698719/bspmm_hierarchical-src.zip)

**Comment by pavanbalaji** [comment]
Is there a test program in the mpich test suite that fails with master?

**Comment by KavithaTipturMadhu** [comment]
> Is there a test program in the mpich test suite that fails with master?

I'll check if we have a test example. Otherwise, I can create a simple case and see if that fails.
