### ISSUE TITLE
lightweight request type does not match all usage

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3497]
The lightweight request returned by completed collective, pt2pt, and RMA operations is statically set to `MPIR_REQUEST_KIND__SEND`. We should either create requests for each type we intend to use, or a "special" type that is known to cover all potential use-cases.

**Comment by hzhou** [comment]
I don't remember if we had this discussion, but why can't we use a predefined integer e.g. `MPI_REQUEST_COMPLETE` and be checked just the way we treated `MPI_REQUEST_NULL`?

**Comment by raffenet** [comment]
No technical reason. The tradeoff is we need to add special cases to the request processing functions for that predefined value.

**Comment by hzhou** [comment]
We treat the special case of `MPI_REQUEST_NULL` anyway, so I think we can treat them together with no additional cost (they are all buit-ins). The light weight request seems to be popping up issues so I wonder if we should re-evaluate its cost (in complexity). It needs init/destroy, and it needs kind, and it is being dealt at deeper level than necessary. Well, I am not really understanding how the light-weight request works, so correct me if I am wrong.

**Comment by hzhou** [comment]
I believe this issue is obsolete with #4550
