### ISSUE TITLE
ch4: optimize XPMEM shmmod

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3515]
#3512 enables the basic support of XPMEM. As the next step, we plan to add the following features under the XPMEM shmmod:
- [ ] Segment cache bug fix. The user program may free a cached buffer and reallocate. The newly allocated buffer may have the same virtual address but map to a different physical address. When using the newly allocated buffer in MPI calls, the XPMEM cache mechanism will find the matching segment which was mapped to the old physical address. Segfault may occur in such a situation. To fix the bug, we need track the user malloc/free function calls, or limit the use of segment cache (e.g., only for buffers allocated by MPI_Alloc_mem).
- [ ] Support noncontiguous send
- [ ] Optimize send/recv LMT protocols
     - [ ] receiver-first 
     - [x] cooperative-copy
- [ ] Optimize collectives over XPMEM
- [x] Optimize attached buffer caching. We need to cache attached buffer info  (each info segment may contain `<offset, size, attached_vaddr>` on every process in order to reuse it for future messages. The caching mechanism uses the preallocated buffer pool (i.e., `MPIR_Handle_obj_alloc`) in order to avoid memory allocation per message. AVL tree structure is used for address range search.
- [ ] Control the number of cached segments to avoid unnecessary memory consumption. As a possible issue, Linux limits the amount of memory maps that can be created by a process (see `vm.max_map_count`), results in limited number of xpmem segments being attached by a process (e.g., attaching more than 64K segments on Cori will result in syserror `12 (Cannot allocate memory)`).
- [x] Mechanism to allow user to enable/disable XPMEM at runtime (i.e., through CVAR).

**Comment by pavanbalaji** [comment]
> Initialize XPMEM resource on demand (i.e., #3452 creates local segid and remote apids at MPIDI_XPMEM_mpi_init_hook, thus always consuming O(ppn) memory for storing other local processes' apids even when XPMEM is unused at runtime).

Are the `segid` and `apid` very large?  If not, I'm not sure we should be too worried about the `O(ppn)` storage.

**Comment by minsii** [comment]
Both ids are integer type.  Only `apid` consumes `O(ppn)` per process, so `O(ppn^2)` per node. It is not large anyway.

Maybe a more important memory consumption is the storage for attached buffer info. We want to use preallocated buffer pool to avoid memory allocation per message.

**Comment by pavanbalaji** [comment]
The description needs to be updated to remove the `O(ppn)` storage for the metadata and the buffer info storage needs to be added.  The current description doesn't mention that.  Also, some indication of the size of that structure should be added.

**Comment by minsii** [comment]
> The description needs to be updated to remove the O(ppn) storage for the metadata and the buffer info storage needs to be added. The current description doesn't mention that. Also, some indication of the size of that structure should be added.

I updated the description.

**Comment by minsii** [comment]
Last update on 2020-04-21

**Comment by hzhou** [comment]
These to-do items are either outdated or no longer being pursued.
