### ISSUE TITLE
ch4: namespace refactoring

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3518]
Track progress on fixing the ch4 namespace inconsistencies and excessive function inlining. See also issue #3015 and pull requests #3220, #3464.

**Comment by pavanbalaji** [comment]
This sounds like a neverending issue if it's phrased as "track progress on something".  Maybe it's better to break it down into smaller issues, each of which looks at fixing a specific thing.

**Comment by yfguo** [comment]
#3464 now has the latest status for the namespace cleanup. I plan to add the uninlining commits on top of that. #3015 and #3220 are for reference only now.

**Comment by gcongiu** [comment]
@raffenet I don't think I did. I only worked on part of the namespace refactoring.

**Comment by raffenet** [comment]
Some remaining instances of `MPIDI_CH4*` naming that should be removed. 
[namespace.txt](https://github.com/pmodels/mpich/files/2956971/namespace.txt)

**Comment by hzhou** [comment]
Shall this issue be closed?

**Comment by hzhou** [comment]
I think this is done.
