### ISSUE TITLE
Improve SHM/POSIX active message

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3525]
Current CH4/SHM/POSIX always uses `fastbox` for active messages (All SHM pt2pt messages go through the active message routine). There is still performance gap between CH3 and CH4. This issue is created to track the performance issues and improve the CH4 version.

- [ ] Measure the performance of CH3 and CH4 `fastbox` and make sure they are equivalent
- [x] Enable `iqueue` (similar to CH3 `cells`) in CH4 (addressed by #3873)
   +  Support `fbox-only` and `iqueue-only` config.
- [ ] Investigate if the `hybrid fbox+iqueue` config is needed in CH4.
   + `iqueue` is used when the `fastbox` is not free or if it's not large enough for the message.
   + `iqueue` outperforms `fastbox` in most cases, except for small message latency
- [ ] Investigate if CH3 `LMT` RNDV protocol is needed in CH4.
   + The `LMT` protocol creates additional shared buffer among two processes. 
    + A `LMT` message is completed by handshake + pipelined double copy.

**Comment by Bayyapu** [comment]
@wesbland  I am trying to note the FY19Q2 progress. Could you please attach a working PR to this issue to monitor the progress or update the issue with the related information?

**Comment by minsii** [comment]
There is no working PR at this moment. The original plan is to let Intel team work on it, but the plan seems changed. @pavanbalaji I am afraid that no one is working on this topic and can finish at Q2. should we move it to Q3 ?

**Comment by wesbland** [comment]
I have a small PR that I can submit that helps a little, but it’s not the main one. 

I’m still working on this, but I wasn’t able to do much on it in the last couple months. I’d estimate that it’ll probably be more than one quarter before there’s something I can send upstream. 

When I have a more concrete plan, we can have a discussion about how to move forward without duplicating effort.

**Comment by hzhou** [comment]
This ticket is done.
