### ISSUE TITLE
build: fails with --enable-izem=sync

### ISSUE THREAD

**Issue by rzambre** [pmodels/mpich#3545]
Build environment: RHEL 7.5 (a JLSE compute node)

Configure options:
`../configure --with-device=ch4:ucx --with-ucx=/path/to/ucx --prefix=/path/to/install --disable-fortran --enable-izem=sync --with-zm-prefix=yes`

Error:
```
In file included from ../src/mpid/ch4/include/mpid_thread.h:14:0,
                 from ../src/mpid/ch4/include/mpidpre.h:23,
                 from ../src/include/mpiimpl.h:207,
                 from ../src/mpi/datatype/pack_size.c:8:
../src/mpid/common/thread/mpidu_thread_fallback.h:13:26: fatal error: lock/zm_lock.h: No such file or directory
 #include "lock/zm_lock.h"
                          ^
```

**Comment by halimamer** [comment]
`--enable-izem=sync` is to enable izem synchronization primitives like locks. Do you really need it?
I you still want them, then you need to point at a hwloc installation with `--with-hwloc`

**Comment by pavanbalaji** [comment]
Does it not work with the embedded `hwloc`?  MPICH's configure can probably pass that in.

**Comment by halimamer** [comment]
I'll have to look into it again. Last time I tried to do it was when `hwloc` was part of hydra and it needed some work. Now that `hwloc` is a standalone submodule, it should be easier. I will leave this issue open to track progress on this.

**Comment by rzambre** [comment]
I tried using `--with-hwloc-prefix` (with both the `embedded` option and pointing to a standalone hwloc installation) but I am running into the same error. The config succeeds, like before. I think the error might be due to the fact that there is no `include/lock` directory in the izem installation location?

**Comment by hzhou** [comment]
This issue is no longer being worked on and probably not relevant as well. Closing it.
