### ISSUE TITLE
OFI: Can't rely on fi_tinject for collectives

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#3551]
Apparently, in Open MPI, @a-ilango was seeing problems where `fi_tinject` was completing successfully, but the message was not actually arriving. He traced this back to the fact that `fi_tinject`'s completion does not actually indicate that the message has been sent (in the same way that `MPI_Send` does not indicate that the message has been sent).

According to @sayantansur, we should be able to use `FI_DELIVERY_COMPLETE` and have the completion counter be incremented when the message actually arrives, but that doesn't help in the case where we have `MPI_ERRORS_RETURN` (or even more challenging, a custom error handler) where we wouldn't be able to tell on which communicator the error occurred (so we couldn't fire the correct error handler). This is because we lack an `fi_context` to be able to refer back to the calling object.

This is fine for `MPI_Send`. It allows us to implement it for small messages directly by calling `fi_tinject`. However, for things that have a different semantic, for example collectives, this could cause problems where messages never arrive and the sender is never aware of it, leading to a hang.

It sounds like we might need to avoid using `fi_tinject` for collectives (and potentially anything else that's using `fi_tinject` internally where dropping messages would be a problem), even when the message is small and always force the usage of the full-fledged `fi_tsend` so we can get back completion events. We could probably just do this when we turn on error handling via a configure flag so we'd have a fast path in the optimized case where we're not doing error handling.

**Comment by wesbland** [comment]
This thread is a little stale on my end so I'm not able find the original discussion, but I believe that the problem was that OFI was trying to return errors saying that messages couldn't be delivered (probably `-FI_EAGAIN`) and the sending function wasn't dealing with them so the application was deadlocking.

**Comment by pavanbalaji** [comment]
That doesn't sound right for a correct application.  I don't think this is a bug in mpich.

**Comment by wesbland** [comment]
I'm not sure how that's not a correct application. If the application hits flow control, we don't usually assign blame to the application. We say that MPICH (or the layer underneath) should handle it. For OFI, it's perfectly valid to return `FI_EAGAIN` when there are no more resources available to buffer messages. In that case, MPICH either needs to handle it internally (which we usually do in the OFI netmod) or return a similar error class to the user (which was recently added in #2976).

**Comment by sayantansur** [comment]
Let's try to recall what the discussion originally was. What are we trying to do here: abort the collective when there is a lost message, abort the collective on user error, or deal with flow control?

**Comment by sayantansur** [comment]
This thread is very confusing to me. This statement is confusing two things: completion of a message and when the call returns.  _"fi_tinject's completion does not actually indicate that the message has been sent (in the same way that MPI_Send does not indicate that the message has been sent)."_

fi_tinject does not have a completion. The completion is set at the endpoint level. fi_tinject _returns_ when the data has been buffered locally (but may not have been delivered).

I suggest we clearly describe what it is that we're trying to achieve here, beyond just describing what Arun may have observed with OpenMPI.

**Comment by a-ilango** [comment]
I found the email thread regarding the OpenMPI discussion. To summarize: inject operations can fail and can be detected by reading the error entry from CQ but the error entry would not provide any context since it was an inject op. MPI should do some sort of book-keeping on its end if it needs the context.

Also, as long as the app reads the CQ at sometime, any errors that happen would be conveyed so there wouldn't be any deadlock.

EAGAIN is returned when there isn't enough resources to send the message. Apps should read the CQ to free up the resources and try sending again.

**Comment by sayantansur** [comment]
The error @a-ilango mentions is a catastrophic error, such as a programmer error, or a link failure.

This is not to be confused with buffering/flow-control issues such as those indicated by FI_EAGAIN ... FI_EAGAIN is returned when you call fi_tinject(), and not the status of the completion counter.

I think the failure indicated here is sufficiently drastic, that all operations on that EP should fail, or could fail.

**Comment by pavanbalaji** [comment]
I agree.  The description/discussion is mixing up (1) catastrophic errors vs. flow-control errors, and (2) point-to-point vs. collectives (which I feel is completely irrelevant here).

**Comment by pavanbalaji** [comment]
@wesbland Any follow-up on this?  I'll close this issue for now as I don't think it's a real issue.  But please reopen if I misunderstood something.

**Comment by wesbland** [comment]
I don’t have time to go track this down. Closing it is fine.
