### ISSUE TITLE
Incorrect semantics in test/mpi/rma/rget_testall.c?

### ISSUE THREAD

**Issue by spickartz** [pmodels/mpich#3558]
Hello,

I have a question concerning the `get_testall.c` test as part of the RMA tests. Here, you can see the relevant parts of the code:

```
    MPI_Win_allocate(2 * sizeof(int), sizeof(int), MPI_INFO_NULL, MPI_COMM_WORLD, &baseptr, &win);

    /* Initialize window buffer */
    MPI_Win_lock(MPI_LOCK_EXCLUSIVE, rank, 0, win);
    baseptr[0] = 1;
    baseptr[1] = 2;
    MPI_Win_unlock(rank, win);

    /* Issue request-based get with testall. */
    MPI_Win_lock_all(0, win);
    MPI_Rget(&val1, 1, MPI_INT, 0, 0, 1, MPI_INT, win, &reqs[0]);
    MPI_Rget(&val2, 1, MPI_INT, 0, 1, 1, MPI_INT, win, &reqs[1]);

    do {
        mpi_errno = MPI_Testall(2, reqs, &flag, stats);
    } while (flag == 0);

    /* Check get value. */
    if (val1 != 1 || val2 != 2) {
        printf("%d - Got val1 = %d, val2 = %d, expected 1, 2\n", rank, val1, val2);
        fflush(stdout);
        errs++;
    }
```

How can we be sure that Rank 0 has written to `baseptr[0]` and `baseptr[1]` when Rank 1 issues the calls to `MPI_Rget()` without further synchronization?

Concerning synchronization between locking periods and exposure epochs, the MPI standard states the following (MPI-3.1 p447 45-46):

> Users need to use explicit synchronization code in order to enforce mutual exclusion between locking periods and exposure epochs on a window.

Therefore, I would guess that the tests needs an additional call to `MPI_Barrier()` before calling `MPI_Win_lock_all()`. Or am I missing something here?

Thanks a lot for your comments!
Simon

**Comment by spickartz** [comment]
Sorr

**Comment by pavanbalaji** [comment]
@spickartz Yes, the test is buggy and the proposed solution is correct.  Could you create a PR for it?

**Comment by spickartz** [comment]
@pavanbalaji Sorry for the huge delay. I finally opened the appropriate PR (see #4062).
