### ISSUE TITLE
Misc CH4 bugs

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#3566]
This issue tracks the failures of the following tests that are xfailed in pmodels/mpich#3565.

```
ofi * am-only ch4:ofi * sed -i "s+\(^issendf .*\)+\1 xfail=ticket0+g" test/mpi/f77/pt2pt/testlist
ofi * am-only ch4:ofi * sed -i "s+\(^issendf90 .*\)+\1 xfail=ticket0+g" test/mpi/f90/pt2pt/testlist
ofi * am-only ch4:ofi * sed -i "s+\(^cancelanysrc .*\)+\1 xfail=ticket0+g" test/mpi/pt2pt/testlist
ofi * am-only ch4:ofi * sed -i "s+\(^huge_anysrc .*\)+\1 xfail=ticket0+g" test/mpi/pt2pt/testlist
```

There are four ch4-level bugs. They currently present in ofi AM-only tests.
It does not show up in ucx jobs because the default ch4/ucx configuration avoids ch4-level shared memory.

**Comment by wesbland** [comment]
These are probably due to the problem that @ddurnov raised previously with the AM-only mode where both the OFI netmod and the ch4/shm code are attaching active message handlers and we don't have a way of routing messages correctly.

**Comment by hzhou** [comment]
I believe the issue no longer exists.
