### ISSUE TITLE
missing MPI Fortran function interface declaration in mpi.mod

### ISSUE THREAD

**Issue by wkliao** [pmodels/mpich#3568]
MPI_Scatter (and many other MPI functions) does not seem to appear in mpi.mod. Below is an error I got. I am using mpifort of MPICH version 3.2.

```
% mpifort test.f90 -c

          use mpi, only: MPI_SUCCESS, MPI_Error_class, MPI_INTEGER, MPI_Scatter
                                                                   1
Error: Symbol 'mpi_scatter' referenced at (1) not found in module 'mpi'
```
The compiler complains function MPI_Scatter missing, but not MPI_Error_class.

**Comment by raffenet** [comment]
`mpi.mod` in MPICH does not contain declarations for functions with choice buffer arguments. They are implicitly declared and resolved at link-time.

**Comment by wkliao** [comment]
Thanks for the information
