### ISSUE TITLE
/lib64/libXNVCtrl.so.0 dependence in 3.3

### ISSUE THREAD

**Issue by mcuma** [pmodels/mpich#3573]
If CUDA is found on a machine where MPICH is built, /lib64/libXNVCtrl.so.0 gets included in the MPICH library (libmpi.so). I tried the --without-x or --with-x=no options but it does not affect this. If I build on a machine that does not have CUDA, /lib64/libXNVCtrl.so.0 is not included and the library seems to work the same (on typical MPI applications).

Further testing shows that this issue is due to hwloc's graphics integration, and can be disabled by putting two options, (enable_gl=no, enable_opencl=no) to src/pm/hydra/configure. We can either do this or wrap it around the --without-x configure option.

OpenMPI is doing something similar at https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/hwloc201/configure.m4#L95, hardcoding disabling the GL/OpenCL.

This will be an issue for heterogeneous clusters where some nodes have GPUs and GPU stack, and some don't. If one builds MPICH on a node with the GPU stack, and runs on one where it's not, on will get a missing libXNVCtrl.so.0 error in mpiexec.

After discovering this issue a few days ago, we just had a ticket from an user building VisIt on a top of his own MPICH 3.3 build that got the same issue. So, we believe this should be taken care of to avoid troubles like this.

I would have created a pull request but I am not all that familiar with the configure scripts integration in MPICH (e.g. relation of the base configure, which also has the hwloc testing, and the one at src/pm/hydra), so I figured it'd be better left to those who know it better.

**Comment by hzhou** [comment]
We have added `--without-cuda` option.

**Comment by hzhou** [comment]
With #5334 we also hardcoded to disabling the GL/OpenCL dependency in hwloc.
