### ISSUE TITLE
Enable GPU-aware generic fallback

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3582]
Current MPICH does not fully support GPU communication. The netmod supports partial GPU communication (e.g., UCX supports only contig GPU data transfer when GPUDirect RDMA is available). We need to extend the existing CH4 code to provide a generic fall back implementation to fully support GPU communication for different architectures (e.g., **assuming no GPUDirect feature is available**) and various communication patterns (e.g., contig or noncontig).

The framework needs to be extended for both **PT2PT** and **RMA**. The following functionalities are required:

- [ ] Contiguous data movement for inter-node communication (e.g., extra DMA + memcpy via host buffers on both sender and receiver for GPU->GPU send/recv)
- [ ] Contiguous data movement for intra-node communication
- [ ] Noncontiguous data movement for inter-node communication (e.g., packed/unpacked via host buffers)
- [ ] Noncontiguous data movement for intra-node communication
- [ ] Reduction operations support through CPU computation (CPU gets GPU data and computes on the CPU)

**Comment by hzhou** [comment]
This is stale and all the fallback paths have completed.
