### ISSUE TITLE
GPU-aware contiguous data movement optimization

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3583]
On GPU platforms, the data movement can be implemented in the following ways in MPICH (take inter-node transfer as the example):
1. The most generic approach is to assume that `neither GPU feature nor hw network feature is available`, which will be addressed in the generic fallback (see #3582).
2. When both `GPUDirect RDMA + hw network feature` (e.g., tag matching for MPI send/recv, RDMA for MPI RMA) are available, we assume the network layer will support it directly, thus no work is needed in MPICH.
3. When the `hw network feature` is not available or `GPUDirect RDMA` is not available, we can provide semi-fast paths for data transfer in MPICH ( `3` is faster than `1`, but slower than `2`)

In this issue, we will optimize contiguous data movement in **option-3** by using GPU features when available. Different optimizations may be designed for cases that involve different communication models (e.g., **point-to-point**, **RMA**), different memory types (e.g., **GPU/CPU pinned mem**, **CUDA unified mem**), different data access directions (e.g., **GPU<->CPU**, **GPU<->GPU**), and **inter-node** or **intra-node** transfer. Possible optimizations could include:

- [ ] Intra-node communication with `GPU Direct 1.0 support` (e.g., via shared pinned host buffer)
- [ ] Intra-node RMA-specific optimization with `GPU Direct 1.0 support` (e.g., optimize `CPU-side win_allocate` by registering remote shared win buffer as pinned host memory)
- [x] Intra-node communication with `GPU Direct 2.0 (IPC) support`(e.g., exchange memory handler and direct DMA for large `GPU<->GPU`/`GPU<->CPU` message)
- [x] Intra-node RMA-specific optimization with `GPU Direct 2.0 (IPC) support` (e.g., exchange memory handler for `GPU-side window` at creation and direct DMA per operation)
- [ ] Inter-node communication with `GPU Direct 1.0 support` (e.g., via pinned network-registered host buffer)
- [ ] Inter-node communication with `GPU Direct 3.0 (RDMA) support` (e.g., using network-registered GPU buffer)
- [ ] Inter-node RMA-specific optimization with `GPU Direct 3.0 (RDMA) support` (e.g., network-registered `GPU-side window`)
- [ ] Optimization with `unified virtual addressing (UVA) support`
- [ ] Optimization when `CUDA unified memory` is used.

<h3>Implementation note</h3>

The optimization code structure can follow `try-and-fallback` logic to avoid complex arch-dependent condition check.

**Comment by hzhou** [comment]
Status: The intra-node IPC is implemented for both pt2pt and rma. For pt2pt, only when sender is from device is implemented. Sending from host buffer and receiving from device buffer is in the plan.

GPU Direct to RDMA is via netmod native path when ucx and libfabric supports it. There is no plan to implement it in MPICH otherwise.

Unified virtual addressing is *assumed*.

Since this ticket is quite outdated, I am closing it.
