### ISSUE TITLE
GPU-aware reduction offloading

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3584]
Some MPI reduce operation involves expensive computation. For instance, NWCHEM frequently issues accumulates with multi-dimensional matrix data, resulting in communication bottleneck. When GPU is available, we should try to use it to accelerate the computation.

This optimization is valid for **RMA accumulate** as well as all **collective reduction operations** (e.g., `MPI_Reduce`, `MPI_Allreduce`...).

The optimization can be separated into three steps:
1. Offload computation to GPU
2. Compute & data copy pipelining
3. GPU idleness aware optimization (i.e., offload computation only when `(1) GPU is idle` and `(2) offload overhead + GPU compute time < CPU compute time`)

**Comment by hzhou** [comment]
Reference #5293 and #5445
