### ISSUE TITLE
Refactor MPIDU_Sched to MPIR_Sched

### ISSUE THREAD

**Issue by rzambre** [pmodels/mpich#3596]
The non-blocking collective operations use the `MPIR_Sched_*`  calls to generate and execute schedules. However, the actual implementation of the `MPIR_Sched_*` API is done by `MPIDU_Sched_*` functions. Both CH3 and CH4 simply redefine these `MPIR_Sched _*` calls to `MPIDU_Sched_*` calls. They do not have any device-specific implementations for these functions. More importantly, these functions implement the logic of executing the schedule of a non-blocking collective, which cannot be regarded as a utility function. 

Seemingly, the current function definitions of `Sched` should lie directly in the `MPIR` namespace (in `src/include/mpir_sched.h`).

**Comment by hzhou** [comment]
I think the suggestion has been abandoned at this point.
