### ISSUE TITLE
Shared memory based `allgather` function

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3599]
An `allgather` function that works at MPI init time (i.e., when no communicator is available yet) is needed by several components in the code. For example, XPMEM initialization requires processes to exchange `sigid`s; Similarly, heterogeneous memory support requires processes to exchange their numa's logical ids for partitioning intranode communication shared memory segments and bind them appropriately.

Such functionality can be provided by a new function, e.g., `MPIDU_shm_allgather`, which will have the same signature as `MPIR_Allgather` exception made for the communicator argument. Additionally we can restrict the support to only contiguous datatypes.

**Comment by hzhou** [comment]
Ideally, this should be implemented as a `PMI` function: the process call `PMI_request_shm(SIZE)`, the PMI server or hydra_proxy either create a shared memory of size `SIZE x NLOCALRANKS` or return the handle of existing one. There may be additional parameters to specify either POSIX or XPMEM. Then you won't need the `allgather` function, each process simply write to their memory block. Would this work?

**Comment by pavanbalaji** [comment]
PMI API is mostly fixed because there are multiple implementations of PMI (from SLURM, Microsoft, etc.)
