### ISSUE TITLE
build: ch4 failure --with-hcoll

### ISSUE THREAD

**Issue by rzambre** [pmodels/mpich#3611]
I set `LD_LIBRARY_PATH`, `LIBRARY_PATH`, and `C_INCLUDE_PATH` to point to the `hcoll` and `sharp` files I downloaded from http://www.mellanox.com/page/products_dyn?product_family=189&mtag=hpc-x.

My configuration options were:
`../configure --prefix=/home/rzambre/mpich/release-install --with-device=ch4:ucx --with-ucx=/home/rzambre/install/ucx-1.5.0 --disable-fortran --enable-thread-cs=per-vci --with-hcoll=/home/rzambre/hpcx-v2.3.0-gcc-MLNX_OFED_LINUX-4.4-2.0.7.0-redhat7.5-x86_64/hcoll`

The error is 
```
In file included from /home/rzambre/mpich/src/mpl/include/mpl.h:16:0,
                 from ../src/include/mpiimpl.h:136,
                 from ../src/mpid/common/hcoll/hcoll_dtypes.c:2:
/home/rzambre/mpich/src/mpl/include/mpl_trmem.h: In function ‘MPL_aligned_alloc’:
/home/rzambre/mpich/src/mpl/include/mpl_trmem.h:252:5: warning: implicit declaration of function ‘aligned_alloc’ [-Wimplicit-function-declaration]
     return aligned_alloc(alignment, size);
     ^
/home/rzambre/mpich/src/mpl/include/mpl_trmem.h:252:5: warning: return makes pointer from integer without a cast [enabled by default]
../src/mpid/common/hcoll/hcoll_rte.c: In function ‘get_mpi_type_envelope’:
../src/mpid/common/hcoll/hcoll_rte.c:435:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     MPI_Datatype dt_handle = (MPI_Datatype) mpi_type;
                              ^
../src/mpid/common/hcoll/hcoll_rte.c: In function ‘get_mpi_type_contents’:
../src/mpid/ch4/netmod/ucx/globals.c:14:1: warning: braces around scalar initializer [enabled by default]
 MPIDI_UCX_global_t MPIDI_UCX_global = { {0} };
 ^
../src/mpid/ch4/netmod/ucx/globals.c:14:1: warning: (near initialization for ‘MPIDI_UCX_global.avtid’) [enabled by default]
../src/mpid/common/hcoll/hcoll_rte.c:449:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     MPI_Datatype dt_handle = (MPI_Datatype) mpi_type;
                              ^
../src/mpid/common/hcoll/hcoll_rte.c: In function ‘get_hcoll_type’:
../src/mpid/common/hcoll/hcoll_rte.c:462:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     MPI_Datatype dt_handle = (MPI_Datatype) mpi_type;
                              ^
  GEN      lib/libmpi.la
libtool: warning: library '/home/rzambre/hpcx-v2.3.0-gcc-MLNX_OFED_LINUX-4.4-2.0.7.0-redhat7.5-x86_64/hcoll/lib/libhcoll.la' was moved.
/usr/bin/ld: cannot find -libmad
/usr/bin/ld: cannot find -libumad
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libmpi.la] Error 1
make[2]: Leaving directory `/home/rzambre/mpich/hcoll-build'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/rzambre/mpich/hcoll-build'
make: *** [install] Error 2
```
but the `libibmad` and `libibumad` are indeed present
```
[rzambre@gomez02 ~]$ ldconfig -p | grep mad
	libibumad.so.3 (libc6,x86-64) => /lib64/libibumad.so.3
	libibmad.so.5 (libc6,x86-64) => /lib64/libibmad.so.5
```

**Comment by raffenet** [comment]
In my experience, this issue is the linker is looking for `libib[u]mad.so`. You need the devel packages, which you can request from `help@jlse.anl.gov`.

> -bash-4.2$ yum search mad-devel
> =========================================================================== N/S matched: mad-devel ============================================================================
> libibmad-devel.i686 : Development files for the libibmad library
> libibmad-devel.x86_64 : Development files for the libibmad library
> libibumad-devel.i686 : Development files for the libibumad library
> libibumad-devel.x86_64 : Development files for the libibumad library

You could also hack the libtool archive file for hcoll to not explicitly add all those extra libraries since inter-library dependencies work on this platform. I have done this successfully in the past.
