### ISSUE TITLE
coll: potential gentran bugs

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#3616]
There are certain collective gentran based algorithm reports singular test failure on particular build. The error does not reproduce on most other builds except for a specific ones, indicating the error may not be specific to the top-layer code but a stress situation for the underlying transport. This issue is to remind us to investigate. 

Case 1: PR #3438, the error only reproduces with ch3:mxm build. 

     ./coll/allred 7 MPIR_CVAR_ALLREDUCE_DEVICE_COLLECTIVE=0     
                          MPIR_CVAR_ALLREDUCE_INTRA_ALGORITHM=nb
                          MPIR_CVAR_IALLREDUCE_DEVICE_COLLECTIVE=0 
                          MPIR_CVAR_IALLREDUCE_INTRA_ALGORITHM=ring
    not ok 350 - ./coll/allred 7
     
    ## Test output (expected 'No Errors'):
    ## Assertion failed in file src/mpid/ch3/channels/nemesis/netmod/mxm/mxm_poll.c 
         at line 459: n_iov > 0

Case 2: ref #3417 (the failing test is for not related to this PR in particular). The error only appears on `ch4:ucx` build and only for one of the config type -- `embedded`. The repeated run did not reproduce the error.

    ./coll/alltoallv0 10 MPIR_CVAR_ALLTOALLV_DEVICE_COLLECTIVE=0 
                                MPIR_CVAR_ALLTOALLV_INTRA_ALGORITHM=nb 
                                MPIR_CVAR_IALLTOALLV_DEVICE_COLLECTIVE=0 
                                MPIR_CVAR_IALLTOALLV_INTRA_ALGORITHM=gentran_scattered 
                                MPIR_CVAR_IALLTOALLV_SCATTERED_BATCH_SIZE=2 
                                MPIR_CVAR_IALLTOALLV_SCATTERED_OUTSTANDING_TASKS=8
    not ok 477 - ./coll/alltoallv0 10

    ## Test output (expected 'No Errors'):
    ## [bb80:23298:0:23298] ucp_proxy_ep.c:215  UCX Assertion `proxy_ep->uct_ep != ((void *)0)'

**Comment by tarudoodi** [comment]
I tried reproducing the second bug with the branch in PR #3417 but it did not show up in about 10 -15 runs.

**Comment by pavanbalaji** [comment]
The second error is not related to this issue.  It shows up every once in a while (even with `master`).  It's unclear if that's an mpich bug or a UCX bug and needs more investigation.  It's already covered under #3537.

**Comment by hzhou** [comment]
`mxm` build are no longer supported, and the UCX bug is apparently not related.
