### ISSUE TITLE
Node level split bug in comm_split_type

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#3625]
When splitting communicator by `subcomm_min_size` or `min_memsize` the current `comm_split_type` code does a first split at the network level and then, if `subcomm_min_size` is still smaller than the number of processes in the node, it further splits the sub communicator at the node level.

In order to do this it:

1. finds the covering object in the topology tree for every process (`bindset`) in the node
2. finds the `min_tree_depth` for all the covering objects
3. goes through the subtree roots at `min_tree_depth` and finds out what process fits under which subtree. The number of such processes per subtree should then be accounted for by an array `processes_cpuset` (`sizeof(processes_cpuset) = # of subtrees`).
4. the subtree array is parsed to build colors based on the `subcomm_min_size`. This is done by further merging processes in adjacent subtrees together until the desired min size is reached and assigning the color as the index of the root of the first subtree in the group.

However, for each `i` `processes_cpuset[i] = 1`. Thus, it would probably group processes in the wrong way.

**Comment by KavithaTipturMadhu** [comment]
I don't understand why 
(`num_processes_at_node[node_index] = 1` always is true. There is an allreduce call before node/network level split happens which updates this bitmap.

**Comment by gcongiu** [comment]
@KavithaTipturMadhu thank you for the clarification, I missed that. I will update the issue. Can you say anything about the second part, i.e., the `process_cpuset[i]=1`? Did I misinterpreted that one too?

**Comment by KavithaTipturMadhu** [comment]
The processes_cpuset[hw_obj_index] assignment in line 661 is buggy and should be modified to increment instead of being assigned value 1.
