### ISSUE TITLE
Baidu's ring algorithm for Allreduce

### ISSUE THREAD

**Issue by akhillanger** [pmodels/mpich#3631]
This is about Badiu's ring algorithm for Allreduce (http://andrew.gibiansky.com/). This algorithm was reverted from MPICH (commit 643f6c4724) because of a bug in one of the configurations (as I have been told). This algorithm is useful for ML/DL apps and should be resurrected once the bug is fixed.

**Comment by hzhou** [comment]
It was reopened in #3662.
