### ISSUE TITLE
mpich-3.3 build error on linux with OracleDeveloperStudio12.6 compilers.

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#3648]
I'm seeing mpich build error on linux with OracleDeveloperStudio12.6 compilers.

```
  GEN      lib/libmpi.la
f90: Warning: Option -shared passed to ld, if ld is invoked, ignored otherwise
/usr/bin/ld: /sandbox/balay/soft/OracleDeveloperStudio12.6-linux-x86-bin/developerstudio12.6/lib/compilers/amd64/crt1x.o: relocation R_X86_64_32 against `__dso_handle' can not be used when making a shared object; recompile with -fPIC
/sandbox/balay/soft/OracleDeveloperStudio12.6-linux-x86-bin/developerstudio12.6/lib/compilers/amd64/crt1x.o: error adding symbols: Bad value
postopt: error: ld failed to link the binary

```
Attaching coresponding config.log
[config.log.txt](https://github.com/pmodels/mpich/files/2944114/config.log.txt)

**Comment by balay** [comment]
BTW: To reproduce - you can use these compilers on MCS/Linux machines with

```
export PATH=/homes/petsc/soft/linux-Ubuntu_14.04-x86_64/OracleDeveloperStudio12.6-linux-x86-bin/developerstudio12.6/bin:$PATH
```

**Comment by gcongiu** [comment]
Hello Satish,

Thank you for reporting this. It looks like it is a known problem.

https://lists.mpich.org/pipermail/discuss/2018-October/011066.html

There is also an issue that has been created:

https://github.com/pmodels/mpich/issues/3358

Unfortunately I don’t think anybody had the time to look into for now.
Please keep an eye on the ticket for further updates.

Sorry I can’t be of much help at this point.

Best,
Giuseppe

On Mar 7, 2019, at 8:13 PM, Satish Balay <notifications@github.com<mailto:notifications@github.com>> wrote:


BTW: To reproduce - you can use these compilers on MCS/Linux machines with

export PATH=/homes/petsc/soft/linux-Ubuntu_14.04-x86_64/OracleDeveloperStudio12.6-linux-x86-bin/developerstudio12.6/bin:$PATH
