### ISSUE TITLE
Warning: stack usage might be unbounded

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3670]
warning: stack usage might be unbounded [-Wstack-usage=]

See this warning with gcc 4.8.5.
(see https://jenkins.mpich.org/view/review-ch4/job/mpich-review-ch4-xpmem-ofi/compiler=gnu,jenkins_configure=strict,label=xpmem,netmod=ofi,shmmod=xpmem/18/artifact/filtered-make.txt)

**Comment by wesbland** [comment]
Yep. I'm starting to see a bunch of these, especially with newer compilers.

**Comment by pavanbalaji** [comment]
I have already reported these to the `hwloc` folks a while ago.  The conclusion was that variable-length arrays have been made optional in C11, which is why compilers have started to throw this warning.  It wasn't clear if they intend to fix it or not.  I'll follow up.

**Comment by pavanbalaji** [comment]
Brice said that the'll fix it in `hwloc-2.1`, to be released before the summer.

**Comment by wesbland** [comment]
This isn’t just an HWLOC problem. If you compile CH4, you’ll start to see these in our code too.

**Comment by pavanbalaji** [comment]
The above link only shows `hwloc` warnings.

**Comment by minsii** [comment]
I am not sure if we are also using `variable-length arrays` in CH4 code. Is there any other reason that might cause this warning ?

**Comment by wesbland** [comment]
It looks like the only example of this I can find might be some code that we haven’t upstreamed yet (or maybe it’s in review). So maybe this isn’t as widespread as I thought.

**Comment by hzhou** [comment]
I am closing this issue since there is no way of retrieving the issue details at this point. Advice for filing issues, try paste some synopsis or attach some log files with the issue. Do not assume links will stay alive.
