### ISSUE TITLE
testsuite: issues with --enable-strict in tests

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#3741]
Currently due to a glitch, all tests are being run with "strict" CFLAGS. I noticed that some of the tests are not being run due to it. For example, with `Jenkins/ch3/tcp`, 19108 tests are reported ; but if we remove the strict option, 19204 tests are reported.

There are 3 issues:
1. Understand why those missing tests in "strict" mode are not reported as errors (problem in `runtests`).
2. Fix `test/mpi/configure.ac` to check `--enable-strict` option appropriately.
3. Fix the tests to be able to run in `--enable-strict`

PR#3710 addresses #2.

**Comment by hzhou** [comment]
After further investigation, the difference in the number of tests being done may be due to PR#3710 based on older commits than the recent PRs that I was comparing to. In particular, the number of collective cvar tests has been changed. Seems the test suite have no problem running in strict mode (other than the warnings during compile).

Closing this issue.

**Comment by pavanbalaji** [comment]
The compile warnings should be fixed too, and not ignored.

**Comment by hzhou** [comment]
OK, so keep looking ... Turns out that there is a difference when we configure with `FROM_MPICH=yes` (configured within mpich) and `FROM_MPICH` unset (configured independently). Othe than `MPICH_ENABLE_xxx`, when we set `FROM_MPICH=yes`, it won't use `mpicc` and it will throw away the configured `CFLAGS`. 

So even though we configured as if `--enable-stricttest` is set, the CFLAGS is reset at some later point, so the tests are still run without strict flags. 

When I test independently (FROM_MPICH not set), the strict flags will get set and mpicc will get used, and the tests won't even build -- due to `-D_POSIX_C_SOURCE=200112L`, which results in `strdup` and `usleep` etc. not defined.

**Comment by hzhou** [comment]
I suggest following:
* `FROM_MPICH=yes` should do as little as possible. Other than enabling mpich specific tests, it should produce identical results as configuring testsuite standalone.
* Relax -D_POSIX_C_SOURCE to at least 2008. I don't see much point in forcing testsuite to older POSIX standards and introducing more compatibility code.
* We should have an option such as `--enable-strict=error`, which adds `-Werror` to facilitate warnings fix.

**Comment by pavanbalaji** [comment]
> * Relax -D_POSIX_C_SOURCE to at least 2008. I don't see much point in forcing testsuite to older POSIX standards and introducing more compatibility code.

This move should not be done lightly.  You can look at the environments that need to be supported and make sure they are all at a newer POSIX version.  A survey of what versions of different UNIX environments are needed to support POSIX 2008 would be useful, similar to what we had done for compiler support:

https://wiki.mpich.org/mpich/index.php/Coding_Standards#Adopting_C99_and_newer_POSIX_standards

**Comment by hzhou** [comment]
I see. If we decide to keep `-D_POSIX_C_SOURCE=200112L` for now, then we need to decide what to do with functions such as `strdup` and `usleep`. I haven't finished checking all the tests yet, but I believe only a few functions are needed. The question is -- shall we bring in `MPL` or duplicate the effort? 

Personally, I would hate to see the extra dependency for testsuite just because of a couple of functions and knowing that we won't need them at some point. I am leaning toward providing compatibility function inside `mtest.c`.

**Comment by hzhou** [comment]
It seems that `usleep` can be replaced by `nanosleep`.

**Comment by pavanbalaji** [comment]
> I see. If we decide to keep `-D_POSIX_C_SOURCE=200112L` for now, then we need to decide what to do with functions such as `strdup` and `usleep`. I haven't finished checking all the tests yet, but I believe only a few functions are needed. The question is -- shall we bring in `MPL` or duplicate the effort?
> 
> Personally, I would hate to see the extra dependency for testsuite just because of a couple of functions and knowing that we won't need them at some point. I am leaning toward providing compatibility function inside `mtest.c`.

My vote is for adding a dependency library, rather than duplicating functionality.  In general, I'd very rarely vote for duplication.

**Comment by hzhou** [comment]
> My vote is for adding a dependency library, rather than duplicating functionality. In general, I'd very rarely vote for duplication.

You would like to bring in `MPL` just to use `MPL_strdup`? :)

**Comment by pavanbalaji** [comment]
> > My vote is for adding a dependency library, rather than duplicating functionality. In general, I'd very rarely vote for duplication.
> 
> You would like to bring in `MPL` just to use `MPL_strdup`? :)

Despite that sarcasm, I'll still respond to your question.

You said you needed POSIX 2008, which is why I recommended using MPL instead to cover that gap.  You are talking about `strdup` as being the only function that needs it, because that's the latest one that you found.  What about threads (which is already duplicated in the tests, btw)?  What about memory tracing?  What about `uthash/utlist`?  What about valgrind functionality?

Every time someone needs a new function, they can't just duplicate it saying "we don't want to bring in MPL just for that one function".  It adds up.

**Comment by hzhou** [comment]
> > You would like to bring in `MPL` just to use `MPL_strdup`? :)
> 
> Despite that sarcasm, I'll still respond to your question.

:) It was a question expresses some of my surprise at your response, but it was a genuine question -- clarifying context and seeking your reasons.

> What about threads (which is already duplicated in the tests, btw)? What about memory tracing? What about `uthash/utlist`? What about valgrind functionality?
 
I have to investigate each case to form my opinion. That said,  I think making descisions based on anticipation is in the same nature as pre-mature optimization. So far (https://github.com/pmodels/mpich/pull/3747/commits/77234630bcfb96e9d814f4b8de85593a4561024a), the `strdup` cases I checked turns out to be unnecessary at all -- i.e. it can be simply removed and use the original string (mostly argv) without problem. The other offending function, `usleep`, are deprecated and `nanosleep` should be used anyway. It is a work in progress, so we might need MPL after all.

There is always some trade-off or balance. On one hand, bringing MPL avoids some duplication of effort. On the other hand, now MPL has to consider its usage in multiple scenario -- e.g. cannot make mpich specific hacks or assumptions; also the testsuite have to further complicate its configure and build; Lastly, the availability of MPL encourages the spread of may-not-be-necessary code -- e.g. those what-abouts. I agree with you that we can't just duplicate every time, but I think there is a balance and making re-evaluation every time the situation changes is not a bad practice.

**Comment by hzhou** [comment]
This is now fixed with #5190
