### ISSUE TITLE
./autogen.sh: line 1017: [: too many arguments

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#3774]
I do not understand this error.  I did a fresh `git pull`, `git submodule update` and `git clean -dfx` but still see this.  The autotools version check passes.

```
Patching ltmain.sh for compatibility with Intel compiler options... ./autogen.sh: line 939: patch: command not found
failed
Patching libtool.m4 for system dynamic library search path..../autogen.sh: line 964: patch: command not found
failed
Patching libtool.m4 for compatibility with ifort on OSX... ./autogen.sh: line 975: patch: command not found
failed
Patching libtool.m4 for fort compatibility with Oracle Dev Studio 12.6..../autogen.sh: line 985: patch: command not found
failed
Patching libtool.m4 for compatibility with Arm LLVM compilers..../autogen.sh: line 995: patch: command not found
failed
Patching libtool.m4 for compatibility with IBM XL Fortran compilers..../autogen.sh: line 1005: patch: command not found
failed
./autogen.sh: line 1017: [: too many arguments
```

[a.log](https://github.com/pmodels/mpich/files/3129263/a.log)

**Comment by hzhou** [comment]
@jeffhammond It is complaining `patch` not found. Do you have `patch` installed?

@yfguo `git blame` points line 1017 to you :) I never see `[` used like this. Is it a bash specific feature?

**Comment by pavanbalaji** [comment]
@jeffhammond It looks like you don't have `patch` on your machine.

**Comment by jeffhammond** [comment]
Thanks. I’ll install patch later. 

Given that the associated error message is useless, autogen.sh should check for patch before trying to use it, in the same manner that it checks for autotools version compliance.

**Comment by wesbland** [comment]
You don't think `patch: command not found` is explicit enough? :)

>

**Comment by jeffhammond** [comment]
This is the error message I focused on:
./autogen.sh: line 1017: [: too many arguments
As for patch not found, I couldn’t tell if that was a shell error or the script telling me a patch MPICH was trying to apply wasn’t found.

**Comment by hzhou** [comment]
> You don't think `patch: command not found` is explicit enough? :)
> […](#)

Well, they were attached to a msg line. A new line would be nice :)

**Comment by jeffhammond** [comment]
Also, why should I have to wait for this script to run for minutes before seeing this error when it could be prevented?

**Comment by hzhou** [comment]
I think it will be very undesirable to turn autogen into another configure... It has the assumption that only the developers or the living on the edge will use autogen, so they should expect such hazard
 :)

**Comment by jeffhammond** [comment]
“User experience can suck because the only users we care about are developers” is a bad way to design software.

I’ll provide the fix for this. Hopefully good error messages is something others will agree is worthwhile.

**Comment by pavanbalaji** [comment]
Better error messages are certainly useful.  It's just that non-user facing scripts haven't gotten much priority for improvement.  But if you have a PR, that'd definitely help.

**Comment by hzhou** [comment]
It is pickle. The `autogen` is really a less ideal solution to begin with, and it contains mostly cluttered preparations and patches. The direction, I believe, is to reduce autogen rather than keeping those patches permanent. The current mpich build, `autogen` is the most slow process. With beefy machines, the entire build is limited to `autogen` and `configure`. Certainly I am not agaist better error messages. But the more (infrastructure) we build into these scripts, the heavier and less like we can move away from them or even consider different solutions. 

As I said, I would hate to see `autogen` turn into another `configure`. It is long way there, but any step to that direction should be taken with caution, or before long, we wouldn't be able to go back.

**Comment by jeffhammond** [comment]
I’m all in favor of simplification and optimization in autogen.sh and configure.

Most likely the Fortran interface generation can be parallelized to be much faster.  I think that’s one of the more expensive steps when I’m building MPICH.

Just please for the love of all that is good in this world do not consider using CMake 😳

**Comment by hzhou** [comment]
I think @raffenet has been thinking about CMake :)

**Comment by jeffhammond** [comment]
CMake is great if you never need to build on a novel platform or love debugging CMake 🙄

**Comment by pavanbalaji** [comment]
The patches are for things that are generated by `libtool`, not internal MPICH stuff.  So I don't think we can make them "permanent", the way we do with other third-party libraries.

**Comment by hzhou** [comment]
The error reporting system or feature detection system, once implemented, will very likely stick, resulting in yet another configure. There is no harm for a lightweight solution, but once the infrastructure is there, it is easy to pile on.

**Comment by pavanbalaji** [comment]
I don't think there's anything wrong with people adding more error reporting later.  I do agree with trying to have a simple solution, and that's a tradeoff with more functionality and we need to figure out where we sit in that tradeoff space.  For this particular point of discussion, I personally am comfortable with that additional error checking.

**Comment by hzhou** [comment]
@jeffhammond I agree with you even though I have little experience with CMake. Complexity is finite. We only can hide complexity to make it look like simple solution. As soon as the exposed part become insufficient and one has to dig into the layer, all the complexity gets exposed. Often, as we try to hide complexity, we add more complexity to them. The more seemingly elegant build system it appears, the more complexity it actually contains. 

My idea of a build system is one that sits at the middle balance of dumb user and power users. For dumb users who only use typical system build typical features, it should work just by following 1-2-3. As soon as one steps away from typical system and typical build, they'll need an expert -- who is willing to dig and learn -- to help, who can tolerate a little roughness. A little roughness in the infrastructure allows many efficient short-cut to keep the system simple.
