### ISSUE TITLE
bug/jenkins: "random" test configuration not working

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3799]
The `RandArgs` function in the Jenkins test script always fails and results in a default configuration build.

**Comment by hzhou** [comment]
Using shell script to generate random configurations are just too hacky to maintain. I added in jenkins-script a Perl script `mpich/random.pl`, that should do a better job.

Test run here: https://jenkins-pmrs.cels.anl.gov/view/mpich-weekly/job/weekly-mpich-random/

Not a combination of options will work and we probably need add new options and remove obsolete options. But that is on-going work.

**Comment by hzhou** [comment]
Out of 8, 7 failed to build, 1 unstable. This random thing is going to be tough to clean 😄

**Comment by hzhou** [comment]
Anyway, closing this ticket as now the random nightly test job is working.
