### ISSUE TITLE
do we need an MPL strcasecmp routine?

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#3825]
Today strcasecmp and strncascecmp are pretty widespread -- we don't even check for their availability  -- but there might be a few oddball architectures that do not have those functions.  We might need  `MPL_strcasecmp` and `MPL_strncasecmp` routines .

**Comment by hzhou** [comment]
So far, seems we just need to include the right headers. I think a good rule of thumb is not to worry about the wrapper until the first reported case shows up.

**Comment by raffenet** [comment]
OK by me. Should we close this?
