### ISSUE TITLE
Linux PPC64le Segfault in mpichversion

### ISSUE THREAD

**Issue by ax3l** [pmodels/mpich#3827]
Hi,

I am currently trying to enable ppc64le support in conda-forge builds (https://github.com/conda-forge/mpich-feedstock/pull/37) and noticed a segfault executing the compiled `mpichversion` binary on native hardware (Travis-CI, see this log: https://travis-ci.org/conda-forge/mpich-feedstock/builds/541672298). As a note, I saw the same segfault when building under qemu on MS Azure (on an x86_64 host).

Do you have recommendations to build MPICH on Linux for PPC64le with a recent GCC?

The conda-forge toolchain is as follows:
- MPICH v3.2.1
- docker image: [condaforge/linux-anvil-ppc64le](https://github.com/conda-forge/docker-images/tree/master/linux-anvil-ppc64le) based on `ppc64le/centos:7`
- GCC 8.2.0
- CFLAGS: -mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe
- CPPFLAGS: -DNDEBUG -D_FORTIFY_SOURCE=2 -O3

**Comment by hzhou** [comment]
I suspect it is the fault of `-fstack-protector-strong` that `gcc` didn't handle correctly for the architecture. Reference issue #3450.

**Comment by ax3l** [comment]
Good to know. So that could either be a gcc bug on ppc64le or actually a memory access violation in mpich. Did you run the examples in #3450 with an address sanitizer to cross-check?

**Comment by hzhou** [comment]
Could you try remove `-fstack-protector` and confirm that is the issue? 

No, I haven't tried anything beyond confirming the issue in #3450.

**Comment by ax3l** [comment]
I removed gcc's `-fstack-protector-strong` now and still receive a segfault when executing `mpichversion`: https://travis-ci.org/conda-forge/mpich-feedstock/builds/541813605

I am also building in parallel the latest `master` of MPICH (c0e0de59c870160ee8299527d47574233bc75c7a) with `export MPICHLIB_CFLAGS="-fsanitize=address"` and `export CFLAGS="-fsanitize=address"` and found that running [your example](https://github.com/pmodels/mpich/issues/3450#issuecomment-442903005) in #3450 on my local laptop (x86_64 with GCC 6.3.0) seams not to show issues from a first quick test.

Maybe we can perform further sanitizer tests on an actual ppc64le architecture? The MPICH version that shows the issue is 3.2.1 .

Also, I just found that `-D_FORTIFY_SOURCE=2` is passed to `CPPFLAGS`. Could this also cause issues?

**Comment by hzhou** [comment]
If you have a core dump, could you run it in gdb and obtain a stack backtrace?

**Comment by ax3l** [comment]
We could try to get gdb into travis, I just see this remotely in CI/CD, unfortunately.

**Comment by hzhou** [comment]
Seems the issue has been resolved.

**Comment by ax3l** [comment]
Yes, it turned out to be an unrelated issue in the build chain when patching binary files for rpaths for relocatable installs. Thank you for your help and sorry for the noise!
