### ISSUE TITLE
"make testing" fails if --disable-static is specified as an option of configure

### ISSUE THREAD

**Issue by n-soda** [pmodels/mpich#3844]
if --disable-static option is specified as an option of the configure command, "make testing" fails with the following error:
    gcc: error: ../dtpools/src/.libs/libdtpools.a: No such file or directory

this is because there is [a reference to a static library libdtpools.a  in  mpich/test/mpi/Makefile.mtest](https://github.com/pmodels/mpich/blob/a34b1b04fa5217023712b2306ff90fdc9eda4e3b/test/mpi/Makefile.mtest#L23) .

the reason why we need the --disable-static option is because [it's required by the installation procedure of https://github.com/pmodels/mpich-pip](https://github.com/pmodels/mpich-pip/blob/a73d1cc07b1a10893c6f7853e4ab891d2b924382/README.vin#L916) .

I attached the log files which were genereated by the the following command sequence against https://github.com/pmodels/mpich (not mpich-pip, but original mpich):
    $ ./configure --prefix=/home/soda/work/pip/install.mpich.latest --disable-static CC=gcc FC=gfortran CXX=g++
    $ make -j5 >make.log 2>&1 
    $ make install >make.install.log 2>&1
    $ make testing V=1 >make.testing.log 2>&1

- [config.log](https://github.com/pmodels/mpich/files/3276093/config.log)
- [make.log](https://github.com/pmodels/mpich/files/3276096/make.log)
- [make.install.log](https://github.com/pmodels/mpich/files/3276097/make.install.log)
- [make.testing.log](https://github.com/pmodels/mpich/files/3276098/make.testing.log)
- [summary.xml.txt](https://github.com/pmodels/mpich/files/3276110/summary.xml.txt)

**Comment by ahori** [comment]
Soda-san is working on PiP stuff for Riken.  He is setting up PiP Jenkins and he found this bug(?) on the current MPICH.  We would be happy if you could fix this issue.

**Comment by hzhou** [comment]
@pavanbalaji @gcongiu Do we want to support distributing/building `dtpools` as a shared library? Supporting shared library rather complicates things. In addition to added configure options and mix-match of them, we may need to install it before running the testsuite; or use libtool to `make` each test which then can't be run outside the build tree. Personally, I would very much prefer only support static dtpool, then the solution is simply to remove `libtool` from test suite altogether.

**Comment by pavanbalaji** [comment]
We need to support shared libraries, @hzhou.  Dropping that is not a good solution.

@gcongiu can you look into this?

**Comment by gcongiu** [comment]
@pavanbalaji sure I will look into this

**Comment by hzhou** [comment]
I believe this has been fixed by #3851.
