### ISSUE TITLE
bug/jenkins: request handle leak in c2f2cf and c2f2cf90 and cancelanysrc

### ISSUE THREAD

**Issue by shawnccx** [pmodels/mpich#3859]
This is reported on xfail file, but with ticket number 0.
Memory leaks are reported in `debug` mode, for both icc and gnu.

```
not ok 1265 - ./f77/ext/c2f2cf 1
  ---
  Directory: ./f77/ext
  File: c2f2cf
  Num-procs: 1
  Timeout: 360
  Date: "Mon Jun 17 19:07:56 2019"
  ...
## Test output (expected 'No Errors'):
##   No Errors
## In direct memory block for handle type REQUEST, 1 handles are still allocated
```
```
not ok 1385 - ./f90/ext/c2f2cf90 1
  ---
  Directory: ./f90/ext
  File: c2f2cf90
  Num-procs: 1
  Timeout: 360
  Date: "Mon Jun 17 19:09:56 2019"
  ...
## Test output (expected 'No Errors'):
##   No Errors
## In direct memory block for handle type REQUEST, 1 handles are still allocated
```

**Comment by hzhou** [comment]
This test also triggers the same error:
`pt2pt/cancelanysrc 2`

**Comment by hzhou** [comment]
During PR #3840, when we were tweaking dtpool algorithm, the following tests fails:
```
rma/lock_contention_dt 4  -type=MPI_INT -count=65530 -seed=149 -testsize=16 
rma/lock_dt 2  -type=MPI_INT -count=65530 -seed=161 -testsize=16 
rma/lock_dt_flush 2  -type=MPI_INT -count=65530 -seed=173 -testsize=16 
rma/lock_dt_flushlocal 2  -type=MPI_INT -count=65530 -seed=185 -testsize=16 
rma/lockall_dt 4  -type=MPI_INT -count=65530 -seed=197 -testsize=16 
rma/lockall_dt_flush 4  -type=MPI_INT -count=65530 -seed=209 -testsize=16 
rma/lockall_dt_flushall 4  -type=MPI_INT -count=65530 -seed=221 -testsize=16 
rma/lockall_dt_flushlocal 4  -type=MPI_INT -count=65530 -seed=233 -testsize=16 
rma/lockall_dt_flushlocalall 4  -type=MPI_INT -count=65530 -seed=245 -testsize=16
```
Example error message:
```
not ok 945 - ./rma/lock_contention_dt 4

## Test output (expected 'No Errors'):
##  No Errors
## [0] 232 at [0x000000000223c0e0], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]
## [0] 232 at [0x0000000002239920], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]
## [0] 168 at [0x0000000002234c80], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]
## [1] 136 at [0x00000000029802f0], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]
## [1] 232 at [0x0000000002976b30], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]
## [2] 168 at [0x0000000002163f10], rc/mpid/ch4/netmod/include/../ofi/ofi_am_impl.h[123]    
```

I only did a cursory look, here is my note:
```
With certain datatype (created by certain DTPool count/seed combination), a request handle initialized in src/mpid/ch4/netmod/ofi/ofi_am_impl.h:MPIDI_OFI_am_init_request is never cleared with matching MPIDI_OFI_am_clear_request.
```
Since they are specific data type related, they may not be easily reproducible. These may or may not be the same to this issue, but definitely related (ofi - request handle clean-up). Note here for cross-referencing and tracking.

**Comment by pavanbalaji** [comment]
This comment seems unrelated to this PR, with only a very cursory connection of both being resource leak related.  This needs to be separated into a new PR.  Also, it needs more investigation into what datatype is causing the failure.

**Comment by hzhou** [comment]
> This comment seems unrelated to this PR, with only a very cursory connection of both being resource leak related. This needs to be separated into a new PR. Also, it needs more investigation into what datatype is causing the failure.

You mean new issue? I'll do that.

**Comment by hzhou** [comment]
New issue created #3863. I'll investigate and followup there.

**Comment by hzhou** [comment]
When `MPI_Irecv` from `MPI_ANY_SOURCE`, we launch both `SHMEM` and `NM` request and attached together with `MPIDI_REQUEST_ANYSOURCE_PARTNER`. We need remember to cancel and free the partner in `MPI_Cancel` and `MPI_Wait`.

**Comment by hzhou** [comment]
Note: as I debug this issue, I noticed `MPIDI_NM_am_request_init` (in `src/mpid/ch4/netmod/ofi/ofi_am.h`) gets called on the `SHM` part of the request object. Remind myself to double check.
