### ISSUE TITLE
Undefined symbols make error in mpich-3.3.1

### ISSUE THREAD

**Issue by rakeshphys** [pmodels/mpich#3889]
I am trying to install mpich-3.3.1 on MacOS 10.14.5 (Xcode 10.2.1) with intel compilers version 19.0.4.233 (gcc version 4.9.0 compatibility):

 curl -OL http://www.mpich.org/static/downloads/3.3.1/mpich-3.3.1.tar.gz
 tar -zxf mpich-3.3.1.tar.gz
 mkdir mpich-build; cd mpich-build
 $PWD/../mpich-3.3.1/configure --prefix=/opt/intel-dev/mpich-3.3.1 CC=icc CXX=icpc F77=ifort FC=ifort
 make

I got the following weird error in the make process:

Undefined symbols for architecture x86_64:
  "__ZTWMPIR_Per_thread", referenced from:
      import-atom in libpmpi.dylib
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "__ZTWMPIR_Per_thread", referenced from:
      import-atom in libpmpi.dylib
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/env/mpivars] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/env/mpichversion] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Is it a bug or I am doing something wrong?

**Comment by raffenet** [comment]
It is a bug in detection of TLS support when using the Intel toolchain on macOS. You may be able to workaround it by adding `ac_cv_tls=none` to your `./configure` line.

**Comment by raffenet** [comment]
You can also add `--disable-fortran` if you do not need Fortran support.

**Comment by rakeshphys** [comment]
Thank you very much for the prompt working solution!!

**Comment by raffenet** [comment]
Dup of #3437. Will track eventual fix there.
