### ISSUE TITLE
ch4/ofi does not build correctly on mac os with `--disable-shared`

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#3908]
I see the following error when trying to build `ch4/ofi` on mac os with `--disable-shared`:

```
Undefined symbols for architecture x86_64:
  "_MPIDI_CH4_SHM_POSIX_FBOX_GENERAL", referenced from:
Undefined symbols for architecture x86_64:
  "_MPIDI_CH4_SHM_POSIX_FBOX_GENERAL", referenced from:
      _MPIDI_POSIX_mpi_init_hook in libpmpi.a(lib_libpmpi_la-posix_init.o)
      _MPIDI_POSIX_mpi_init_hook in libpmpi.a(lib_libpmpi_la-posix_init.o)
  "_MPIDI_POSIX_eager_fbox_control_global", referenced from:
  "_MPIDI_POSIX_eager_fbox_control_global", referenced from:
      _arb_progress_hook in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_anysource_matched in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_OFI_handle_lmt_ack in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_OFI_do_handle_long_am in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _arb_progress_hook in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_anysource_matched in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_OFI_handle_lmt_ack in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _MPIDI_OFI_do_handle_long_am in libpmpi.a(lib_libpmpi_la-ch4_init.o)
      _progress_fn in libpmpi.a(lib_libpmpi_la-async.o)
      _MPIDIG_do_irecv in libpmpi.a(lib_libpmpi_la-async.o)
      _MPIDIG_handle_unexpected in libpmpi.a(lib_libpmpi_la-async.o)
      _progress_fn in libpmpi.a(lib_libpmpi_la-async.o)
      _MPIDIG_do_irecv in libpmpi.a(lib_libpmpi_la-async.o)
      _MPIDIG_handle_unexpected in libpmpi.a(lib_libpmpi_la-async.o)
      ...
      ...
```

Here's the full config line that I used, but the problem seems to be with `--disable-shared` (the error goes away if I don't disable shared libraries):

```
../mpich/configure --prefix=/Users/balaji/software/mpich/build/install --disable-romio
    --enable-g=all --enable-spawn --enable-maintainer-mode --enable-cxx
    --with-device=ch4:ofi --disable-shared CC=clang CXX=clang++ FC=gfortran
    --enable-strict=noopt --disable-fast --disable-perftest
```

**Comment by hzhou** [comment]
`mpichversion.c` directly includes `mpiimpl.h` and links with `lib/libmpi.la`. I don't understand the exact mechanism yet, but suspect something to do with hidden symbols and inline functions. FWIW, I have been walking around this issue by deleting the `mpichversion` target from `Makefile`.

**Comment by hzhou** [comment]
Apparently, I was mistaken. The static build on mac is permanently broken, can't build any binary. I'll try to understand.

**Comment by hzhou** [comment]
`src/mpid/ch4/shm/posix/eager/fbox/globals.c` contains a single global variable definition (`MPIDI_CH4_SHM_POSIX_FBOX_GENERAL`). It compiles into a common symbol. Apparently, during static linking on mac, this lonely common symbol will get lost. By adding a zero initializer, turning it into an explicit `bss` symbol, seems to solve the issue.

**Comment by hzhou** [comment]
I believe on mac it uses llvm's linker [lld](https://lld.llvm.org/). Quoting on their page: "LLD is very fast". Maybe we should consider testing lld in our CI.

**Comment by raffenet** [comment]
> I believe on mac it uses llvm's linker [lld](https://lld.llvm.org/). Quoting on their page: "LLD is very fast". Maybe we should consider testing lld in our CI.

Seems reasonable to add to CI. It may also happen for us in a later version of FreeBSD if `lld` becomes the default.
