### ISSUE TITLE
dtpools: make triggers autoconf

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3939]
This build issue is problematic if building from tarball because autotools are not required, or may not match exactly the ones used to create the tarball.

How to reproduce:
1. Build and install MPICH from source
2. Go to any test directory and type `make`

```raffenet@glitch:attr/ (master*) $ make
  CC       attrt.o
(cd ../util && make mtest.o)
  CC       mtest.o
(cd ../util && make mtest_common.o)
  CC       mtest_common.o
(cd ../dtpools && make)
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /sandbox/mpich/test/mpi/confdb/missing aclocal-1.16
 cd . && /bin/sh /sandbox/mpich/test/mpi/confdb/missing automake-1.16 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /sandbox/mpich/test/mpi/confdb/missing autoconf
/bin/sh ./config.status --recheck
[snip]
```

**Comment by raffenet** [comment]
cc: @hzhou @gcongiu

**Comment by hzhou** [comment]
One quick fix may be to simply disable automake's maintainer mode by default: https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html

I believe user always can pass `--enable-maintainer-mode` when they want to.

**Comment by hzhou** [comment]
I never figured out the intricacies how the maintainer mode dependency worked :)

**Comment by raffenet** [comment]
The rules are complex! https://www.gnu.org/software/automake/manual/automake.html#CVS

 Maintainer mode was the method I used for the json-c submodule. I'm more curious about this case because dtpools is our package from the state.

**Comment by raffenet** [comment]
Turns out dtpools was attempting to use the confdb directory from `test/mpi`. Surely that caused conflicts. Giving dtpools its own copy seems to fix the issue.
