### ISSUE TITLE
mpiexec runs too slow?

### ISSUE THREAD

**Issue by THUzhangga** [pmodels/mpich#3942]
Platform: Windows server 2012 R2 Datacenter
Version: mpich2-1.3
Problem: I have installed mpich2 on my windows server before and I could start mpiexec quickly. However, recently I added a domain for my windows server. After I shifted to my new domain and account, mpiexec seems to start too slow. I tried re-install MPICH2, but it still takes about 2 minutes to start the example cpi.exe. My intent is to use MPICH2 to run another program, which is much bigger than cpi.exe, and even if an hour passes, the calculation seems not start. I am quite confused. If you know any solution/guidance, please tell me.

**Comment by hzhou** [comment]
I am not familiar with how mpiexec in mpich2 works; but if you create a "hosts" file with numeric ip address and pass that hosts file to mpiexec, would that help?

**Comment by THUzhangga** [comment]
> I am not familiar with how mpiexec in mpich2 works; but if you create a "hosts" file with numeric ip address and pass that hosts file to mpiexec, would that help?

Thank you for your reply. I tried that, but it still launches quite slow. I tried 'mpiexec -validate', the result is 'success'.
I don't know which process is wrong.

**Comment by hzhou** [comment]
@THUzhangga The windows port of MPICH has not been maintained for quite a while. However, the official (Microsoft MPI)[https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi] can be freely downloaded and it is officially supported. It is based on MPICH so porting your code should be relatively easy. I suggest to give Microsoft MPI a try.

**Comment by THUzhangga** [comment]
> @THUzhangga The windows port of MPICH has not been maintained for quite a while. However, the official [Microsoft MPI](https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi) can be freely downloaded and it is officially supported. It is based on MPICH so porting your code should be relatively easy. I suggest to give Microsoft MPI a try.

Thank you. I manged to move from MPICH2 to MS-MPI, and it works now! Besides, some configures of visual studio need to be set while using MS-MPI.

**Comment by hzhou** [comment]
@THUzhangga You are welcome. I am glad you resolved your issue.
