### ISSUE TITLE
macOS: multisend4 test timing out in Jenkins

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3943]
This has been happening periodically in default, debug and strict configurations on macOS since July 9th. I suspect this PR may be the cause https://github.com/pmodels/mpich/pull/3917, as it is the only PR merged that day that would affect ch3 builds.

```not ok 1621 - ./threads/pt2pt/multisend4 5
  ---
  Directory: ./threads/pt2pt
  File: multisend4
  Num-procs: 5
  Timeout: 180
  Date: "Wed Jul 24 17:44:23 2019"
  ...
## Test output (expected 'No Errors'):
## [mpiexec@mpich-mac3.mcs.anl.gov] APPLICATION TIMED OUT, TIMEOUT = 180s
```

**Comment by raffenet** [comment]
cc: @rzambre

**Comment by hzhou** [comment]
Just confirmed on my laptop. It is not deadlock, but very slow. After revert the commit in #3917, the progress goes much faster.

**Comment by hzhou** [comment]
What the test does is having 5 process 5 threads each, and each round do one `Isend` and one `Irecv` for each thread, then one thread will `MPI_Waitall`. 

In the `Waitall` there is no contention, but it repeatedly yields. Turns out on osx, somehow the implementation of `sched_yield` is really expensive.

**Comment by hzhou** [comment]
On OSX, `sched_yield` is very fast on its own. But when there are oversubscribed threads (as far as the test case goes) waiting in `pthread_barrier_wait`, it appears the kernel scheduler will yield to those threads and those threads are quite slow to return the yield. So this ticket might have something to do with how `pthread_barrier_wait` is implemented as well as the kernel scheduling policy.

**Comment by hzhou** [comment]
So for OSX at least, `sched_yield` have the undesired effect of messing up kernel scheduler policy (I think). From my test, using `usleep(0)` works very well. One worry is that `usleep(0)` may bypass kernel. I tested on my mac laptop and apparently this is not the case. 

So it appears the solution is to use `usleep(0)` on OSX.
