### ISSUE TITLE
valgrind: Unbalanced alloc/free counts reported with --enable-g=meminit

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3945]
Originally reported at https://lists.mpich.org/pipermail/discuss/2019-July/005744.html

Reproducible with `master` branch and simple init/finalize MPI program. The MPICH memory pools make valgrind client requests to inform of handle object allocs and frees, but they may be unbalanced based on the valgrind output.

```==8578== Memcheck, a memory error detector
==8578== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==8578== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==8578== Command: ./a.out
==8578==
==8578==
==8578== HEAP SUMMARY:
==8578==     in use at exit: 0 bytes in 0 blocks
==8578==   total heap usage: 1,979 allocs, 1,974 frees, 4,720,483 bytes allocated
==8578==
==8578== All heap blocks were freed -- no leaks are possible
==8578==
==8578== For counts of detected and suppressed errors, rerun with: -v
==8578== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by hzhou** [comment]
I am not sure this is something we need to fix. I think the count includes duplicated or extra counts anyway, for example `realloc`, `free(NULL)`. Since there is no leaked memory or double free, I think we are clean.
