### ISSUE TITLE
CI: Introduce Sanitizers

### ISSUE THREAD

**Issue by ax3l** [pmodels/mpich#3950]
Hi Ken (@raffenet),

we just talked at ATPESC about adding novel sanitizers, such as [`$(CC) -fsanitize=address`](https://en.wikipedia.org/wiki/AddressSanitizer), `$(CC) -fsanitize=memory`, and [`$(CC) -fsanitize=undefined`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) (available in GCC and Clang) to CI runs.

Contrary to tools such as valgrind, compiler-added sanitizers are relatively low in overhead and have minimal false-positives in recent compilers (due to their actual context-awareness). They would be wonderful to be compiled into automatically run tests in your matrix to keep the code base memory leak and memory violation free.

There are also [more fancy sanitizers](https://clang.llvm.org/docs/SanitizerSpecialCaseList.html) ([ref2](https://github.com/google/sanitizers/wiki)), e.g. checking race conditions in threading and control flows, among others. I can definitely recommend the address, memory and undefined behavior sanitizer for C/C++ codes. Please be aware that they might need to be run exclusively (e.g. one CI matrix entry with Address+Memory SAN & one CI matrix entry compiling & running with UBsan).

> AddressSanitizer is currently implemented in Clang (starting from version 3.1) , GCC (starting from version 4.8) and Xcode (starting from version 7.0) .
> [note: the later the version the better, haven't seen issues with recent compilers at all.]

I haven't tried them yet with the latest MPICH code base, yet am currently trying to get the same CI into [PMIx](https://github.com/pmix/pmix/pull/1265). I got there while trying to sanitize my libs and applications with OpenMPI recently.
That's actually also my main motivation: in order to use sanitizers in MPI-parallel "downstream" libraries and applications one actually has to fix the upstream issues first :). (Also, it avoids maintaining notoriously outdated suppression files.)

**Comment by hzhou** [comment]
We have added `asan` tests in our nightly Jenkins.

**Comment by ax3l** [comment]
Thanks a lot @hzhou! This is great for us using `asan` downstream!
In practice, I found `ubsan` to be also very helpful as a 2nd sanitizer, too (needs an independent ci job though since they usually do not work together).

**Comment by hzhou** [comment]
Sounds good. I'll leave the issue open until we add the `ubsan` test then.

**Comment by hzhou** [comment]
Both `asan` and `ubsan` are in our nightly tests and they are mostly clean.

**Comment by ericch1** [comment]
Hi @hzhou ,

just posted on mailing list the following questions regarding address sanitizer (https://lists.mpich.org/pipermail/discuss/2025-October/006767.html) but found this issue after...

Can you point me to the CI configuration you are using?

I tried with this configuration:
```
./configure
--prefix=/opt/mpi/mpich-4.3.0-debug
--enable-g=dbg,meminit
--enable-debuginfo
--enable-fast=none
CC=/usr/bin/gcc
CXX=/usr/bin/g++
FC=/usr/bin/gfortran
F77=/usr/bin/gfortran
--enable-romio
--disable-java
--disable-opencl
--without-hwloc
--without-cuda
--without-hip
--with-device=ch4:ucx
--with-pm=hydra
```

but for now, I have no luck... with a simple MPI "hello world" example, as soon as I compile with `-fsanitize=address`. I have the following  error:
```
$ clang --version
clang version 17.0.6 

$ clang -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -isystem /opt/mpi/mpich-4.3.0-debug/include -L/opt/mpi/mpich-4.3.0-debug/lib -lmpi -o hw hw.c

AddressSanitizer:DEADLYSIGNAL
=================================================================
==1819697==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000441 (pc 0x000000000441 bp 0x00000000000c sp 0x7ffdab7286b8 T0)
==1819697==Hint: pc points to the zero page.
==1819697==The signal is caused by a READ memory access.
==1819697==Hint: address points to the zero page.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```
the same code works fine with valgrind...

Thanks,
Eric
