### ISSUE TITLE
Build ch4: duplicate symbols _MPIDI_workq_elemt_direct

### ISSUE THREAD

**Issue by Komdosh** [pmodels/mpich#3953]
File [ch4_globals.c](https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/src/ch4_globals.c) have definition of `MPIDI_workq_elemt_direct`
```
#if defined(MPIDI_CH4_USE_WORK_QUEUES)
struct MPIDI_workq_elemt MPIDI_workq_elemt_direct[MPIDI_WORKQ_ELEMT_PREALLOC];

MPIR_Object_alloc_t MPIDI_workq_elemt_mem = {
    0, 0, 0, 0, MPIR_WORKQ_ELEM, sizeof(struct MPIDI_workq_elemt), MPIDI_workq_elemt_direct,
    MPIDI_WORKQ_ELEMT_PREALLOC
};
#endif /* #if defined(MPIDI_CH4_USE_WORK_QUEUES) */
```
while file [ch4i_workq.h](https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/src/ch4i_workq.h) also has defined structure `MPIDI_workq_elemt_direct`

```
#if defined(MPIDI_CH4_USE_WORK_QUEUES)
struct MPIDI_workq_elemt MPIDI_workq_elemt_direct[MPIDI_WORKQ_ELEMT_PREALLOC];
extern MPIR_Object_alloc_t MPIDI_workq_elemt_mem;
```
compiling with `gcc` on MacOS cause problem `duplicate symbols`. 
So for fix that you should define `MPIDI_workq_elemt_direct` in [ch4i_workq.h](https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/src/ch4i_workq.h) as `extern`. Like that:

```
#if defined(MPIDI_CH4_USE_WORK_QUEUES)
extern struct MPIDI_workq_elemt MPIDI_workq_elemt_direct[MPIDI_WORKQ_ELEMT_PREALLOC];
extern MPIR_Object_alloc_t MPIDI_workq_elemt_mem;
```

After that fix, problem is gone.

**Comment by hzhou** [comment]
@Komdosh Thanks for submitting issue and also offering the solutions. Fix in PR #3955.
