### ISSUE TITLE
build/warnings: ICC "dropping qualifiers" warnings in MPL/atomic

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#3997]
MPL/atomic is by default uses C11 if possible, but this C11 version shows warnings if it is compiled with ICC. Specifically, when it is compiled with ICC-19.0.3, the following warnings are issued:
```
./include/mpl_atomic_c11.h(90): warning #2330: argument of type "atomic_int={_Atomic(int)} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
./include/mpl_atomic_c11.h(90): warning #2330: argument of type "const atomic_int={_Atomic(int)} *" is incompatible with parameter of type "const volatile void *" (dropping qualifiers)
```
This problem comes from the difference of how compilers handle C11's stdatomic. See the following code:
```
// cc -std=c11 code.c
#include <stdatomic.h>
void func(atomic_int_fast32_t *a, const atomic_int_fast32_t *b, int *c, const int *d)
{
    int a_1 = atomic_load(a); // [1]: Warning: ICC (19.0.3)
    int b_1 = atomic_load(b); // [2]: Error: Clang (<8.0), Warning: ICC (19.0.3)
    int c_1 = atomic_load(c); // [3]: Error: Clang
    int d_1 = atomic_load(d); // [4]: Error: Clang
}
```
[1] is correct as far as I read the C11 specification.
[2] should be warned if the compiler is very strictly C11 compatible (it is because C11 atomic_load seemed to forget const. See https://reviews.llvm.org/D47618), but it should be allowed (and will be from C18 and from Clang 8 even with C11).
[3] and [4] is, as far as I read the specification, incorrect though ICC only considers it correct.

Right now [2] is used in mpl/atomic, causing many warnings with ICC-19. Anyway the `const` qualifier is necessary, so I need to choose [2] or [4]. It seems that [2] is officially supported from C18 (and unofficially supported from Clang 8 with C11).

There are several ways to fix this issue.
 - A. Create a new version for Intel, which uses [4] (i.e., `atomic_c11_icc.h`).
 - B. With Intel Compilers, use GCC's `__atomic`.
 - C. Use pragmas/compilation flags to suppress this warning in this file.
 - D. Wait and see if ICC will change the behavior.

Note that:
- Clang < 8.0 will anyway fall back to GCC's `__atomic` since neither [2] nor [4] is accepted. Clang (>= 8.0) does not have this issue with [2]. 
- I do not think this pointer type error causes a real error at runtime, though I cannot 100% guarantee.

I'm happy to hear any opinion.
This issue was reported by @sagarth Thanks!

**Comment by hzhou** [comment]
If I read correctly, the case 1 is passing a C11 atomic type to a C11 atomic function and somehow ICC implemented that function with a `volatile void *` which is deemed incompatible to the atomic type. That is very screwed of `icc`.  :)

So it appears to be one of the rolling-out period that there is a difference between a claimed support and a everyone accepted support in the C11 land.

As the situation stands and if `gcc` `__atomic` support is more usable, then I think we'll simply prioritize for `gcc` `__atomic` in the configure.

**Comment by raffenet** [comment]
Can you strengthen the configure test to weed out compilers that don't behave like they should? We did this for `_Thread_local` support. Also @jeffhammond is good at getting Intel compiler bugs fixed if you can supply the simple test case :).

**Comment by raffenet** [comment]
I guess what I am saying is, I like solution B if it can be done automatically through a configure test. Once `icc` deploys the correct behavior, it will automatically switch to using the C11 implementation.

**Comment by shintaro-iwasaki** [comment]
The test case is the following, which causes warnings at compile time (not an error):
```
// icc -std=c11 code.c
#include <stdatomic.h>
void func(atomic_int_fast32_t *a, const atomic_int_fast32_t *b)
{
    int a_1 = atomic_load(a); // [1]: Warning: ICC (19.3)
    int b_1 = atomic_load(b); // [2]: Warning: ICC (19.3)
}
int main() {return 0;}
```

@raffenet I agree. I will improve the configuration file so that it will reject if (some specific) warnings are issued. Maybe I will use `-Werror` here:
https://github.com/pmodels/mpich/blob/master/src/mpl/configure.ac#L830

**Comment by raffenet** [comment]
Right, we do force `-Werror` in configure tests where we consider any warning an error. See https://github.com/pmodels/mpich/blob/master/confdb/aclocal_cc.m4#L356

**Comment by jeffhammond** [comment]
Interesting.  I have not had any issues with C11 atomics in ICC (e.g. https://github.com/jeffhammond/HPCInfo/blob/master/atomics/ping-pong/c11-ping-pong.c).  I will see what I can do to get this addressed.

**Comment by shintaro-iwasaki** [comment]
@jeffhammond Thanks!
In my environment this behavior might be affected by the implementation of `stdatomic.h` (e.g., I used intel-parallel-studio(19) with GCC-8.3, so ICC possibly read GCC-8.3's `stdatomic.h`). @sagarth reported the same issue, so I don't think this issue is very specific to my environment, though.

**Comment by jeffhammond** [comment]
https://en.cppreference.com/w/c/atomic/atomic_load indicates that `volatile` is required here.  I haven't looked at the C11 spec itself to confirm that cppreference is reliable.

**Comment by shintaro-iwasaki** [comment]
Thanks! You're right. The `atomic_load` should be `C atomic_load(volatile A* obj);` (http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf, p281, no const in C11, see https://reviews.llvm.org/D47618).

I made a `volatile` version.
```
#include <stdatomic.h>
void func(volatile atomic_int_fast32_t *a, const volatile atomic_int_fast32_t *b)
{
    int a_1 = atomic_load(a);
    int b_1 = atomic_load(b);
}
int main() {return 0;}
```
However, the above code still shows the following warnings (icc (ICC) 19.0.3.199):
```
$ icc -std=c11 code2.c
check2.c(4): warning #2330: argument of type "volatile atomic_int_fast32_t={_Atomic(long)} *" is incompatible with parameter of type "const volatile void *" (dropping qualifiers)
      int a_1 = atomic_load(a);
                ^
check2.c(5): warning #2330: argument of type "const volatile atomic_int_fast32_t={_Atomic(long)} *" is incompatible with parameter of type "const volatile void *" (dropping qualifiers)
      int b_1 = atomic_load(b);
                ^
```

**Comment by hzhou** [comment]
So it is complaining on the incompatibility between `_Atomic(long) *` and `void *`. @shintaro-iwasaki How about adding a `(void *)` cast?

**Comment by jeffhammond** [comment]
I filed a bug report already. ICC should behave like GCC and Clang unless both are nonconforming.

**Comment by shintaro-iwasaki** [comment]
@jeffhammond Thank you for reporting the bug!
@hzhou The code works if you cast the pointer to `long *`. If you make it to `void *`, the following error is shown since `atomic_load` needs to identify a type to return:
```
error: incomplete type is not allowed
```

In any case, I will fix `configure` for this version of ICC and possibly other compilers. Thank all of you!

**Comment by jeffhammond** [comment]
A related bug was already reported and a fix is in the pipeline.  I am optimistic that it will land in a future release of ICC 19.
