### ISSUE TITLE
romio: noncontig and i_noncontig tests expectations

### ISSUE THREAD

**Issue by reflectored** [pmodels/mpich#4001]
I have multiple issues with these tests. I have read MPI-3 Standard [1] and ROMIO "Data Sieving and Collective I/O" paper [2] and I find some discrepancies in the expectations in "noncontig.c" and "i_noncontig.c" tests found in mpich/src/mpi/romio/test in the current master branch.

First i_noncontig.c is described in the README file in that folder as non-blocking independent I/O test, whereas I would assume "noncontig.c" is the blocking variant. However, atomicity is not set for the file header in that test. It could be that the locking is actually used in the wrong case in ADIOI_BUFFERED_WRITE, I have fixed that in the following PR: https://github.com/pmodels/mpich/pull/3981.

Furthermore, in both cases **non**-contiguous in file **independent** read/write with data sieving is performed. However, the ROMIO data sieving paper [2] and MPI-3 standard [1] do not promise consistency in those cases:

> The process is also assured that concurrent writes from pro-
cesses other than those involved in this collective-I/O oper-
ation will not occur, because MPI-IO’s consistency seman-
tics [6] do not automatically guarantee consistency for such
writes.

I would suggest removing the non-contiguous in file cases in those tests.

[1] https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf
[2] https://www.mcs.anl.gov/~thakur/papers/romio-coll.pdf

**Comment by wkliao** [comment]
Enabling atomic mode gives you a stronger I/O consistency. Consistency is about the
order of data appeared in the file in the end. Atomicity is not required for non-contiguous
file access.

Locking used in  ADIOI_BUFFERED_WRITE is to ensure every piece of write data
from a process gets written to the file, and not lost due to the read-modify-write
on the same file region by a different process.

**Comment by reflectored** [comment]
Thank you for the comment! Due to my "fix" for ADIOI_BUFFERED_WRITE have I encountered the problem. Everything is clear now.
