### ISSUE TITLE
Fortran: disable real128 when compiler does not support

### ISSUE THREAD

**Issue by keszybz** [pmodels/mpich#4005]
Fails with v3.3.1, v.3.2.1 is OK:
```
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:355:16:

  355 |     real(real128),dimension(..) :: x
      |                1
Error: Kind -1 not supported for type REAL at (1)
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:385:19:

  385 |     complex(real128),dimension(..) :: x
      |                   1
Error: Kind -1 not supported for type COMPLEX at (1)
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:383:36:

  383 | subroutine MPI_Sizeof_xcomplex128 (x, size, ierror)
      |                                    1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:353:33:

  353 | subroutine MPI_Sizeof_xreal128 (x, size, ierror)
      |                                 1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:353:30:

  353 | subroutine MPI_Sizeof_xreal128 (x, size, ierror)
      |                              1
......
  383 | subroutine MPI_Sizeof_xcomplex128 (x, size, ierror)
      |                                 2
Error: Ambiguous interfaces in generic interface 'mpi_sizeof' for ‘mpi_sizeof_xreal128’ at (1) and ‘mpi_sizeof_xcomplex128’ at (2)
make: *** [Makefile:48733: src/binding/fortran/use_mpi_f08/mpi_f08_types.stamp] Error 1
```
Fails in Fedora rawhide, F31, F30.

**Comment by keszybz** [comment]
I now built it with a simple patch which removes those MPI_Sizeof_xcomplex128, MPI_Sizeof_xreal128. Not sure if it'll cause any problems down the road ;)

**Comment by nmorey** [comment]
I'm also seeing this issue on SUSE Tumbleweed. This also impacts mvapich2 2.3.2.

@keszybz  Would you mind sharing the patch ?

Mentionning @hari.subramoni for tracking in mvapich2

**Comment by keszybz** [comment]
https://src.fedoraproject.org/rpms/mpich/blob/3b497cff602f88dd1664ba31a34504d40da44156/f/0001-Drop-real128.patch

**Comment by keszybz** [comment]
... but I'm only applying it on arm (https://src.fedoraproject.org/rpms/mpich/blob/master/f/mpich.spec#_111). It'd have to be conditionalized to apply everywhere.

**Comment by nmorey** [comment]
@keszybz Thanks. Will do the same for now until a proper fix is available.
Note: this applies cleanly to mvapich2 2.3.1 aswell

**Comment by harisubramoni** [comment]
@keszybz @nmorey - Thanks for the discussion and the patch.

@raffenet - do you recommend that I take this into the MVAPICH2 codebase in the interim while you guys work on a full solution?

Thx,
Hari.

**Comment by hzhou** [comment]
The only side effects removing `MPI_Sizeof_xreal128` is on system that do support `real128`, which is `real*16` I believe, and the user write code `call MPI_Sizeof(x, size_x, ierror)` where x is of that long double type, the compilation will fail. A proper fix probably need check configure. 

In the interim, removing them essentially just removed the support of `real128` for the `MPI_Sizeof`. Both the usage of `real128` and `MPI_Sizeof` as well as `use mpi_f08`  are rare anyway, so the impact is likely minimal.

**Comment by hzhou** [comment]
Currently we generate the fortran bindings at `autogen` time, before `configure`. In order to use `configure`, we generate `.in` files with `autoconf` macros in them and run them through `configure`. This is convoluted and limited. The proper way is have `configure` test features, then run `buildiface` as `ac_config_commands` so it can generate interfaces that reflect feature options directly.

**Comment by hzhou** [comment]
Tagging PR #3819

**Comment by raffenet** [comment]
> The proper way is have `configure` test features, then run `buildiface` as `ac_config_commands` so it can generate interfaces that reflect feature options directly.

Yes! This way `--disable-fortran` would actually save `buildiface` from running.

**Comment by swepettax** [comment]
I ran in to the same problem today, using Arch Linux on my RPI. Any solution yet?

**Comment by everythingfunctional** [comment]
Found this issue today trying to build a Pi cluster for testing parallel Fortran code. Just made the fix myself, but it would be nice if the configure step could do it :wink:
