### ISSUE TITLE
mpl/atomic: interprocess atomicity

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#4026]
Now MPL/atomic (or OPA) guarantees thread-thread atomicity and corresponding memory ordering, but it is unclear whether it supports "process-process" atomicity and/or memory ordering.
The example of the interprocess atomicity is as follows:
```
int shared_memory = 0; // mmapped
Process1:
  atomic_fetch_add(&shared_memory, 1);
Process2:
  atomic_fetch_add(&shared_memory, 1);
// Does shared_memory become 2???
```

---
Current situation

https://en.cppreference.com/w/cpp/atomic/atomic_is_lock_free says interprocess atomicity is not "required", so the current C11 atomics does not guarantee the interprocess atomicity. I don't know the case of GCC's `__atomic` and `__sync`. MPL/atomic + emulation lock has supported this interprocess atomicity, but this might be dropped (#4025).

Anyway OPA and MPL/atomic try to support interprocess atomicity, but actually they fail to guarantee it.

---

If we drop the interprocess atomicity requirement from MPL/atomic, what will happen?

- For example, any atomic operation to shared-memory data (e.g., #4018) is not correct (=system dependent, not portable),
- The code becomes very simple (I can remove ugly `OPA_Interprocess_lock_init` from `shm_alloc.c`:
https://github.com/pmodels/mpich/blob/master/src/mpid/common/shm/mpidu_shm_alloc.c#L199)

---

If we want to support interprocess atomicity, what do we need to do? What will be changed?

- For non-emulation lock versions (e.g., C11, `__atomic`, and `__sync`)
  1. The configure script needs to detect whether the certain atomic operations guarantees interprocess atomicity (e.g., `mmap` + GCC's `__atomic`); I don't know how to do it :(
  2. If supported, we can use the compiler-supported atomic operations.
  3. If not supported, we should fall back to the interprocess mutex mode (which is extremely heavy since any atomic operations start to use nodes-shared mutex).
- For emulation lock version
  1. Need to keep the ugly `OPA_Interprocess_lock_init`-ish mechanism.
    - We need to feed the shared memory to this lock initialization (all processes on the same node needs to share the interprocess lock).
    - Note that any functions that might call MPL/atomic need to ensure that the atomic library is initialized beforehand (e.g., `MPI_Initialized`).

---

Any feedback is welcome. As a maintainer of MPL/atomic, I'd like to drop this requirement and create another layer for the interprocess atomic operations (though maybe the new layer only supports mutex) .

**Comment by shintaro-iwasaki** [comment]
Boost::interprocess might be useful to implement an efficient interprocess locking mechanism.
https://www.boost.org/doc/libs/1_63_0/doc/html/interprocess.html

**Comment by hzhou** [comment]
@shintaro-iwasaki Now I understand the situation better, it seems we need inter-process lock after all. Either that or remove lock-based MPL_atomic fallback altogether. The reason is MPICH depends on shared-memory atomics. Without inter-process lock emulation it is necessary to disable entire shared-memory support in MPICH, which currently there is no clean way of doing it.

If non-emulation atomics are supported, I think we can safely assume the safety comes from CPU instruction itself and therefore it is safe regardless OS processes?

So we are only looking at the case of using lock to emulate atomics. This is a fallback for correctness with an understanding of performance impact, so let's not worry about heaviness and focus on correctness.

One option is to migrate OPA code to MPL. I am leaning toward create an MPL wrapper for OPA. For one, we don't have to duplicate the code; for two, it can fallback to OPA assemblies transparently.

**Comment by shintaro-iwasaki** [comment]
#### Does using CPU instruction guarantee inter-process atomicity?

This solution is not portable, since we do not know whether the `mmap`'ed memory is really atomically accessed like normal stack/head memory in a mulithreaded program. For example, `mmap` might cache `mmap`'ed data. I am not sure if `volatile` can address this issue.

In my opinion, introducing assembly code for this imperfect solution is too painful.

#### Creating an OPA wrapper for MPL

It is a promising solution for #4383, but this does not solve the interprocess lock issue. As I wrote, using OPA assembly code does not address this issue.

#### What is a correct implementation?

As you mentioned, an emulation lock (synchronizing all atomic operations by an interprocess pthread mutex) is the only way to implement interprocess atomic operations correctly to the best of my knowledge.

To implement correct and performant atomic operations, MPICH can be aware of the difference between intraprocess atomicity and interprocess atomicity so that MPICH can use special ones only for interprocess atomicity.  It will be as follows:

- Use compiler-supported atomic operations for intraprocess atomicity (critical sections, completion counters of objects)

- Use emulation-lock based atomic operations for interprocess atomicity (shared memory algorithms). Developers can choose a compiler-supported one or assembly code (or whatever) at configuration time If they know it works.

I talked with Ken about this idea, but he said it is too extreme, though. Even if we create a new layer, we cannot solve the dilemma of performance and portability (i.e., correctness on any architectures).

**Comment by hzhou** [comment]
> This solution is not portable, since we do not know whether the `mmap`'ed memory is really atomically accessed like normal stack/head memory in a mulithreaded program. For example, an OS might cache `mmap`'ed data. I am not sure if `volatile` can address this issue.

We know linux `mmap` is truly mapping to CPU-MEMORY-bus, right? Anyway, linux can always be verified. FreeBSD as well. We have to trust closed-source OSes. But if the OS do memory emulation, it probably will mention it somewhere, I hope. In the end, I believe pthread mutex is basing on the same assumption. It has to, right?

> Use emulation-lock based atomic operations for interprocess atomicity (shared memory algorithms). 

My understanding is for the inter-process lock, all we need is an explicit initialization of the mutex pointer, right? MPL or OPA just need add a `init(lock_t * lock)` and mpich makes sure to call it during init time, that's not too complicated.

**Comment by hzhou** [comment]
I am drawing following preliminary conclusion: 

* Because mpich uses atomics for shared memory operation, the only lock-emulated atomics that can work is an inter-process lock emulation. So MPL should provide by-lock atomics using mutex pointers that are to be initialized.

* MPL-should provide an OPA wrapper, enabled by `--with-mpl-atomic-primitives=openpa`. This provides a fallback when necessary.

Are we agreeing on these two?

**Comment by shintaro-iwasaki** [comment]
We don't know how mmap mapping is implemented, but in most cases it should be directly mapped as you wrote.

2. Interprocess pthread mutex. https://linux.die.net/man/3/pthread_mutexattr_setpshared guarantees it. Maybe this implementation is based on this assumption, but anyway assuming such is not portable.

3. Adding an explicit `init` of the mutex pointer won't be complicated.

4. I will make a PR to implementing by-lock atomics using mutex pointers 

5. An OPA wrapper can solve #4388, too. I will make a separate PR.

**Comment by hzhou** [comment]
@shintaro-iwasaki Shall we close this issue?
