### ISSUE TITLE
Dependency error with external hwloc

### ISSUE THREAD

**Issue by scroogie** [pmodels/mpich#4038]
There seems to be a problem when configuring with --with-hwloc-prefix=... 

Make complains with the following message:

make[2]: *** No rule to make target `-lhwloc', needed by `lib/libmpi.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....

This seems to be because pmpi_convenience_libs contains "-lhwloc" in case an external hwloc is used, and this is used as dependency specification for libmpi.la. The other convenience libs correctly point to local files, but in case hwloc is external I guess it should be removed from that variable.

**Comment by raffenet** [comment]
I think I ran into this in the past and made https://github.com/pmodels/mpich/pull/3540 as a solution. It's a little out of date, but shouldn't be too much effort to rebase.

**Comment by scroogie** [comment]
I think the important thing is that pmpi_convenience_libs won't contain @hwloc@ anymore, because thats treated as a dependency line. I don't know your automake files well enough to judge if thats addressed with the above PR. But thanks for investigating this!

**Comment by hzhou** [comment]
Need check build with external hwloc. If it works now then we should close this issue.

**Comment by hzhou** [comment]
I believe this issue no longer exists.
