### ISSUE TITLE
testsuite: remove collective length tests

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4042]
There are a series of tests in `errors/coll/` that requires our code to detect user errors resulting mismatched datatype/size. These errors are "user errors", or in MPI standard's term -- erroneous programs. Certainly for a high quality implementation, it should provide users useful error messages, if it is not too much trouble. However, in this case, it is too much trouble. Unlike typical argument error, that we can simply check at MPI-layer, to detect mismatch error, we need propagate contexts all the way down and up. Since the collective contexts is irrelevant as we decompose into pt-to-pt operations and as we descend down to device layer, having to keep and propagate collective context up and down breaks the layer-abstraction and introduces significant complexities. We need balance the Pros of giving user better error message on these relatively rare errors with the Cons of adding extended complexity that cost us the ability to refactor, extend, and improve our core performance goal. I think this trade-off is imbalanced, therefore, I suggest simply remove these tests, and consider remove the code that are solely created for passing these tests.

EDIT: My new opinion (https://github.com/pmodels/mpich/issues/4042#issuecomment-696482199) is to greatly simplify the code of this feature by simply running a `allgather` in the configurable "error-checking" path.

**Comment by hzhou** [comment]
reference: 
   Issue #3775 
   PR #3655

**Comment by hzhou** [comment]
@wesbland @pavanbalaji @jain-surabhi-23 @raffenet , any input?

**Comment by hzhou** [comment]
The current status is: we are having an outstanding failure on `ibcastlenght` with `ch3-ofi`. We have been fixing `bcastlength` in `ch4-ofi` for quite a while, and any new collective algorithm introduced need individual code to prevent the regression.

The length error on other collectives have been in `xfails` since the beginning.

**Comment by hzhou** [comment]
As a case in hand, PR #4041 adds 130 lines to support this error detection in a single bcast release-gather algorithm.

**Comment by wesbland** [comment]
This isn't just a case of providing better error messages. It's also to prevent deadlock if an error happens during the collective. If we don't continue the communication and propagate the error around, at least some of the processes will deadlock if the user doesn't use `MPI_ERRORS_ARE_FATAL`.

**Comment by hzhou** [comment]
@wesbland I understand. But the deadlock is a result of erroneous user program. Erroneous programs resulting in deadlocks are common and most users will understand and accept, right?

**Comment by wesbland** [comment]
That’s not necessarily true. Any error could cause a deadlock. These specific tests are for mismatched length, but it could be a process failure, out of memory error, etc.

**Comment by hzhou** [comment]
I have been seeing test failures in `bcastlength` as a timeout, which indicates a deadlock. But I am not sure I understand why it is causing the deadlock? By default (that is if we remove all the error propagation and data length annotation), underlying pt2pt should still match. We can add checks to see if the recved message is the expected sizes -- don't we (or should we) always have that check? But even we don't check and continue, it is just creating more pt2pt operations with mismatched sizes plus potential memory corruptions, right? How does it result in deadlocks?

**Comment by hzhou** [comment]
I think I understand better now. We have to continue despite the size mismatch, or we will result in deadlocks, right?

**Comment by hzhou** [comment]
So if we simply continue (sending messages potentially with mismatched length), it should work out without deadlock, right? Some of the processes (may not be all of them) will report errors in the end. That should be good enough, right?

**Comment by wesbland** [comment]
Correct. That’s what we do now. If you don’t see an error, there wasn’t one that impacted you.

**Comment by jain-surabhi-23** [comment]
@hzhou I dont have a strong opinion on whether to keep these error checking, just want to add in the information that in most algorithms it is not very complicated to do these checks. One just have to retrieve the amount of data received from the `status` object after `recv`. Only in case of `release_gather` it was more complex because we don't do send-recv there.

**Comment by hzhou** [comment]
Here is a new thought --

The current way of implementing collective error checking is very complex, yet only with limited benefits. I think we should regard this feature as part of error checking. If we regard error checking as something that we can turn off for production run, then the cost of error checking is less of a concern relative to the cost of code complexity and maintenance. With that thought, I think we can easily support collective error checking with a simple `allgather` . Since this "error checking" is more costly than "normal error" checking, we probably want to disable it by default, and only enable it when configured with, e.g. `--with-eror-checking=collective`.

**Comment by hzhou** [comment]
Reviewing the past comments, one of the concern is dead lock when one of the process went away. That is a general fault tolerance topic that needs more strategic solution. I just thought that one of the solution may be --

When we are in a progress loop for certain iterations with no progress (assuming we are trying to receive from a remote process), we should ping PMI server for whether the target process is alive or not. So if PMI server keeps log of the lively hood of all processes, then the waiting process can get itself out-of the dead progress loop. This means any process can simply invoke fatal error and bail out without causing dead locks.

**Comment by wesbland** [comment]
> This means any process can simply invoke fatal error and bail out without causing dead locks.

What if the user sets `MPI_ERRORS_RETURN`?

**Comment by hzhou** [comment]
> 
> 
> > This means any process can simply invoke fatal error and bail out without causing dead locks.
> 
> What if the user sets `MPI_ERRORS_RETURN`?

`MPI_ERRORS_RETURN` has no quick and easy solutions :( I am tempted to run an `allgather` error checking if user want `MPI_ERRORS_RETURN`.

**Comment by wesbland** [comment]
> `MPI_ERRORS_RETURN` has no quick and easy solutions :( I am tempted to run an `allgather` error checking if user want `MPI_ERRORS_RETURN`.

I don't think it's easy either. That's why we have put a bunch of work into error propagation. Is this a problem of not wanting to maintain error handling code or being concerned about performance?

**Comment by hzhou** [comment]
> 
> 
> > `MPI_ERRORS_RETURN` has no quick and easy solutions :( I am tempted to run an `allgather` error checking if user want `MPI_ERRORS_RETURN`.
> 
> I don't think it's easy either. That's why we have put a bunch of work into error propagation. Is this a problem of not wanting to maintain error handling code or being concerned about performance?

It is mainly out of concern of code maintenance and development. Currently the error propagation code is weaved inside every algorithm. It is difficult to maintain and affects the development of algorithm as well. In fact, the error checking part is still in complete as we have these collective length xfails with no sight of being fixed. I am just brainstorming here. If we can separate the error handling from the key algorithm, even if we end up with more complexity, the separation alone will allow more sustainable maintenance and development.

**Comment by wesbland** [comment]
> It is mainly out of concern of code maintenance and development. Currently the error propagation code is weaved inside every algorithm. It is difficult to maintain and affects the development of algorithm as well. In fact, the error checking part is still incomplete as we have these collective length xfails with no sight of being fixed. I am just brainstorming here. If we can separate the error handling from the key algorithm, even if we end up with more complexity, the separation alone will allow more sustainable maintenance and development.

But if we separate them (as you proposed with using an allgather), that's the same as removing them. Of course no one will turn on the "make my performance terrible" switch, but when there's some sort of fault that occurs, they'll wonder why they've deadlocked.

I would argue that those algorithms are incorrect. Part of designing any code is specifying which cases you want to handle and which ones you don.t I'm arguing that proper error returning is one we should handle. And it's not even really that difficult. We have plenty of examples of when errors should be fatal and when they shouldn't.

**Comment by hzhou** [comment]
> Of course no one will turn on the "make my performance terrible" switch, but when there's some sort of fault that occurs, they'll wonder why they've deadlocked.

I disagree. I would argue that this is in the same category  of `address-sanitizer`. There  is plenty of motivation to configure the code in a more thorough but performance non-great way and do a small scale test run before, for example, a 1 million-core-hour run.

The collective length errors are usage errors that should be caught by test runs, right?

**Comment by wesbland** [comment]
> The collective length errors are usage errors that should be caught by test runs, right?

I think we're arguing for different things. I don't care about the length checking. You can take those out. It's good to have, but user errors are not what we're trying to correct.

What I don't want to see taken out is the proper returning of errors that occur during a collective call, regardless of what they are (length, out of memory, communication failure, etc.). We still need to correctly set the error bit, conclude the communication algorithm, and return the correct error code to the user.

**Comment by hzhou** [comment]
> What I don't want to see taken out is the proper returning of errors that occur during a collective call, regardless of what they are (length, out of memory, communication failure, etc.). We still need to correctly set the error bit, conclude the communication algorithm, and return the correct error code to the user.

I see.

But we have to talk about the  source of the errors. Generally speaking of it blurs the question.

Case 1, dead lock from algorithm error (with correct user code). That should be fixed as bug, not the concern of error behavior.

Case 2, dead lock due to error in user program. That should be fixed by user, by employing debugging instrumentation or enabling extra error checking options. Since it is a bug in user program, I don't think it is a concern of error behavior.

Case 3, dead lock due to run time situations such as dynamic values or hardware failures or random bit-shifts. That is the realm of fault tolerance.

Case 4, non-fatal error return. Both bugs (either in user program or our code) and runtime fault, imo, is not in this category. I don't have much concrete examples in my head right now, but I think we need look at the actual cases to discuss.

**Comment by wesbland** [comment]
> Case 3, dead lock due to run time situations such as dynamic values or hardware failures or random bit-shifts. That is the realm of fault tolerance.

This is the part I disagree with. You're combining too many things into this category. I understand if you don't want to do excessive **fault detection** (e.g., incorrect data or fancy agreement algorithms). That's difficult and expensive.

What I *do* expect from MPICH is to do reasonable **fault propagation**. If you see an error, tell the other processes about it. This isn't hard and isn't expensive. This includes much simpler things like, a call to `fi_tsenddata` returned `-FI_EAGAIN` and we've run out of retries so this needs to be returned up the stack. This is exactly the sort of thing non-catastrophic errors are designed to help with and is easy to do with something like the current error propagation system we have. There's no fancy detection (like what we use for detecting inconsistent lengths) or making sure return codes are consistent among all processes. It's just returning error codes that come up in the course of the algorithm.

That's what `MPI_ERRORS_RETURN` is supposed to be about. Tell the user what you know and let them decide what to do in a lightweight way. It's also how every other library on Earth functions.

**Comment by hzhou** [comment]
> If you see an error, tell the other processes about it. This isn't hard and isn't expensive.

In the case of collective, this is complicated. It involves to continue issuing the pt2pt messages even though the data is incomplete which may keep generating more errors as we continue. And in the case of `-FI_EAGAIN` in `fi_tsenddata`, how do you prevent deadlock since the very process that we are trying to send to won't receive the message and it will keep waiting, right? How do we tell that process that we failed to send when we failed to tell?

**Comment by hzhou** [comment]
> That's what `MPI_ERRORS_RETURN` is supposed to be about.

I think it depends on what we are thinking here. If we treat `MPI_ERRORS_RETURN` just a local process thing, that is certainly not hard and expensive. However, I think we are really talking about to return that `error` to a remote process -- that is very different.

**Comment by hzhou** [comment]
I think the plan now is to explore error-checking options to add more general collective error checking. Thus I am closing this ticket.
