### ISSUE TITLE
Configure MPICH with logging (and timing) fails

### ISSUE THREAD

**Issue by christgau** [pmodels/mpich#4054]
Hi, 

with MPICH 3.3.1, the built-in logging appears to be unusable as the configure command fails. I've tried to configure both on CentOS 7.6 and on an up-to-date Arch Linux with `configure --enable-timing --with-logging=rlog` (as MWE) but the command returns with an error:

```
configure: ===== configuring src/util/logging/rlog =====
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/opt/local/mpich/debug/3.3.1'  '--with-logging=rlog' --cache-file=/dev/null --srcdir=.
RUNNING CONFIGURE FOR RLOG
./configure: line 2021: PAC_ARG_CACHING: command not found
./configure: line 2054: PAC_PROG_CC: command not found
checking for ar... /usr/bin/ar
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
./configure: line 2234: PAC_PROG_CHECK_INSTALL_WORKS: command not found
./configure: line 2235: PAC_PROG_INSTALL_BREAKS_LIBS: command not found
./configure: line 2236: PAC_PROG_MKDIR_P: command not found
./configure: line 2237: PAC_PROG_MAKE: command not found
checking for perl... /usr/bin/perl

[... succeeding header file checks ...]

checking for unistd.h... (cached) yes
./configure: line 3663: PAC_CC_SUBDIR_SHLIBS: command not found
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
configure: error: src/util/logging/rlog configure failed
```
Indeed, there is no Makefile.in, neither in the download version nor in the Github tag for 3.3.1. 

Any idea how to get logging and timing to work?

**Comment by hzhou** [comment]
The `rlog` facility has not been maintained for a while due to very few reported usage. In practice, developers often find the simple debug event logging, https://wiki.mpich.org/mpich/index.php/Debug_Event_Logging, sufficient. When timing is needed, developers nowadays often use a profiler for better analysis.

**Comment by christgau** [comment]
Thanks. I was aware of the debug event logging, but thought that the timing logging was something more useful for me.

Since the configure is broken (for a while!?) and the documentation in `doc/logging` and the `configure` help differ, wouldn't it be good to remove that feature completely? At least it would avoid confused users/developers like me ;-)

**Comment by hzhou** [comment]
I agree :) I guess we have been sitting in the dilemma of whether to spend time to fix rlog or spend time to clean it up. I am in the camp of keep it simple, so clean it up it is :)

**Comment by travisk1154** [comment]
Rlog has been removed as of this [PR](https://github.com/pmodels/mpich/pull/5113). The documentation has been updated as well. Marking this issue as closed.
