### ISSUE TITLE
coll: neighborhood collective bug with cyclic topologies

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4061]
https://github.com/mpi-forum/mpi-issues/issues/153 investigates MPI neighborhood collective behavior with cyclic cartesian topologies. Experimentation finds that when # processes in the communicator is <= 2, MPI places data incorrectly. Attaching example for testing purposes.
[ring_neighbor_alltoall_TEST.c.txt](https://github.com/pmodels/mpich/files/3681293/ring_neighbor_alltoall_TEST.c.txt)

**Comment by thananon** [comment]
Is there any update on this issue?

**Comment by RolfRabenseifner** [comment]
[ring_neighbor_alltoall_TEST.c.txt](https://github.com/pmodels/mpich/files/5538477/ring_neighbor_alltoall_TEST.c.txt)
[mpich-cla-individual-2016-11-25_RolfRabenseifner.pdf](https://github.com/pmodels/mpich/files/5538483/mpich-cla-individual-2016-11-25_RolfRabenseifner.pdf)

You can use the attached file for testing the correctness of your MPI_Neighbor_alltoall implementation.
Best regards
Rolf Rabenseifner

**Comment by RolfRabenseifner** [comment]
Caution: You should run the test with 1, 2 and 3 processes:
- 3 procceses have been never a problem, but of course be checked after any modification of the MPI library.
- 2 and 1 processes were implemented wrong in both mpich and OpenMPI.
