### ISSUE TITLE
ch4/ofi: Compile time assert fails for 32-bit builds

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4066]
https://github.com/pmodels/mpich/blob/9b6343287be3b93a40b68b33e01eccb7a99ed289/src/mpid/ch4/netmod/ofi/ofi_iovec_util.h#L387-L388

`fi_rma_iov` uses `uint64_t` for addr field as opposed to `void *` in `struct iovec`, which causes a mismatch when `sizeof(void *) < 8`.

https://github.com/ofiwg/libfabric/blob/master/include/rdma/fi_rma.h#L43-L47

**Comment by wesbland** [comment]
Looks like that was original CH4 code from Charles. He added a bunch of these that were probably too strict.

**Comment by raffenet** [comment]
I've afraid the macros involved are probably unsafe for 32-bit, since they appear to cast from one iovec representation to the other. https://github.com/pmodels/mpich/blob/9b6343287be3b93a40b68b33e01eccb7a99ed289/src/mpid/ch4/netmod/ofi/ofi_iovec_util.h#L83-L89

I'm testing my theory manually and will report results here.

**Comment by raffenet** [comment]
Turns out we don't even get that far. All RMA tests segfault during window creation in my testing.

**Comment by raffenet** [comment]
pt2pt works perfectly, though!

**Comment by raffenet** [comment]
This has been fixed for some time. ch4/ofi 32-bit nightly tests in Jenkins are clean.
