### ISSUE TITLE
ch4/ucx: Message-rate slows down considerably in some runs with multiple threads

### ISSUE THREAD

**Issue by rzambre** [pmodels/mpich#4113]
Build: MPICH `master` configured with `--with-device=ch4:ucx --with-ucx=/home/rzambre/ucx/1.5.0-release-mt-install --prefix=/home/rzambre/mpich/ucx-1.5.0-global-nm-only-install --disable-fortran --enable-thread-cs=global --disable-spawn --enable-ch4-direct=netmod --enable-fast=O3 --disable-cxx`

With the global critical section, the multithreaded (MPI_Isend) message-rate benchmark executes extremely slowly even going from 1 thread to 2 threads. I initially thought it was hanging but after including some print statements, I see that it just becomes very slow. This is not repeatable, though (once every 5 runs). Most runs with 2 threads execute in the expected amount of time but occasionally, the benchmark with 2 threads will take more than 3 minutes to execute. The probability of the slow run occurring increases with an increase in thread count. I have yet to witness the completion of the benchmark with 16 threads.

This problem happens to be more reproducible if I use an embedded UCX build. 

I have attached the reproducer. There are print statements on the sender side to see the slow execution.

I am not sure what is going on. Any ideas?

[reproducer.zip](https://github.com/pmodels/mpich/files/3764978/reproducer.zip)
To run: `mpiexec -n 2 -ppn 1 -env OMP_PLACES cores -env OMP_PROC_BIND close -env UCX_NET_DEVICES mlx5_0:1 -env UCX_TLS rc_mlx5,rc -hosts gomez03,gomez03 ./multiple_isir_waitall_mbw_mr -T 2 -S 8 -M 64000`

**Comment by rzambre** [comment]
@raffenet @hzhou What UCX transport is used for our Jenkins testing with `ch4/ucx`?

**Comment by hzhou** [comment]
`UCX_TLS=rc,mm,self`

**Comment by hzhou** [comment]
Thanks for the update, Rohit.
