### ISSUE TITLE
Update source for debug flags

### ISSUE THREAD

**Issue by Dekken** [pmodels/mpich#4128]
https://github.com/pmodels/mpich/blob/master/src/mpi/debugger/dbginit.c#L179

Is this still correct?

**Comment by raffenet** [comment]
Oops. The option should read `--enable-debuginfo`. I'll submit a PR to fix.

**Comment by raffenet** [comment]
It's also kind of evil that we wrap `MPII_Wait_for_debugger` in a function called `MPII_wait_for_debugger` (lowercase w)`. That function is just a single line + preprocessor guards. Taking HAVE_DEBUGGER_SUPPORT as an argument might be more clear to reader...

**Comment by raffenet** [comment]
https://github.com/pmodels/mpich/blob/d6091ffb3fd6a63d190c8e0fff5450c13ef1ea08/src/mpi/init/mpi_init.h#L114-L122
