### ISSUE TITLE
style: use of C11 anonymous struct/union

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4135]
In the effort of squashing warnings for Oracle Developer Studio (#4132), I discovered that we are already using anonymous union, in `src/mpid/ch4/include/mpidpre.h` - the definition of `MPIDIG_req_ext_t`. It is a C11 feature, so `suncc` barks, and it barks a lot.

Since we are only adopting C99, it seems the right fix is to add a useless name to the union (and insert the name everywhere that struct is being used -- quite a lot). However, I couldn't bring myself to do it. Anonymous struct/union, especially the latter, makes the code reads so much better, and when it compiles, there is no doubt of its correctness. So I am would like to instead fix the warning by turn off that particular warning in `suncc`'s `CFLAGS`.

For reference, both `gcc`, `clang`, and `icc` accepts anonymous struct/union without warning even in `c89` or `c99` standard mode.

The implication: at the end of this issue, we need arrive at a decision, that we either fix all the current usage of anonymous struct/union, or we allow it. With the latter, we definitely would promote its usage and use it everywhere.

**Comment by yfguo** [comment]
I think the large questions here is if we are ready to adopt some C11
features in development. It depends on how widely is it supported in
old compilers. I recall our guideline is the compilers ten years ago
should have the support for the feature, if we are adopting. For C11,
this might be premature.

**Comment by hzhou** [comment]
I am not saying or suggesting adopting `C11`. I am only looking at this particular feature. An anecdote for the "10-year" guideline, `gcc-4` supports it even with `-std=c89` without warning.

**Comment by shintaro-iwasaki** [comment]
Note that `gcc` (and supposedly other compilers) warns if `-Wc99-c11-compat` (warns if c11 features that do not appear not in c99 are used) is given. https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by raffenet** [comment]
gavl tree in MPL uses anonymous struct/union, too. PETSc folks ran into this in their builds - they still use ch3. https://github.com/pmodels/mpich/blob/cd216a2a3af59cdddeca11ac3452e57dfa1869e8/src/mpl/include/mpl_gavl.h#L45-L53

I don't really see the point of using the union here, since it only saves 1 pointer worth of storage. I am going to propose flattening it completely.

**Comment by hzhou** [comment]
> I don't really see the point of using the union here, since it only saves 1 pointer worth of storage. I am going to propose flattening it completely.

Union is semantically cleaner so we know the fields used exclusively for different purposes. I think we should just add name to the union and struct.

**Comment by raffenet** [comment]
> > I don't really see the point of using the union here, since it only saves 1 pointer worth of storage. I am going to propose flattening it completely.
> 
> Union is semantically cleaner so we know the fields used exclusively for different purposes. I think we should just add name to the union and struct.

Fair enough. We can use `u` for the union. Any suggestion for the struct portion?

**Comment by hzhou** [comment]
"s"? :)

**Comment by raffenet** [comment]
> "s"? :)

Heh, I'll go with that. I think if I spend any more time on this, I'll end up making a bunch more changes 😆 .

**Comment by hzhou** [comment]
The usage of anonymous struct in `mpl_gavl.h` has been fixed.
