### ISSUE TITLE
object: refactor object API to distinguish user objects and internal objects

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#4142]
The object API provides convenient object pool allocation. It is used for both user objects such as `comm` and `request`, and also for several internal objects such as `workq_elem` and `xpmem_seg`. Each object is associated with a 32-bit `handle` with several embedded attributes  (see structure below).

```
Direct object:
---------------------------------------------------------
handle_kind (2bits) | obj_kind(4bits) | handle index
---------------------------------------------------------
Indirect object:
---------------------------------------------------------------------------------
handle_kind (2bits) | obj_kind(4bits) | block num (14bits) | handle index (12bits)
---------------------------------------------------------------------------------
```

This design has several drawbacks:
- For internal objects, the `handle` is unneeded. `struct` with attributes should be sufficient. 
- For user objects, the `object kinds` are all predefined and `4 reserved bits` should be sufficient. However, we have to increase it to hold also internal objects. It reduces the number of available handle indexes for user objects.

We plan to distinguish these two usage models:
- For user objects, still use the current handle based design.
- For internal objects, delete the `handle` limit and directly use `struct`. Besides, the `object kind` attribute should be unnecessary.

**Comment by wesbland** [comment]
Would this have an ABI impact? I guess it depends on how things are implemented.

**Comment by minsii** [comment]
@wesbland Let's discuss the refactoring at #4141

**Comment by hzhou** [comment]
#4141 has been merged. Closing this issue
