### ISSUE TITLE
deadlock occurs in testing test/mpi/threads/pt2pt/multisend4

### ISSUE THREAD

**Issue by KaimingOuyang** [pmodels/mpich#4163]
**Issue description:**
When using ch4 device, deadlock will happen in the test `test/mpi/threads/pt2pt/multisend4`. The test code is located at `test/mpi/threads/pt2pt/multisend4.c`. 

The easiest way to trigger this bug is as follows:

---

**Configuration:**
`./configure CC=gcc CXX=g++ --prefix=$HOME/ANL/installed/stdmpich-ch4 --with-device=ch4:ofi --disable-fortran --disable-ft-tests --with-libfabric=embedded --enable-nemesis-dbg-localoddeven --disable-perftest --with-wrapper-dl-type=rpath`

**Run:**
`mpiexec -n 3 ./multisend4 -mode=1`

---

Note: we should execute this program many times (I trigger the deadlock by 53 times execution) until deadlock happens; adding `--with-strict` to the configuration options does not affect this bug triggering. I haven't triggered this bug by using 2 processes, so 3 processes seem to be the minimal number we have to use.

**Comment by minsii** [comment]
Can you please try to narrow down the bug reasons? E.g., does it happen without configure `--enable-strict`? Can it happen with smaller number of processes or number of threads? What is the simplest pattern to reproduce this deadlock?

**Comment by hzhou** [comment]
I did not reproduce this failure. This test is active in our test suite and we have not seen the failure for quite a while. Thus I assume it has been long fixed.
