### ISSUE TITLE
config: better handling of extension specific code

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4173]
As we focus on performance, some solutions will depend on specific extensions. The current code does that on a case by case bases. This has become messy. On one hand, we are always concerned about what we can use, preventing us to implement solutions that is typical on modern linux platforms. On the other hand, the feature management code is scattered, and it is difficult to understand where certain feature is being enabled and when the fall-back is being used -- which often defeats the purpose of the feature in the first place.

I suggest use an envelope configure option, for example, `--enable-linux=[minimum version]`, then we can implement linux specific solutions under that guard.

**Comment by wesbland** [comment]
Don't we already use the argument for `--enable-foo=bar` for other things? For example:

* `--enable-izem=atomic,queue`
* `--enable-g=all`
* `--enable-threads=multiple`

When we're talking about libraries, we do:

* `--with-ofi=/path/to/foo`

So are you suggesting we duplicate the above example with:

* `--enable-ofi=1.5`

**Comment by hzhou** [comment]
> So are you suggesting we duplicate the above example with:
> 
>     * `--enable-ofi=1.5`

`--enable--xxx` is about turning on/off features. So if we are adding code that specific to ofi 1.5 and would like to turn it on/off even when ofi 1.5 or later is used, then `--enable-ofi=1.5` may be appropriate.  But even when we add that option, it does not replace `--with-ofi=/path/to/foo`, which is merely for the availability of the library.

**Comment by wesbland** [comment]
What about the other places where we already have `--enable` options. I'm just afraid that this won't actually improve clarity.

**Comment by hzhou** [comment]
Actually, I don't think it is a bad idea have both `--with-xxx` and `--enable-xxx` options for all *optional* libraries. It is a common practice that projects double use `--with-xxx` for enable/disable the libraries. This often bring issues as it is not clear to the user whether a dependency is desirable or optional. If we have both options, then user will easily tell whether a library is optional by checking if there is an "enable/disable" option with it. So I think the separation of `enable` and `with` options can bring clarity.

**Comment by wesbland** [comment]
Ok. If you’re comfortable with it, that’s fine with me.

**Comment by hzhou** [comment]
I would like to note that the discussion of library config option is irrelevant to this issue.

**Comment by hzhou** [comment]
This issue served its purpose for discussions. Since there is no clear action items, closing it for now.
