### ISSUE TITLE
Accelerator Pipelining Interface - Internode

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#4175]
# Problem Statement
This issue describes the proposed data structures and interfaces for efficiently managing MPI communications when data is residing in GPU memory and the network hardware does not support GPU Direct RDMA. In such case the MPI implementation has to stage data through the host memory before it can hand it over to the network. To alleviate the cost inherent in the PCIe bus transfer the MPI implementation can pipeline this with network transfers.

# Use Case
For now we limit to the case in which send and receive datatypes are contiguous; We also consider the case in which the source buffer is in GPU memory on one node and the destination buffer is in GPU memory on another node. However, the case in which source and destination buffers are on separate GPU memories that share the same node should be similar. We also assume data in the GPU buffer is always valid when such buffer is passed to MPI, implying that appropriate host/device synchronization has been performed by the MPI program (no synchronization is implicitly done by MPI at this time).

In this scenario MPI communication happens by copying data from GPU memory into a series of staging buffers in host memory and then sending the data to the network from such buffers. Each buffer needs an associated `cudaEvent_t` to synchronize the `cudaMemcpyAsync()` operation with the host thread before this can pass the buffer to the network layer for sending its content. Additionally, each buffer also needs an `MPI_Request` to synchronize the host thread with network progress, so that after network transfer is finished the buffer can be reused to stage additional data.

# Pipeline Context
As already said we only consider Host-Device/Device-Host pipelining. The pipelining in this case can be represented using a context. Follows a description of such context:

```
/* To be implemented as opaque object */
typedef struct MPIDI_gpu_pipeline_ctx {
    /* TODO: define context */ 
} MPIDI_gpu_pipeline_ctx_t;
```

The pipeline context is created, managed, and destroyed using appropriate APIs:
```
typedef enum {
    MPIDI_GPU_PIPELINE_DIR__H2D,
    MPIDI_GPU_PIPELINE_DIR__D2H
} MPIDI_gpu_pipeline_dir_e;

/* take a new context from the ctx pool or create a new one - 
   this step also allocates staging area and registers it. */
int MPIDI_gpu_pipeline_ctx_create(int num_stages,
                                  size_t stage_sz,
                                  MPIDI_gpu_pipeline_ctx_t **ctx);

/* return the context to the ctx pool */
int MPIDI_gpu_pipeline_ctx_destroy(MPIDI_gpu_pipeline_ctx_t *ctx);

/* attach user buffer to context */
int MPIDI_gpu_pipeline_attach_buf(MPIDI_gpu_pipeline_ctx_t *ctx,
                                  void *buf,
                                  size_t buf_sz);

/* detach user buffer from context: optionally this can be done by destroy */
int MPIDI_gpu_pipeline_detach_buf(MPIDI_gpu_pipeline_ctx_t *ctx);

/* set direction of the data transfer: H2D or D2H */
int MPIDI_gpu_pipeline_set_dir(MPIDI_gpu_pipeline_ctx_t *ctx,
                               MPIDI_gpu_pipeline_dir_e direction);

/* triggers cudaMemcpyAsync and return next stage buffer (might block) */
int MPIDI_gpu_pipeline_get_next_chunk(MPIDI_gpu_pipeline_ctx_t *ctx, 
                                      void **chunk_ptr,
                                      size_t *chunk_len,
                                      MPIR_Request **chunk_req);
```

The context create interface gets a context from a context pool. If the pool is empty a new context is actually created. This also has gpu specific information (such as  NVIDIA GPU streams and events to manage the different pipeline stages).

A new context is created at runtime (e.g., `MPI_Send`). When the transfer is complete, the context is not destroyed. Instead, the user buffer can be detached and the context returned to the context pool for later reuse. When a new context is needed, if the context pool is empty a new context is created otherwise an existing one is used.

# Active Message Pipelining Protocol
A new active message protocol for the pipelining is also required. The pipeline protocol has the following phases:

- Send Message Header: on sender, create `MPIDIU_gpu_pipeline_ctx_t` , initialize it (attach user buffer, set transfer direction), prepare the message header and sends it to receiver;
- Receive Header and Reply: on receiver, create `MPIDIU_gpu_pipeline_ctx_t` (if receive buffer on GPU), reply ACK to sender;
- Send/Recv Chunk: on sender, call `MPIDIU_gpu_pipeline_get_next_chunk()` to get new chunk of data, pass it to netmod for send. On receiver, call `MPIDIU_gpu_pipeline_get_next_chunck()` to get a new chunk pointer, pass it to the netmod to receive data.

The pipeline context is attached to the request returned by the non blocking send. The pipeline context internally manages additional MPI request handlers to progress the pipelining of data from the CPU to the network. When the send of a chunk completes it launches the send for the next chunk, until all chunks have been sent.

![pipeline](https://user-images.githubusercontent.com/851634/70258908-b6367200-1752-11ea-85ee-1afcab13a38f.png)

# Example
[...]

# Attach Compute to the Context
[...]

**Comment by hzhou** [comment]
Outdated
