### ISSUE TITLE
hydra: need decide the direction of hydra and hydra2

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4176]
Currently we have both hydra and hydra2 active. Hydra is more mature and has been tested more thoroughly. Hydra2 addresses some of the shortcomings of hydra and a few partners had already adopted hydra2 and been actively developing it. Both hydra and hydra2 share large chunks of code that are duplicated in both subtrees. Bug fixes and feature changes often need be patched for both or discrepancy creeps in, adds on to the accumulating technical debt. In fact, that has already happened. This is not sustainable.

Ongoing, we need a better plan. There are 3 options. One, drop hydra2. I am not quite familiar with hydra2, but my impression is the original issue prompted hydra2 -- the slow startup for large scale launch -- has been largely mitigated even with hydra. There are no evident barriers with hydra so focusing the development on hydra-only seems viable. Two, drop hydra. The same stated reason probably applies to hydra2 as well, so dropping hydra and focus on hydra2 is also an option. However, hydra2 is significantly less tested, so expect some time before hydra2 reaches the same maturity of hydra. Third, keep both active, because both have pros and cons -- again, I am not familiar with both code to list them. If this is the descision, then we need to factor the common code between hydra and hydra2 to a convenience library, to avoid inconsistency and the annoying overhead of keeping both branches in sync.

**Comment by wesbland** [comment]
cc: @ddurnov

**Comment by hzhou** [comment]
We'll focus on enhancing hydra rather than forking the maintenance over hydra2. Closing hydra2 issues.
