### ISSUE TITLE
ofi: provider ofi_rxd not working

### ISSUE THREAD

**Issue by aingerson** [pmodels/mpich#4185]
I'm trying to run the ofi_rxd provider and am getting some sequence errors when running the mpi_stress test.

I have investigated and found the issue being that MPICH is calling RMA reads for larger messages which will be out of order, causing the sequence errors.

RXD settings are not defined in src/mpid/ch4/netmod/ofi/globals.c causing it to go through the default settings. While the default settings set .enable_rma to off, .enable_tagged is also set to off and .enable_am is set to on which eventually causes the operation to go through fi_readmsg in MPIDI_OFI_do_rdma_read.

Ideally, this would be fixed for the default path (ie not needing tagged or RMA operations) but maybe the solution is to just add rxd settings to let us go through the normal tagged (non-RMA) path.

If I take out all the MPICH references and specifications to RXM and let it go through the default path, it also calls RMA reads as well.

**Comment by wesbland** [comment]
@aingerson Can you put in your basic `./configure` command? Specifically, are you using `--with-device=ch4:ofi` with the environment variable `MPIR_CVAR_USE_PROVIDER=ofi_rxm` or are you trying something else?

**Comment by aingerson** [comment]
Configure:
./configure --prefix=/home/aingerson/mpich --disable-oshmem --enable-fortran=no --with-device=ch4:ofi --enable-ch4-direct=netmod --with-libfabric=/home/aingerson/workspace/install/libfabric/head

MPIR_CVAR_OFI_USE_PROVIDER="verbs;ofi_rxd"
Run command:
mpirun -n 16 -ppn 8 -hosts n108,n109 ./mpi_stress -dcr

**Comment by wesbland** [comment]
It's possible that this is related to #4188

**Comment by aingerson** [comment]
@hzhou your PR #4197, (commit 2980cf1 again) seems to fix this issue as well. Thank you!

**Comment by hzhou** [comment]
Closed by #4197
