### ISSUE TITLE
ofi: tcp:ofi_rxm provider turns off TAGGED and RMA support

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4200]
According to comment in Issue #4188, `tcp:ofi_rxm` provider is supposed to support both `FI_TAGGED` and `FI_RMA` capability, but current MPICH code turns both settings off when `tcp:ofi_rxm` provider is selected. We need follow-up to resolve the exact issues, and potentially fix it.

EDIT: `verbs:ofi_rxm` has the same issue

**Comment by aingerson** [comment]
@hzhou more information for you:
I have been experimenting with different combinations of MPICH and providers and have found that there seems to be some issues that were introduced between MPICH 3.3 (what I was using before) and master/master + your fix. I've compiled them below. After applying your fix, I'm seeing some inconsistent errors when running the stress test. I'll have to look into the difference between the tests to understand why the OSU tests are all passing but the stress test is not when using rxm. Another thing I noticed is that in the rxm debug logs I'm seeing the following:
```
libfabric:146761:ofi_rxm:cq:rxm_handle_recv_comp():707<debug>   Got TAGGED op
```
which suggests that rxm is using tagged messaging.

Here are the various inconsistent errors I'm seeing with rxm with your fixes applied:

```
Abort(606684687) on   node 4 (rank 4 in comm 0): Fatal error in PMPI_Comm_split: Other MPI error,   error stack:
PMPI_Comm_split(491)........................:   MPI_Comm_split(MPI_COMM_WORLD, color=770112681, key=4,   new_comm=0x7ffe1ec331b0) failed
PMPI_Comm_split(472)........................:
MPIR_Comm_split_impl(162)...................:
MPIDI_Allgather_intra_composition_alpha(945):
MPIDI_NM_mpi_allgather(173).................:
MPIR_Allgather_intra_recursive_doubling(97).:
(unknown)(): Other MPI error
 
Abort(205604366) on node 13 (rank 13 in   comm 0): Fatal error in PMPI_Comm_split: Message truncated, error stack:
PMPI_Comm_split(491)........................:   MPI_Comm_split(MPI_COMM_WORLD, color=888122643, key=13,   new_comm=0x7fff7cc00da0) failed
PMPI_Comm_split(472)........................:
MPIR_Comm_split_impl(162)...................:
MPIDI_Allgather_intra_composition_alpha(945):
MPIDI_NM_mpi_allgather(173).................:
MPIR_Allgather_intra_recursive_doubling(97).:
(unknown)(): Message truncated
 
INTERNAL ERROR: invalid error code a40e   (Ring ids do not match) in MPIDI_NM_mpi_allgather:173
Abort(876693007) on node 11 (rank 11 in   comm 0): Fatal error in PMPI_Comm_split: Other MPI error, error stack:
PMPI_Comm_split(491)........................:   MPI_Comm_split(MPI_COMM_WORLD, color=888122643, key=11,   new_comm=0x7ffdf7ef20f0) failed
PMPI_Comm_split(472)........................:
MPIR_Comm_split_impl(162)...................:
MPIDI_Allgather_intra_composition_alpha(945):
MPIDI_NM_mpi_allgather(173).................:
```

Overall MPICH + OFI status:
![mpich_status](https://user-images.githubusercontent.com/10183414/69687459-d80b6700-1077-11ea-8aee-114f7242f2dd.PNG)

**Comment by hzhou** [comment]
@aingerson 
Thanks for the report. It is helpful. Seems the inconsistent error is a result of using "minimal` capability set. I wonder what will happen if we use `MPIR_CVAR_OFI_USE_PROVIDER=minimal` and use `FI_PROVIDER` to select `sockets` or `psm2`.

What is the difference between `ofi_rxm` and `ofi_rxd`?

**Comment by aingerson** [comment]
We're having some issues with our lab right now but I'll try that when it starts working again.

ofi_rxm and ofi_rxd are options to layer over core providers for added functionality. rxm is 'RDM over MSG' and rxd is 'RDM over DGRAM' so the idea is given a core provider that supports msg endpoints, you can layer rxm over it to add RDM functionality and given a core provider that supports dgram endpoints, you can layer rxd over it to add RDM functionality. Verbs has support for msg endpoints as well as UD endpoints so verbs(MSG);ofi_rxm and verbs(UD);ofi_rxd are both viable options. As for tcp, it supports only msg endpoints, so it can only be layered with ofi_rxm. You can also layer ofi_rxd over udp as well.

An RDM endpoint should have support for MSG, TAGGED, RMA, and ATOMICS so any provider using ofi_rxm or ofi_rxd should be able to support any of those capabilities.

**Comment by aingerson** [comment]
@hzhou See the results for the requested combinations below.
Looks like requesting MPIR_CVAR_OFI_USE_PROVIDER results in ENODATA for both psm2 and sockets
![mpich_psm2-sockets](https://user-images.githubusercontent.com/10183414/69759396-de9ceb80-1116-11ea-9899-b3cec85ecac1.PNG)

**Comment by aingerson** [comment]
Following up with this issue and updating status.
The previous data collected was a spot check and only collected over mlx hardware. We tried enabling all of the tests on our CI which tests all combinations of providers and hardware over all tests which resulted in the following:
![mpich_status](https://user-images.githubusercontent.com/10183414/70283522-4934d380-1776-11ea-881a-82cf846e456b.PNG)
