### ISSUE TITLE
thread: use MPIR-layer global mutex for non-performance critical path

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4203]
Currently all our thread critical section code goes through macros in `src/mpid/common/thread/mpidu_thread_fallback.h`. As we implement and experiment with different thread models, every critical section is being affected, resulting in recursive locking and multiple locking (for different models). The code become complex and difficult to move forward. 

We need to recognize that there are in general two directions for improvement: for performance-critical paths, the direction is to move down, using granular critical sections, only protect individual data/components that needs to be protected. For example, request handling should only take on the lock when we allocating/enqueuing, etc. and unlock as soon as done with such *atomic* operation. For netmod, we will need to take on the lock when we accessing completion-queue, and we should take off the lock as soon as we have done with the queue. There are limited components for performance-critical paths, so its complexity is bounded.

On the other hand, for non-performance-critical paths, the direction is to move up. Serializing with a single global lock is not a bad idea and can easily ensure correctness. For example, `Init`, `Finalize`, datatype creation/destroy, communicator creation/destroy, all can be protected by a single global lock. Unlike critical path, these routines are very complex and difficult to granularize. Having a single lock greatly simplifies the logic. When we use different mutexes for global locks and granular locks, these global locks won't even affect performance-critical paths. 

The serializing global lock doesn't need fancy schemes and should stabilize. Therefore, I propose to use a set of MPIR-layer macros. I introduced these macros in this commit: https://github.com/pmodels/mpich/pull/4199/commits/34ad9e08263432666acf6df830b185045e62cdf5. It is currently not in header files because it still relies on `MPID_` namespace macros (`MPID_Thread_mutex_lock`) and can't be directly placed in `MPIR-`layer yet. One solution would be to use `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` exclusively with `MPIR-` layer macros. Then we don't need `MPID-`layer macros to maintain the mutex-cooperability and can live in MPIR-layer entirely.

**Comment by wesbland** [comment]
cc: @sagarth

**Comment by hzhou** [comment]
Outdated.
