### ISSUE TITLE
GPU: outline of GPU integration

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4220]
This is a retake on issue #3519. While Issue#3519 is still relevant, this issue tries outline from a top-view.

## Communication components
There are three communication paths: pt2pt, RMA, and collectives.

### Collectives
Collectives all dissolve into pt2pt operations, therefore, it does not need to worry about the GPU integration in the actual communication. However, to better utilize the lower layer GPU integration, it may benefit from good partitions. Currently, we only do intra/inter-node partition. Can it benefit from GPU-aware partitions? 

Reduction with ops may be able to benefit from GPU offloading.

### pt2pt and RMA
pt2pt and RMA, although with different sets of functions, share a similar structure. At the top of the structure, it is either in the NETMOD path or the SHMMOD path.

#### NETMOD path
There are two branches, depending on the underlying library supports GPU-direct transparently -- either hardware or software but entirely managed by the library.

* Direct path -- GUP-direct is supported && message is not too large && contig data type
There is little work to be done in this branch. In fact, we should ignore GPU awareness and treat it as if it is CPU-to-CPU communication.

* Active message path
When either GPU direct is not available or the communication can benefit from pipelining or off-loading, we'll need the active message path to implement a sequence of protocols 

** [ ] Refactor current AM path

We identify the following action items:
** [ ] Send from GPU
** [ ] Recv into GPU
** [ ] Offloading with GPU

All these items can benefit from pipelining -- set up chunks that is to be copied from GPU to CPU or vice versar. Referece: PR #4175 

#### SHMMOD path

This path only involves memcpy, therefore it may be simpler to address first. It can benefit from the pipelining PR.

**Comment by wesbland** [comment]
cc: @zhenggb72 @shawnccx

**Comment by hzhou** [comment]
The issue is now outdated.
