### ISSUE TITLE
ch4: refactor ANYSOURCE handling

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4221]
## Background

When user issues a `recv` from `ANYSOURCE`, we  spawn both `MPIDI_SHM_mpi_irecv` and `MPIDI_NM_mpi_irecv`, and both requests have a `MPIDI_REQUEST_ANYSOURCE_PARTNER` linked to the other request. 

This setup singlehandedly tangles NETMOD and SHMMOD at multiple levels. It constrains each implementation and complicates the code. It has been the source of multiple difficult-to-track bugs.

## Proposal
Due to its complicated nature, it is worthwhile to create a separate infrastructure to special treat `ANYUSOURCE`, so that we can leave NETMOD and SHMMOD as pristine as possible.

* Create a composite request type for `ANYSOURCE` `recv`, and spawn both SHMMOD request and NETMOD request as sub-requests

* Only concern is we cannot have both requests to be fulfilled simultaneously, as both of them will be writing to the same buffer.

* SHMMOD and NETMOD, despite the symmetrical design, are not symmetrical. NETMOD is more opaque and heavy. SHMMOD is fully in-house transparent and "lightweight".

* Leave NETMOD pristine, i.e. completely unaware of composite requests.

* When SHMMOD matches and right before it starts to write buffer, it need to check a flag to see if it is part of a composite request. If it is, it needs to call *cancel* on all other sub-requests. If the cancel returns false, SHMMOD aborts and cancels its own request. If the cancel returns true, it proceeds. Either case, atomicity is achieved.

* At progress, if the request is a composite, it needs to check the completeness of both sub-requests. Due to the atomicity, it only needs to check the first subrequest to tell whether the request has been matched.

## Performance impact
* No impact (or better performance) on NETMOD path, since it does not need to check `ANYSOURCE_PARTNER`.
* One additional branch on SHMMOD to check whether it's part of a composite request type. Impact minimal.
* Potentially much slower for SHMMOD ANYSOURCE `recv` due to the need to cancel netmod requests as a blocking call. It may be possible to mitigate this impact.
* Progress will also incur one additional branch to check for the composite request type. Impact minimal.

## Optimization
* The dominant slow part is to cancel a netmod `recv` request, which needs go through the completion queue, which itself needs to acquire a lock, potentially be blocked.
* If the message is small, we could use separate buffers NETMOD. No synchronization is necessary. When  SHMMOD calls "cancel" on NETMOD and if NETMOD already completes the request, we move the completed request to an unexpected queue and wait for future matching. If the NETMOD fulfills in the end, an additional `memcpy` is needed. SHMMOD remain fast, only incur an additional non-blocking  "cancel" call. NETMOD need a check for pre-completed request list, but the list should be very shallow except for pathological use cases.
* If the message is large, the overhead of cancel may not be that significant.

**Comment by hzhou** [comment]
tag @raffenet

**Comment by wesbland** [comment]
> Leave NETMOD pristine, i.e. completely unaware of composite requests.

So you want to remove the part where the netmod informs the shmmod about a matched request in the callback handler?

**Comment by hzhou** [comment]
> > Leave NETMOD pristine, i.e. completely unaware of composite requests.
> 
> So you want to remove the part where the netmod informs the shmmod about a matched request in the callback handler?

Yes. The idea is to let `shmmod` always check `netmod` (in case of anysrc) before writing the buffer. The same effort that netmod to inform shmmod could be used to simply update complete counter, and have the same effect of canceling shmmod.

**Comment by wesbland** [comment]
I was thinking about this some more today. How does the request on the shared memory side get cleaned up if the netmod matches? Since the netmod never tells the shared memory side, that request will sit around forever and never get matched or get cleaned up.

I don't think this causes a correctness problem (if the message is ever matched in the future, it'll get cancelled then), but if no other message ever comes in on the communicator, it'll never get freed either so there will be memory leaks and debugging errors spit out at finalize time.

**Comment by hzhou** [comment]
The clean up happens at MPIR-layer (wait or test). If the request is of a composite type, it need free every sub-requests.

**Comment by wesbland** [comment]
I see. That makes more sense.

**Comment by hzhou** [comment]
It is less of an issue now that anysource code in ch4 has been refactored.
