### ISSUE TITLE
mpiexec: unifying mpiexec behaviors

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4223]
Current MPI standard currently  recommends a standard `mpiexec` interface that includes following options
* `-n <numprocs>`
* `-soft <...>`
* `-host <...>`
* `-arch <...>`
* `-wdir <...>`
* `-path <...>`
* `-file <...>`
* and `mpiexec {...} : {...} : ... : {...}`, i.e. colon separated multiple command lines

However, implementations often supports additional options that users needed for better utilization of modern hardware, in particular:
* `-bind-to <...>`
* `-map-by <...>`
* world process rank ordering

These options have become critical in modern HPC; and because of the importance, user expect some semi-consistent behaviors so they can use with some degree of reliability and portability.

This issue is created to start the discussion and solicit input, start with MPICH and OpenMPI, to survey status, identify scope, reach consensus, and establish action items.

## Reference
* MPI 3.1 section 8.8: https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf
* MPICH wiki page: https://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager
* OpenMPI man page: https://www.open-mpi.org/doc/v3.0/man1/mpiexec.1.php

**Comment by hzhou** [comment]
tag @raffenet @jsquyres

**Comment by wesbland** [comment]
If this is really that critical (and I'm not disagreeing that it is), maybe this is something that should be discussed with the MPI Forum to potentially add new behavior to the standard? Particularly as we now have years and years of prior art.

**Comment by hzhou** [comment]
> If this is really that critical (and I'm not disagreeing that it is), maybe this is something that should be discussed with the MPI Forum to potentially add new behavior to the standard? Particularly as we now have years and years of prior art.

I think it will go much faster and easier if we can get the implementations going *first*.

**Comment by hzhou** [comment]
Close due to lack of response from OpenMPI team
