### ISSUE TITLE
mpl: Rename MPL_strncpy

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4227]
MPL_strncpy is *not* a portable version of ANSI C `strncpy`. It has different behavior, at least with regard to null-termination. We should rename it to avoid confusion.

I am not sure if it is 100% the same, but BSD `strlcpy` does implement similar null-termination behavior. Perhaps it is as simple as calling it `MPL_strlcpy`.

**Comment by raffenet** [comment]
There is one different between `MPL_strncpy` and `strlcpy`. It does not return the size of the string it tried to create in case of truncation. It only returns a binary success or failure. It should be trivial to align it with `strlcpy`.

**Comment by hzhou** [comment]
It is not clear to me that there is such confusion exist or matters.

**Comment by hzhou** [comment]
I am not sure we have a better name to rename and not sure the renaming will make the code any cleaner. Close for now.
