### ISSUE TITLE
mpl/atomic: fix __sync implementation

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#4228]
As discussed in #4222 (discussion about the OpenPA implementation of `__sync` and `__atomic`), the current implementation of `__sync` in mpl/atomic seems incorrect: https://github.com/pmodels/mpich/blob/master/src/mpl/include/mpl_atomic_gcc_sync.h

It should be fixed as soon as we find how to fix it.

**Comment by raffenet** [comment]
@shintaro-iwasaki this was fixed in #4233, right? Shall we close this? Or was there more that needs fixing?

**Comment by shintaro-iwasaki** [comment]
Yes, it has been fixed by #4223. Let's close this issue.
