### ISSUE TITLE
ch4: Revamp active message path

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4232]
Active message path will be required for the GPU integration and potentially other protocols such as large message, chunked message, RDMA etc. The current active message infrastructure are designed with limited foresight of these new demand, and does not show a clean way of expand its scope; therefore, it is beneficial to try a new and simpler/cleaner revamp.

## Objective
* Simpler interface
  ** Potentially just one `AM_send` and a send-side callback to clean up due to asynchronous device send semantics, and a target-side callback to execute active message handlers
* Better isolations
  ** The netmod/shmmod layer should not worry about any upper-layer details (for the am path) and simply call the callbacks upon send/recv
  ** AM layer should treat active message payload as opaque buffer and only worry about assembling active message header and running the handlers
  ** Upper protocol layer will implement all protocol procedures using handler functions and calling the AM layer

* Modular protocol layer
** The protocol layer should be modular and easily expandable. Each module implements one specific protocol. Each module is independent.
** ch4 layer will exercise decisions on which protocols to use for different message criterion and call the protocol function accordingly.
** It may be also possible for the netmod layer to exercise decisions based on its netmod specific information and fall back to one of the protocol module. Care need  be taken to prevent circular scenario. If we design the protocol modules to be specific, such scenario can be prevented by design. 

## Action items
* Add interface and implementation for ch4 AM layer
** directory structure:
```
ch4/am/include/
ch4/am/src/
ch4/am/rndv/
...
```
** If it is inlined, a potential place is `ch4/include/ch4_am.h`
** If it is not inlined, a potential place is `ch4/am/common.c`
** `MPIDI_AM_send(int handler_id, void *payload, int payload_size, void *callback_arg)`
*** Potentially, we'll need `MPIDI_AM_send_v` 
*** ...and `MPIDI_AM_send_dt1`
** `MPIDI_AM_send_callback(void * callback_arg)`
** `MPIDI_AM_target_callback(int handler_id, void * payload, int payload_size)`
** AM handler registration

* Add example RNDV protocol
** Potentially, `ch4/common/AM/rndv.c`

* Add NETMOD active message send and event dispatch
** `MPIDI_NM_am_send(void * buffer, int size)`
** on send completion even, call `MPIDI_AM_Send_callback`
** on recv event dispatch, call `MPIDI_AM_target_callback`
** UCX implementation
** OFI implementation

* Add SHMMOD active message send and event dispatch
** Question: does it make sense to force SHMMOD go through the same interface or SHMMOD can benefit from its own custom active message path? I guess the question is how many protocol layer can be shared between SHMMOD and NETMOD

* Implement code for MPI functions to use the new active message protocol.

**Comment by gcongiu** [comment]
@hzhou can we rename `MPIDI_AM_send_callback -> MPIDI_AM_send_src_cb` and `MPIDI_AM_target_callback -> MPIDI_AM_send_dst_cb`? These are both callbacks for the send operation, using target is confusing as target is normally used in RMA operation. Modules will provide their own versions of these, e.g., for rndv `MPIDI_AM_rndv_send_src_cb` and `MPIDI_AM_rndv_send_dst_cb` that will be called by the generic ones after inspecting the `handler_id`.

**Comment by hzhou** [comment]
Obsolete
