### ISSUE TITLE
no PMPI version of conversion routines

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#4248]
Michael Raymond reports:

 One of our testing scripts was looking at Fortran entry points and noticed that there are no PMPI versions of

MPI_CONVERSION_FN_NULL
mpi_conversion_fn_null
mpi_conversion_fn_null_
mpi_conversion_fn_null__

  Functions like MPI_COMM_DUP_FN have them. I don’t care about this and I don’t see why a customer would, but I thought I’d mention it.

**Comment by hzhou** [comment]
To my understanding, `MPI_CONVERSION_FN_NULL` is not an "MPI Function", it is a predefined constant. There are no PMPI versions of constants.

**Comment by hzhou** [comment]
Closing it as it is not clear this requires a fix.
