### ISSUE TITLE
thread: multi threaded iprobe + isendrecv tests time out for ch3/tcp

### ISSUE THREAD

**Issue by sagarth** [pmodels/mpich#4258]
Failing tests (from PR #4255 ):
threads/pt2pt/mt_iprobe_isendrecv 2
threads/pt2pt/mt_improbe_isendrecv 2

Configurations:
ch3/tcp freebsd64

**Comment by hzhou** [comment]
@sagarth The nightly ch3-FreeBSD tests has been clean for a while. Is this still an issue or should we close it?

**Comment by sagarth** [comment]
@hzhou  We do no test ch3 locally. If it is clean at Argonne's testing, that's probably a good sign that these failures are resolved and that we can close this issue now.

**Comment by hzhou** [comment]
Sounds good
