### ISSUE TITLE
Accelerator Pipelining Interface - Intranode

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#4271]
# Problem Statement
This issue describes the proposed data structures and interfaces for efficiently managing MPI communications when data is residing in GPU memory and GPU Direct Peer-to-peer can't be used. In such case the MPI implementation has to stage data through the host shared memory before it can hand it over to the destination buffer. For collective reductions and one-sided operations the PCIe transfer overhead can be alleviated by pipelining data transfer with compute on the GPU.

# Use Case
For now we limit to the case in which send and receive datatypes are contiguous; We also consider the case in which the source buffer is on one GPU memory and the destination buffer is one another GPU memory on the same node. We also assume data in the GPU buffer is always valid when such buffer is passed to MPI, implying that appropriate host/device synchronization has been performed by the MPI program (no synchronization is implicitly done by MPI at this time).

In this scenario MPI communication happens by copying data from GPU memory into a series of staging buffers in host shared memory and then further copying it from these to the destination buffer in GPU memory. Each buffer needs an associated `cudaEvent_t` to synchronize the `cudaMemcpyAsync()` operation with the host thread.

# Pipeline Context
As already said we only consider the Device-Host-Device pipelining. Similarly to the internode case, also in this case the pipelining can be represented using a context. Follows a description of such context:

```
typedef struct MPIDI_gpu_shared_pipeline_ctx {
    /* size of shared context (includes staging area) */
    size_t ctx_sz;

    /* serialized handle for shared context */
    char ctx_hnd[MAX_NAME_LENGTH];

    /* source GPU memory handle (opened by receiver) */ 
    MPL_gpu_ipc_mem_handle_t src_hnd;

    /* source buffer size */
    size_t src_sz;

    /* source GPU memory pointer */
    char *src_ptr;

    /* destination buffer size */
    size_t dst_sz;

    /* destination GPU memory pointer */
    char *dst_ptr;

    /* number of stages in pipeline */
    int num_stages;

    /* data size for each stage */
    size_t stage_sz;

    /* offset to stage area in the shared context */
    size_t stage_area_off;

    /* pointer to stage area */
    char *stage_area_ptr;

    /* offset to GPU events in the shared context */
    size_t stage_events_off;

    /* pointer to GPU events */
    MPL_gpu_event_t *stage_events_ptr;

    /* pointer to stage (chunk) for source buffer */
    char *stage_src_ptr;

    /* pointer to stage (chunk) for destination buffer */
    char *stage_dst_ptr;

} MPIDI_gpu_shared_pipeline_ctx_t;
```

The pipeline context is created, managed, and destroyed using appropriate APIs:
```
/* take a new context from the ctx pool or create a new one - 
   this step also allocates staging area and registers it. */
int MPIDI_gpu_shared_pipeline_ctx_create(int num_stages,
                                         size_t stage_sz,
                                         MPIDI_gpu_shared_pipeline_ctx_t **ctx);

/* attach to shared context */
int MPIDI_gpu_shared_pipeline_attach_ctx(char *ctx_hnd, size_t ctx_sz);

/* return the context to the ctx pool */
int MPIDI_gpu_share_pipeline_ctx_destroy(MPIDI_gpu_shared_pipeline_ctx_t *ctx);

/* attach source user GPU buffer to context */
int MPIDI_gpu_shared_pipeline_attach_src_buf(MPIDI_gpu_shared_pipeline_ctx_t *ctx,
                                             void *buf,
                                             size_t buf_sz);

/* attach destination user GPU buffer to context */
int MPIDI_gpu_shared_pipeline_attach_dst_buf(MPIDI_gpu_shared_pipeline_ctx_t *ctx,
                                             void *buf,
                                             size_t buf_sz);

/* detach user buffer from context: optionally this can be done by destroy */
int MPIDI_gpu_shared_pipeline_detach_buf(MPIDI_gpu_shared_pipeline_ctx_t *ctx);

/* make progress by calling cudaMemcpyAsync */
int MPIDI_gpu_shared_pipeline_make_progress(MPIDI_gpu_shared_pipeline_ctx_t *ctx, 
                                            void **chunk_ptr,
                                            size_t *chunk_len,
                                            MPIR_Request **chunk_req);
```

The context create interface gets a context from a context pool. If the pool is empty a new context is actually created. This also has gpu specific information (such as  NVIDIA GPU streams and events to manage the different pipeline stages).

A new context is created at runtime (e.g., `MPI_Send`). When the transfer is complete, the context is not destroyed. Instead, the user buffer can be detached and the context returned to the context pool for later reuse. When a new context is needed, if the context pool is empty a new context is created otherwise an existing one is used.

# Active Message Pipelining Protocol
[...]

# Example
[...]

# Attach Compute to the Context
[...]

**Comment by hzhou** [comment]
Outdated
