### ISSUE TITLE
Wrong condition statement for return value of MPL_get_sockaddr in PMII_Connect_to_pm

### ISSUE THREAD

**Issue by Mahdiehgh-osu** [pmodels/mpich#4278]
MPL_get_sockaddr returns 0 on success while PMII_Connect_to_pm assumes that it returns 0 on failure.

Here a simple fix for it:

$git diff
diff --git a/src/pmi/simple/simple_pmi.c b/src/pmi/simple/simple_pmi.c
index 4df33e9..ac60723 100644
--- a/src/pmi/simple/simple_pmi.c
+++ b/src/pmi/simple/simple_pmi.c
@@ -891,7 +891,7 @@ static int PMII_Connect_to_pm(char *hostname, int portnum)
     int q_wait = 1; 
     ret = MPL_get_sockaddr(hostname, &addr);
-if (!ret) {
+if (ret) {
         PMIU_printf(1, "Unable to get host entry for %s\n", hostname);
         return PMI_FAIL;
     }

**Comment by hzhou** [comment]
Wait, `!ret` means `ret != 0`, which means error condition, right? I think the current code is correct.

**Comment by hzhou** [comment]
You are right, patches coming.
