### ISSUE TITLE
Remove -fallow-argument-mismatch option for frotran compilers

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4300]
The upcoming Fedora release will include GCC 10 packages. In this version, gfortran will now consider mismatchs between function calls and procedure definitions to be an error, and require additional flags to allow.

> -fallow-argument-mismatch
> Some code contains calls to external procedures whith mismatches between the calls and the procedure definition, or with mismatches between different calls. Such code is non-conforming, and will usually be flagged wi1th an error. This options degrades the error to a warning, which can only be disabled by disabling all warnings vial -w. Only a single occurrence per argument is flagged by this warning. -fallow-argument-mismatch is implied by -std=legacy.
> 
> Using this option is strongly discouraged. It is possible to provide standard-conforming code which allows different types of arguments by using an explicit interface and TYPE(*).

The NAG compiler has been doing this for some time. MPICH configure suggests to the user flags to use to workaround the issue. Shall we continue to do this for GCC? Or do update the Fortran bindings to avoid it altogether?

**Comment by wesbland** [comment]
Sorry for not following enough of the discussion on the mailing list. Is changing this an MPI Standard problem? An MPICH problem? Does it have ABI implications?

**Comment by raffenet** [comment]
It's...complicated. The way to fix this involves non-standard Fortran features, which some argue is an overreach of the MPI Standard.  I'm not sure of the ABI impact. The C ABI should not be affected. We could do some tests with Fortran to understand better.

**Comment by wesbland** [comment]
Ugh...I withdraw my interest. 😄

**Comment by balay** [comment]
I'm encountering this issue with building mpich and gcc/gfortran 10 now

**Comment by jxy** [comment]
Google gave me this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91731
I see that macports got the fix in as above.

For anyone got here, use `FFLAGS=-fallow-argument-mismatch` as a workaround.

**Comment by pavanbalaji** [comment]
We should probably update the Fortran bindings to avoid this issue, if that's an option.

**Comment by hzhou** [comment]
> 
> 
> We should probably update the Fortran bindings to avoid this issue, if that's an option.

That is difficult. The issue is caused by MPI standards allow user defined attribute functions and these functions have different signatures in FORTRAN and C binding. I need refresh myself to recall the details, but I remember it has always been the pain. In fact, our f08 is currently broken also due to this issue and because gfortran and ifort interpreted the iso binding differently. We implemented to meet intel compiler which result in gfortran broken. Our finger has been pointing to gcc.

**Comment by hzhou** [comment]
By the way, I am not exactly sure about the nature of this issue, is it for `use mpi` (FORTRAN 90) or `use mpi_f08`? The former has a C layer that should be able to turn the type mismatch to the C side, which is more lenient on casting function pointers. For `f08`, we may have to also add a C glue just for these user function passings. I'll investigate more when I get a chance.

**Comment by raffenet** [comment]
`use mpi` module. The C backend is not the issue. It is that we do not generate all possible type TKR combinations for the Fortran interfaces, or use non-standard features to disable argument checking for choice buffers.

**Comment by pavanbalaji** [comment]
If someone can explain what needs to be generated, I can probably script it out.

**Comment by harisubramoni** [comment]
Hi, Guys.

I am also interested in this issue since it affects MVAPICH2 as well. Please let me know if I can help.

Best,
Hari.

**Comment by longb** [comment]
Just to point out that assumed-type and assumed-rank dummy arguments were put into the Fortran standard, largely based on requests from the MPI community, to avoid the problems of including generic interfaces with specifics to cover all TKR combinations, if the ultimate callee was a C function anyway.   The MPI module should be using these.

**Comment by dev-zero** [comment]
> > We should probably update the Fortran bindings to avoid this issue, if that's an option.
> 
> That is difficult. The issue is caused by MPI standards allow user defined attribute functions and these functions have different signatures in FORTRAN and C binding. I need refresh myself to recall the details, but I remember it has always been the pain. In fact, our f08 is currently broken also due to this issue and because gfortran and ifort interpreted the iso C binding differently. We implemented to meet intel compiler which result in gfortran broken. Our finger has been pointing to gcc.

Did you open a GCC Bugzilla issue for that? Just for reference.

**Comment by hzhou** [comment]
> That is difficult. The issue is caused by MPI standards allow user defined attribute functions and these functions have different signatures in FORTRAN and C binding. I need refresh myself to recall the details, but I remember it has always been the pain. In fact, our f08 is currently broken also due to this issue and because gfortran and ifort interpreted the iso C binding differently. We implemented to meet intel compiler which result in gfortran broken. Our finger has been pointing to gcc.

The latest mpi_f08 module uses C proxy functions (the same mechanism as f90) rather than fortran proxy functions, thus we no longer relying on the compiler support of writing C-like functions (in particular, passing parameter by value) in fortran.

**Comment by hzhou** [comment]
Revised the title to reflect the goal of this ticket.
