### ISSUE TITLE
testing: make failure due to mpi_f08 module dependency issue

### ISSUE THREAD

**Issue by abrooks98** [pmodels/mpich#4307]
Since #4199, dependency on the mpi_f08 module in `test/mpi` is not preserved during make. I believe when `mtest_f08.f` was moved from `test/mpi/f08/util` to `test/mpi/util` ([in this commit](https://github.com/pmodels/mpich/pull/4199/commits/13617eceba173327ba37dd0ddb33f489d57f8df6)), additional checks for making target `mtest_f08.$(OBJEXT)` were not added, causing make in `test` to fail when f08 support is not enabled (i.e. via `--enable-fc`).

## To Reproduce:
(config used from pmodels' Jenkins)

```
CC=gcc CXX=g++ FC=gfortran F77=gfortran /home/alexbroo/software/mpich-ofi/configure --prefix=/home/alexbroo/opt/mpich/install/gnu/master-argonne-jenkins-check --with-device=ch4:ofi -disable-ft-tests --with-libfabric=embedded --disable-mlx --enable-nemesis-dbg-localoddeven --enable-large-tests --enable-collalgo-tests --disable-perftest --with-wrapper-dl-type=rpath
make -j16
make install
cd test/mpi
make -j16
```

## Error:
```
Making all in util
make[1]: Entering directory '/home/alexbroo/opt/mpich/stage/gnu/master-argonne-jenkins-check/test/mpi/util'
  CC       mtest.o
  CC       dtypes.o
  CXX      mtest_cxx.o
  F77      mtest_f77.o
  FC       mtest_f08.o
  CC       mtest_thread.o
/home/alexbroo/software/mpich-ofi/test/mpi/util/mtest_f08.f90:8:12:

         use mpi_f08
            1
Fatal Error: Can't open module file ‘mpi_f08.mod’ for reading at (1): No such file or directory
compilation terminated.
make[1]: *** [Makefile:616: mtest_f08.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/alexbroo/opt/mpich/stage/gnu/master-argonne-jenkins-check/test/mpi/util'
make: *** [Makefile:547: all-recursive] Error 1
```

**Comment by abrooks98** [comment]
@hzhou Could you take a look? We can't merge these commits until its resolved; In Jenkins we build the test directory.

**Comment by hzhou** [comment]
> @hzhou Could you take a look? We can't merge these commits until its resolved; In Jenkins we build the test directory.

OK, I'll look at it.
