### ISSUE TITLE
general: banish size_t and use MPI_Aint

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4308]
In working on PR #4306 today, I had a test error on `coll/gather_big`. By the time I fixed the bug, my entire day is nearly gone. The bug was an integer overflow, and the bug was not mine. It has been lurking in our code for quite a while. We test `gather_big` all the time, why it didn't fail before? Let me tell the story.

`gather_big` gathers from 8 processes count (of 27bit) long (4-8bit), so at some point the internal buffer will exceed 32-bit. Our gather algorithm is 64-bit clean, but it calls `MPIC_Recv`. Our `MPIC_Recv` calls `MPID_Recv` and it calls `MPIDI_Recv_safe`, and it calls `MPIDI_Recv_unsafe`... I am describing it slowly to emphasize that try to proofread our code is a very daunting (cross that, impossible) task. We rely on tests to clean our code.

Turns out MPIDI_Recv_xxx uses int for its count argument, I am sure it is an oversight that no-one should be blamed. So the receive-size now become negative, which doesn't make sense and any operation that based on that negative count will give bizarre results. Tests fail and we fix it -- no big deal. Except when it further travels down to protocol layer and transport layer, we used `size_t` somewhere, on the rationale that size_t is guaranteed to be big enough and count is supposed to positive anyway. So the conversion goes smoothly and our count become legitimate again (positive) but very large.  Turns out, very large is OK in our current code. We checked and see the data will fit into this "very large" receive buffer and happily moved forward. No alarms!

The problem is it should alarm. The code is wrong. At its critical place, it is holding a wrong information. 

`unsigned` number can't go negative, and that is a problem. It is impossible to detect when an unsigned number overflow or underflow. Overflow check is only possible with a datatype that is bigger than our valid range so that we can check against our boundaries. If we used `MPI_Aint`, which is so big that practically guaranteed to never overflow, we will always be able to check when its value are invalid. We put one assert somewhere, it ensures our entire code chain! Why wouldn't we like that?

I have a PR #3826 just do that. Please let me convince you it is a good thing. :)

**Comment by pavanbalaji** [comment]
If the concern is between signed and unsigned, perhaps `ssize_t` might be better than `size_t` (`MPI_Aint` is, in practice, just a wrapper for `ssize_t`; configure does additional logic only because it was created in C89 world).  Although, I'm surprised that the compiler did not throw a warning for a `size_t` argument being passed to a function that takes an `int` parameter.  That's a downcast and compilers are usually pretty good about throwing warnings in such cases.  Are you sure there was no compiler warning that was ignored?

**Comment by hzhou** [comment]
Compiler would complain about signed/unsigned conversion, so developers get around by casting. E.g.
```
int x = 1;
size_t count;

count = (size_t) x;
```
No warnings for that and negative numbers get lost.

**Comment by hzhou** [comment]
The concern with unsigned is its common values sits right at the boundary of under-flow. With `ssize_t` (or MPI_Aint as we already using it), the common values sits in the middle -- much safer.

**Comment by raffenet** [comment]
We should be able to easily catch these errors with the compiler, assuming we can clean up the code first 😄
https://github.com/pmodels/mpich/blob/d1665bb7594358251d82d44952ecd6afd4993092/confdb/aclocal_cc.m4#L472-L475

**Comment by hzhou** [comment]
> We should be able to easily catch these errors with the compiler, assuming we can clean up the code first 😄

If that is a warning about explicit `cast`, then I am not sure it will be a good idea. There are too many legitimate cases that we do down-sizing cast. In principle, explicit cast in C always means that the programmer knows better and the compiler should keep silence.

If that is a warning about "implicit" conversion, it is a good option. But I suspect that is not the case.

**Comment by raffenet** [comment]
```
#include <stdlib.h>

int main(void) {
    size_t a = 100;
    int b = a;

    return 0;
}
```

> raffenet@mcswl049:~/ $ gcc -Wshorten-64-to-32 foo.c
> foo.c:5:13: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
>     int b = a;
>         ~   ^
> 1 warning generated.

**Comment by hzhou** [comment]
Issue served its discussion purpose. Closing it since no immediate clear actions.
