### ISSUE TITLE
ch4/shm: glue layer function table and --disable-ch4-shm-inline

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4315]
In the original ch4/shm design, we envisioned multiple shmmods at the same level of netmods. Therefore, we built in the infrastructure to inline all shm code by default, but also give the ability to build multiple shmmods and use runtime selection using a function table.

The design evolved over time and now there is a non-optional ch4/shm "glue" layer which calls down to lower-level shm transports. However the function table infrastructure remains, despite it only being possible to use a single implementation. To me, it seems unnecessary and I would like to remove it.

One possible caveat is without some alternative, just removing the function table would always inline the perf critical parts of the glue layer. This means some development workflows might have longer compiler times if they are modifying the glue layer. Is this of concern to anyone?

**Comment by hzhou** [comment]
I don't disagree. However, this is a minor to-do item that is only useful if someone is working on it. Since it is getting stale, I am closing it for now.
