### ISSUE TITLE
Recursive Lock Acquisition

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#4348]
When MPICH is configured with `--enable-threads=multiple` it acquires a global lock at every MPI communication call. There are currently cases in which MPICH might acquire this lock recursively. One example is MPI generalized requests. The callback associated with a `MPI_Grequest` contains user defined code and is executed by the MPI progress engine when `MPI_Wait` is called on the greq handle, if this has been marked by the user program as complete (using `MPI_Grequest_complete`). It is possible for a `MPI_Grequest` callback to make MPI communication calls such as `MPI_Isend`. In this case MPICH will acquire the global lock recursively. This behavior should be avoided by releasing the lock before executing the callback.

**Comment by gcongiu** [comment]
@hzhou

**Comment by hzhou** [comment]
Added a commit taking off the global lock in PR #4385

**Comment by hzhou** [comment]
Recursive locking has been eliminated.
