### ISSUE TITLE
Message combining algorithms for neighborhood collectives - #2631.

### ISSUE THREAD

**Issue by tks2004** [pmodels/mpich#4365]
Is the commit "a0bd3416a798ded39c3fca0675bf575bbab06041" based on 3.3.1 version.

**Comment by hzhou** [comment]
You are referring to PR #3892?

No, that PR is based on master branch, in particular, commit "85dad9cc0" dated 6/26/2019.

**Comment by tks2004** [comment]
Ok. Thanks! Will this be merged to the master branch?

**Comment by hzhou** [comment]
I don't think it will happen anytime soon. There is still debate on the pros and cons and the benefits toward practical applications.

**Comment by hzhou** [comment]
On the other hand, there is still enough interest to keep it alive. If you needed it and have trouble rebasing to a recent master or certain branch, ping us.

**Comment by hzhou** [comment]
@tks2004 Can this issue be closed?

**Comment by tks2004** [comment]
If you can help with rebasing this commit with the master branch it will be helpful

**Comment by hzhou** [comment]
tag @raffenet

**Comment by hzhou** [comment]
@tks2004 I have rebased #3892 to the latest master. It compiles cleanly. If you have problems to get it working for you or have questions, please comment on that PR. 

Closing this issue.

**Comment by tks2004** [comment]
Thanks! I was able to compile and run with this rebased version
