### ISSUE TITLE
MPL/atomics: introduce a workaround for PGI compilers

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#4383]
Currently, PGI compilers do not support MPL/atomics (i.e., C11, GCC `__sync`, and GCC `__atomics`), which forces a fallback to very inefficient lock-based atomics.

There are several ways to address this issue:
1. Introduce an OpenMP atomics layer since (as far as I remember) PGI supports OpenMP atomics.
2. Introduce an x86/64 assembly layer.
3. Create an OpenPA wrapper layer.
3.a. Use the current embedded OpenPA.
3.b. Put an OpenPA library into MPL/atomics.
3.c. Link an external OpenPA library.
4. Introduce an C++11 atomic layer since (as far as I remember) PGI supports C++11 atomics.
    - This can solve the Windows atomic issue as well (for reference, now MPL/atomics has a Windows native atomic intrinsics layer only for Windows)
5. Wait till someone complaints.

We want to remove the current OpenPA from MPICH, so if we just need to work this issue around, I like 3b so that we can remove OpenPA-related options from MPICH's configure. If 3b is chosen, we can just automatically choose the best one.

Any suggestion is welcome!

**Comment by hzhou** [comment]
I vote for `3.b`. It is the most smooth solution, right?

> 5. Wait till someone complaints.

Having the PGI compiler support crippled right now is enough a reason IMHO :)

**Comment by hzhou** [comment]
If we do `3.b`, I would recommend only enable it with explicit user option, i.e. `--with-mpl-atomic-primitives=openpa`, remove the `mpl` lock emulation option and raise error if user choose `auto` but we have to fallback.

If we only support explicit option, then we can easily setup and configure openpa from MPICH's configure, that will keep the amount of code change minimum and organization clean.

**Comment by hzhou** [comment]
We have migrated atomics to MPL. This issue is stale. If necessary, open a new one with more specific descriptions.
