### ISSUE TITLE
doc: MPIEXEC_PREFIX_DEFAULT doesn't work

### ISSUE THREAD

**Issue by simonbyrne** [pmodels/mpich#4388]
I tried using the `MPIEXEC_PREFIX_DEFAULT` environment variable (which is suggested on the [man page](https://www.mpich.org/static/docs/latest/www1/mpiexec.html)) but it doesn't seem to have an effect:
```
> MPIEXEC_PREFIX_DEFAULT=1 mpiexec -n 2 echo "hello world"
hello world
hello world
```

However the `-prepend-rank` option (which isn't mentioned on the man page, but _is_ mentioned under `mpiexec --help`) does work correctly:
```
> mpiexec -prepend-rank -n 2 echo "hello world"
[0] hello world
[1] hello world
```

(Discovered in https://github.com/JuliaParallel/MPI.jl/issues/360)

**Comment by hzhou** [comment]
Thanks for reporting.

**Comment by travisk1154** [comment]
I have submitted a [PR](https://github.com/pmodels/mpich/pull/5135) that fixes this issue. There was no code that handle this environment variable and we felt that it should stay so I've added some.
