### ISSUE TITLE
coll: memory leaks

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4396]
LeakSanitizer flags some unfreed memory. Looks to be mostly from the json library. Perhaps we are not fully destroying those resources in finalize.

https://pmrs-jenkins.cels.anl.gov/job/mpich-master-address-sanitizer/lastCompletedBuild/compiler=clang-8,jenkins_configure=asan,label=centos64,netmod=ch3-tcp/console

**Comment by hzhou** [comment]
Sigh...external dependency brings in so much hassle.
