### ISSUE TITLE
cxx: not to enable CXX binding by default

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4412]
Since cxx binding has been removed from MPI-standard, I propose let's remove the cxx bindings from mpich 3.4. Instead of supporting legacy cxx bindings, we should instead provide `mpicxx` that works with c++ compiler and links to the standard `libmpi.so`.

**Comment by wesbland** [comment]
cc: @ddurnov

**Comment by hzhou** [comment]
Originally this issue was motivated by configure issue when `--disable-cxx` won't build `ucx`. That is now fixed, so there isn't a pressing need for this issue now, and I think there is no reason to remove the binding just to give hard time to some old applications.

On the other hand, I think it is good idea to make `cxx` binding disabled by default -- I am renaming the issue.

**Comment by hzhou** [comment]
Apparently, there are some users who like using the CXX bindings. Since there are no good reasons for one way or another, I am closing this issue.
