### ISSUE TITLE
test/mpich/threads: MTest_init_thread_pkg() is not called.

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#4422]
### Problem

In MPICH multithreaded tests, `MTest_init_thread_pkg()` should be called in `MTest_Init_thread()` but it is not. This causes an uninitialized error when underlying threads require initialization (which is now applies to Argobots). In fact, it breaks tests with Argobots (see #4421).

### Reason

The following part is expected to initialize `MTest_init_thread_pkg()`, but it is ignored since `mtest.o` is compiled without `-DMTEST_USE_THREAD`.
https://github.com/pmodels/mpich/blob/master/test/mpi/util/mtest.c#L85-L87

Note that other thread-dependent calls are defined in `mtest_thread.c` (and compiled into `mtest_thread.o`)
https://github.com/pmodels/mpich/blob/master/test/mpi/util/mtest_thread.c

This was introduced by 28b3059 in order to split single-threaded `mtest` (`mtest.o`) and multithreaded `mtest` (`mtest_thread.o`). I believe the root cause of this issue is that `mtest.o` calls a thread-related feature and `mtest_thread.o` is considered an additional object that adds functionalities on top of `mtest.o`. Note that the current linking is as follows:
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o
```

### How to fix

There are several ways to fix it. I list some reasonable ones. Personally I like the solution 0.

#### 0. Remove `MTest_init_thread_pkg()`
  - Right now only Argobots has this restriction. Argobots can solve it internally in `mtest_thread_abt.h` (by checking initialization in every thread-function calls).

#### 1. Define `MTest_Init_thread()` and `MTest_Finalize()` in `mtest_thread.o`.
  - Put common implementation in a header (say, `mtest_common.h`) and both `mtest.c` and `mtest_thread.c` implement `MTest_Init_thread()` and `MTest_Finalize()`. `mtest_thread.c` does not rely on `mtest.c`
```
Multithreaded tests are linked to mtest_thread.o
Single-threaded tests are linked to mtest.o
```
#### 2. Create single-threaded `MTest_init_thread_pkg()`
  - This can remove `#ifdef MTEST_USE_THREAD` in `mtest.c`.
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o and mtest_single.o
```

#### 3. Create another wrapper function (say, `MTest_Init_thread_with_thread_pkg()`)
  - `MTest_Init_thread_with_thread_pkg()` is implemented in `mtest_thread.c`
  - This needs to change all the tests in `test/mpi/threads/`.
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o
```

#### 3.b. Use a macro trick.
 - Similar to 3 but use a macro trick to avoid rewriting tests in `test/mpi/threads/`
```c
// in mtest_thread.h
#define MTest_Init_thread(...) \
do {                           \
  MTest_init_thread_pkg(...);  \
  MTest_Init_thread(...);      \
while (0)
```

#### * Dirty solutions:
- Define `MTest_init_thread_pkg()` as a weak symbol.
- Use `__attributes__((constructor))` (initialize a thread package in program initialization).

Any suggestions are welcome.

**Comment by hzhou** [comment]
My preference is to prefer "explicit" or "simple", so solution 2 fits the bill :)

**Comment by hzhou** [comment]
To expand, I would create `Makefile.common`. And in `Makefile.mtest`, include `Makefile.common` and add to `LDADD` `mtest_single.o`. And in `Makefile_threads.mtest`, just replace the include of `Makefile.mtest` with `Makefile.common`.

**Comment by shintaro-iwasaki** [comment]
@hzhou Thank you for your comment. Actually I implemented solution 0 by using refcount (see the last commit of #4421) and found it is not very complicated.

At present only Argobots uses `MTest_init_thread_pkg()`, which also imposes a restriction that all `MTest_thread_xxx()` (e.g., mutex creation) must be called between `MTest_Init_thread()` and `MTest_Finalize()`.  I am not sure if we should keep this mechanism only for Argobots.

If Pthreads and Windows threads might use `MTest_init_thread_pkg()` for something (e.g., debugging) in the future, I am happy to fix this issue (I will implement solution 2 first as you suggested).  If this is maintained only for Argobots, however, maybe we can just remove `MTest_init_thread_pkg()` and `MTest_finalize_thread_pkg()`.

**Comment by hzhou** [comment]
I think having an explicit `MTest_init_thread_pkg` is semantically clean. For example, if we want put some additional thread-related test initialization, we have an obvious place to go. Since we already have `Init/Finalize`, having the mentioned restriction is intuitive and I don't think it is an issue. 

That said, I think I am fine with your solution 0.
