### ISSUE TITLE
Supporting f18

### ISSUE THREAD

**Issue by naromero77** [pmodels/mpich#4427]
@raffenet 

`f18`, the successor to `flang`, will be upstreamed into LLVM hopefully by the end of April 2020. I wanted to start the conversation going w.r.t. supporting f18 into the mpich build system. I tried to build mpich a couple of different ways with f18 -- it seems to mostly (>90%) work, but fails near the end when the building mpich Fortran modules. As best I can tell, f18 default extensions for modules is `.f18.mod` instead of `.mod` which throws off the build system. Even if I override the default f18 Fortran module extension with a compiler flag -- there are still problems.

If you have access to the GCE environment, I could document the steps need to reproduce the issue and you could try to reproduce it. I suspect the issue is the build system, because if I compile the problematic files by hand using f18 it works.

**Comment by naromero77** [comment]
Also including @eugeneswalker in case he is interested

**Comment by naromero77** [comment]
I was out of the office yesterday and missed the excitement. I need to rebuild f18 and make sure that is working first, then will try to build mpich master.

**Comment by hzhou** [comment]
Why are we tracking two issues of the same effort simultaneously? Closing this issue and reference #4417. @naromero77 @coti , please follow the discussion there.
