### ISSUE TITLE
bug: memory leaks in json library

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#4428]
version: mpich-master from within a few days ago (v3.4a2-503-g4156831a)

description: valgrind reports 700k of lost memory in json routines

expected behavior:  clean up all resources so that when I run valgrind I find only my errors

output:

here's the valgrind log.  I noticed this as part of a "mochi service" so please ignore the items about 'mochi' or 'bv'.

[bv-server.11564.vg.txt](https://github.com/pmodels/mpich/files/4428323/bv-server.11564.vg.txt)

**Comment by pavanbalaji** [comment]
@roblatham00 Are you passing any special flags valgrind?  I'm not able to reproduce any memory leaks:

```
% ./install/bin/mpiexec -n 4 valgrind -q --leak-check=full ./examples/cpi
Process 0 of 4 is on frosty
Process 1 of 4 is on frosty
Process 2 of 4 is on frosty
Process 3 of 4 is on frosty
pi is approximately 3.1415926544231239, Error is 0.0000000008333307
wall clock time = 0.000230
```

**Comment by pavanbalaji** [comment]
Or, is this a failure case of some sort, where we didn't clean up resources when something failed?

**Comment by raffenet** [comment]
Dup of #4396.
