### ISSUE TITLE
bug/romio: potential division by zero in ADIOI_LUSTRE_Get_striping_info

### ISSUE THREAD

**Issue by dqwu** [pmodels/mpich#4449]
This SIGFPE was first reproduced on LLNL's quartz Cluster (lustre file system) with intel compiler and mvapich2/2.3 (based on mpich 3.2.1). It can also be reproduced with mpich 3.2.1 on NERSC's Cori and ALCF's Theta (both use lustre file system).

There is a simple PnetCDF test program to reproduce this issue, see https://gist.github.com/dqwu/5d68b869e1c424a1a6d34c748055fec2

It turns out that the following code inside ADIOI_LUSTRE_Get_striping_info does not check whether stripe_count is 0 or not before division:
```
...
stripe_count = fd->hints->striping_factor;
...
if (nprocs_for_coll >= stripe_count)
    ...
    avail_cb_nodes = stripe_count * MPL_MIN(nprocs_for_coll / stripe_count, CO);
...
```
For the PnetCDF test program built with mpich 3.2.1 and run on a lustre file system with 2 processes, one process gets stripe_count 1 while the other gets 0.

That test program can only reproduce the floating point exception with mpich 3.2.1 or earlier versions. For mpich 3.3, @wkliao has confirmed that the following commit guarantees that both processes get stripe_count 1 (the file striping hints are sync-ed):
https://github.com/pmodels/mpich/commit/a33abfab501908b2fc02565819b653937f1637b1

Since this unprotected division still exists in latest ROMIO lustre driver code (src/mpi/romio/adio/ad_lustre/ad_lustre_aggregate.c), I suggest adding an if statement or ADIOI_Assert for it.

A similar issue (from the same source file) was reported in 2015:
https://lists.mpich.org/pipermail/discuss/2015-November/000918.html

That issue has been fixed by @roblatham00 in the following commit:
https://github.com/pmodels/mpich/commit/538f8abb47d47dd3bb39e648e771ac705b2bf274

**Comment by roblatham00** [comment]
This was fixed in release 3.2.2
