### ISSUE TITLE
Undefined symbol errors building on Mac OS X 10.15.4 with Intel Compilers

### ISSUE THREAD

**Issue by paulfons** [pmodels/mpich#4452]
I am trying to build mpich to run some first-principles fortran code on mac running 10.15.4. I have installed the (current) intel compilers icc and ifort version 19.1.1.216 20200306.  As there is no mpi library available for the mac os from intel, I decided to compile mpich to take advantage of the mkl cluster support for mpich that comes with the intel compiler, namely libmkl_blacs_mpich. I ran configure with the line

./configure -prefix=/opt/mpich FC=ifort CC=icc CXX=icpc

which ran to completion with no errors.  I then attempted to build mpich using make without success due to undefined symbols:

ranlib: file: lib/.libs/libpmpi.a(mpl_dbg.o) has no symbols
  GEN      lib/libmpi.la
  CXXLD    lib/libmpicxx.la
  CCLD     src/env/mpichversion
  CCLD     src/env/mpivars
  GEN      lib/libmpifort.la
Undefined symbols for architecture x86_64:
  "__ZTHMPIR_Per_thread", referenced from:
      import-atom in libpmpi.dylib
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/env/mpichversion] Error 1
make[2]: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "__ZTHMPIR_Per_thread", referenced from:
      import-atom in libpmpi.dylib
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/env/mpivars] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Any suggestions as to how to avoid this problem.

**Comment by hzhou** [comment]
Which version of mpich were you building?

**Comment by paulfons** [comment]
openmpi-4.0.3


Paul Fons
paulfons@keio.jp

Keio University, Faculty of Science and Technology, Department of Electronics and Information Engineering

〒223-8522 3-14-1 Hiyoshi, Kohoku-ku, Yokohama, Kanagawa 223-8522, Japan
Keio University Faculty of Science and Technology Yagami Campus.

〒223-8522　横浜市港北区日吉3-14-1 慶應義塾大学理工学部電子工学科

**Comment by hzhou** [comment]
> openmpi-4.0.3

That is OpenMPI -- https://github.com/open-mpi/ompi?

**Comment by hzhou** [comment]
> > openmpi-4.0.3
> 
> That is OpenMPI -- https://github.com/open-mpi/ompi?

The original description does appear to come from mpich. @paulfons Please double check which mpich version were you building?

**Comment by paulfons** [comment]
I apologize for copying the openmpi version (I have been using both).  The version of mopish is mpich-3.3.2 .


Paul


Paul Fons
paulfons@keio.jp

Keio University, Faculty of Science and Technology, Department of Electronics and Information Engineering

〒223-8522 3-14-1 Hiyoshi, Kohoku-ku, Yokohama, Kanagawa 223-8522, Japan
Keio University Faculty of Science and Technology Yagami Campus.

〒223-8522　横浜市港北区日吉3-14-1 慶應義塾大学理工学部電子工学科

**Comment by hzhou** [comment]
Could you try the latest master?

**Comment by paulfons** [comment]
Sure thing.  I will give it a try.


Paul Fons
paulfons@keio.jp

Keio University, Faculty of Science and Technology, Department of Electronics and Information Engineering

〒223-8522 3-14-1 Hiyoshi, Kohoku-ku, Yokohama, Kanagawa 223-8522, Japan
Keio University Faculty of Science and Technology Yagami Campus.

〒223-8522　横浜市港北区日吉3-14-1 慶應義塾大学理工学部電子工学科

**Comment by bknaepen** [comment]
The latest master compiles on Mac OS X 10.15.4 with the latest intel compilers.
