### ISSUE TITLE
Cannot build mpich 3.1.4 with clang 8

### ISSUE THREAD

**Issue by haampie** [pmodels/mpich#4453]
I'm trying to build mpich 3.1.4 using clang 8, but it fails with:

```
src/mpi/pt2pt/greq_start.c:239:62: error: alias definition is part of a cycle
        MPIX_Grequest_class *greq_class) __attribute__((weak,alias("MPIX_Grequest_class_create")));
                                                             ^
1 error generated.
make[2]: *** [src/mpi/pt2pt/lib_libmpi_la-greq_start.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

It seems this is the commit that introduced this change between 3.1.3 and 3.1.4: https://github.com/pmodels/mpich/commit/82c14ecd3ae8aa9b66db6ede46ec79fb138ec851

Building mpich 3.1.3 with clang 8 works fine.

To reproduce:

```
$ cat Dockerfile
FROM ubuntu:18.04

WORKDIR /root

# Install basic tools
RUN apt-get update -qq && apt-get install -qq -y --no-install-recommends \
    software-properties-common \
    clang-8 make \
    git tar wget curl gpg-agent && \
    rm -rf /var/lib/apt/lists/*

ENV CC=clang-8
ENV CXX=clang++-8

ARG MPICH_VERSION=3.1.4
ARG MPICH_PATH=/usr/local/mpich

RUN wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz && \
    tar -xzf mpich-${MPICH_VERSION}.tar.gz && \
    cd mpich-${MPICH_VERSION} && \
    ./configure \
      --disable-fortran \
      --prefix=$MPICH_PATH && \
    make install -j$(nproc) && \
    rm -rf /root/mpich-${MPICH_VERSION}.tar.gz /root/mpich-${MPICH_VERSION}
$ docker build .
```

**Comment by hzhou** [comment]
Hi @haampie, may I ask why are you particularly interested in building ver 3.1.4 with clang 8?

**Comment by haampie** [comment]
On the cluster I'm working with there is a vendor-specific version of libmpi.so installed which is ABI compatible with mpich 3.1.x, so I tried locally to build and link against mpich 3.1.4.

**Comment by hzhou** [comment]
The latest mpich is 100% ABI compatible to ver 3.1.4, according to this site: https://abi-laboratory.pro/index.php?view=timeline&l=mpich

**Comment by haampie** [comment]
Thanks. I was building 3.1.4 because then I conveniently know at compile-time I'm not using any new or breaking features.

**Comment by hzhou** [comment]
@haampie Is this issue still pending for fix?

**Comment by haampie** [comment]
If you're not supporting 3.1.x anymore, then I'm fine closing this. Otherwise the issue probably remains. I've just started using a newer release of mpich afterwards.

**Comment by hzhou** [comment]
@haampie Any fix will go to newer release anyway, and they are ABI compatible to 3.1.4. It seems the newer release has been working for you? Otherwise, let us know. Closing this issue now.
