### ISSUE TITLE
jenkins: Move ofi testing to tcp provider

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4480]
The sockets provider is deprecated in favor of the new "tcp" provider in libfabric. We should change our testing to use it and/or the verbs provider which share the same RxM utilities.

**Comment by wesbland** [comment]
We've been investigating this (in the context of `verbs;ofi_rxm`. There are currently still some known shortcomings of the RXM provider, but we're working on this with the OFI developers. Hopefully we'll have something we could share soon.

**Comment by wesbland** [comment]
cc: @atulkulk

**Comment by hzhou** [comment]
status ref: https://github.com/pmodels/mpich/pull/4932#issuecomment-843153113

**Comment by hzhou** [comment]
We are now default to test `psm3`.
