### ISSUE TITLE
bug/jenkins: rma/accpscw1

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4483]
```
not ok  - ./rma/accpscw1 4
  ---
  Directory: ./rma
  File: accpscw1
  Num-procs: 4
  Timeout: 180
  Date: "Thu Apr 30 20:16:49 2020"
  ...
## Test output (expected 'No Errors'):
## expected 65536 at a1de90, but found 1087233792
## Data received with type nesting levels: 0
## base: MPI_INT
##  does not match data sent with type nesting levels: 3
## 0: blkindx [numblks 1, blklen 131072, displs (0)]
## 1: resized [lb -400, extent 4]
## 2: resized [lb 0, extent 40]
## base: MPI_INT
## 
##  Found 1 errors
```

**Comment by hzhou** [comment]
This one currently only triggers on our Solaris node. However, I believe it is a datatype bug not unique to solaris. The reason it doesn't show up on other tests is probably due to random number generator that somehow we failed to generate this bug case.

Nemesis sends data in 256KB segments. When the first level datatype block exceed this size and the next two sub-datatype is of resized type with different extent, this bug shows up.

The reason is we do `MPIR_Dataloop_dup` for resized datatype, but failed to reset the dataloop's extent.

**Comment by pavanbalaji** [comment]
@hzhou  It might be useful to create a simple non-DTPools based test for this, so it's easier to debug on other platforms.

**Comment by hzhou** [comment]
Alternatively, we should have a DTP interface to create custom datatypes, which will also make reproducing bugs much easier.

**Comment by pavanbalaji** [comment]
> Alternatively, we should have a DTP interface to create custom datatypes, which will also make reproducing bugs much easier.

It's hard to do that with the way DTP works.

**Comment by hzhou** [comment]
> > Alternatively, we should have a DTP interface to create custom datatypes, which will also make reproducing bugs much easier.
> 
> It's hard to do that with the way DTP works.

I am thinking we could just create a separate function to do that. It is probably simpler than trying to reuse the exisiting code since the existing code is mostly dealing with random stuff.

**Comment by hzhou** [comment]
I believe this bug has been fixed. At least the nightly solaris tests have been clean.
