### ISSUE TITLE
Linking issue with yaksa

### ISSUE THREAD

**Issue by bknaepen** [pmodels/mpich#4496]
I have compiled the latest (5726ff7) master branch on a Mac running MacOS 10.15.4 using the latest versions of the intel compiler. If I then try to compile a standard helloworld-mpi.c program, the linking phase fails. To succeed I have to explicitly mention add the yaksa library. Is this the intended behaviour?

Here are the details:

```
bknaepen@MacProBK1 test-mpi % mpicc helloworld-mpi.c 
Undefined symbols for architecture x86_64:
  "_yaksa_finalize", referenced from:
      _MPI_Finalize in libmpi.a(lib_libmpi_la-finalize.o)
      _PMPI_Finalize in libpmpi.a(lib_libpmpi_la-finalize.o)
  "_yaksa_init", referenced from:
      _PMPI_Init_thread in libpmpi.a(lib_libpmpi_la-initthread.o)
      _MPIR_Init_thread in libpmpi.a(lib_libpmpi_la-initthread.o)
ld: symbol(s) not found for architecture x86_64
bknaepen@MacProBK1 test-mpi % mpicc -lyaksa helloworld-mpi.c
bknaepen@MacProBK1 test-mpi % 
```

**Comment by pavanbalaji** [comment]
@bknaepen   Can you give some more detail on your configure options?  I don't see this error on our mac machines.  Also, my `libpmpi.dylib` correctly has a dependency on the yaksa library.

```
% otool -L install/lib/libpmpi.dylib 
install/lib/libpmpi.dylib:
	/Users/autotest/balaji/mpich/build/install/lib/libpmpi.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/Users/autotest/balaji/mpich/build/install/lib/libyaksa.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

**Comment by bknaepen** [comment]
I build mpich using:

source /opt/intel/bin/compilervars.sh intel64
export CC=icc
export FC=ifort
export F77=ifort
export CXX=icpc
./autogen.sh
./configure  --enable-fortran --enable-shared=no --with-device=ch3 --prefix=/opt/mpich3/intel-19.1.1.216/
make -j 12

**Comment by hzhou** [comment]
>  Also, my `libpmpi.dylib` correctly has a dependency on the yaksa library.

We are not embedding `yaksa` by default?

**Comment by pavanbalaji** [comment]
> > Also, my `libpmpi.dylib` correctly has a dependency on the yaksa library.
> 
> We are not embedding `yaksa` by default?

Hmm.  We do.  I wonder why it's showing up as a dependency then.  Let me investigate this.

**Comment by bknaepen** [comment]
Commit ccd708e solves this issue on my side. Thanks to all...
