### ISSUE TITLE
ch4: global mutexes need better organization

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4542]
Currently we define several global mutexes as part of the mutex array in `MPIDI_global` in `ch4_types.h`. Some of these mutexes are from old code that now is removed, such as `MPIDIU_THREAD_PROGRESS_MUTEX`, some of them are stale usage, such as `MPIDIU_THREAD_UTIL_MUTEX` are used for `pobj` thread granularity but the `pobj` hasn't been maintained and will be removed at some point. Some of the mutex really belong to upper layer, such as `MPIDIU_THREAD_SCHED_LIST_MUTEX` and `MPIDIU_THREAD_TSP_QUEUE_MUTEX`.

When per-component locks (such as these) are defined globally, they tend to fall out-of sync to the actual usage of the components. We need move these mutex into the component code. Each component can have a `init/finalize` stub that are called at either `MPIR_Init_thread` or `ch4_init` or `ofi_init`, and each component can maintain its locks independently.

**Comment by wesbland** [comment]
cc: @sagarth

**Comment by hzhou** [comment]
Lowered to very low priority.
