### ISSUE TITLE
GPU fallback: incorrect release of host staging buffer at request completion

### ISSUE THREAD

**Issue by gcongiu** [pmodels/mpich#4545]
The existing GPU fallback code for OFI (as well as the GPU AM fallback) relies on `MPIDIU_request_complete` to release the host staging buffer used to store GPU data. This is only called by `recv_event` in `ofi_events.c` and not, for example, by `recv_huge_event`. So in some cases the received data is never moved to the destination buffer in GPU memory and the host buffer never released.

It is not clear at this time where the release of the host buffer should happen. `MPID_Request_complete` might be an option but it is not well documented and seems to be taking care of AM resource release. `MPIDIU_request_complete` appears to be used inconsistently across the code.

**Comment by gcongiu** [comment]
@shawnccx @hzhou

**Comment by shawnccx** [comment]
`recv_huge_event` uses `recv_event` when 0 bytes left. See: https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ofi/ofi_events.c#L285

**Comment by hzhou** [comment]
Looks like `MPIDIU_request_complete` is a lightweight version of `MPID_Request_complete` that when it is certain there isn't any resource freeing checks. I think having this "light" version really confuses the code. For example, at one point we are certain that `ofi` direct path never allocates any dynamic resources that needs freeing, but at any point of development, we may start to add them.

**Comment by gcongiu** [comment]
Isn't `MPID_Request_complete` only for active messages and shmmod?

**Comment by hzhou** [comment]
> Isn't `MPID_Request_complete` only for active messages and shmmod?

There is nothing in the name to suggest so. In fact, its usage is all over the place

**Comment by gcongiu** [comment]
> `recv_huge_event` uses `recv_event` when 0 bytes left. See: https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ofi/ofi_events.c#L285

Right, but still we need this to work also for UCX. UCX does not have a dedicated event handling as OFI. So when staging data in UCX_AM we still need to manage the buffer appropriately at request completion

**Comment by gcongiu** [comment]
> > Isn't `MPID_Request_complete` only for active messages and shmmod?
> 
> There is nothing in the name to suggest so. In fact, its usage is all over the place
> 
> EDIT: I guess in `ch4`, maybe we do make that differentiation.

Right, I was looking at CH4.

**Comment by gcongiu** [comment]
I think your idea of using only `MPID_Request_complete` is the best option.

**Comment by hzhou** [comment]
After #4524, `MPID_Request_complete` is only used inside device layer, so maybe we should consider rename it to `MPIDI_Request_complete` , and we can have another version called `MPIDIG_am_request_complete`, that will make its usage/purpose clear.

**Comment by hzhou** [comment]
I still don't understand why `ofi` gpu fallback don't simply fallback to `ch4` layer, similar to the way it fallback to the AM path?

**Comment by shawnccx** [comment]
> I still don't understand why `ofi` gpu fallback don't simply fallback to `ch4` layer, similar to the way it fallback to the AM path?

In that case it is making things very pessimistic. The only missing part is GPU-aware, but moving to `AM` also gives up hardware tag matching in `ofi`, which makes more complicated.

**Comment by hzhou** [comment]
> it is making things very *pessimistic*

Hehe, I think I am more of optimistic. I want the best option -- direct native GPU support. When that is not available, I don't think it matters. There is the overhead of GPU memory transfer, will the "hardware tag matching" really matter with that backdrop?

I was thinking that just have a GPU am fallback protocol, you can use the same active message handling infra structure which is already there. I think it is much less complicated. In my picture, you only need add one source file: `src/mpid/ch4/generic/gpu/gpu_fallback.c` and one header file to declare the init/finalize and `MPIDIG_gpu_send`. For gpu receive, you just implement a `MPIDIG_gpu_copy_segment` with the same semantics as in `mpidig_am_msg.h`.

**Comment by shawnccx** [comment]
You are bringing up this topic again, requiring more people to be involved.

**Comment by hzhou** [comment]
Right. 😄

**Comment by gcongiu** [comment]
> > it is making things very _pessimistic_
> 
> Hehe, I think I am more of optimistic. I want the best option -- direct native GPU support. When that is not available, I don't think it matters. There is the overhead of GPU memory transfer, will the "hardware tag matching" really matter with that backdrop?
> 
> I was thinking just to have a GPU am fallback protocol, you can use the same active message handling infra structure which is already there. I think it is much less complicated. In my picture, you only need add one source file: `src/mpid/ch4/generic/gpu/gpu_fallback.c` and one header file to declare the init/finalize and `MPIDIG_gpu_send`. For gpu receive, you just implement a `MPIDIG_gpu_copy_segment` with the same semantics as in `mpidig_am_msg.h`.

I think yours is just a matter of preference. It will not change in any way how the fallback happens just where it happens. I think we decided to avoid falling back to the generic layer as we were going down the same direct netmod path anyways but adding one function call in the path (the one for `gpu_fallback.c`. The AM fallback is a separate path and is dealt with in this PR: https://github.com/pmodels/mpich/pull/4464.

**Comment by gcongiu** [comment]
> > `recv_huge_event` uses `recv_event` when 0 bytes left. See: https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ofi/ofi_events.c#L285
> 
> Right, but still we need this to work also for UCX. UCX does not have a dedicated event handling as OFI. So when staging data in UCX_AM we still need to manage the buffer appropriately at request completion

Actually, UCX also calls `MPIDIU_request_complete` so there should not be any problem. For the AM path I just need to add request handling in `MPID_Request_complete`. But the all request completion is a little confusion currently.

**Comment by hzhou** [comment]
I guess the current GPU fallback is a simple `cudaMemcpy` to a stage buffer? I was in the mindset that the functionality may grow, for example, chunks pipe-lining, or GPU direct, which will involve additional protocols. Having two (and more) separate paths will making extension difficult and ugly. Even now, you need take care of the releasing of stage buffer in two places with no obvious clues for a new developer.

And I am fundamentally bothered by why do we make two decision points? Just let ch4 make one single final decision. If ch4 needs more information on netmod capability, let netmod provide query function for it.

**Comment by gcongiu** [comment]
Right, at the moment we actually do packing of the GPU buffer into the host buffer directly using typerep. Concerning the why, we internally had a similar discussion for AM fallback. I think keeping fallback at the netmod level is best for several reasons; just to mention a few:
- there is no reason to fallback to the generic layer only to do packing. We always do packing at the lowest level; For high density datatypes, for example, we don't need to fallback as the netmod might use IOV to transfer data directly. Accounting for these cases to decide whether to fallback or not would just duplicate checks;
- pipelining will be implemented in the netmod, regardless, for host buffers as well. With the new typerep yaksa backend gpu buffers are no different from host buffers, as long as we only use typerep pack/unpack (even for contiguous datatypes) or pass the buffer directly, if the network layer allows it;
- generally, we fallback every time the network layer does not support some functionality, e.g., atomics. In those cases we fall back AM and supply the requested functionality in software. In the case of GPU, from the point of view of the network layer, the fallback path changes nothing, so we can just do staging directly in the netmod without falling back at all.

**Comment by gcongiu** [comment]
This issue should be resolved now.

**Comment by raffenet** [comment]
Fixed in https://github.com/pmodels/mpich/pull/4464.
