### ISSUE TITLE
hydra: unable to connect on RHEL6 using slurm

### ISSUE THREAD

**Issue by bjpalmer** [pmodels/mpich#4599]
I've encountered a problem when upgrading from MPICH-3.3.1, which works fine, to MPICH-3.3.2. I'm also having similar problems running MPICH-3.4a2.

I'm trying to use MPICH-3.3.2 on our old Infiniband cluster running the RHEL6 operating system and the slurm scheduler. Applications are consistently hanging in MPI_Init when I try and run on more than one node, sometimes with the error

```
[proxy:0:1@node168.local] HYDU_sock_connect (utils/sock/sock.c:145): unable to connect from "node168.local" to "node100.local" (Connection refused)
[proxy:0:1@node168.local] main (pm/pmiserv/pmip.c:183): unable to connect to server node100.local at port 54762 (check for firewalls!)
```

Running with multiple processors on one node seems to be okay. I've checked with the sys admins and they say there are no firewalls between nodes. As I've mentioned, MPICH 3.3.1  works fine. I've been configuring MPICH with the line

```
./configure --prefix=/people/d3g293/mpich/mpich-3.3.2/install --with-device=ch4:ofi:sockets --with-libfabric=embedded --enable-threads=multiple --with-slurm CC=gcc CXX=g++
```

I've also tried

```
./configure --prefix=/people/d3g293/mpich/mpich-3.3.2/install --enable-threads=multiple --with-slurm CC=gcc CXX=g++
```

and gotten the same result. I've been launching codes using mpiexec and mpirun. Launching with srun does not seem to work and results in each processor running with an MPI_COMM_WORLD of 1 process.

**Comment by hzhou** [comment]
Hi Bruce, thanks for filing the issue. Let's first establish what was working -- could you rebuild `MPICH-3.3.1` and verify it is working for you? The tarball link for `3.3.1` is http://www.mpich.org/static/downloads/3.3.1/mpich-3.3.1.tar.gz.

**Comment by bjpalmer** [comment]
I was just using MPICH-3.3.1 this morning. It seems to be working fine.

Bruce

**Comment by hzhou** [comment]
> I was just using MPICH-3.3.1 this morning. It seems to be working fine.

Did you build it from source? Could you list the configure line and how you were launching jobs?

**Comment by bjpalmer** [comment]
I’m building from source. The configure line is


./configure --prefix=/people/d3g293/mpich/mpich-3.3.1/install --with-device=ch4:ofi:sockets --with-li

bfabric=embedded --enable-threads=multiple --with-slurm CC=gcc CXX=g++

and my environment is


[d3g293@constance03 mpich-3.3.1]$ module list

Currently Loaded Modulefiles:

  1) gcc/5.2.0             3) cmake/3.8.2           5) mkl/15.0.1

  2) python/2.7.8          4) git/2.11.0(default)

I’m launching processes using mpirun.

Bruce

**Comment by pavanbalaji** [comment]
@bjpalmer   Why are you passing `--with-slurm` if you are using `mpirun`?

**Comment by bjpalmer** [comment]
I don’t know anything about schedulers so I’m blindly going with what has worked in the past. Our cluster uses slurm for job launching. I’          ve tried using srun to launch jobs, but it just doesn’t work on our machine. As far as I can tell, if you launch on N processes, you get N independent launches and each launch is running on a MPI_COMM_WORLD of size 1.

There is a moderately long email thread on mpich-discuss that goes over this. I think at some point I tried configuring without slurm but I could try it again and see if it makes a difference.

Bruce

**Comment by pavanbalaji** [comment]
@bjpalmer  You might not need it, but the error seems to be orthogonal to slurm usage.

Based on the error message, I have two guesses: (1) firewalls or (2) the `/etc/hosts` file on `node168.local` is not correctly setup to recognize `node100.local`.  Since you have already checked for firewalls, let's go down the `/etc/hosts` path a little bit.  The question is why is the proxy on `node168.local` trying to connect to `node100.local`, instead of `node100`?  Can you try running the program with the `-verbose` option to `mpiexec` (or `mpirun`, they are the same thing), and post the output here?

**Comment by hzhou** [comment]
I think I got a clearer a picture now. Let's focus on this:

> ` unable to connect from "node168.local" to "node100.local"`

Is `node00.local` a valid hostname? For example, if you try to `ssh node100.local` from another compute node, will it succeed?

I suspect that `.local` part is added by the OS which makes it an invalid host name. What is the OS by the way?

**Comment by bjpalmer** [comment]
The OS is RHEL 6. I tried launching a test job using 3.3.2 and it hangs. I then checked standard out and saw the error message about being unable to connect. I then ssh’d to the two compute nodes using the names in the error message and was able to log on with no problem. The output is below.

Bruce


[d3g293@constance03 testing]$ squeue | grep d3g293

          13405559     short bruce.jo   d3g293  R       3:54      2 node[008-009]

[d3g293@constance03 testing]$ more test.out

[proxy:0:1@node009.local] HYDU_sock_connect (utils/sock/sock.c:145): unable to connect from "node009.

local" to "node008.local" (Connection refused)

[proxy:0:1@node009.local] main (pm/pmiserv/pmip.c:183): unable to connect to server node008.local at

port 39565 (check for firewalls!)

srun: error: node009: task 1: Exited with exit code 5

[d3g293@constance03 testing]$ ssh node008.local

Last login: Fri May 29 10:16:56 2020 from constance01.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node008 ~]$ exit

logout

Connection to node008.local closed.

[d3g293@constance03 testing]$ ssh node009.local

Last login: Fri May 29 10:16:34 2020 from constance01.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node009 ~]$ exit

logout

Connection to node009.local closed.

**Comment by hzhou** [comment]
> [d3g293@constance03 testing]$ ssh node008.local
> Last login: Fri May 29 10:16:56 2020 from constance01.local
>

You are connecting from `constance03.local` to `node008.local`? Is `constance03` an alias of `node#`? Otherwise, if possible, could you try ssh from one compute node `nodexxx.local` to another `nodexxx.local`?

**Comment by pavanbalaji** [comment]
My suspicion is that this is an MPICH fault with how we detect hostnames: that's what is likely causing `.local` to appear.  Hence my request for the output of the `-verbose` option.  It'll show what hostname `mpiexec` is passing down to the proxies.

**Comment by bjpalmer** [comment]
Hi,

I submitted a two node job to the queue with the --verbose option. The results are attached. I also tried logging into the nodes running the hung job. The results are below, but it appears that you can ssh into the nodes from both the login node and from each other without any problems.

Bruce


[d3g293@constance03 testing]$ squeue | grep d3g293

          13455281     short bruce.jo   d3g293  R       4:00      2 node[015-016]

[d3g293@constance03 testing]$ ssh node015.local

Last login: Tue Jun  2 08:18:51 2020 from constance-e.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node015 ~]$ ssh node016.local

Last login: Tue Jun  2 08:19:04 2020 from node015.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node016 ~]$ logout

Connection to node016.local closed.

[d3g293@node015 ~]$ logout

Connection to node015.local closed.

[d3g293@constance03 testing]$ ssh node016.local

Last login: Tue Jun  2 08:30:28 2020 from node015.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node016 ~]$ ssh node015.local

Last login: Tue Jun  2 08:30:04 2020 from constance03.local

Rocks Compute Node

Rocks 6.1.1 (Sand Boa)

Profile built 10:31 18-May-2017



Kickstarted 10:42 18-May-2017

[d3g293@node015 ~]$ logout

Connection to node015.local closed.

[d3g293@node016 ~]$ logout

Connection to node016.local closed.

**Comment by pavanbalaji** [comment]
@bjpalmer  You'll need to login to GitHub and upload the file, rather than email it.  I don't see the attachment.

**Comment by bjpalmer** [comment]
Okay, hopefully this shows up.

[test.txt](https://github.com/pmodels/mpich/files/4718870/test.txt)

**Comment by pavanbalaji** [comment]
As suspected, mpiexec is not able to detect that it is running on one of the compute nodes.  So it's querying for the local host again and getting `node015.local` instead.  That address does not seem to appear on `node016`'s `/etc/hosts` or name server resolution, so the connection is failing.

This patch seems to be the culprit: https://github.com/pmodels/mpich/commit/46da9453d505340db65c9f267c2cbafe405f010a

Can you revert this patch and try?

**Comment by bjpalmer** [comment]
I checked out 619164f (the parent of 46da945) and copied the mpl_host.c file from this branch to my 3.3.2 build. I’m still getting a hang. I will try the 619164f and 46da945 branches and see if either of them work.

**Comment by pavanbalaji** [comment]
You can also try using the `mpiexec` from mpich-3.3.1 to run the job (even if the application is compiled with mpich-3.3.2).

**Comment by bjpalmer** [comment]
I reverted the source tree and tried the 46da945 image and the code still hangs. Both 3.3.2 and 3.4a2 work if a I use the mpirun from 3.3.1.

Bruce

**Comment by hzhou** [comment]
@bjpalmer This ticket has become stale, Are you still having the issue and interested in resolving it? From the discussion, since you have verified that you are able to ssh using `node016.local`, it rules out the hostname being a issue. So it narrows down to the suspicion that there is firewall blocking the port (43918 in your log). However, I admit it is curious that 3.3.1 were working for you. If you could provide us a log (with `mpirun -v`) with a working MPICH 3.3.1, it may provide us further clue on what may be the issue.

Anyway, since we can't make progress without interactive debugging, if the issue is no longer of interest, we need to close this issue.

**Comment by hzhou** [comment]
Closing the issue due to lack of response. Feel free to reopen if similar issues are encountered.
