### ISSUE TITLE
Bug with MPI_Ibcast/MPI_Wait since 2020-02-14 on mpich/master

### ISSUE THREAD

**Issue by ericch1** [pmodels/mpich#4635]
Hi,

first, sorry for the delay.  We noticed a failure with mpich/master since 2020-02-14.

Our nightly tests showed errors with MPI_Ibcast/MPI_Wait.

On 2020-02-13, always on mpich/master, everything was fine with SHA 44013c5f60 .

On 2020-02-14, our nightly tests tested cf1f4046798a and it was faulty.

Fortunately, the bug is very simple to reproduce: I happens only if the "root" of MPI_Ibcast is not 0, and it is visible only if someone check the return code of MPI_Wait (hum hum, that means there are no validation of this in MPICH nightly tests? )
 
Here is the simple reproducer attached, compiled and ran like this:
<pre>
mpicxx -o bug bug_ibcast_2020_02_14.cc
mpiexec -n 3 ./bug
</pre>

gives:

<pre>
Fatal error in PMPI_Wait: Other MPI error, error stack:
PMPI_Wait(199).................: MPI_Wait(request=0x7ffe00f508cc, status=0x7ffe00f508d0) failed
MPIR_Wait(99)..................: 
MPIDU_Sched_progress_state(958): Invalid communicator
Message from process 0 : Hello, world
Fatal error in PMPI_Wait: Other MPI error, error stack:
PMPI_Wait(199).................: MPI_Wait(request=0x7ffcae68070c, status=0x7ffcae680710) failed
MPIR_Wait(99)..................: 
MPIDU_Sched_progress_state(958): Invalid communicator
</pre>

[bug_ibcast_2020_02_14.zip](https://github.com/pmodels/mpich/files/4766872/bug_ibcast_2020_02_14.zip)

Thanks,

Eric

**Comment by hzhou** [comment]
@ericch1 Thanks for the bug report! I have located the bug. Patch will follow soon. The bug in in `src/mpi/coll/ibcast/ibcast_intra_smp.c`. There is a check of recved length but we somehow checked on both on send-side and recv-side. The send-side, of course, is garbage.  As far as I can tell, the bug existed for years. But somehow it only triggers by some unrelated commits. 

We'll make sure we cover this test in our test suite.

**Comment by ericch1** [comment]
Ok thanks! That was fast! :)

**Comment by ericch1** [comment]
Tests are 100% good this morning.  Thanks! :)
