### ISSUE TITLE
MPICH does not allow using MPI_DATATYPE_NULL in isend/irecv

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#4659]
MPI standard allows MPI_DATAYPE_NULL to be used in communication. However, when I was trying to run a test for this use case, the test failed immediately complaining "Datatype for argument datatype is a null datatype".

Here is a simple code to produce the problem.

```
/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 */

#include "mpi.h"

int main(int argc, char **argv)
{
    int err = 0;
    int recv_tag = 0;
    int world_rank;
    MPI_Request req;
    MPI_Status status;
    char buf = 0;

    MPI_Init(&argc, &argv);

    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    if (world_rank == 0) {
        MPI_Isend(&buf, 0, MPI_DATATYPE_NULL, 1, 1, MPI_COMM_WORLD, &req);
        MPI_Wait(&req, &status);
    } else {
        MPI_Irecv(&buf, 0, MPI_DATATYPE_NULL, 0, MPI_ANY_TAG, MPI_COMM_WORLD, &req);
        MPI_Wait(&req, &status);
        recv_tag = status.MPI_TAG;
        if (recv_tag != 1) {
            err = 1;
        }
    }

    MPI_Finalize();
    return err;
}
```

**Comment by hzhou** [comment]
@yfguo Could you cite the reference to standard?

**Comment by pavanbalaji** [comment]
> @yfguo Could you cite the reference to standard?

Yanfei's test above is correct.  This does look like a bug in MPICH.  The MPI standard explicitly allows `count` to be `0`.  It doesn't directly say anything about the datatype and buffer, and it stands to reason that those parameters would be ignored when `count` is `0`.

But I'm a little confused by thus bug.  This is a common usage pattern that several applications (including GFMC at Argonne) use.  And, of course, MPICH has been working fine for all those applications for many years.  Did something change recently?  For example, is this failing only with `ch4`?

**Comment by hzhou** [comment]
I see. It is not exactly that `MPI_DATATYPE_NULL` is allowed, but it should be *ignored* when count is `0`. I'll push a PR to fix this.

**Comment by pavanbalaji** [comment]
> I see. It is not exactly that `MPI_DATATYPE_NULL` is allowed, but it should be _ignored_ when count is `0`. I'll push a PR to fix this.

Correct.  The test can be further improved by setting `buf` to `NULL` too, because that should be ignored too.

**Comment by hzhou** [comment]
@yfguo Could you contribute your test to test suite? You can push it onto PR #4661.

**Comment by yfguo** [comment]
Will do

**Comment by hzhou** [comment]
All send versions (e.g. `MPI_Rsend`) and all recv versions suffer the same issue. @yfguo You test may need cover all send/recv varieties.

**Comment by hzhou** [comment]
I just verified that this has been fixed by the new python C binding generations.
