### ISSUE TITLE
can't build mpich 3.2.1 with pmi2

### ISSUE THREAD

**Issue by liwenhui-soul** [pmodels/mpich#4669]
run script like this
`./configure --with-pic --enable-static --enable-g=debug --with-pmi=pmi2 --enable-shared --disable-fortran --disable-mpi-fortran --enable-mpi-thread-mutliple`
and recieve the error:
`configure: error: The PM chosen (hydra) requires the PMI implementation simple but pmi2 was selected as the PMI implementation.`

**Comment by raffenet** [comment]
Are you able to use a newer release? The 3.2.x series is not actively maintained at this time. This configuration should work with MPICH 3.3.2.

**Comment by liwenhui-soul** [comment]
ok I'll try

**Comment by liwenhui-soul** [comment]
> Are you able to use a newer release? The 3.2.x series is not actively maintained at this time. This configuration should work with MPICH 3.3.2.

I try to build MPICH 3.3.2 in Mac os, but got this error:

```
####################################
## Checking user environment
####################################

Verifying the location of autogen.sh... done
Checking if autotools are in the same location... no
	autoconf is in /opt/dependency/package
	automake is in /opt/dependency/package
	libtool  is in /usr/local
===> WARNING: Autotools are in different locations. In rare occasion,
===> WARNING: resulting configure or makefile may fail in some unexpected ways.
Checking if autoreconf accepts -I /usr/local/share/aclocal... yes
Checking for autoconf version... >= 2.67
Checking for automake version... >= 1.15
Checking for libtool version... >= 2.4.4
Checking for UNIX find... done
Checking if xargs rm -rf works... yes

###########################################################
## Checking submodules
###########################################################

===> ERROR:   Submodule src/hwloc is not checked out
```

how can I fix it?

**Comment by hzhou** [comment]
@liwenhui-soul You need to checkout the submodules:
```
git submodule init
git submodule update
```

**Comment by hzhou** [comment]
@liwenhui-soul Has this issue been resolved?

**Comment by oushu1fengsihan1** [comment]
> run script like this
> `./configure --with-pic --enable-static --enable-g=debug --with-pmi=pmi2 --enable-shared --disable-fortran --disable-mpi-fortran --enable-mpi-thread-mutliple`
> and recieve the error:
> `configure: error: The PM chosen (hydra) requires the PMI implementation simple but pmi2 was selected as the PMI implementation.`

I got the same error with 3.3.2 release. Should I update MPICH to the latest commit of 3.3.2?

**Comment by hzhou** [comment]
Could you try with `--with-pmi=pmi2/simple`?

**Comment by oushu1fengsihan1** [comment]
> Could you try with `--with-pmi=pmi2/simple`?

Thanks. It works.
