### ISSUE TITLE
"Host key verification failed." error when running on an mpi cluster

### ISSUE THREAD

**Issue by Gunavaran** [pmodels/mpich#4712]
I have been trying to create an mpi cluster by connecting two laptops. I configured everything according to https://medium.com/mpi-cluster-setup/mpi-clusters-within-a-lan-77168e0191b1. I am able to ssh to other nodes without password. However when I run `mpiexec -n 2 -hosts manager,worker ./main` I get the following error. 
[proxy:0:1@gunavaran-HP-Pavilion-Notebook] HYDU_sock_connect (utils/sock/sock.c:113): unable to get host address for gunavaran-HP-ENVY-15-Notebook-PC
[proxy:0:1@gunavaran-HP-Pavilion-Notebook] main (pm/pmiserv/pmip.c:181): unable to connect to server gunavaran-HP-ENVY-15-Notebook-PC at port 41849 (check for firewalls!)
Host key verification failed.

**Comment by hzhou** [comment]
Could you try setting your laptops' hostname to `manager` and `worker` respectively?

**Comment by wesbland** [comment]
I'd recommend using the original version of that webpage: https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/

The one you're using seems to have been directly (and badly taken from that website).

On that page, it gives you some advice for this:

```
$ cat /etc/hosts

127.0.0.1       localhost
172.50.88.34    worker
```

You will need to change the IP address to whatever is correct for you and you can change the hostname to whatever you like.

**Comment by Gunavaran** [comment]
> I'd recommend using the original version of that webpage: https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/
> 
> The one you're using seems to have been directly (and badly) taken from the original website.
> 
> On that page, it gives you some advice for this:
> 
> ```
> $ cat /etc/hosts
> 
> 127.0.0.1       localhost
> 172.50.88.34    worker
> ```
> 
> You will need to change the IP address to whatever is correct for you and you can change the hostname to whatever you like.

@wesbland Sorry for the late reply. I followed the original version as you suggested and facing the same problem again

**Comment by Gunavaran** [comment]
> I'd recommend using the original version of that webpage: https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/
> 
> The one you're using seems to have been directly (and badly) taken from the original website.
> 
> On that page, it gives you some advice for this:
> 
> ```
> $ cat /etc/hosts
> 
> 127.0.0.1       localhost
> 172.50.88.34    worker
> ```
> 
> You will need to change the IP address to whatever is correct for you and you can change the hostname to whatever you like.

@hzhou I tried changing the hostname. Now that problem is resolved. Thank you so much.
