### ISSUE TITLE
How to query if CUDA awareness is actually turned on or not at runtime?

### ISSUE THREAD

**Issue by leofang** [pmodels/mpich#4716]
Hello, I work with the mpi4py developer @dalcinl on supporting CUDA awareness, and we would like to request a feature to detect the CUDA support at runtime. This query needs to know 
1. Is the library compiled with CUDA support?
2. Is CUDA support enabled "right now" (for some definition of "right now", likely after `MPI_Init()`)?

It seems MPICH already has preliminary CUDA support based on UCX, which I would really like to find some time to test! We understand the possible complicated interaction between an MPI library and UCX, and we have raised the same request to UCX (https://github.com/openucx/ucx/issues/5471) and Open MPI (https://github.com/open-mpi/ompi/issues/7963), and on the Open MPI side a PR for this support is being discussed (https://github.com/open-mpi/ompi/pull/7970), so you can refer to those issues/PR for more context. It would be great if MPICH is able to provide the same information. Perhaps the community could be engaged as a whole to come up with a *de facto* standard?

Thank you.

**Comment by leofang** [comment]
cc: @chingking from MVAPICH2

**Comment by pavanbalaji** [comment]
@leofang While I understand the intent of your suggestion, I'd urge the community to come up with a model that is broader than just CUDA.  For example, Intel and AMD GPUs, or other memory subsystems (byte-addressable NVRAM, etc.).  `MPIX_Query_cuda_support` from its name is specific to CUDA.

Generally speaking, any memory that is CPU accessible for load/store access is assumed to be supported by all MPI libraries.  For memories that are not CPU accessible for load/store access, perhaps the query model should be based on the virtual address range, rather than simply querying for "CUDA".  An example instance where simply querying for CUDA would fall apart is if I try to move data from constant memory instead of device global memory, even though that's still technically CUDA.

**Comment by leofang** [comment]
Hi @pavanbalaji Thanks for your reply. Sorry I know MPICH very little, so perhaps I'm being naive and please do correct me if I'm wrong 🙂 

> For example, Intel and AMD GPUs, or other memory subsystems (byte-addressable NVRAM, etc.). `MPIX_Query_cuda_support` from its name is specific to CUDA.

Is any of these currently being explicitly supported by MPICH? My impression is we do not yet have a production-quality support of "ROCm awareness", "Intel awareness", etc, do we? However, CUDA awareness is already the status quo in other MPI libraries like Open MPI, Spectrum MPI, MVAPICH2, etc. 

I think on the one hand your suggestion makes sense that we need to have a somewhat unified query for every possible offloading pathways to avoid the nuisance, but on the other hand
1. being able to query CUDA is the most urgent thing at the moment, and the discussion is very likely too ambitious to be resolved in a reasonable period
2. it would be hard to agree upon a unified approach, as not every programming model supports the same way for context initialization, registration, etc, and the interplay between this runtime query and `MPI_Init` would be complex
3. what you're suggesting should really be part of the next-generation MPI standard, and we simply can't wait until it's out

> perhaps the query model should be based on the virtual address range, rather than simply querying for "CUDA". 

Again, it really depends on the device's programming model. Not every offloading device supports the same unified virtual memory model as in CUDA. 

I can imagine an even more complex use case, say I run 2 MPI process with one on NVIDIA GPU and the other on ROCm GPU, both on the same node for silliness. What you're suggesting would also need to address how MPI can be employed in such a scenario, wouldn't it? But I have no idea how to make this work...Perhaps someone already did?!

> An example instance where simply querying for CUDA would fall apart is if I try to move data from constant memory instead of device global memory, even though that's still technically CUDA.

I don't understand this part. Could you elaborate please?

**Comment by pavanbalaji** [comment]
I think this is essentially a decision between a simple solution that we know has very limited scope vs. a more generic solution for multiple devices that would take longer to define/implement.  Given that Open MPI and MVAPICH already support the `MPIX_Query_cuda_support` function, I think we can add that to MPICH too.  It's obviously super hacky, but adding it for now might give users a path forward till we figure out the right solution.
