### ISSUE TITLE
test/mpi/configure is using mpicc to detect GPU libs

### ISSUE THREAD

**Issue by shawnccx** [pmodels/mpich#4717]
GPU libs are detected in configure of `test/mpi`.
For config.log, `mpicc` in install path is used to test and verify CUDA availability.
However, `mpicc` is not ready at that time, which causes GPU libs detection failure.

For example:
```
configure:30264: checking for cudaStreamSynchronize in -lcudart
configure:30289: /tmp/jenkins.tmp.N9WNInOP/_inst/bin/mpicc -o conftest    conftest.c -lcudart   >&5
./configure: line 1901: /tmp/jenkins.tmp.N9WNInOP/_inst/bin/mpicc: No such file or directory
configure:30289: $? = 127
```

Currently, I think users have to do `test/mpi/configure` with GPU lib path one more time, after `make install`, in order to detect GPU libs and create GPU tests.

**Comment by raffenet** [comment]
Is this addressed by this PR? https://github.com/pmodels/mpich/pull/4652

**Comment by shawnccx** [comment]
I have cherry-picked that PR for our downstream repo.
Let me rerun main branch on the cluster and verify again.

**Comment by shawnccx** [comment]
@hzhou 
You mentioned PR #4652 is fixing standalone build of test suite, that is, configure after make install.

This issue I posted here is for building src and test suite together case.

**Comment by shawnccx** [comment]
My local build of main branch had same issue, because `mpicc` is used to check at `configure:30239: checking for cudaStreamSynchronize in -lcudart`.

Let me re-clarify this issue.

If mpich test suite is a stand-alone build, this is not a issue. Because users have to configure mpich test suite after `make install`, `mpicc` is ready by then.

This issue rises when users configure mpich src code and test suite together. In that case, test/mpi/configure runs before compiling mpich src code, and it detects `mpicc` unavailable. Users need to do a more configure for test/mpi to setup up configuration for tests correctly.

The intention of creating this issue, is that, I'm wondering if test/mpi/configure can be taken out from mpich/configure dependency.

**Comment by shawnccx** [comment]
The problem is that user has to run test/mpi/configure explicitly again, to enable gpu tests, even if --with-cuda is given to configure option for mpi src.

**Comment by shawnccx** [comment]
I just talked with @hzhou , will post future update.
