### ISSUE TITLE
config: Unable to use --enable-fast=O3,ndebug

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4773]
Reported by @wgropp to discuss@mpich.org.

> —enable-fast in the top level configure accepts multiple, comma-separated items.  The configure in modules/yaksa/configure.ac expects (without checking) an O level only. This causes the configure step to fail with an unrelated error (yaksa thinks that it can’t fine pthreads).

**Comment by hzhou** [comment]
We could fix this in MPICH, which is messy as we need decide what option is safe and should be passed down. I would prefer to simply strip away all options (except for `MPL`), and only pass down a few hand picked options.

Alternatively, we could file an issue at yaksa and fix it in yaksa.

**Comment by hzhou** [comment]
Related issue #4497
