### ISSUE TITLE
Requesting a maintainer for the spack mpich package.

### ISSUE THREAD

**Issue by rblake-llnl** [pmodels/mpich#4785]
I'm a developer over on the [spack](https://github.com/spack/spack) project, which is a package manager for building software like MPI on HPC systems. Spack is used on many US national laboratory supercomputers. 

We have a package for [mpich](https://github.com/spack/spack/pull/18330) that needs a maintainer. We need someone to answer questions and make sure we're feeding sane configure options to the mpich build system.

Would anyone here be willing to volunteer themselves as a maintainer for the spack mpich package? 

Thanks!

**Comment by yfguo** [comment]
@rblake-llnl I can help with that.

**Comment by rblake-llnl** [comment]
Thank you so much @yiguo !
