### ISSUE TITLE
Support for NVIDIA HPC Compilers (NVHPC)

### ISSUE THREAD

**Issue by carsten-clauss** [pmodels/mpich#4787]
This is just for documentation: NVIDIA has recently renamed the acquired PGI compilers (pgcc -> nvc, pgc++ -> nvc++, pgf90/pgfortran -> nvfortran, but PGI aliases are still in place). [https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-user-guide/index.html](https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-user-guide/index.html)
However, MPICH's configure does not yet support these new compiler names, as the Autotools do not yet support them either -- but this will most likely change: [https://www.mail-archive.com/libtool-patches@gnu.org/msg07391.html](https://www.mail-archive.com/libtool-patches@gnu.org/msg07391.html)

**Comment by yfguo** [comment]
Thanks for submitting. I will take a look at this. We could start by adding that libtool patch so we don't need to wait for upstream.

**Comment by yfguo** [comment]
I have a preliminary branch that adds the libtool patch. Status:

- [ ] build with embedded OFI
- [ ] build with embedded UCX
- [ ] build with external OFI (not with CXX bindings, link failure)
- [ ] build with external UCX (presumably to work)

**Comment by raffenet** [comment]
Fixed in #4802.

**Comment by raffenet** [comment]
The applied patch broke existing PGI builds in Jenkins. This needs to be reverted and fixed.

**Comment by yfguo** [comment]
@carsten-clauss I have tried the patched posted in https://www.mail-archive.com/libtool-patches@gnu.org/msg07391.html. Unfortunately, it seems breaking the C++ building of MPICH. After some digging and trying, I come up with a version that works with MPICH build. You can find it at https://gist.github.com/yfguo/5b7dc6edbf79e358a18e0d3dd72f8b94 . Does this looks good from your side?
