### ISSUE TITLE
mpi_gather is not explicitly declared with implicit none (external) in Fortran

### ISSUE THREAD

**Issue by IgorGayday** [pmodels/mpich#4812]
Consider the following Fortran program:
```
program test_prg
  use mpi
  implicit none (type, external)
  integer :: source, dest, ierr
  call MPI_Init(ierr)
  call MPI_Gather(source, 1, MPI_INTEGER, dest, 1, MPI_INTEGER, 0, MPI_COMM_WORLD, ierr)
  call MPI_Finalize(ierr)
end program
```
An attempt to compile with `mpifort test_prg.F90 -ffree-line-length-0` (gfortran 10.2, mpich 3.3.2) results in the following error message:
```
6 |   call MPI_Gather(source, 1, MPI_INTEGER, dest, 1, MPI_INTEGER, 0, MPI_COMM_WORLD, ierr)
  |                                                                                        1
Error: Procedure ‘mpi_gather’ called at (1) is not explicitly declared; did you mean ‘mpi_barrier’?
```

Note, that there are no problems with `MPI_Init` and `MPI_Finalize`. The same program works with `mpi_f08`. So is `MPI_Gather` actually not explicitly declared in `mpi` or is this a `gfortran` bug?

**Comment by hzhou** [comment]
The difference between `MPI_Init` and `MPI_Gather` is the latter contains "choice" argument -- the `source`, `dest` can be any type. So internally `MPI_Gather` is exposed as an "interface" rather than a direct procedure name. I guess `gfortran` in this case doesn't regard the interface name as an imported name and only links them at later stage? So I am not sure whether this is a compiler bug or mpich bug, and am not sure what to do if it is the latter 😞 

As work around, you may either consider not to declare `implicit none (external)`, or add additional external declarations, e.g. `external :: MPI_Gather`.

**Comment by IgorGayday** [comment]
I tried the following test case and it worked:
```
module test_mod

  interface generic_sub
    module procedure :: test_int, test_real
  end interface

contains

  subroutine test_int(arg)
    integer :: arg
  end subroutine

  subroutine test_real(arg)
    real :: arg
  end subroutine
end module

program test_prg
  use test_mod
  implicit none (type, external)
  integer :: arg1
  real :: arg2
  call generic_sub(arg2)
end program
```
Is it different from how it `MPI_Gather` is declared internally?

**Comment by hzhou** [comment]
> Is it different from how `MPI_Gather` is declared internally?

We didn't use the the "generic " feature -- the code base was developed before "generic" is available. Strictly speaking, our usage is not standard conforming but Fortran compilers have been lenient so far :). 

If we use "generic" interface, how do we express that the "choice" argument could be *any* type?

**Comment by IgorGayday** [comment]
Well, that depends on what Fortran standards need to be supported. When you say _any_ type, do you mean arbitrary derived types as well? I'm not too familiar with all the requirements and caveats, but maybe something like `class(*)` could work? But it was introduced in Fortran 2003 (I think).

**Comment by hzhou** [comment]
> 
> 
> Well, that depends on what Fortran standards need to be supported. When you say _any_ type, do you mean arbitrary derived types as well? I'm not too familiar with all the requirements and caveats, but maybe something like `class(*)` could work? But it was introduced in Fortran 2003 (I think).

It is the C equivalent of `void *`, so yeah, anything goes.

**Comment by raffenet** [comment]
> The difference between `MPI_Init` and `MPI_Gather` is the latter contains "choice" argument -- the `source`, `dest` can be any type. So internally `MPI_Gather` is exposed as an "interface" rather than a direct procedure name. I guess `gfortran` in this case doesn't regard the interface name as an imported name and only links them at later stage? So I am not sure whether this is a compiler bug or mpich bug, and am not sure what to do if it is the latter 😞

MPICH does not declare function prototypes with choice buffers in `use mpi`. This is technically against what the MPI standard mandates, but it is the current state of the library.

**Comment by hzhou** [comment]
@raffenet I finally located this text from MPI specification: 
```
   INTERFACE 
     SUBROUTINE MPI_...(buf, ...)  
       !DEC$ ATTRIBUTES NO_ARG_CHECK :: buf  
       !$PRAGMA IGNORE_TKR buf  
       !DIR$ IGNORE_TKR buf 
       !IBM* IGNORE_TKR buf 
       REAL, DIMENSION(*) :: buf 
       ... ! declarations of the other arguments 
     END SUBROUTINE 
   END INTERFACE 
```
I guess what you were saying all along is: in `mpi_base.f90`, we currently are omitting "choice buffer" routines; and we could/should add them using above suggestions? Yeah, I think we can do that.

I guess the flip side is we may break compilers that doesn't support `IGNORE_TKR` extensions. Hopefully all our supported compilers have that extension. I guess in the worst case user always can fall back to `mpif.h` -- which they probably do anyway considering their use of old compilers.
