### ISSUE TITLE
Question about MPICH equivalent constant of MVAPICH constant 

### ISSUE THREAD

**Issue by Picolau** [pmodels/mpich#4827]
Good afternoon!

Although my issue is big, i just have a simple question. 

I am currently developing with mpich and was running some latency and bandwidth tests using one process per GPU in a big server with multiple nodes. I am currently using the OSU benchmark and some of the tests I did worked perfectly. The problem is that some others tests, which involve CUDA managed memory or memory allocated in the GPU (device) and not in the host, i got the following message:

```
Warning: OMB could not identify the local rank of the process.
         This can lead to multiple processes using the same GPU.
         Please use the get_local_rank script in the OMB repo for this.  
```

Then looking up in the documentation of the OSU Benchmark, i get this (about the get_local_rank):

```
Setting GPU affinity
--------------------
GPU affinity for processes is set before MPI_Init is called in the benchmarks.
The process rank on a node is normally used to do this and different MPI
launchers expose this information through different environment variables. The
benchmarks use an environment variable called LOCAL_RANK to get this
information.

Starting with OMB v5.4.4, the benchmarks automatically identify the process rank
on a node for MVAPICH2 when launched with mpirun_rsh. However, a script like
below can be used to export this environment variable when using OMB to work
with other MPI launchers and libraries.

    #!/bin/bash

    export LOCAL_RANK=$MV2_COMM_WORLD_LOCAL_RANK
    exec $*

A copy of this script is installed as get_local_rank alongside the benchmarks.
It can be used as follows:

    mpirun_rsh -np 2 -hostfile hostfile MV2_USE_CUDA=1 get_local_rank \ 
        ./osu_latency D D 
```

As you can see, the documentation is assuming I am using MVAPICH and not MPICH, i wonder now, what is the equivalent of MPICH of the MVAPICH constant MV2_COMM_WORLD_LOCAL_RANK. I just need to know that.

Very much thanks!

**Comment by raffenet** [comment]
Assuming you are building MPICH with Hydra, which is the default `mpiexec` included with MPICH, then you can use `PMI_RANK`.

**Comment by raffenet** [comment]
> Assuming you are building MPICH with Hydra, which is the default `mpiexec` included with MPICH, then you can use `PMI_RANK`.

Oh, sorry, I misread that you were actually looking for the node-local rank. In that case, you should look for `MPI_LOCALRANKID`.

**Comment by Picolau** [comment]
Ok, will try! Thank you very much.

**Comment by hzhou** [comment]
Closing. Reopen if necessary.
