### ISSUE TITLE
CUDA-aware MPICH 3.4b1 failed

### ISSUE THREAD

**Issue by huanghua1994** [pmodels/mpich#4832]
Hardware: Xeon Gold 6226, Mellanox ConnectX-5 ERD IB
Software: RHEL 7.6, ICC 19.0.5, CUDA 10.1, more information about IB driver see [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mv2-bug-report/sys-info.txt)

Test code: simple `MPI_Sendrecv` for GPU memory buffer, code is available [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/sendrecv.cu) 

Configuration:
--prefix=/storage/home/hhive1/hhuang368/scratch/mpich/3.4b1/intel/19.0.5/cuda/10.1 
--enable-g=all --enable-fast=none --enable-fortran=all --enable-cxx --enable-threads=multiple 
--enable-shared --enable-static --with-device={...}

with-device using CH3: single node 4 MPI processes running crashed, backtrace log [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch3-sendrecv-coredump-backtrace.txt)

with-device using CH4+UCX: single node 4 MPI processes running crashed, backtrace log [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch4ucx-sendrecv-crash.txt)

with-device using CH4+OFI: single node 1 MPI process `mpivars` crashed, backtrace log [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch4ofi-mpivars-coredump-backtrace.txt)

**Comment by raffenet** [comment]
Can you provide `src/mpl/config.log`?

**Comment by huanghua1994** [comment]
Using which device, or all three devices?

**Comment by raffenet** [comment]
Any of them will shed some light on the issue. For actual MPICH+CUDA usage at the moment, I would recommend ch4:ucx.

**Comment by huanghua1994** [comment]
ch4:ucx `src/mpl/config.log` uploaded [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch4ucx-src-mpl-config.log). It seems that `conftest.c` has some problems.

**Comment by raffenet** [comment]
Those errors in the log are normal. `configure` does lots of test compiles that might fail in order to set things up internally. CUDA looks correctly detected in `src/mpl`. Can you also provide `modules/yaksa/config.log`?

**Comment by huanghua1994** [comment]
For `modules/yaksa/config.log` please see [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch4ucx-modules-yaksa-config.log).
For `modules/libfabric/config.log` please see [here](https://github.com/huanghua1994/HPC_Playground/blob/master/CUDA/CUDA-aware_MPI_debug/mpich-bug-report/ch4ofi-modules-libfabric-config.log)

**Comment by raffenet** [comment]
It looks like yaksa failed to fully detect CUDA. It was unable to successfully test `nvcc`, so it disabled support. Can you try adding `--with-cuda=<path/to/install>` to your configuration line instead of setting flags?

**Comment by huanghua1994** [comment]
Adding `--with-cuda=<path/to/cuda/install>` works for yaksa. When I ran `./configure --help` in MPICH top directory, the output help message did not mention using `--with-cuda`, and later I saw the configuration successfully detected CUDA header files. I checked `modules/{yaksa, ucx, libfabric}/configure --help`, they all have the option `--with-cuda`. So I will suggest that also put this option in the top directory configuration help message. 

Unfortunately the compiled version is still not working. Running on a single node using only 1 MPI gives me the following error message:
```shell
$ mpirun -np 1 ./sendrecv.exe
mbind: Invalid argument
(repeat many times)
mbind: Invalid argument
arr_size = 1024
[atl1-1-01-018-31:647019:0:647019] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x2aab1c801ff0)
==== backtrace ====
 0 0x0000000000153d69 __memcpy_ssse3_back()  :0
 1 0x00000000000220be uct_self_ep_am_short()  ???:0
 2 0x0000000000029ab5 ucp_tag_send_nb()  ???:0
 3 0x00000000005af1b6 MPIDI_UCX_send()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/netmod/include/../ucx/ucx_send.h:74
 4 0x00000000005afc68 MPIDI_NM_mpi_isend()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/netmod/include/../ucx/ucx_send.h:224
 5 0x00000000005b10cd MPIDI_isend_unsafe()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_send.h:104
 6 0x00000000005b131d MPIDI_isend_safe()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_send.h:334
 7 0x00000000005b14d8 MPID_Isend()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_send.h:516
 8 0x00000000005b441a PMPI_Sendrecv()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/src/mpi/pt2pt/sendrecv.c:179
 9 0x0000000000402e1f main()  /storage/home/hhive1/hhuang368/scratch/HPC_Playground/CUDA/CUDA-aware_MPI_debug/sendrecv.cu:51
10 0x00000000000223d5 __libc_start_main()  ???:0
11 0x0000000000402a29 _start()  ???:0
===================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 647019 RUNNING AT atl1-1-01-018-31.pace.gatech.edu
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

Running on 2 nodes each node has 1 MPI process gives me the following error:
```shell
$ mpirun -np 2 --hostfile host.txt ./sendrecv.exe
/storage/home/hhive1/hhuang368/.bashrc: line 16: module: command not found
/storage/home/hhive1/hhuang368/.bashrc: line 18: module: command not found
/storage/home/hhive1/hhuang368/.bashrc: line 21: module: command not found
mbind: Invalid argument
(repeat many times)
mbind: Invalid argument
arr_size = 1024
[1602174655.409169] [atl1-1-01-018-33:145572:0]          ib_md.c:362  UCX  ERROR ibv_reg_mr(address=0x7fff4f001000, length=4096, access=0xf) failed: Bad address
[1602174655.409192] [atl1-1-01-018-33:145572:0]         ucp_mm.c:108  UCX  ERROR failed to register address 0x7fff4f001000 length 4096 on md[2]=ib/mlx5_0: Input/output error
[1602174655.409195] [atl1-1-01-018-33:145572:0]    ucp_request.c:263  UCX  ERROR failed to register user buffer datatype 0x8 address 0x7fff4f001000 len 4096: Input/output error
Abort(404347663) on node 1 (rank 1 in comm 0): Fatal error in PMPI_Sendrecv: Other MPI error, error stack:
PMPI_Sendrecv(243).....: MPI_Sendrecv(sbuf=0x7fff4f001000, scount=1024, MPI_INT, dest=0, stag=0, rbuf=0x7fff4f003000, rcount=1024, MPI_INT, src=0, rtag=0, MPI_COMM_WORLD, status=0x1) failed
MPID_Isend(518)........:
MPIDI_isend_unsafe(117):
MPIDI_UCX_send(85).....:  returned failed request in UCX netmod(ucx_send.h 85 MPIDI_UCX_send Input/output error)
```

Running in a single node using 4 MPI processes (there are 4 V100s on a single node) gives me the following error message:
```shell
]$ mpirun -np 4 ./sendrecv.exe
CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,139): all CUDA-capable devices are busy or unavailable
sendrecv.exe: src/frontend/types/yaksa_contig.c:64: yaksa_type_create_contig: Assertion `yaksi_global.is_initialized' failed.
CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,139): all CUDA-capable devices are busy or unavailable
sendrecv.exe: src/frontend/types/yaksa_contig.c:64: yaksa_type_create_contig: Assertion `yaksi_global.is_initialized' failed.
CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,139): all CUDA-capable devices are busy or unavailable
sendrecv.exe: src/frontend/types/yaksa_contig.c:64: yaksa_type_create_contig: Assertion `yaksi_global.is_initialized' failed.
^C[mpiexec@atl1-1-01-018-31.pace.gatech.edu] Sending Ctrl-C to processes as requested
[mpiexec@atl1-1-01-018-31.pace.gatech.edu] Press Ctrl-C again to force abort
```
The cluster I am using disabled NVIDIA MPS, but yaksa enumerates all devices on the host and set current device to each device to detect P2P access capability. Shall I make a bug report to yaksa?

**Comment by raffenet** [comment]
I believe a similar issue already exists here: https://github.com/pmodels/yaksa/issues/114. Your info would be helpful to confirm the problem.

**Comment by raffenet** [comment]
Are you linked against an external UCX library or the embedded one included with MPICH? I am wondering if an external library is being used that may not have CUDA-awareness builtin.

FWIW, I was able to build and test your code successfully on a GPU here at ANL.

**Comment by huanghua1994** [comment]
Previously I was using the embedded one in MPICH. 

I also tried compiling an external UCX 1.9.0 and use it to compile MPICH 3.4b1. UCX 1.9.0 configuration is as follow:
```shell
$ ucx_info -v
# UCT version=1.9.0 revision
# configured with: --prefix=/storage/home/hhive1/hhuang368/scratch/ucx/1.9.0/intel/19.0.5/cuda/10.1 --with-cuda=/usr/local/pace-apps/manual/packages/cuda/10.1 --enable-mt --with-mlx5-dv --disable-numa
```
This version of MPICH 3.4b1 can run the sendrecv.cu on 2 nodes / 1 MPI process per node. But it cannot run the put_and_acc.cu on 2 nodes / 1 MPI process per node. Error message as follow:
```shell
[atl1-1-01-018-29:202684:0:202684] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7fff4f000000)
==== backtrace (tid: 202684) ====
 0 0x000000000040da40 __intel_avx_rep_memcpy()  ???:0
 1 0x0000000000043e40 ucp_rma_sw_put_pack_cb()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma_sw.c:32
 2 0x000000000003ffe9 uct_rc_mlx5_ep_am_bcopy.h()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/uct/ib/rc/accel/rc_mlx5_ep.c:338
 3 0x0000000000043ef7 uct_ep_am_bcopy()  /storage/home/hhive1/hhuang368/scratch/ucx-1.9.0-src/src/uct/api/uct.h:2561
 4 0x0000000000043ef7 ucp_rma_sw_progress_put()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma_sw.c:45
 5 0x000000000004257d ucp_request_try_send()  /storage/home/hhive1/hhuang368/scratch/ucx-1.9.0-src/src/ucp/core/ucp_request.inl:223
 6 0x000000000004257d ucp_request_send()  /storage/home/hhive1/hhuang368/scratch/ucx-1.9.0-src/src/ucp/core/ucp_request.inl:258
 7 0x000000000004257d ucp_rma_send_request()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma.inl:39
 8 0x000000000004257d ucp_rma_nonblocking()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma_send.c:178
 9 0x000000000004257d ucp_put_nbx()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma_send.c:249
10 0x000000000004225d ucp_put_nbi()  /storage/hive/scratch/8/hhuang368/ucx-1.9.0-src/src/ucp/rma/rma_send.c:186
11 0x00000000006352ba MPIDI_UCX_contig_put()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/netmod/include/../ucx/ucx_rma.h:49
12 0x0000000000636930 MPIDI_UCX_do_put()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/netmod/include/../ucx/ucx_rma.h:226
13 0x0000000000636c7e MPIDI_NM_mpi_put()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/netmod/include/../ucx/ucx_rma.h:315
14 0x000000000063899f MPIDI_put_unsafe()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_rma.h:46
15 0x0000000000638be1 MPIDI_put_safe()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_rma.h:466
16 0x0000000000638e20 MPID_Put()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/./src/mpid/ch4/src/ch4_rma.h:794
17 0x000000000063a9bf PMPI_Put()  /storage/hive/scratch/8/hhuang368/mpich-3.4b1-src/src/mpi/rma/put.c:143
18 0x000000000040303c main()  /storage/home/hhive1/hhuang368/scratch/HPC_Playground/CUDA/CUDA-aware_MPI_debug/put_and_acc.cu:57
19 0x00000000000223d5 __libc_start_main()  ???:0
20 0x0000000000402c29 _start()  ???:0
=================================
```

**Comment by raffenet** [comment]
Well that's some progress 😄 .

For RMA, GPU buffers are not supported with native UCX. What you'll need to do is to force MPICH software emulation for RMA, which should work. To do this, add `--enable-ch4-am-only` to your configuration line.

Unfortunately, this option forces software emulation for **all** MPI features, including tagged send/recv with ch4:ucx. It would probably be a good idea for us to add an option to do this at a more fine-grained level, so you can still benefit from the native support that is available. A wiki page detailing all this information is also a good idea, which I will work on. Thanks for being patient and trying this stuff out!

**Comment by raffenet** [comment]
> For RMA, GPU buffers are not supported with native UCX. What you'll need to do is to force MPICH software emulation for RMA, which should work. To do this, add `--enable-ch4-am-only` to your configuration line.

I tried this test on my machine and still ran into a crash in the software path. I will look into it.

**Comment by huanghua1994** [comment]
> For RMA, GPU buffers are not supported with native UCX. What you'll need to do is to force MPICH software emulation for RMA, which should work. To do this, add --enable-ch4-am-only to your configuration line.
> 
> I tried this test on my machine and still ran into a crash in the software path. I will look into it.

I just tried it and got the same crash result. 

BTW, I also tried MPICH 3.3.2 stable release with UCX 1.9.0, GPUDirect send and recv also work well. The embedded UCX in 3.3.2 does not work with CUDA 10.1.

**Comment by raffenet** [comment]
@huanghua1994 I believe I located the problem. I posted a PR (https://github.com/pmodels/mpich/pull/4835) that should address it. If you inclined to build from git source, it would be great if you could confirm the fix. I intend to backport to the 3.4.x branch so it will be included in a future release candidate.

**Comment by raffenet** [comment]
I have drafted this wiki page to answer some common GPU support questions: https://github.com/pmodels/mpich/wiki/GPU-Support-Matrix-(3.4.x).

**Comment by huanghua1994** [comment]
Can I use `--with-device=ch4:ucx` and `--enable-ch4-am-only` at the same time?

**Comment by raffenet** [comment]
> Can I use `--with-device=ch4:ucx` and `--enable-ch4-am-only` at the same time?

Yes, but the caveat is that `--enable-ch4-am-only` will disable the "well supported" paths that `ch4:ucx` offers. It is clear that some more fine-grained control is needed to enable the best paths for all types of communication. We will work on putting those controls in place.

**Comment by hzhou** [comment]
This issue has served its purpose for discussion/explanation. Since it doesn't point to immediate action, I am closing it.
