### ISSUE TITLE
Singleton feature request

### ISSUE THREAD

**Issue by martinGHub** [pmodels/mpich#4853]
Hi all.
I would like to request the singleton functionality in MPICH (i.e. runs without _mpirun_). I have an interactive application which uses ncurses library and it doesn't work with _mpirun_. Currently I'm using OpenMPI which supports this feature but I would like to make it work with this implementation too. I have understood that it's not a prioritary feature now, so I add this issue like as a way for you to keep it present for the future.
Thanks.

**Comment by hzhou** [comment]
Reference PR #3440. We need port that in hydra.

**Comment by hzhou** [comment]
Reference #1074 has more background discussions.

**Comment by edric-e** [comment]
Hi, just wanted to say: I'd love to see this feature implemented, we would definitely take advantage of it immediately. (Right now, we have to work around this by manually wrapping our application in "mpiexec" - this is rather awkward).

**Comment by hzhou** [comment]
> Hi, just wanted to say: I'd love to see this feature implemented, we would definitely take advantage of it immediately. (Right now, we have to work around this by manually wrapping our application in "mpiexec" - this is rather awkward).

Acknowledged. I have some code to make this work -- #5162. We'll try to merge it next.
