### ISSUE TITLE
Error code ignored in "MPIR_Allreduce_intra_recursive_doubling"

### ISSUE THREAD

**Issue by aolia-0303** [pmodels/mpich#4865]
I noticed that:

1. In `MPIR_Allreduce_intra_recursive_doubling()`, the return code of `MPIC_Sendrecv` is ignored

https://github.com/pmodels/mpich/blob/main/src/mpi/coll/allreduce/allreduce_intra_recursive_doubling.c#L127

2. When performing `fi_msg` operations, only `-FI_EAGAIN` is checked.

For example, in `MPIDI_OFI_send_normal `, `fi_tsenddata` has been called in the following way (https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_send.h#L239)

```
        MPIDI_OFI_CALL_RETRY(fi_tsenddata(MPIDI_OFI_global.ctx[vni_src].tx,
                                            send_buf,
                                            data_sz,
                                            cq_data,
                                            MPIDI_OFI_av_to_phys(addr, vni_local, vni_remote),
                                            match_bits), vni_local, tinjectdata,
                             FALSE /* eagain */);
```

Note that `MPIDI_OFI_CALL_RETRY` only looks for `-FI_EAGAIN`

```
MPIDI_OFI_ERR(_ret!=-FI_EAGAIN,             \
                              mpi_errno,                    \
                              MPI_ERR_OTHER,                \
                              "**ofid_"#STR,                \
                              "**ofid_"#STR" %s %d %s %s",  \
                              __SHORT_FILE__,               \
                              __LINE__,                     \
                              __func__,                       \
                              fi_strerror(-_ret));          \
```

Given the above two facts, MPICH will only looks for `-FI_EAGAIN` ignore all other err codes when calling `MPIR_Allreduce_intra_recursive_doubling()`. Can someone explain why it is like this and fix this issue?

**Comment by raffenet** [comment]
We check for `-FI_EAGAIN` so the message can be retried until it succeeds, occasionally poking progress to free up resources. All other errors are treated as errors, and would either cause MPI to abort (default), or return the error to the user (MPI_ERRORS_RETURN). What behavior are you seeing that needs fixing?

**Comment by raffenet** [comment]
> I noticed that:
> 
> 1. In `MPIR_Allreduce_intra_recursive_doubling()`, the return code of `MPIC_Sendrecv` is ignored
> 
> https://github.com/pmodels/mpich/blob/main/src/mpi/coll/allreduce/allreduce_intra_recursive_doubling.c#L127
> 

This return code is not ignored. Could you clarify what you mean?

**Comment by raffenet** [comment]
@aolia-0303 do you have any response to the questions above?

**Comment by raffenet** [comment]
Closing due to lack of follow-up.
