### ISSUE TITLE
ch4: shm collective will run out of memory with too many comms

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4866]
We allocate a block a shared memory for each communicator when encountering `bcast` or `reduce` operations. When we have too many communicators doing such operation, we'll hit the threshold of total shared memory and encounter failures. Reference PR #4864. That PR fixes it by releasing the memory counter at the time of freeing the communicator. That fixes for some cases, but if an application is having too many concurrent communicators, or if running too many processes on a single node and several concurrent communicators, or if we later expand shm algorithm for more collective operations, we will run into the same issue again.

Therefore, Ideally we need a scalable solution.

One idea is to have an internal shmem allocation system and allocate and de-allocate a block for each collective operation. We incur the overhead of synchronization in this case.

Alternatively, we could simply use one global shmem block shared by all communicators and operations. Each time we check whether the block is available, if yes, then mark it (by its context id) and use it. Otherwise, simply fallback (use non-shm algorithms). Since typical applications don't run concurrent collectives (even with different communicators), the fallback cost may not be that significant. The overhead in this case is one atomic compare and swap for each process.

**Comment by raffenet** [comment]
> Alternatively, we could simply use one global shmem block shared by all communicators and operations. Each time we check whether the block is available, if yes, then mark it (by its context id) and use it.

Just want to say that context ids are not guaranteed to be unique, even on the same node. 2 disjoint groups of processes can have the same context id, so this scheme would need some additional id to avoid collisions.

**Comment by raffenet** [comment]
> When we have too many communicators doing such operation, we'll hit the threshold of total shared memory and encounter failures.

Does MPICH crash, or just fallback to regular pt2pt collectives? I was under the impression it was the latter, which is not an issue for users. SHM is a limited resource.

**Comment by hzhou** [comment]
> > When we have too many communicators doing such operation, we'll hit the threshold of total shared memory and encounter failures.
> 
> Does MPICH crash, or just fallback to regular pt2pt collectives? I was under the impression it was the latter, which is not an issue for users. SHM is a limited resource.

It falls back. But nevertheless it is undesirable, as it falls back when actually there are SHM resource available but just held up by non-active communicators.

**Comment by hzhou** [comment]
Since there is no interest fixing this issue, close for now.
