### ISSUE TITLE
mpi4: partitioned communication

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4879]
## Standard
link: https://github.com/mpi-forum/mpi-issues/issues/136
pdf: https://github.com/mpi-forum/mpi-issues/files/4913679/mpi40-report-ticket136-11jul20.pdf
## Action items
* 6 new APIs
* Basic implementations
  ** Simple adaptation from persistent request
  ** May do the actual communication when all partitions are ready.
  ** Basic tests
* Advanced implementations
  ** Send and track completion of individual partitions
  ** Multiple thread performance
  ** Optimize for GPU

## Pull requests

**Comment by minsii** [comment]
Will there be a timeline or deadline for each of the tasks?

**Comment by hzhou** [comment]
Let's put 1/31/2021 as the deadline for now.
