### ISSUE TITLE
mpi4: communicator info hints

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4882]
## Standard
link: https://github.com/mpi-forum/mpi-issues/issues/123

## Action Items
* Communicator info hints:
  ** `mpi_assert_no_any_source`
  ** `mpi_assert_no_any_tag`
  ** `mpi_assert_exact_length`
  ** `mpi_assert_allow_taking`
* Basic implementations
  ** accept hints without necessary behavior change
* Advanced implementations
  ** Optimize performance based on specific hints
  ** Evaluate correctness and performance

## Pull requests

**Comment by raffenet** [comment]
These hints are already registered in `main` https://github.com/pmodels/mpich/blob/main/src/mpi/comm/commutil.c#L158-L168. I will create a PR to move the tests for setting/getting them from `test/mpi/impls/mpich` to `test/mpi/comm` and verify they are 4.0 standard compliant.

**Comment by hzhou** [comment]
This is done.
