### ISSUE TITLE
mpi4: error functions need always be threadsafe

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4891]
https://github.com/mpi-forum/mpi-issues/issues/152

**Comment by raffenet** [comment]
In the current implementation, I do not believe any thread safety is needed. But there is a dependency on https://github.com/pmodels/mpich/issues/4885, which will add the ability to remove error objects and thus require protection from races with threads querying vs. removing. Does that sound right?

In the meantime, I can easily remove the `MPIR_ERRTEST_INITIALIZED_ORDIE();` checks.

**Comment by raffenet** [comment]
#4906 is complete for MPI-4.0 purposes. I am thinking more about the thread safety needs of these functions, and am not sure additional protection is needed.

For instance, if an application is removing a dynamic error code or class, then it is the application's responsibility to ensure it is not removed while it is still in use. I.e. if another thread might potentially query for more information, then it must not be removed, thus required protection above MPI. @hzhou what do you think?

**Comment by hzhou** [comment]
The particular issue "#152" only mentions the thread-safety rather than making those functions available before init, right? I believe it is another ticket mentions that. @raffenet  Could you find the link of that ticket and add to the description?

As for thread-safety, you are arguing for the practical reasons, which is beyond the scope of the standard. Per standard, we need ensure these functions to be thread-safe, period. The question then, is whether the current implementation is already thread-safe? I don't see there is function to remove error class or error code. Since the mentioned two functions are only accessing a static array with index derived from the error code, I think it is already thread-safe.

**Comment by raffenet** [comment]
> The particular issue "#152" only mentions the thread-safety rather than making those functions available before init, right? I believe it is another ticket mentions that. @raffenet Could you find the link of that ticket and add to the description?

https://github.com/mpi-forum/mpi-issues/issues/102 made them available before/after init.

> As for thread-safety, you are arguing for the practical reasons, which is beyond the scope of the standard. Per standard, we need ensure these functions to be thread-safe, period. The question then, is whether the current implementation is already thread-safe? I don't see there is function to remove error class or error code. Since the mentioned two functions are only accessing a static array with index derived from the error code, I think it is already thread-safe.

Yes, I agree they are already thread-safe. I think we are on the same page.
