### ISSUE TITLE
Question: MPICH support for apple silicon

### ISSUE THREAD

**Issue by JAF130195** [pmodels/mpich#4908]
Hello,

Hope all of you on the MPI dev team are doing well.

Apple has recently announced the arrival of their new ARM-based machines. I personally develop on mac and deploy to linux and I find it very useful to debug MPI programs for a small number of processes on my mac. 

So my question is what level of support will there be for these new machines? I am no expert on processor architecture but these chips do look significantly different from you would expect from a standard x86_64 architecture so I am curious what issues may arise from porting to these new macs.

Thanks for your time,

John.

**Comment by hzhou** [comment]
We support ARM in general. We have not tested on apple silicon in particular yet, but we currently expect it to work.

**Comment by JAF130195** [comment]
Ok, good to know! Thanks for getting back to me so quickly.
