### ISSUE TITLE
mpi4: check misc clarifications

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4924]
link:
* https://github.com/mpi-forum/mpi-issues/issues/263
* https://github.com/mpi-forum/mpi-issues/issues/262
* https://github.com/mpi-forum/mpi-issues/issues/259
* https://github.com/mpi-forum/mpi-issues/issues/257
* https://github.com/mpi-forum/mpi-issues/issues/252
* https://github.com/mpi-forum/mpi-issues/issues/182
* https://github.com/mpi-forum/mpi-issues/issues/119

**Comment by yfguo** [comment]
Checked the standard text and code, here are the results.

mpi-forum/mpi-issues#263 -- errata, no code change needed
mpi-forum/mpi-issues#262 -- clarification, no code change needed
mpi-forum/mpi-issues#259 -- clarification, no code change needed
mpi-forum/mpi-issues#257 -- errata, no code change needed
mpi-forum/mpi-issues#252 -- errata, no code change needed
mpi-forum/mpi-issues#182 -- errata, no code change needed
mpi-forum/mpi-issues#119 -- clarification, no code change needed
