### ISSUE TITLE
Broken check for errno after strtol

### ISSUE THREAD

**Issue by rdietric** [pmodels/mpich#4944]
The check of the `errno` value after `strtol` might lead to a wrong detected error:

https://github.com/pmodels/mpich/blob/934e9ebcf4de11ce03abc2c2d219f1d9a26eddbb/src/pm/hydra/pm/pmiserv/pmip_utils.c#L566

A previous library call could have set `errno`. Hence, `errno` should be set to zero `errno = 0;` before the call to `strtol`. The proposed check from https://linux.die.net/man/3/strtol:

```
errno = 0;
count = strtol(**argv, NULL, 10);
if ((errno == ERANGE && (count == LONG_MAX || count == LONG_MIN))
    || (errno != 0 && count == 0)) 
```

**Comment by hzhou** [comment]
Thanks for reporting issue. Just opened a PR #5107 to fix it. From what I understand, just setting `errno` to `0` and check the non-zero status is sufficient for detecting error since we don't care about the exact cause of the error anyway.

Sorry it took so long for us to address the issue.
