### ISSUE TITLE
Codespell report for "MPICH" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [pmodels/mpich#4982]
The FOSS server [fossies.org](https://fossies.org) - supporting also the "MPICH" project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "MPICH" release 3.4:

&nbsp;https://fossies.org/linux/misc/mpich/codespell.html

That version-independent URL should redirect always to the last report (if available), so currently to

&nbsp;https://fossies.org/linux/misc/mpich-3.4.tar.gz/codespell.html.

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Of particular interest may be unassigned errors marked by a "?" since they may be contained in the source code itself (here I especially noticed the typo "stae -> state" at line 712 of the file [src/mpid/ch3/include/mpidpre.h](http://www.schiller-fossies.org/linux/misc/mpich-3.4.tar.gz/mpich-3.4/src/mpid/ch3/include/mpidpre.h?M=712#l_712)). Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/misc/mpich/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/misc/mpich/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/misc/mpich/codespell_hist.html) (log).

Perhaps more meaningful may be a similar and continuously updated report for the MPICH GitHub "main" version which could be generated on request within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines.

Although the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

**Comment by hzhou** [comment]
This is nice!
