### ISSUE TITLE
config.guess in release tarball is old for json-c and ucx modules, even after running autogen.sh.

### ISSUE THREAD

**Issue by brianv0** [pmodels/mpich#4987]
Compiling mpich 3.4 in conda-forge recipe initially failed when cross-compiling for Apple arm64 in the json-c module. This seemed to me to be related to old versions of config.sub/config.guess in the release tarball in combination with autogen.sh not updating them (it seems like the force (timestamp on those files is 2014). autogen.sh seemed to also not update ucx module files as well.

I couldn't quickly determine why those files weren't being updated for those two modules. My fix was to patch all config.sub/config.guess files myself, but I would expect making sure autogen.sh is overwriting them with new files would be good.

**Comment by raffenet** [comment]
I believe those files are imported from the automake installation used to generate the tarball. We'll make sure to use a newer automake for the 3.4.2 release.

**Comment by hzhou** [comment]
How old is too old? We should investigate and potentially update the version check in autogen.sh.

A side note, since our scripts are not updated with autoconf 2.70 yet, we should check against 2.70 in autogen as well.

**Comment by raffenet** [comment]
This fell off my radar, but I'd like to resolve it before the 4.1 GA release. I'm tempted to just enforce the latest automake in `release.pl`. What do you think @hzhou?

**Comment by hzhou** [comment]
Yeah, sounds good, assuming the newer generated config.guess will work with older automake (as it should be).
