### ISSUE TITLE
build: configure failure for MPL with autoconf 2.70

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#5014]
The configure step fails with the following message when using autoconf 2.70. It was working fine with autoconf 2.69.

```
./configure: line 15041: syntax error near unexpected token `else'
./configure: line 15041: `else $as_nop'
configure: error: MPL configure failed
```

As Ken has pointed out in an early Slack message that `https://github.com/pmodels/mpich/blob/main/src/mpl/configure.ac#L429` seems to be the cause.

It seems autoconf is doing a major update (https://lwn.net/Articles/834682/). According to the release note (https://lwn.net/Articles/839395/), there are many changes from some macros being obsolete to requirement on syntax being more strict.

As prompted by `autoconf`, I tried to use `autoupdate` on the `configure.ac`. It fixes some of the problems, but has made significant changes to `configure.ac` which may or may not compatible with pre-2.70 autoconf. This need a bit more investigation and could be low priority for now since major distros would take some time to pick this new version up.

**Comment by raffenet** [comment]
The timer discovery macro is pretty messy (lots of unnecessary nesting). I think we should address it first, and worry about the warnings later.

**Comment by hzhou** [comment]
It will require quite some effort. I think split this ticket into smaller issues may help to make progress. For example, we should --
* remove or replace (obsolete macros)[https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html]
  This itself is quite daunting task, so further splitting down
  ** Identify a list of obsolete macros that we still uses
  ** replace `AC_TRY_LINK`
  ** ...

* Address autoconf 2.70 issues.

reference: (autoconf 2.70 release notes)[https://lwn.net/Articles/839395/]

**Comment by hzhou** [comment]
Just did a quick check. It appears #5206 has fixed the issue. I am able to use `autoconf` 2.70 and successfully build the current `main`, despite a lot of warnings on remaining obsolete macros.

**Comment by yfguo** [comment]
fix is confirmed.
