### ISSUE TITLE
OFI receive code assumes invalid WC behavior

### ISSUE THREAD

**Issue by RaymondMichael** [pmodels/mpich#5020]
The OFI receive code for huge receives incorrectly assumes that all OFI providers return the receive buffer address in the Work Completion object. MPIDI_OFI_get_huge_event() uses WC.buf as the receive buffer base address in the call to fi_read(). The man page for fi_cq(3) says though that the field is only valid when FI_MULTI_RECV was used. Storing the receive buffer address in WC.buf is convenient, and most providers do it, but it's not required and therefore can't be used.

There is a simple fix to this. In MPIDI_OFI_do_irecv(), store the recv_buf into MPIDI_OFI_request_util_iov(rreq)->iov_base before the fi_trecv() call. Use the address later for the fi_read(). Note that I have not looked at the MPIDI_OFI_recv_iov() case.

**Comment by hzhou** [comment]
Interesting. Do we know any provider that doesn't set buffer address in cq entry?

**Comment by RaymondMichael** [comment]
HPE Slingshot does not put the buffer address in the CQ WC
