### ISSUE TITLE
gpu: direct-netmod builds fail due to lack of MPL_gpu_init call

### ISSUE THREAD

**Issue by abrooks98** [pmodels/mpich#5048]
In #4640, the call to `MPL_gpu_init` was moved from `MPIR_Init_thread` to `MPIDI_GPU_mpi_init_hook`, resulting in `MPL_gpu_init` being called only if the GPU shmmod is enabled. As a result, GPU-enabled direct-netmod builds fail because `MPL_gpu_init` is never called.

In order to support GPUs in direct-netmod builds, `MPL_gpu_init` should either be moved to a generic location, or called in a direct-netmod path.

**Comment by hzhou** [comment]
@abrooks98 Could you describe which parts in netmod is failing because of this?

**Comment by abrooks98** [comment]
I believe only GPU-enabled tests are failing (i.e. anything from `testlist.gpu`s)

**Comment by hzhou** [comment]
> 
> 
> I believe only GPU-enabled tests are failing (i.e. anything from `testlist.gpu`s)

Aha, I see. Maybe this is the reason that all the gpu tests are failing -- https://jenkins-pmrs.cels.anl.gov/view/mpich-review/job/mpich-review-ch4-gpu/compiler=gnu,jenkins_configure=default,label=gpu,netmod=ofi/26/console

**Comment by hzhou** [comment]
I believe this issue is fixed by #5054
