### ISSUE TITLE
binding/c: Skipping validation changes _impl function declaration

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#5061]
In the MPI_T Events bindings, users are allowed to pass `NULL` to the `info` argument of `MPI_T_event_get_info` and `MPI_T_source_get_info`. I added `skip: validate-INFO` to remove a `NULL` check from the error-checking block. What resulted, in addition to the validation being removed, is the argument to `MPIR_T_[source|event]_get_info_impl` was incorrectly changed from `MPI_Info **info_ptr` -> `MPI_Info *info`.

**Comment by raffenet** [comment]
@hzhou is the idea that the argument should just be passed thru and the _impl function will do any validation/conversion instead of the binding layer?

**Comment by hzhou** [comment]
The binding script processes handle conversion and parameter validation in a synchronized fashion, so `skip: validate-INFO` will skip both the validation and handle conversion. Typically `skip` means `_impl` wants to handle the original param directly.

Anyway, currently the binding script doesn't expect an "output" handle parameter can be `NULL`. If this is just a one-off thing (only one or two functions does that), then I think it is simpler to pass `MPI_Info *info` directly to `_impl` and let `_impl` deal with `NULL` (skip info output) directly. If we'll have more functions do similar thing, we can add validation logic into the script and let binding script takes care of that.

**Comment by raffenet** [comment]
OK, I can work with that.
