### ISSUE TITLE
Locks in MPIDI_set_progress_vci()

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#5070]
## Problem

The current implementation of `get_vci_wrapper()` in `ch4_wait.h` returns `0` when a request is not "real". https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_wait.h#L20-L21
This request will not be checked in the `MPIR_Test/Wait_xxx()` functions, but at least it takes a global lock (`vci[0]`'s lock) in  `MPIDI_set_progress_vci(_n)()`.
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_wait.h#L70-L75
This becomes a global lock even if that request is originally associated with a different VCI.

This should be significant when a small message `MPI_Isend()` is followed by `MPI_Wait(all)` but they use different VCIs internally (at least for `MPI_ISend()`). Specifically, this matters the latency test that uses multiple VCIs although it depends on the window size.

If we follow TODO and can just skip when `vci = 0` by setting `vci_count = 0`, I will make a PR.

### More Fundamental Question

This is orthogonal to the problem above. Fundamentally, do we really need a VCI lock here to get `MPIDI_global.progress_counts[vci]`?
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_wait.h#L72-L74

For example, if `MPIDI_global.progress_counts[vci]` is updated after this small critical section by other threads that progress the same VCI, anyway `state->progress_counts[i]` is not the latest value.

1. If `state->progress_counts[i]` must be kept as an up-to-date value (=always the same as `MPIDI_global.progress_counts[vci]`).

    The current algorithm looks broken.

2. If `state->progress_counts[i]` is just a reference and anyway the `MPIR_Test/Wait()` functions will check this strictly later.

    Then I believe `relaxed_load` is fine since we just need an atomicity (=a value may not be an intermediate value: if the originally value is 0x2 and the new value is 0x1, it must be either 0x1 or 0x2, not 0x3).

**Comment by hzhou** [comment]
> The current implementation of `get_vci_wrapper()` in `ch4_wait.h` returns `0` when a request is not "real". https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_wait.h#L20-L21
> This request will not be checked in the `MPIR_Test/Wait_xxx()` functions

The quoted code is for *persistent* request. When persistent request doesn't have a real request associated, it isn't even started. Only the real request need progress at the device layer. None device native request are entirely handled above device, thus doesn't have a vci association, at least not in the sense of virtual network interface contention. All non-dvice request need to use the same lock or they will corrupt the MPIR-layer global data. Therefore, they are all using vci(0).

**Comment by hzhou** [comment]
> do we really need a VCI lock here to get `MPIDI_global.progress_counts[vci]`?
> https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_wait.h#L72-L74

If we don't enter vci lock, wouldn't there be a risk of getting garbage value if another thread is updating the count?

> If state->progress_counts[i] must be kept as an up-to-date value (=always the same as MPIDI_global.progress_counts[vci]).

`state->progress_counts[i]` is used to track when progress are made -- by comparing when `MPIDI_global.progress_counts[vci]` is advanced beyond `state->progress_counts[i]`. So they are not always the same.

**Comment by shintaro-iwasaki** [comment]
Thanks @hzhou!

> Therefore, they are all using vci(0).

This is quite counterintuitive to me since even `MPI_Send()` that uses a different communicator needs to refer to `vci[0]` although `MPI_Recv()`, for example, uses a VCI that is associated with that communicator. For example, `Waitall()` for `Isend()` seems taking `vci[0]`'s lock in `MPIDI_set_progress_vci_n()` while `Waitall()` for `Irecv()` takes another lock (e.g., `vci[3]`'s lock) in `MPIDI_set_progress_vci_n()`:
```c
while (1) {
  if (sender) {
    MPI_Isend(buf, 1, MPI_CHAR, target, 0, comm, &requests[0]); // Tiny message.
  } else {
    MPI_Irecv(buf, 1, MPI_CHAR, target, 0, comm, &requests[0]);
  }
  MPI_Waitall(1, requests, statuses);
  sender = !sender;
}
```
If this behavior is intended, it's fine.

---

> If we don't enter vci lock, wouldn't there be a risk of getting garbage value if another thread is updating the count?

Yes, but practically no. For example, if the current MPICH code should do the following, there would be a risk.
```c
        MPID_THREAD_CS_ENTER(VCI, MPIDI_VCI(vci).lock);
        MPIDI_global.progress_counts[vci] = 0xbad; // Somehow this thread assigns a random broken value, but who does such?
        do_something();
        MPIDI_global.progress_counts[vci] = (right value); // Then assign a correct value.
        MPID_THREAD_CS_EXIT(VCI, MPIDI_VCI(vci).lock);
```
If `MPIDI_global.progress_counts` becomes an atomic variable (we will use relaxed_load/store to access it), no one will newly write such code.

---

> `state->progress_counts[i]` is used to track when progress are made -- by comparing when `MPIDI_global.progress_counts[vci]` is advanced beyond `state->progress_counts[i]`. So they are not always the same.

I'd like to know how this count should be managed. For example, assume that there are two threads `Thr1` and `Thr2` both access `vci[1]` and make some progress in the following path at the same time.
```c
// Inside MPIDI_set_progress_vci_n()
MPID_THREAD_CS_ENTER(VCI, MPIDI_VCI(vci).lock);
state->progress_counts[i] = MPIDI_global.progress_counts[vci];
MPID_THREAD_CS_EXIT(VCI, MPIDI_VCI(vci).lock);
...
MPID_Progress_test(); // internally MPIDI_VCI(vci).lock will be taken.
```
If the original `MPIDI_global.progress_counts[1]` is 1 and `Thr1` executes `MPID_Progress_test()` earlier than `Thr2`, `Thr2`'s  `state->progress_counts[i]` can be either 1 (before `Thr1`'s `MPID_Progress_test()`) or 2 (after `Thr1`'s `MPID_Progress_test()`). More specifically, is it okay in the following cases?
1. `Thr2`'s `state->progress_counts[i]` is 1.
2. `Thr2` enters `MPID_Progress_test()` after `Thr1` executed `MPID_Progress_test()` and updated `MPIDI_global.progress_counts[vci]` to 2.

If it's fine, I think this lock is unnecessary to read `MPIDI_global.progress_counts[vci]`.

**Comment by hzhou** [comment]
> This is quite counterintuitive to me since even `MPI_Isend()` that uses a different communicator needs to refer to `vci[0]` although `MPI_Irecv()`, for example, uses a VCI that is associated with that communicator. For example, `Waitall()` for `Isend()` seems taking `vci[0]`'s lock in `MPIDI_set_progress_vci_n()` while `Waitall()` for `Irecv()` takes another lock (e.g., `vci[3]`'s lock) in `MPIDI_set_progress_vci_n()`:

`MPI_Isend` and `MPI_Irecv` will only use the vci determined by hashing (currently by sequence number in the communicator). They do not always refer to `vci[0]`

**Comment by shintaro-iwasaki** [comment]
Thanks. After the discussion with @hzhou, the first problem seems happening because currently `MPI_Waitall()` does not have a request completion check and unnecessarily enters progress engine even though all/most of the requests have been completed (e.g., when requests are lightweight ones). I will investigate this issue.

The second question is not solved. I don't think this lock is necessary. I'd be happy if anyone would have ideas about the necessity of this.

**Comment by hzhou** [comment]
> I'd like to know how this count should be managed. For example, assume that there are two threads `Thr1` and `Thr2` both access `vci[1]` and make some progress in the following path at the same time.
> 
> ```c
> // Inside MPIDI_set_progress_vci_n()
> MPID_THREAD_CS_ENTER(VCI, MPIDI_VCI(vci).lock);
> state->progress_counts[i] = MPIDI_global.progress_counts[vci];
> MPID_THREAD_CS_EXIT(VCI, MPIDI_VCI(vci).lock);
> ...
> MPID_Progress_test(); // internally MPIDI_VCI(vci).lock will be taken.
> ```

`MPID_Progress_test` always returns (which is different from `MPID_Progress_wait` which have the concern of sticking in progress forever due to missed `progress_count`. What should be concerned here is the counts are not recent enough and `MPID_Progress_test` may skip device progress altogether due to progress made immediately. I am just commenting on the two issues that are of concern regarding the progress counter, not necessarily mean they are relevant here.

Currently, the `progress_counts` are not atomic variables, so without lock, wouldn't you risk getting corrupted values?

The reason `progress_counts` are not atomic variables because they are queried during progress under per-vci lock anyway. This is not obvious in `MPID_Progress_test`, which is much less optimized. With `MPID_progress_wait`, it will spend inside progress loop for a while so the goal is to reduce the atomic operations inside the loop.

The progress counter design is probably outdated and may not be optimal.

**Comment by shintaro-iwasaki** [comment]
Thanks for your comment. I created a PR.

> With MPID_progress_wait, it will spend inside progress loop for a while so the goal is to reduce the atomic operations inside the loop.

Yes, that should be a major concern of using atomic variables. That PR uses `atomic_relaxed_load/store`, which is very lightweight (actually no difference from a normal read/write) on most CPUs. So yes we use `atomic`, but `relaxed` ones are okay in terms of performance.

> Currently, the progress_counts are not atomic variables, so without lock, wouldn't you risk getting corrupted values?

`relaxed` is still "atomic", so the value is updated atomically (I mean, we do not observe `0x00011111` if we write data `0x11111111` to a variable that has `0x0000000`: we should observe either of them). Since it is not `acquire-release`, it does not guarantee any thread-thread synchronization, though.
