### ISSUE TITLE
Open_port and Connect fails on ch4:ofi

### ISSUE THREAD

**Issue by cesarpomar** [pmodels/mpich#5093]
I try to connect two process launched by mpirun using functions Open_port/Accept and Connect. The code works with ch3 but when I use the same code with ch4 not work. I have tried with two processes on the same and different hosts. 

when I call the funcion connect the libfabric conn fails:
`Assertion failed in file src/mpid/ch4/netmod/ofi/ofi_spawn.c at line 581: conn != FI_ADDR_NOTAVAIL`

I try to compile the last version of libfabric 1.11.2 and using ubuntu precompiled package, but no changes.

**Comment by hzhou** [comment]
Could you dump the port_name string?

**Comment by cesarpomar** [comment]
yes, "tag#0$connentry#02009296C0A8010D0000000000000000$"

**Comment by hzhou** [comment]
> tag#0$connentry#02009296C0A8010D0000000000000000

Thanks. That string looks okay. It just says "192.168.1.13:38546", which is a normal IP:port address. Did you try using embedded libfabric? For example, `--with-libfabric=embedded`

**Comment by cesarpomar** [comment]
Thanks. I recompile with `--with-libfabric=embedded` and no changes. I tested in my computer, in a cluster and inside a clear ubuntu docker image.

I use the following script:

```
MPICH_VERSION=3.4.1
mkdir /tmp/mpi && \
	cd /tmp/mpi && \
	wget https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz && \
	tar -zxf mpich-${MPICH_VERSION}.tar.gz && \
	cd mpich-${MPICH_VERSION} && \
	./configure --with-device=ch4:ofi --with-libfabric=embedded --enable-g && \
	make -j && \
	make install && \
        rm -fR /tmp/mpi
```

**Comment by hzhou** [comment]
> Thanks. I recompile with `--with-libfabric=embedded` and no changes. I tested in my computer, in a cluster and inside a clear ubuntu docker image.

Thanks. I appreciate your patience. Do you have a simple test program that you can share? We have tests in our test suite and they are clean in our nightly tests. Maybe testing on the same test program can help narrow down the issue.

**Comment by cesarpomar** [comment]
Sorry, -with-libfabric=embedded it’s works, I forget recompile one of binaries.
Thanks for your support.

**Comment by hzhou** [comment]
If support for a specific pre-installed libfabric is required/desired, open separate issues as we will only support this on a case-by-case basis. Closing this issue.
