### ISSUE TITLE
Issue with MPI_Issend() and MPI_Testall()

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5147]
This is with `ch4:ofi`, either 3.4.1 or main branch.

Consider the trivial code below. The last assertion fails. If I replace the synchronous-mode `Issend()` with the standard-mode `Issend()`, the the assertion pass.

```python
from mpi4py import MPI
comm = MPI.COMM_SELF

requests = []
for _ in range(10):
    req = comm.Issend([b"@", 1, MPI.BYTE], 0, 1)
    requests.append(req)

for _ in range(10):
    buf = bytearray(1)
    comm.Recv(buf, 0, 1)

flag = MPI.Request.Testall(requests)
assert flag == True
```

PS: I left a comment to @hzhou in mpi4py/mpi4py#33 with a another example that used matched probes and receives, however that example fails with either `Issend()` or `Isend()`.

**Comment by hzhou** [comment]
@dalcinl `ch3` has a dedicated self-communication channel. In ch4, we haven't done that. There is no requirement from the standard that `Testall` needs to succeed on its first try even after the `recv` complete, right?

**Comment by dalcinl** [comment]
@hzhou LOL! Now you throw the standard in front of my face, too :rofl: !!! Yes, I believe your assessment is right. But I hope you agree such behavior is quite unintuitive, even more considering that the behavior changes by just replacing `Issend` by `Isend` (or is that just an accident?). The standard is large, it certainly has rough edges and corner cases, but its spirit has always been to align to common sense and adhere to the principle of least surprise.

Anyway, I understand from your words that changing this behavior in the ch4 implementation is probably not that easy. Given that the standard allows for it, you will keep things as they rather than performing major surgery to your code. If that is the case, please close this issue.

PS: I don't see this problem with `ch4:ucx`. I'm just being lucky?

**Comment by dalcinl** [comment]
> There is no requirement ... `Testall` needs to succeed on its first try

With the current implementation, would it succeed in the second try? I'm still a bit confused, you said `ch4`..  Are both `ucx` and `ofi` supposed to behave similarly?

**Comment by hzhou** [comment]
> But I hope you agree such behavior is quite unintuitive

It is a *side effect*, intuitive or not. The real question, is it of significance? Does the side effect allow better performance or simpler user code?

Semantically, send to self is no different from sending to peer. There may be optimizations with self-communication, but users can't depend on the "side effects" of optimization.

> even more considering that the behavior changes by just replacing Issend by Isend (or is that just an accident?).

The difference between `Issend` and `Isend` is, the former need to wait for acknowledgment from receiver before complete. Certainly, with self-communication, it is possible to "look ahead" for such acknowledgment, but it will be extra complexity and need be justified by its significance. With a different implementation design, sometimes we get these extra side effects for free, but that's not an argument that every implementation needs to have the same side effects.

>  I don't see this problem with ch4:ucx. I'm just being lucky?

Yes, I would say that's just "lucky". You may also get lucky with `ch4:ofi` as well depend on the libfabric providers or simply some unrelated progress tuning. But they are just side effects of no significance in my view.

In my opinion, the example you quoted is an incorrect test.

**Comment by hzhou** [comment]
> 
> 
> > There is no requirement ... `Testall` needs to succeed on its first try
> 
> With the current implementation, would it succeed in the second try? I'm still a bit confused, you said `ch4`.. Are both `ucx` and `ofi` supposed to behave similarly?

`ch4:ofi` has separate shared memory enabled. `ch4:ucx` handles shared memory inside `ucx` library.

**Comment by hzhou** [comment]
> With the current implementation, would it succeed in the second try?

I am not sure. `Testall` will eagerly jump out of progress for any progress in order to shorten the latency. So it may take as many as the number of your messages to complete all of them.

**Comment by dalcinl** [comment]
OK, thanks for your explanations. This is all user code. Actually, it is test code, written on purpose that way. I'll update my testing accordingly.
