### ISSUE TITLE
MPI_WIN_SIZE attribute for dynamic windows in ch4:ofi

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5148]
Consider the following trivial code

```python
from mpi4py import MPI
win = MPI.Win.Create_dynamic(MPI.INFO_NULL, MPI.COMM_SELF)
base = win.Get_attr(MPI.WIN_BASE)
size = win.Get_attr(MPI.WIN_SIZE)
win.Free()
print(base, size)
```

Depending on the device, I get the following output printed:

| Device | Output |
| --- | --- |
| ch3 | `0 0` |
| ch4:ucx | `0 0` |
| ch4:ofi | `0 -1` |

May I request to fix `ch4:ofi` to also return size := 0 ?

**Comment by hzhou** [comment]
Sounds reasonable :)
