### ISSUE TITLE
ROMIO header include order

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#5191]
Thanks for auditing:  for many years MPICH tried hard not to use _GNU_SOURCE , so it didn't matter when we included configure.h .  At some point _GNU_SOURCE was useful enough to check for but a lot of header files were not updated.

_Originally posted by @roblatham00 in https://github.com/pmodels/mpich/issues/5101#issuecomment-812260422_

**Comment by roblatham00** [comment]
Relevant audit:  https://github.com/pmodels/mpich/pull/5101#issuecomment-810556138

**Comment by hzhou** [comment]
@roblatham00 This ticket is fixed by https://github.com/pmodels/mpich/pull/5184, right?

**Comment by roblatham00** [comment]
indeed.  great!  closing
