### ISSUE TITLE
hydra2: Remove hydra2

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5207]
Hydra and hydra2 share a lot of cruft and this is adding significant maintenance burden whenever we fix some of them. At this point, hydra is much more mature than hydra2 and makes more sense to enhance rather than spending the effort in hydra2 to catch up. So I suggest remove hydra2 from the MPICH repository.

We should run some benchmarks to establish the baseline and understand what is lacking in hydra currently against hydra2 and make a roadmap for hydra enhancement. Unless we identify critical issues and conclude no feasible path, we should then drop hydra2.

**Comment by wesbland** [comment]
cc: @ddurnov

**Comment by ddurnov** [comment]
@hzhou As far as I remember ideas behind hydra2 it was more modular as well. We definetly interested in hydra2 so we could align what we have on our side with your changes easier. Our code is hydra2 based and we expected that you were going to invest into it and make it as MPICH's primary solution

**Comment by irozanova** [comment]
Hi @hzhou,
Do you have a list what `hydra` has, but missed is `hydra2`?

**Comment by hzhou** [comment]
First, I think it is clear that we are not able to simultaneously maintain both `hydra` and `hydra2`. Keeping `hydra2` has not resulted in the benefit of making downstream align to our changes easier because the changes are simply not going into `hydra2`. It has not happened for the past several years since the hydra2 inception, and I believe now it is even less likely to happen.

So the decision has to be made to drop one. From our side, `hydra` is more mature, more tested, with more fixes accumulated, and we are more familiar with it. We roughly understand what `hydra2` has and I am confident that we can bring those features to `hydra` easier than to identify the list of small things that `hydra` has but missed in `hydra2`, that plus the high potential of new bugs or new incompatible behaviors simply may result from switching to the new codebase.

Rest assured, that we will not remove `hydra2` until we refactor `hydra` and bring the major features of `hydra2` back into `hydra`. Once that is achieved, we can re-evaluate this decision. `hydra` probably will be more modular as well. I believe it is more feasible for Intel to identify the list of new features that have been accumulated on the Intel side and upstream back to `hydra`. But we may end up discovering that it is too difficult to modernize `hydra`  and modify the plan accordingly.
