### ISSUE TITLE
ch4:ofi MPIDI_OFI_index_datatypes() must be called after calling create_vni_context()

### ISSUE THREAD

**Issue by ahori** [pmodels/mpich#5236]
File: mpid/ch4/netmod/ofi/ofi_init.c
Func: int MPIDI_OFI_init_local(int *tag_bits)

I moved the MPIDI_OFI_index_datatypes() call just after the create_vni_context() call, but I do not know if this is the correct way to fix this issue (SIGSEGV when calling MPIDI_OFI_index_datatypes()).

**Comment by hzhou** [comment]
Yes. I think that is a correct fix. I only wonder why it didn't cause an issue in our testings.

**Comment by ahori** [comment]
Yes, I also wonder too.  Thanks for the fix.
