### ISSUE TITLE
pmi: Remove unnecessary encoding for PMIx put/get values

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#5241]
The PMIx put/get usage in MPICH converts values to string representation despite PMIx supporting binary blob data. It should be OK to remove this extra step without any loss of functionality.

**Comment by hzhou** [comment]
How much impact if we extend hydra/PMI1 to allow binary put/get? I would really like not to have to maintain two different mechanisms.

**Comment by raffenet** [comment]
Hydra is not the only PMI1/PMI2 implementation in use in the wild. I don't think extending it buys us anything.

**Comment by hzhou** [comment]
How about we treat it similar to MPIX, use the extended feature only if the Process manager supports it, otherwise we fallback. The fallback should allow the transition before the other PMI1/PMI2 implementation catches up. Having a universal mechanism makes the logic of business card exchange orthogonal to which PMI we use, I think it has its long-term benefits. For example, we can debug and compare with different protocols to identify whether it's MPICH issues or PMI issues, and each layer can evolve relatively independently.

**Comment by raffenet** [comment]
So add a 4th and 5th put/get implementation?

**Comment by hzhou** [comment]
> 
> 
> So add a 4th and 5th put/get implementation?

No. Just one put/get with hex encoding and maximum value length (the fall back version) and another put/get with binary and arbitrary size. The logic to select which version (based on CVAR and PMI capability) is orthogonal to the put/get implementations.

**Comment by raffenet** [comment]
> > So add a 4th and 5th put/get implementation?
> 
> No. Just one put/get with hex encoding and maximum value length (the fall back version) and another put/get with binary and arbitrary size. The logic to select which version (based on CVAR and PMI capability) is orthogonal to the put/get implementations.

Sure, but that means client and server implementations of binary put/get for PMI1 and PMI2 + the MPIR-layer client glue. Right now `put_ex|get_ex` in MPIR assume string encoding. Can we at least start small and remove that assumption to enable one binary-capable client (PMIx)?

**Comment by raffenet** [comment]
> You will create `put_binary|get_binary` anyway, right? My point is to create that in a general way rather than tie it to the PMIx in its design. We can just do `MPIR_Assert(0)` for `PMI1/2` for now.

This seems reasonable. It should be no problem.

**Comment by hzhou** [comment]
In `mpir_pmi.c`, the `put_ex/get_ex` is essentially `put_binary/get_binary`, so yes, we should directly use PMIx binary put/get.
