### ISSUE TITLE
coll: remove TSP abstraction

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5265]
The idea of the TSP abstraction is to swap the transport scheduling system without modifying the actual algorithm. However, we are not implementing multiple transports, and the current abstraction creates a lot of clutter and makes code reading very difficult. And if we ever will create multiple transports, then the different transports has to be visible to the algorithm selection layer, thus necessitates separate names for each algorithm each transport anyway and the code reuse can be easily managed within each algorithm. Thus the benefit of this complicated macro name swapping has very little potential benefit. 

I suggest we remove the TSP abstraction and simply use the gentran namespace directly. If we are looking into experimenting with an alternate TSP mechanism or tuning, it can be easily achieved with #ifdef or automaker conditions. Only until we establish the need to have multiple alternate transports available to users, then we need to worry about proper abstraction.

An example is the current implementation of persistent collectives. Since we need expose the sched to the very top layer, the TSP abstraction is already broken.

**Comment by hzhou** [comment]
cc @wesbland @tarudoodi

**Comment by tarudoodi** [comment]
+ @zhenggb72
