### ISSUE TITLE
3.4.1: mpitch source tree is not autoconf 2.71 ready

### ISSUE THREAD

**Issue by kloczek** [pmodels/mpich#5282]
- During regenerate all GNU autotools files there emitted a lot of warnings
- To regenerate all files should be used only `autoreconf -fiv` and what is implemented in `autoge.sh` proves that whole GNU autotools support is impended not as it should be
- When to regenerate all files is used `autoge.sh` configure fails.
- When `autoreconf -fiv` is used some files are mot regenerated and configure fails as well
- Many autoreconf warnings can be fixed by apply changes generated by `autoupdate` command. As those changes will be backward compatible will try to submit some PR of those changes.

Here is log from `autoge.sh` + `configure`

[mpich-autoge_sh_configure_log.txt](https://github.com/pmodels/mpich/files/6489132/mpich-autoge_sh_configure_log.txt)

**Comment by hzhou** [comment]
The `main` branch should work with autoconf 2.7x now.

**Comment by kloczek** [comment]
OK.
May I ask about ET when new version out of main branch will be released?

**Comment by hzhou** [comment]
> 
> 
> OK.
> May I ask about ET when new version out of main branch will be released?

Alpha release 4.0a2 that will contain the mentioned fixes will come out early next month.

@raffenet Do you think we should port the autoconf fixes to `3.4.x`? It is mainly #5206 and #5244

**Comment by kloczek** [comment]
That really depends how quickly will land 4.0.0.
If it would be few weeks I think that backporting may not be necessary.

**Comment by hzhou** [comment]
> 
> 
> That really depends how quickly will land 4.0.0.
> If it would be few weeks I think that backporting may not be necessary.

We are probably looking at early next year for the stable 4.0 release.

**Comment by hzhou** [comment]
@kloczek By the way, if you are looking at official releases, which is a source tarball format, why would you be concerned with running `autoconf`?

**Comment by kloczek** [comment]
To be honest I don't need official tar ball (remember generate it not by `make dist` but by `make distcheck`).
In my building procedure I'm using tar ball basing on autogenerated from git tag downloaded over github REST interface (starting from which is way better suited to apply patches from git commits downloaded as same over github REST interface).
On release probably will be used a bit older so in my case I'll be forced to regenerate all GNU autotools files (so starting from git tar ball will make no difference).

Simple I can wait a bit if some crucial work to finish next release will be done and then I'll try to add some my changes.
I see that in those two PRs are fixed most critical parts but ac 2.71 still is barking about many warnings.
Simple working on ac I would like to start from something stable/proven that it at has fixed known/key issues :)

So when do you think 4.0.0 may land? :P

**Comment by kloczek** [comment]
I see that first PR fixes most critical changes and `autogen.s` + `./consigure` are able to pass full GNU autotools regeneration.
So if you would be planning to make new 3.4.x release that first PR should be IMO included as absolute minimum :)
I think that because that first PR added most critical fixes we can close that ticket (feel free to do that).

Thank you for info about these PRs :)

**Comment by kloczek** [comment]
> @kloczek By the way, if you are looking at official releases, which is a source tarball format, why would you be concerned with running autoconf?

Because you are using buggy libtool.

**Comment by kloczek** [comment]
> We are probably looking at early next year for the stable 4.0 release.

Just checked 3.4.x branch and I see that only in that branch is already +100 commits since 3.4.1. IMO you should ASAP make new 3.4.2 release (I'm assuming those commits are only bugfixes) and with that rate of the commits each next minor release should monthly .. top every 3 months.

Yet another advice.
I would recommend to make new devel release as `dev/3.99.1` and rename `v4.0a1` to `dev/3.99.0`
That visioning convention will allow easy upgrade to final `4.0.0`. `dev/` in tag will clearly indicate that it is not version for the usage in most stable envs.
To speedup development I would recommend to make devel release every 2 weeks up to month.

In tags can be used slashes and that part automatically is skipped in autogenerated tar balls from git tags.

**Comment by kloczek** [comment]
I'll try ASAP to build my own package with 3.4.1 + all commits from 3.4.x branch to check that branch.
Will back shortly :)

**Comment by raffenet** [comment]
> @raffenet Do you think we should port the autoconf fixes to `3.4.x`? It is mainly #5206 and #5244

I'd rather not, since 3.4.x is only a maintenance branch and not actively developed.

**Comment by raffenet** [comment]
> Yet another advice.
> I would recommend to make new devel release as `dev/3.99.1` and rename `v4.0a1` to `dev/3.99.0`
> That visioning convention will allow easy upgrade to final `4.0.0`. `dev/` in tag will clearly indicate that it is not version for 

Renaming a public release is not something we typically consider.

**Comment by raffenet** [comment]
> To be honest I don't need official tar ball (remember generate it not by `make dist` but by `make distcheck`).
> In my building procedure I'm using tar ball basing on autogenerated from git tag downloaded over github REST interface (starting from which is way better suited to apply patches from git commits downloaded as same over github REST interface).
> On release probably will be used a bit older so in my case I'll be forced to regenerate all GNU autotools files (so starting from git tar ball will make no difference).
> 
> Simple I can wait a bit if some crucial work to finish next release will be done and then I'll try to add some my changes.
> I see that in those two PRs are fixed most critical parts but ac 2.71 still is barking about many warnings.
> Simple working on ac I would like to start from something stable/proven that it at has fixed known/key issues :)
> 
> So when do you think 4.0.0 may land? :P

Can you explain your use-case and why you choose not to use tarball releases?

**Comment by hzhou** [comment]
I think it makes some sense if they maintain internal patches and some of those patches are for `configure.ac`.

**Comment by kloczek** [comment]
> > @raffenet Do you think we should port the autoconf fixes to 3.4.x? It is mainly #5206 and #5244

> I'd rather not, since 3.4.x is only a maintenance branch and not actively developed.

That first PR is IMO absolutly safe from point of view maintainance 3.4.x releaes. All ac 2.71 changes are backward compatible. Including it in next 3.4.x release would allow people who already started using ac 2.71 to regenerate all autotools files and not have some errors on that process.

**Comment by raffenet** [comment]
> > > @raffenet Do you think we should port the autoconf fixes to 3.4.x? It is mainly #5206 and #5244
> 
> > I'd rather not, since 3.4.x is only a maintenance branch and not actively developed.
> 
> That first PR is IMO absolutly safe from point of view maintainance 3.4.x releaes. All ac 2.71 changes are backward compatible. Including it in next 3.4.x release would allow people who already started using ac 2.71 to regenerate all autotools files and not have some errors on that process.

This is not a situation we or our downstream partners are currently in. I'd like to understand more how you are using the software before committing effort to this kind of work in the maintenance branch.

**Comment by kloczek** [comment]
> Can you explain your use-case and why you choose not to use tarball releases?

- as I wrote you are using buggy libtoot
- second thing is that on use as base resource tagged tar ball and additional patches downloaded over gitlab/github REST interface I havve 100% guarantee that those parches will be appliet as dist tar ball may not be identicall to state of the resorces on which git patches needs to be applied.
I can give you glimpse of my mp[ich.spec file which I'm usimg to build my mpitch pacjage:
```spec
VCS:            https://github.com/pmodels/mpich/
Source0:        https://www.mpich.org/static/downloads/%{version}/%{name}-%{version}.tar.gz
Source1:        %{name}.macros
Source2:        %{name}.pth.py3
Patch000:       %{VCS}/commit/03ed4bd5.patch#/%{name}-config-Fix-test-for-_Float16.patch
Patch001:       %{VCS}/commit/3d2d1b53.patch#/%{name}-ch4-ofi-free-allocated-mr-key-during-win-detach.patch
Patch002:       %{VCS}/commit/47969a01.patch#/%{name}-ch4-ofi-modify-mr_key-utility-functions-for-coll-mr-.patch
Patch003:       %{VCS}/commit/aed3d555.patch#/%{name}-ch4-ofi-generate-collective-mr_key-in-win-init.patch
Patch004:       %{VCS}/commit/cdd044c2.patch#/%{name}-config-enhance-PAC_SET_HEADER_LIB_PATH.patch
Patch005:       %{VCS}/commit/adae8657.patch#/%{name}-config-use-USE_WRAPPER_FLAGS-for-WRAPPER_LIBS-usage.patch
Patch006:       %{VCS}/commit/67b1e078.patch#/%{name}-config-add-additional-PAC_CHECK_HEADER_LIB-macros.patch
Patch007:       %{VCS}/commit/84ae6243.patch#/%{name}-config-update-configure-of-cuda-and-ze.patch
Patch008:       %{VCS}/commit/04bb7220.patch#/%{name}-ch4-ofi-add-back-GNI-capability-set.patch
Patch010:       %{VCS}/commit/1b0054a3.patch#/%{name}-preq-fix-wrong-usage-of-MPIDIG_REQUEST.patch
Patch011:       %{VCS}/commit/a1b5561e.patch#/%{name}-hydra-fix-error-checking-for-strtol.patch
Patch012:       %{VCS}/commit/47750282.patch#/%{name}-hydra-fix-an-bug-in-freeing-published-entries.patch
Patch013:       %{VCS}/commit/ff62e7d4.patch#/%{name}-hydra-add-man-page-for-hydra_nameserver.patch
Patch014:       %{VCS}/commit/11600f03.patch#/%{name}-ch4-ucx-terminate-the-string-in-MPIDI_UCX_mpi_comm_d.patch
Patch015:       %{VCS}/commit/ef9b2190.patch#/%{name}-ch4-ucx-add-free-in-MPIDI_UCX_mpi_comm_disconnect.patch
Patch016:       %{VCS}/commit/447f1b8a.patch#/%{name}-coll-cleanup-memory-in-ireduce_scatter_block.patch
Patch017:       %{VCS}/commit/dc953fca.patch#/%{name}-comm-use-MPIR_Allreduce_impl-in-contextid-routines.patch
Patch018:       %{VCS}/commit/5134244a.patch#/%{name}-make-ADIOI_GEN_WriteStrided-not-step-on-itself.patch
Patch019:       %{VCS}/commit/e2227581.patch#/%{name}-ch4-ofi-set-MPIR_CVAR_OFI_SKIP_IPV6-default-to-true.patch
Patch020:       %{VCS}/commit/63e3a03b.patch#/%{name}-making-romio-GPFS-able-to-build.patch
Patch021:       %{VCS}/commit/d92ce967.patch#/%{name}-romio-gpfs-avoid-freeing-NULL.patch
Patch022:       %{VCS}/commit/804e8b6b.patch#/%{name}-romio-GPFS-missing-initialization.patch
Patch023:       %{VCS}/commit/6391f911.patch#/%{name}-romio-fix-when-used-in-Wpedantic-build-environments.patch
Patch024:       %{VCS}/commit/bb587a33.patch#/%{name}-group-Fix-memory-leaks-in-group-routines.patch
Patch025:       %{VCS}/commit/d3b5bf18.patch#/%{name}-config-stddef.h-is-not-included-with-the-ac_check_al.patch
Patch026:       %{VCS}/commit/bccefdce.patch#/%{name}-op-MPI_NO_OP-and-MPI_REPLACE-should-be-non-commutati.patch
Patch027:       %{VCS}/commit/c2a0849d.patch#/%{name}-ch4-netmod-remove-size-check-for-native-PUT-and-GET.patch
Patch028:       %{VCS}/commit/4c38b235.patch#/%{name}-mpl-threads-argobots-fix-MPL_thread_join.patch
Patch029:       %{VCS}/commit/1fb8ebb4.patch#/%{name}-mpl-threads-argobots-implement-MPL_thread_create.patch
Patch030:       %{VCS}/commit/6a39eedf.patch#/%{name}-init-enable-asynchronous-progress-even-with-Argobots.patch
Patch031:       %{VCS}/commit/b142cc38.patch#/%{name}-test-Fix-buffer-name-in-MTestAlloc.patch
Patch032:       %{VCS}/commit/498486bd.patch#/%{name}-coll-Fix-gpu-fallback-path-for-redscat-collectives.patch
Patch033:       %{VCS}/commit/9a8ee0a9.patch#/%{name}-test-mpi-Remove-buffer-content-check-for-rank-0-in-M.patch
Patch034:       %{VCS}/commit/f66746dd.patch#/%{name}-test-mpi-Fix-bugs-in-op_coll.c.patch
Patch035:       %{VCS}/commit/fa996033.patch#/%{name}-ch4-posix-decrease-shm_limit_counter-when-freeing-co.patch
Patch036:       %{VCS}/commit/ce5dc3fa.patch#/%{name}-ch4-posix-set-coll-fallback-as-silent.patch
Patch037:       %{VCS}/commit/2ef6a958.patch#/%{name}-ch4-posix-set-MPIDI_POSIX_shm_limit_counter-as-dummy.patch
Patch038:       %{VCS}/commit/f8d71dc8.patch#/%{name}-ch4-fix-warning-in-formatting-spec.patch
Patch039:       %{VCS}/commit/d246f4c9.patch#/%{name}-test-Check-for-bash-for-testing-scripts.patch
Patch040:       %{VCS}/commit/b807cb96.patch#/%{name}-f08-warning-squash.patch
Patch041:       %{VCS}/commit/c0e56070.patch#/%{name}-ch4-coll-call-MPIR_Xxx_impl-on-fallback.patch
Patch042:       %{VCS}/commit/f3fe5682.patch#/%{name}-array-main-path-needs-a-resize-in-the-block-cyclic-s.patch
Patch043:       %{VCS}/commit/9df9a154.patch#/%{name}-darray-romio-needs-a-resize-in-the-block-cyclic-subt.patch
Patch044:       %{VCS}/commit/a518a6c2.patch#/%{name}-romio-flatten-has-flat-count-consistency-problems.patch
Patch045:       %{VCS}/commit/ba395a94.patch#/%{name}-romio-daos-update-configure-to-remove-unneeded-libra.patch
Patch046:       %{VCS}/commit/44eb9092.patch#/%{name}-datatype-ensure-datatype-fields-are-consistent-with-.patch
Patch047:       %{VCS}/commit/f4ebb5b8.patch#/%{name}-datatype-run-commit-at-the-end-of-MPIR_Type_dup.patch
Patch048:       %{VCS}/commit/954e4850.patch#/%{name}-typerep-yaksa-fix-warning-of-pointers-with-different.patch
Patch049:       %{VCS}/commit/52ed3d93.patch#/%{name}-romio-daos-fix-a-double-free-issue-when-path-has-.-i.patch
Patch050:       %{VCS}/commit/82bde6de.patch#/%{name}-romio-daos-conditionally-compile-out-svcl-setting-as.patch
Patch051:       %{VCS}/commit/20dbdb0b.patch#/%{name}-coll-Convert-buffer-swap-macro-to-function.patch
Patch052:       %{VCS}/commit/c1f097b2.patch#/%{name}-test-mpi-Cleanup-test-generation-script-output.patch
Patch053:       %{VCS}/commit/cf1d43e1.patch#/%{name}-test-mpi-util-fix-Argobots-tests.patch
Patch054:       %{VCS}/commit/cf891932.patch#/%{name}-fortran-fix-MPI_STATUS-type-in-use_mpi.patch
Patch055:       %{VCS}/commit/71c93812.patch#/%{name}-test-mpi-add-unified-shared-memory-type-for-ZE-gpu-t.patch
Patch057:       %{VCS}/commit/bc27f29c.patch#/%{name}-mpl-gpu-update-to-new-Level-zero-API-v1.0.patch
Patch060:       %{VCS}/commit/ebd9e6b7.patch#/%{name}-mpl-thread-argobots-extend-MPL_thread_self-to-suppor.patch
Patch061:       %{VCS}/commit/e1290515.patch#/%{name}-init-update-tag_ub-after-MPID_Init.patch
Patch062:       %{VCS}/commit/241be49a.patch#/%{name}-test-util-add-missing-argument-for-cudaMallocManaged.patch
Patch063:       %{VCS}/commit/bbefe9bf.patch#/%{name}-test-fix-a-few-gpu-testing-bug.patch
Patch064:       %{VCS}/commit/a9f80022.patch#/%{name}-test-f08-fix-usage-of-mpi_type_hindexed-and-mpi_type.patch
Patch065:       %{VCS}/commit/0f0b554e.patch#/%{name}-op-fix-wrong-MPIR_OP_N_BUILTIN.patch
Patch066:       %{VCS}/commit/b5101102.patch#/%{name}-test-fix-pingping-ignoring-recvcnt.patch
Patch067:       %{VCS}/commit/5d81ffb8.patch#/%{name}-ch4-ucx-return-error-for-non-supported-functions.patch
Patch068:       %{VCS}/commit/93c0f3ff.patch#/%{name}-ch4-ipc-remove-early-return-when-xpmem-is-off.patch
Patch069:       %{VCS}/commit/befe7af4.patch#/%{name}-ch4-ipc-check-return-errno-of-ipc-handle-map.patch
Patch070:       %{VCS}/commit/7624988b.patch#/%{name}-ch4-ucx-fix-use-of-WINATTR_NM_REACHABLE.patch
Patch071:       %{VCS}/commit/2092c6f3.patch#/%{name}-ch4-ucx-disable-native-rma-if-win-base-is-device-mem.patch
Patch072:       %{VCS}/commit/f17c13a8.patch#/%{name}-ch4-ucx-use-win-info_table-to-optimize-full-AM-falba.patch
Patch073:       %{VCS}/commit/3e129ea6.patch#/%{name}-ch4-relax-definition-of-MPIDI_WINATTR_NM_REACHABLE.patch
Patch074:       %{VCS}/commit/8ae1efb8.patch#/%{name}-ch4-ucx-free-temp-am-buffer-using-MPL_gpu_free_host.patch
Patch075:       %{VCS}/commit/5520bd5a.patch#/%{name}-ch4-ipc-fully-disable-xpmem-when-it-is-unsupported-a.patch
Patch076:       %{VCS}/commit/861090cf.patch#/%{name}-ch4-ofi-remove-setting-size-in-dynamic-window.patch
Patch077:       %{VCS}/commit/61480ce5.patch#/%{name}-romio-gpfs-Fix-header-include-order.patch
Patch078:       %{VCS}/commit/f223c218.patch#/%{name}-mpl-cuda-Fix-header-include-order.patch
Patch079:       %{VCS}/commit/405e28d0.patch#/%{name}-coll-upgrade-the-internal-count-and-offset-variables.patch
Patch080:       %{VCS}/commit/e7d5bee5.patch#/%{name}-typerep-yaksa-return-error-for-unspported-datatype.patch
Patch081:       %{VCS}/commit/0ad26315.patch#/%{name}-ch4-spawn-fix-MPID_Comm_spawn_multiple.patch
Patch082:       %{VCS}/commit/cfe71ee2.patch#/%{name}-ch4-spawn-fix-copy-of-pmi_errcodes.patch
Patch083:       %{VCS}/commit/65518470.patch#/%{name}-mpl-ze-Fix-device-query-during-initialization.patch
Patch084:       %{VCS}/commit/04e5d026.patch#/%{name}-mpl-ze-Fix-potential-memory-leak-in-initialization.patch
Patch085:       %{VCS}/commit/29a98c71.patch#/%{name}-test-mpi-fix-missing-cuda-or-ze-lib-with-system-path.patch
Patch086:       %{VCS}/commit/ba7c58aa.patch#/%{name}-mtest-reduce-default-MPITEST_MAXBUFFER-on-32-bit.patch
Patch087:       %{VCS}/commit/89a273d4.patch#/%{name}-romio-ensure-config-headers-are-included-first.patch
Patch088:       %{VCS}/commit/ccabcaad.patch#/%{name}-mpl-threads-argobots-use-MPL_free.patch
Patch089:       %{VCS}/commit/a3ec2ba0.patch#/%{name}-romio-fix-usage-error-of-DBG_FPRINTF.patch
Patch090:       %{VCS}/commit/9a15c75e.patch#/%{name}-mpl-gpu-add-gpu-attributes-query-functions.patch
Patch091:       %{VCS}/commit/5a4e1fdc.patch#/%{name}-mpl-gpu-move-MPL_gpu_init-finalize-to-MPII_-layer.patch
Patch092:       %{VCS}/commit/25289123.patch#/%{name}-mpl-add-missing-PATH_MAX-definition.patch
Patch093:       %{VCS}/commit/b7309fc4.patch#/%{name}-config-externally-configure-hwloc.patch
Patch094:       %{VCS}/commit/0bd6e16f.patch#/%{name}-hydra-update-configure-of-mpl-and-hwloc.patch
Patch095:       %{VCS}/commit/a9e10f22.patch#/%{name}-config-Add-minimum-version-check-for-hwloc.patch
Patch096:       %{VCS}/commit/57e11494.patch#/%{name}-config-do-not-check-hwloc-minimal-version-if-user-se.patch
Patch097:       %{VCS}/commit/f5a6947c.patch#/%{name}-mpl-test-Fix-header-include-order.patch
Patch099:       %{VCS}/commit/3d386ad5.patch#/%{name}-misc-fix-macros-in-mpir_hwtopo.c.patch
Patch100:       %{VCS}/commit/69481949.patch#/%{name}-misc-simplify-mpichversion.patch
Patch101:       %{VCS}/commit/5fc2ceec.patch#/%{name}-binding-fortran-avoid-using-MPL_malloc-in-fortran-bi.patch
Patch102:       %{VCS}/commit/d2ab5d74.patch#/%{name}-binding-fortran-do-not-include-mpiimpl.h-in-bindings.patch
Patch103:       %{VCS}/commit/f6228d61.patch#/%{name}-Revert-config-externally-configure-hwloc.patch
Patch104:       %{VCS}/commit/dc32a377.patch#/%{name}-Revert-hydra-update-configure-of-mpl-and-hwloc.patch
Patch200:       %{name}-modules.patch
Patch201:       %{VCS}/commit/8f0c7128.patch#/%{name}-Drop-real128.patch
Patch202:       %{VCS}/pull/5206.patch#/%{name}-config-fix-obsolete-macros.patch
Patch203:       %{name}-do_not_install_some_doc.patch
```
With above if I'll execute `rpmbuild -ba mpitch.spec` tagged tar ball and all partches will be donloaded and appliet in rpm `%prep`.
To youse such trick you must have kind of guarntee that those patches will be applied wiithout rejections so only way to have fiulfeeled such condition is to use tagged tar balls :)
Below may show you on how massive scale I'm using that trick .
```console
[tkloczko@barrel SPECS]$ grep '^Source0:.*%{VCS}' *| wc -l; ls -1 *spec|wc -l; grep '^Patch.*:.*%{VCS}' *| wc -l
856
3022
5339
```

**Comment by kloczek** [comment]
I just realised that I'm not using in case mptch tagged tar ball bacause submodules :P
Nevertheless my goal is to maximise use of above approach as it opens many other gates to not obviouse possibilities :)

**Comment by raffenet** [comment]
> I just realised that I'm not using in case mptch tagged tar ball bacause submodules :P

What do you mean?

**Comment by kloczek** [comment]
> Renaming a public release is not something we typically consider

Just to let you now .. "more patches added since last release than more likely that your hands will be shaking" :)
And "we are living in world where all available software is not enouhg tested".
From that point of view only matters how quicly maintar(s)a re reacting on spotted issue and smaller batches of fixes allows better observe exact impact of miltiple fixes (number of those interractions is growing with factorial of N where N is number of fixes :))
Looking on size of the mpich project IMO bugfix releases should be on montly base + eventual JFDJ releases.

The same could be applied for devel releases as they clearly will be marked as devel/non prod releases.
https://github.com/pmodels/mpich/releases/tag/v3.4.1 shows that last releases is already almost 1.3k commits behind master.

**Comment by kloczek** [comment]
> > I just realised that I'm not using in case mptch tagged tar ball bacause submodules :P

> What do you mean

It means that https://github.com/pmodels/mpich/archive//v4.0a1.tar.gz does not contain all files listed as inked git submodules .. only beacause linked repos do not have git tag(s) which have beed added mpich git repo.

**Comment by raffenet** [comment]
> > > I just realised that I'm not using in case mptch tagged tar ball bacause submodules :P
> 
> > What do you mean
> 
> It means that https://github.com/pmodels/mpich/archive//v4.0a1.tar.gz does not contain all files listed as inked git submodules .. only beacause linked repos do not have git tag(s) which have beed added mpich git repo.

GitHub generated tarballs are not official MPICH releases. http://www.mpich.org/static/downloads/4.0a1/mpich-4.0a1.tar.gz contains all the needed source files to build MPICH. We may consider publishing official MPICH tarballs to GitHub in the future. I will there was a way to disable GitHub's automated generation from tags, because it often confuses users who are not familiar with its shortcomings.

**Comment by hzhou** [comment]
We are not going to make significant changes to the 3.4.x branch. The main branch and the upcoming 4.x branch should work with autoconf 2.7 already.

**Comment by kloczek** [comment]
How close is to release 4.0.0?

**Comment by hzhou** [comment]
This November.
