### ISSUE TITLE
Running mpich in combination with Podman

### ISSUE THREAD

**Issue by adrianreber** [pmodels/mpich#5292]
I just opened a issue in the Podman repository about running mpich in combination with Podman:

https://github.com/containers/podman/issues/10409

It is possible to use Podman in combination with Open MPI (https://podman.io/blogs/2019/09/26/podman-in-hpc.html). This works by Podman copying all environment variables from the host into the container. With mpich this does not seem to work.

My current theory is that mpich uses FDs to communicate between the main process and the ranks. Is that correct?

Could someone from mpich maybe add a comment on the Podman issue to confirm that FD passing is really the reason. Or to tell me that I am completely wrong and what would be necessary to run mpich with Podman containers.

**Comment by marcodelapierre** [comment]
I have just open another Podman issue, detailing the error in attempting to use Podman with MPICH:

https://github.com/containers/podman/issues/10410

**Comment by hzhou** [comment]
`hydra` -- the default process manager used by mpich -- can use both `PMI_FD` (default) or `PMI_PORT` (tcp socket connection) for PMI (process management interface) communications. To use latter, pass in the option `--pmi-port`. E.g. 
```
    mpirun -pmi-port -n 2 ./cpi
```

**Comment by adrianreber** [comment]
Perfect. That was easy and that works out of the box. Thanks.
