### ISSUE TITLE
ch3/nemesis: assertion failed on Cortex-A75

### ISSUE THREAD

**Issue by AlimAkhtar** [pmodels/mpich#5309]
Hello
I am facing an issue when running mipbench on ARM's Cortex-A75 CPUs. By default MPI Bench was compiled for using CH3. 
On searching mpi mailing list, got some suggestion to use ch4 instead of ch3.

Recompiled mpibench to use ch4 and that works well on this architecture. 
This wad observed only when using multiple CPUs (with one CPU core, ch3 works well)

The failure signature looks like below:
Assertion failed in file
src/mpid/ch3/channels/nemesis/src/ch3_progress.c at line 530:
payload_len >= sizeof (MPIDI_CH3_Pkt_t)
after some loop.

or sometime I see like :
Assertion failed in file
src/mpid/ch3/channels/nemesis/src/ch3_progress.c at line 567:
!vc_ch->recv->active

Please have a look into this and suggest if any fix need to be added.

**Comment by hzhou** [comment]
@AlimAkhtar I suspect it is due to the atomics used in nemesis is not strong enough on this chip. Could you try the attached patch to see if it fixes the issue?

[t.patch.txt](https://github.com/pmodels/mpich/files/6566379/t.patch.txt)

**Comment by AlimAkhtar** [comment]
Hi Hzhou
Yes, this patch fixes the issues on this architecture. Are you going to apply this on mpi repository?
 
So, what does this mean, is that was an issue with the mpi-bench or there are some architecture problem that this patch adding a work around for?

**Comment by hzhou** [comment]
@AlimAkhtar Thanks for the confirmation. The issue was different architectures have differences in the atomic semantics. The patch swaps all atomics into the strongest semantics, thus are more likely to work but potentially is overkill and may negatively affect performance. The next step is to identify exactly which instruction is the offending ones in our algorithm and to identify whether we need the fix or it is simply compiler bugs or even CPU bugs.

**Comment by AlimAkhtar** [comment]
ok, so what do you suggest, how to proceed on this? Will you be able to check the compiler part?
I understand you are not going to add this patch in mpi-bench, right?

**Comment by hzhou** [comment]
> 
> 
> ok, so what do you suggest, how to proceed on this? Will you be able to check the compiler part?
> I understand you are not going to add this patch in mpi-bench, right?

It will depend on your use case. Is using `ch4` not an option? Is managing your own patch (before we work out the final solution) not an option? By the way, what is `mpi-bench`?

**Comment by AlimAkhtar** [comment]
Well using ch4 does work and even we can have this patch for ch3.
Can you put some light on why ch4 work and not ch3? Does ch4 already using strong atomic instruction? if so, why not ch3?
Basically I am interested in root causing this, if this is a compiler issue or a real CPU issues.

**Comment by hzhou** [comment]
Yes, ch4 uses a slightly different queue design and uses stronger atomics. Ch3 has been widely tested on leading supercomputers, so it is not wise for us to blindly replace the atomics without a thorough understanding of the cause and performance impact.
