### ISSUE TITLE
Possible bug or regression in spawn

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5318]
@hzhou Please see the following logs for full details: https://github.com/mpi4py/mpi4py-testing/runs/2727215069?check_suite_focus=true

```
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf) ... [proxy:0:0@fv-az231-834] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:896): assert (!closed) failed
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
[proxy:0:0@fv-az231-834] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@fv-az231-834] main (pm/pmiserv/pmip.c:169): demux engine error waiting for event
[mpiexec@fv-az231-834] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:73): one of the processes terminated badly; aborting
[mpiexec@fv-az231-834] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:21): launcher returned error waiting for completion
[mpiexec@fv-az231-834] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:179): launcher returned error waiting for completion
[mpiexec@fv-az231-834] main (ui/mpich/mpiexec.c:325): process manager error waiting for completion
=   PID 136667 RUNNING AT fv-az231-834
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
Error: Process completed with exit code 255.
```

**Comment by hzhou** [comment]
Is this test always broken or did we just broke it?

**Comment by hzhou** [comment]
From our nightly log:
```
...
testGetProcNull (test_rma_nb.TestRMAWorld) ... ok
testPutGet (test_rma_nb.TestRMAWorld) ... ok
testPutProcNull (test_rma_nb.TestRMAWorld) ... ok
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testArgsOnlyAtRootMultiple (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testCommSpawn (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testCommSpawnMultiple (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testCommSpawnMultipleDefaults1 (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testCommSpawnMultipleDefaults2 (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testErrcodes (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testErrcodesMultiple (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testNoArgs (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testNoArgsMultiple (test_spawn.TestSpawnSelf) ... skipped 'mpich'
testArgsOnlyAtRoot (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testArgsOnlyAtRootMultiple (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testCommSpawn (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testCommSpawnMultiple (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testCommSpawnMultipleDefaults1 (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testCommSpawnMultipleDefaults2 (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testErrcodes (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testErrcodesMultiple (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testNoArgs (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testNoArgsMultiple (test_spawn.TestSpawnSelfMany) ... skipped 'mpich'
testArgsOnlyAtRoot (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testArgsOnlyAtRootMultiple (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testCommSpawn (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testCommSpawnMultiple (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testCommSpawnMultipleDefaults1 (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testCommSpawnMultipleDefaults2 (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testErrcodes (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testErrcodesMultiple (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testNoArgs (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testNoArgsMultiple (test_spawn.TestSpawnWorld) ... skipped 'mpich'
testArgsOnlyAtRoot (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testArgsOnlyAtRootMultiple (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testCommSpawn (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testCommSpawnMultiple (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testCommSpawnMultipleDefaults1 (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testCommSpawnMultipleDefaults2 (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testErrcodes (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testErrcodesMultiple (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testNoArgs (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testNoArgsMultiple (test_spawn.TestSpawnWorldMany) ... skipped 'mpich'
testConstructor (test_status.TestStatus) ... ok
testCopyConstructor (test_status.TestStatus) ... ok
testDefaultFieldValues (test_status.TestStatus) ... ok
...
```

**Comment by dalcinl** [comment]
@hzhou I ran it a second time, it failed again: https://github.com/mpi4py/mpi4py-testing/runs/2728290234?check_suite_focus=true

This test was passing about a month ago: https://github.com/mpi4py/mpi4py-testing/actions/runs/809263593

Hold on! Look carefully at your output. It says `skipped 'mpich'`. The test is not actually running. Perhaps you are executing the tests without `mpiexec -n <np> python ...` ?

**Comment by hzhou** [comment]
> 
> 
> Oh, you are probably using `mpi4py@master`, right? I have not merged in `mpi4py@testing/mpi`, that is the good one. I'm going to do it now, see [mpi4py/mpi4py#37](https://github.com/mpi4py/mpi4py/pull/37)

Yes, we are just using `mpi4py@master` for now. Ideally, we'd like to test against a stable branch or tag. Would you recommend one?

**Comment by dalcinl** [comment]
I would recommend to keep using `mpi4py@master` for now, things are quite stable. Alternatively, I could create a branch, let say `testing/mpich` you can point to. Perhaps I should give you write access to mpi4py repo? If you ever want it, just ask for it.

About `mpiexec -n 4`, that should suffice. However, if you can do `mpiexec -n 5 ...`, that would be even better. Ages ago I catched an MPICH bug running that way :wink: (there is a test splitting `COMM_WORLD` in two and creating an intercomm, the two disjoint groups have size 2 and 3, both larger than one, and different each other).

**Comment by dalcinl** [comment]
@hzhou Should I merge mpi4py/mpi4py#37 into `mpi4py@master`? You should test MPICH with the changes from that PR (branch `mpi4py@testing/mpi`). Note however that  if I merge that PR into master, the builds within your our CI infrastructure may start failing. Should I want until you investigate and resolve this spawn issue? Please advise.

**Comment by hzhou** [comment]
Either way, it's fine. The mpi4py nightly tests are not blocking our development, so it's ok to have them fail. You should make the merging decision purely based on your side.

**Comment by dalcinl** [comment]
OK, merged! Now you can try to reproduce.

**Comment by hzhou** [comment]
@dalcinl Following up, our nightly tests have been clean. We are running against mpi4py-master with `mpirun -n {1,2,3,5}`. All of them are ok. Are you able to reproduce the failure manually/locally?

**Comment by dalcinl** [comment]
I just run things again in GitHub Actions, and now it worked https://github.com/mpi4py/mpi4py-testing/actions/runs/921060527.

I'm not sure what to say. Before, I got two successive failures in my `ch4:ofi` build. Could it be some sort of race condition? A bug that only triggers with you run things in the constrained, slower environment of a CI builder?

Mmm... No, hold on. Now that I looks at the code, it seems that a `ECONNRESET` can trigger the failure. The CI builders usually have network hiccups. I should probably set things up to use `HYDRA_IFACE=lo` for these CI builds. 
What do you think? Would you recommend this approach? I've done that elsewhere to avoid bogus `gethostbyname()` failures.

PS: At this point, I think we can close this issue. The problems are unlikely to be MPICH's fault.

**Comment by hzhou** [comment]
@dalcinl Apparently you have more insight than I do 😄 I think using the loopback interface may be worthwhile, depending on the purpose of the testing.
