### ISSUE TITLE
MAX_FINALIZE_FUNC is too small

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/mpich#5323]
## Problem

When many VCIs (e.g., 64 VCIs) are used, it hits the upper limit of `MAX_FINALIZE_FUNC`.

## Reason

The assertion happens in the following function:
https://github.com/pmodels/mpich/blob/main/src/mpi/init/init_util.c#L37-L38

MPICH can register only 64 finalization functions now.
https://github.com/pmodels/mpich/blob/main/src/mpi/init/init_util.c#L29

This `MPIR_Add_finalize()` is called per `MPIR_Object_alloc_t`.  (If `MPICH_DEBUG_HANDLEALLOC` is set, 2 `MPIR_Add_finalize()` per `MPIR_Object_alloc_t`.)

https://github.com/pmodels/mpich/blob/main/src/include/mpir_handlemem.h#L305-L312

`MPIR_Object_alloc_t` is used per VCI that is actually used.  So for example, if 64 VCIs are used, 64 `MPIR_Object_alloc_t` are used for requests (in my understanding).

## Impact

Now the default number of VCIs is 64 (https://github.com/pmodels/mpich/pull/5209), so if the program enables VCIs and creates many `MPI_Comm`, the program uses 64 VCIs no matter it is intended or not, which would hit this issue.

---

I can create a patch for this, but which solution is better? (It has been discussed once: https://github.com/pmodels/mpich/issues/337)

1. Increase `MAX_FINALIZE_FUNC` to, say 256: very ad-hoc but easy.

2. Use a linked list/`realloc` or something to make the size of this array variable.  Dynamic memory allocation is necessary.

**Comment by hzhou** [comment]
Last time we increased from 32 to 64 (in 2008) and that lasted for 13 years until now. So I think it is not a bad solution to increase that number again.
