### ISSUE TITLE
Invalid pointer free in ad_gpfs_wrcoll.c and ad_gpfs_rdcoll.c

### ISSUE THREAD

**Issue by ashwinraghu** [pmodels/mpich#5339]
I have an MPI application that aborts when configured to use the ad_gpfs driver in ROMIO with the following error message 
Attempt to free null pointer in file ../../../../src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c, line 432

This perhaps needs a fix similar to the one for others_req[0].offsets implemented in commit  b35ee6b.
I suppose the analogous code in "src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c" needs fixing as well.
 417     ADIOI_Free(my_req[0].offsets);

**Comment by ashwinraghu** [comment]
Please note that this was reported by a customer site.

Here's the relevant parts of ad_gpfs_wrcoll.c that produced the error:
 
94 void ADIOI_GPFS_WriteStridedColl(ADIO_File fd, const void *buf, int count,
...
432     ADIOI_Free(my_req[0].offsets);

`

**Comment by hzhou** [comment]
> This perhaps needs a fix similar to the one for others_req[0].offsets implemented in commit b35ee6b.

Could you find a link for the said commit?

**Comment by ashwinraghu** [comment]
I realize that the commit id is from our repo. Sorry about that.
Here is the original commit:
https://github.com/pmodels/mpich/pull/5099/commits/313289a82ac7fa14081d292a16b4b11d76c7baed

And the PR:
https://github.com/pmodels/mpich/pull/5099/

**Comment by ashwinraghu** [comment]
Hi. I would like to post an update at the customer site that reported this issue. Do we have any potential solutions that might be available soon? Are we looking at a different strategy to fix this compared to the fix in commit 313289a?

**Comment by hzhou** [comment]
@ashwinraghu I am not as familiar with the MPI-IO code but I agree that the fix should be similar. Would you like to contribute a PR?

**Comment by roblatham00** [comment]
Sorry for the inconsistent state of the code.  both ROMIO and I have been around long enough to have seen both "ok to free null" and "not ok to free null" policies in place.   How does https://github.com/pmodels/mpich/pull/5416 look to you?

**Comment by ashwinraghu** [comment]
> Sorry for the inconsistent state of the code. both ROMIO and I have been around long enough to have seen both "ok to free null" and "not ok to free null" policies in place. How does #5416 look to you?

#5416 looks right to me, Rob. I noticed the differing styles wr.t. braces though. Out of curiosity, does ANL's coding style prefer one over the other?

**Comment by hzhou** [comment]
> I noticed the differing styles wr.t. braces though. Out of curiosity, does ANL's coding style prefer one over the other?

There is no official requirement on this yet, but I personally *strongly* prefer always use explicit curly braces for the case of single statement `if` or `for`.

**Comment by hzhou** [comment]
https://github.com/pmodels/mpich/pull/5416#issuecomment-876145180

We need check whether offsets are NULL initialized.

**Comment by ashwinraghu** [comment]
Replicating the comment I posted in the pull request:
in ADIOI_GPFS_Calc_my_req() we have:

522 if (count_my_req_per_proc[i]) {
523     my_req[i].offsets = (ADIO_Offset *)
524           ADIOI_Malloc(count_my_req_per_proc[i] * 2 * sizeof(ADIO_Offset));
525     my_req[i].lens = my_req[i].offsets + count_my_req_per_proc[i];
526      count_my_req_procs++;
527 } 

So, if count_my_req_per_proc[i] is zero, we could still have an invalid pointer in my_req[i].offsets.
I believe my_req[i].offsets and my_req[i].lens should be init'd NULL in an else{} perhaps?

**Comment by ashwinraghu** [comment]
Hi. Would like to know if the above suggestion to fix the initialization is doable and can be incorporated?

**Comment by hzhou** [comment]
> 
> 
> Hi. Would like to know if the above suggestion to fix the initialization is doable and can be incorporated?

I'll take a look tomorrow. Sorry for the delay.

**Comment by ashwinraghu** [comment]
> > Hi. Would like to know if the above suggestion to fix the initialization is doable and can be incorporated?
> 
> I'll take a look tomorrow. Sorry for the delay.
Thanks. That'll help.

**Comment by hzhou** [comment]
@ashwinraghu At line 334 -- https://github.com/pmodels/mpich/blob/60be52c7de1b7c9c76395c28ea21162fa6adc854/src/mpi/romio/adio/common/ad_aggregate.c#L334
The `offsets` is always set to `ptr`, so I believe the code is okay. In fact, I am not sure the fix in #5416 was needed. 

Do you have a reproducer for the original reported issue?

**Comment by ashwinraghu** [comment]
GPFS uses the initializers in ad_gpfs_aggrs.c. doesn't it, when GPFS_MPIIO_TUNEBLOCKING is set,(set by default )
Yes, I have a reproducer for the original reported issue.

**Comment by hzhou** [comment]
I see. Now I am looking at `ADIOI_GPFS_Calc_my_req`. It seems each `my_req[i].offsets` is individually allocated, thus in https://github.com/roblatham00/mpich/blob/3662196ece110cc8982a327f1fd5e4cd6aadcc7a/src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c#L413 it is insufficient to just free `my_req[0]`?

**Comment by ashwinraghu** [comment]
> I see. Now I am looking at `ADIOI_GPFS_Calc_my_req`. It seems each `my_req[i].offsets` is individually allocated, thus in https://github.com/roblatham00/mpich/blob/3662196ece110cc8982a327f1fd5e4cd6aadcc7a/src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c#L413 it is insufficient to just free `my_req[0]`?

That's correct as well and is what I've captured (tried to) in https://github.com/pmodels/mpich/issues/5340.

**Comment by hzhou** [comment]
Okay. Thanks for the confirmation. Let me try fix it.

**Comment by hzhou** [comment]
@ashwinraghu Can you review #5471 and verify whether it fixes the issue?

**Comment by ashwinraghu** [comment]
> @ashwinraghu Can you review #5471 and verify whether it fixes the issue?

Sure can. Stay tuned for updates.
