### ISSUE TITLE
Recursive behavior for improper setting of MPICH_CC or MPICH_CXX

### ISSUE THREAD

**Issue by PHHargrove** [pmodels/mpich#5343]
I am fully aware that what I am about to report is a case of "pilot error".  
However, as I will describe, I believe MPICH could do better to help minimize the consequences.

I am looking at two projects where one advises `CXX=mpicxx`, while the other sets `MPICH_CXX=$CXX; CXX=mpicxx` in its Makefile. Unfortunately the composition of these leads that second project to perform roughly the same as the two following minimal reproducers (for your choice of hello world, or ring, etc.).

```
$ env MPICH_CC=mpicc mpicc hello_world.c
OR
$ env MPICH_CXX=mpicxx mpicxx hello_world.cpp
```

The problem is that `mpicc` or `mpicxx` simply spawns another instance of itself recursively without any self-imposed bound. This fills either the process table or memory or otherwise hits OS-imposed limits before the cycle terminates.

I believe one could provide fairly robust protection against this sort of behavior by adding something like the following (untested and lacking any helpful error message) to the `mpicc`/`mpicxx` scripts:
```
if [ -n $MPICH_RECURSION_CHECK ]; then exit 1; fi
MPICH_RECURSION_CHECK=1
export MPICH_RECURSION_CHECK
```

Lacking a contributors' agreement, I am not planning to evolve that sketch any further.

**Comment by hzhou** [comment]
Hi Paul,
so the intention is to have `mpicc` fail in the recursive case?

**Comment by bonachea** [comment]
>  is to have mpicc fail in the recursive case?

Exactly. 

Failure with a nice error message for this (accidental) erroneous input seems preferable to silently fork-bombing the machine...

**Comment by hzhou** [comment]
Sounds good. I'll make a PR apply the suggestion.
