### ISSUE TITLE
build: MPICHLIB_CFLAGS not picked up by submodule configure

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5360]
@jedbrown reports --

Related to this, I see the BASE_CFLAGS being picked up by default when building UCX and this causes the build to fail with gcc-11 -Werror=array-bounds.

$ rg Werror modules/ucx/config
modules/ucx/config/m4/compiler.m4
12:BASE_CFLAGS="-g -Wall -Werror"
515:                                 [-Werror-implicit-function-declaration],

In file included from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_request.inl:17,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.c:17:
../../../../../modules/ucx/src/ucp/wireup/wireup.c: In function ‘ucp_wireup_msg_send’:
/home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/datastruct/mpool.inl:78:10: error: array subscript -1 is outside array bounds of ‘ucp_request_t[1]’ {aka ‘struct u
cp_request[1]’} [-Werror=array-bounds]
   78 |     mp   = elem->mpool;
      |     ~~~~~^~~~~~~~~~~~~
In file included from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/sys/sys.h:19,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/async/signal.h:13,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/async/async.h:11,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_thread.h:14,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_context.h:14,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.h:11,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.c:11:
/home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/debug/memtrack.h:130:52: note: referencing an object of size 240 allocated by ‘malloc’
  130 | #define ucs_malloc(_s, ...)                        malloc(_s)
      |                                                    ^~~~~~~~~~
../../../../../modules/ucx/src/ucp/wireup/wireup.c:161:11: note: in expansion of macro ‘ucs_malloc’
  161 |     req = ucs_malloc(sizeof(*req), "wireup_msg_req");
      |           ^~~~~~~~~~
In file included from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_request.inl:17,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.c:17:
/home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/datastruct/mpool.inl:55:20: error: array subscript -1 is outside array bounds of ‘ucp_request_t[1]’ {aka ‘struct u
cp_request[1]’} [-Werror=array-bounds]
   55 |         elem->next = mp->freelist;
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/sys/sys.h:19,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/async/signal.h:13,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/async/async.h:11,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_thread.h:14,
                 from /home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucp/core/ucp_context.h:14,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.h:11,
                 from ../../../../../modules/ucx/src/ucp/wireup/wireup.c:11:
/home/jed/src/aur/mpich/src/mpich-3.4.2/build/modules/ucx/../../../modules/ucx/src/ucs/debug/memtrack.h:130:52: note: referencing an object of size 240 allocated by ‘malloc’
  130 | #define ucs_malloc(_s, ...)                        malloc(_s)
      |                                                    ^~~~~~~~~~
../../../../../modules/ucx/src/ucp/wireup/wireup.c:161:11: note: in expansion of macro ‘ucs_malloc’
  161 |     req = ucs_malloc(sizeof(*req), "wireup_msg_req");
      |           ^~~~~~~~~~
cc1: all warnings being treated as errors

Note that adding -Wno-error=array-bounds to MPICHLIB_CFLAGS does not cause it to be propagated to UCX.

config.log

This is currently an issue for Arch Linux packaging of 3.4.1 and 3.4.2.
https://aur.archlinux.org/packages/mpich/

**Comment by hzhou** [comment]
@jedbrown Could you try this patch:
```
--- a/configure.ac
+++ b/configure.ac
@@ -254,10 +254,6 @@ AC_CONFIG_MACRO_DIR([confdb])
 FROM_MPICH=yes
 export FROM_MPICH

-# Save a copy of precious flags as USER_* before any of these flags
-# are being modified by configure tests.
-PAC_PREFIX_ALL_FLAGS(USER)
-
 # WRAPPER_xFLAGS are used by mpicc and friends.
 #
 # WRAPPER_CFLAGS and other compile flags are used for compile options
@@ -314,6 +310,10 @@ CXXFLAGS="$CXXFLAGS $MPICHLIB_CXXFLAGS"
 FFLAGS="$FFLAGS $MPICHLIB_FFLAGS"
 FCFLAGS="$FCFLAGS $MPICHLIB_FCFLAGS"

+# Save a copy of precious flags as USER_* before any of these flags
+# are being modified by configure tests.
+PAC_PREFIX_ALL_FLAGS(USER)
+
 dnl include all subsystem m4 fragments now that the core autoconf functionality
 dnl has been setup.  No fragment should do anything except define
 dnl PAC_SUBCFG_{PREREQ,BODY} macros which will be expanded later as
```

**Comment by jedbrown** [comment]
I needed `autoreconf -fi` (or equivalent), but this succeeded.
```diff
diff --git c/PKGBUILD w/PKGBUILD
index 0d7a99e..6cfe970 100644
--- c/PKGBUILD
+++ w/PKGBUILD
@@ -15,13 +15,17 @@ makedepends=('texlive-core' 'sowing')
 optdepends=(perl)
 install="${pkgname}.install"
 source=("https://www.mpich.org/static/downloads/${pkgver}/${pkgname}-${pkgver}.tar.gz"
-	"mpich.profile")
+	"mpich.profile"
+    "mpich.diff")
 sha256sums=('5c19bea8b84e8d74cca5f047e82b147ff3fba096144270e3911ad623d6c587bf'
-            'b9716439a544511bf88618edeb40c3eb80f1b5d0d9369c30d750251feed02284')
+            'b9716439a544511bf88618edeb40c3eb80f1b5d0d9369c30d750251feed02284'
+            'ce0b565b11a6abc2771e75b53ba84c17bf6534e7f83d20c0fc226ff468c40bae')
 options=('!libtool')
 
 build() {
   cd ${srcdir}/${pkgname}-${pkgver}
+  patch -p1 < ${srcdir}/mpich.diff
+  autoreconf -fi
 
   # CFLAGS etc are normally written into the wrapper compilers.  This
   # gives surprising results, e.g. when the user wants to compile their
diff --git c/mpich.diff w/mpich.diff
new file mode 100644
index 0000000..a20e9d6
--- /dev/null
+++ w/mpich.diff
@@ -0,0 +1,24 @@
+--- a/configure.ac
++++ b/configure.ac
+@@ -254,10 +254,6 @@ AC_CONFIG_MACRO_DIR([confdb])
+ FROM_MPICH=yes
+ export FROM_MPICH
+
+-# Save a copy of precious flags as USER_* before any of these flags
+-# are being modified by configure tests.
+-PAC_PREFIX_ALL_FLAGS(USER)
+-
+ # WRAPPER_xFLAGS are used by mpicc and friends.
+ #
+ # WRAPPER_CFLAGS and other compile flags are used for compile options
+@@ -314,6 +310,10 @@ CXXFLAGS="$CXXFLAGS $MPICHLIB_CXXFLAGS"
+ FFLAGS="$FFLAGS $MPICHLIB_FFLAGS"
+ FCFLAGS="$FCFLAGS $MPICHLIB_FCFLAGS"
+
++# Save a copy of precious flags as USER_* before any of these flags
++# are being modified by configure tests.
++PAC_PREFIX_ALL_FLAGS(USER)
++
+ dnl include all subsystem m4 fragments now that the core autoconf functionality
+ dnl has been setup.  No fragment should do anything except define
+ dnl PAC_SUBCFG_{PREREQ,BODY} macros which will be expanded later as
```

**Comment by hzhou** [comment]
> ```diff
>  optdepends=(perl)
> ```

BTW, we now also optionally depend on `python` (`python3`) during configure if Fortran (`mpi_f08` module) is enabled.
