### ISSUE TITLE
test: `testlist.gpu` is not generated in out-of-tree builds

### ISSUE THREAD

**Issue by tarudoodi** [pmodels/mpich#5366]
In out-of-tree builds, teslist.gpu is not created in any testing sub-dirs.
```
~/mpich/config-main/test/mpi/coll> ls
Makefile  testlist  testlist.cvar  testlist.dtp
```

**Comment by hzhou** [comment]
I wonder how other testlist files that are not from `testlist.in` worked.

**Comment by tarudoodi** [comment]
Probably because they are generated by the scripts at compile time and end up being written to `$PWD/test/mpi/coll`, where `$PWD` is the out-of-tree path.

**Comment by hzhou** [comment]
When we do `make testing`, `runtests` is invoked with `-srcdir=$(srcdir)`, so it will check both the srcdir and builddir for testlist files. `testlist.gpu` files are in the source tree and it should work.
```
$ find . -name testlist.gpu
./test/mpi/rma/testlist.gpu
./test/mpi/pt2pt/testlist.gpu
./test/mpi/coll/testlist.gpu

```

**Comment by tarudoodi** [comment]
I am not sure if it checks for testlists in the `srcdir` as well, it probably only checks for source of tests listed in the testlist. I am just speaking from my experience at runtime and do not discount user error.

**Comment by hzhou** [comment]
Here is the excerpt: https://github.com/pmodels/mpich/blob/9f160df3deb88a57ce088ec014fbc17095b969a0/test/mpi/runtests.in#L439-L442

It first assumes the file in the current path, which is your build path in the VPATH build. If not found, it will check in the source path and use that path instead.

**Comment by hzhou** [comment]
@sudheer9 Could you verify that whether out-of-tree build and (gpu) testing works?

**Comment by hzhou** [comment]
@travisk1154 has confirmed that `make testing` works with vpath build. All the `testlist.gpu` files are located in the source tree and `runtests` is able to find testlist files in both the build tree and source tree.
