### ISSUE TITLE
Fortran: cross compile

### ISSUE THREAD

**Issue by chen-coco** [pmodels/mpich#5380]
I needed Fortran Compiling，But it's a cross compilation 
`configure: error: Unable to configure with Fortran support because configure could not determine the size of a Fortran INTEGER.  Consider setting CROSS_F77_SIZEOF_INTEGER to the length in bytes of a Fortran INTEGER`
so i use
 ```
sudo ./configure -host=riscv64-unknown-linux-gnu --prefix=/usr/local/mpich-git/ FC=gfortran F77=gfortran CROSS_F77_SIZEOF_INTEGER=4 
 CROSS_F77_TRUE_VALUE=1 CROSS_F77_FALSE_VALUE=0
```
but just same ， enclosed log
[config.log](https://github.com/pmodels/mpich/files/6691935/config.log)

**Comment by hzhou** [comment]
Create a "cross" file with content e.g.
```
CROSS_F77_SIZEOF_INTEGER=4                  
CROSS_F77_SIZEOF_REAL=4                     
CROSS_F77_SIZEOF_DOUBLE_PRECISION=8         
CROSS_F90_ADDRESS_KIND=8                    
CROSS_F90_OFFSET_KIND=8                     
CROSS_F90_INTEGER_KIND=8                    
CROSS_F90_REAL_MODEL=6,37                   
CROSS_F90_DOUBLE_MODEL=15,307               
CROSS_F90_INTEGER_MODEL_MAP={9,4,4},        
CROSS_F77_TRUE_VALUE=1                      
CROSS_F77_FALSE_VALUE=0                     
```

Then configure with option `--with-cross=path-to-cross-file`.

**Comment by chen-coco** [comment]
> Create a "cross" file with content e.g.
> 
> ```
> CROSS_F77_SIZEOF_INTEGER=4                  
> CROSS_F77_SIZEOF_REAL=4                     
> CROSS_F77_SIZEOF_DOUBLE_PRECISION=8         
> CROSS_F90_ADDRESS_KIND=8                    
> CROSS_F90_OFFSET_KIND=8                     
> CROSS_F90_INTEGER_KIND=8                    
> CROSS_F90_REAL_MODEL=6,37                   
> CROSS_F90_DOUBLE_MODEL=15,307               
> CROSS_F90_INTEGER_MODEL_MAP={9,4,4},        
> CROSS_F77_TRUE_VALUE=1                      
> CROSS_F77_FALSE_VALUE=0                     
> ```
> 
> Then configure with option `--with-cross=path-to-cross-file`.
it's can be worked!Tanks!
But why does this happen?

**Comment by hzhou** [comment]
When cross-compiling, we don't have a reliable way to detect Fortran datatype sizes, thus require a cross file to supply that information.

**Comment by chen-coco** [comment]
I understand. Thank you again

**Comment by pop-yasigi** [comment]
How do I create a "cross" file?

**Comment by hzhou** [comment]
You can try --
```
perl maint/gen_cross.pl
```
Since we are cross-compiling, the generated file may not be correct. You can either run the script on the target system, or you may manually edit the file with the correct values.
