### ISSUE TITLE
bug: MPI_Reduce may overwrite receive buffer for non-root ranks in v3.4.2

### ISSUE THREAD

**Issue by spickartz** [pmodels/mpich#5397]
When passing a non-`NULL` receive buffer at a non-root to `MPI_Reduce()`, this buffer may be overwritten if the receive buffer resides in GPU memory. This happens as the staging is always performed without checking for the root rank: 

https://github.com/pmodels/mpich/blob/0ad21edcecdeaa3db8b71fa82b2a211b469d7e0c/src/mpi/coll/reduce/reduce.c#L301-L305

For the current `main` branch it seems that the swap back is missing completely (probably leading to issues at the root rank, or am I overseeing something here?):
https://github.com/pmodels/mpich/blob/b345a8d3bed080dbbe8c62c91085a45771363d88/maint/gen_coll.py#L502-L505

**Comment by hzhou** [comment]
Indeed!
