### ISSUE TITLE
MPI-4: Bad C binding for MPI_Info_create_env()

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5399]
The MPI-4 C binding for `MPI_Info_create_env` should be
```c
int MPI_Info_create_env(int argc, char argv[], MPI_Info *info)
```

I believe that is a typo, it should really be like a C `main` function argument list:
```c
int MPI_Info_create_env(int argc, char *argv[], MPI_Info *info)
```

In any case, in MPICH we currently have:
```c
int MPI_Info_create_env(int argc[], char ***argv, MPI_Info *info) MPICH_API_PUBLIC;
```

**Comment by hzhou** [comment]
@dalcinl I think you are correct.

@raffenet Is this issue already raised in the MPI Forum?

**Comment by raffenet** [comment]
> @raffenet Is this issue already raised in the MPI Forum?
> 

No, I don't think so. I'll create an issue.
