### ISSUE TITLE
MPI-4: Bad error checking in MPI_P{send|recv}_init

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5412]
If `count` is zero, then passing `NULL` for `buf` should not error. However:

```c
internal_Psend_init(121): MPI_Psend_init(buf=(nil), partitions=1, count=0, MPI_SIGNED_CHAR, 0, 0, MPI_COMM_SELF, MPI_INFO_NULL, request=0x7f9709fbe2f0) failed
internal_Psend_init(75).: Null pointer in parameter buf
```

**Comment by raffenet** [comment]
I would like to clarify with the forum if zero length partitioned communication is allowed before we make this change.

**Comment by raffenet** [comment]
> I would like to clarify with the forum if zero length partitioned communication is allowed before we make this change.

Confirmed via Slack that zero length is intended to work. We should fix this 😅.

**Comment by dalcinl** [comment]
> Confirmed via Slack that zero length is intended to work.

Otherwise the standard would need an amendment, as both `partitions` and `count` are described as "non-negative integer".
