### ISSUE TITLE
Ireduce: assertion failure for invalid root values

### ISSUE THREAD

**Issue by mquinson** [pmodels/mpich#5443]
Hello,

providing a root that is larger than the communicator size to MPI_Ireduce (as in 
[this code](https://github.com/pmodels/mpich/files/6837106/Ireduce_RootTooLarge.c.txt)) leads to an assertion failure. This code is obviously wrong, but the other collective return a proper MPI error in this case. Ireduce should probably behave the same.

Here is the full output I get when running the provided code:
```
root@3a71714f1f70:/tmp# mpirun -np 2 ./a.out 
Hello from rank 0 
Hello from rank 1 
Assertion failed in file src/util/procmap/local_proc.c at line 250: r < comm_ptr->remote_size
Assertion failed in file src/util/procmap/local_proc.c at line 250: r < comm_ptr->remote_size
0x7f6b854b4707 ???
        ???:0
0x7f6b854b46a7 ???
        ???:0
0x7f6b85463cbb ???
        ???:0
0x7f6b853ae1a7 ???
        ???:0
0x7f6b853aeac7 ???
        ???:0
0x563a98ea8377 ???
        ???:0
0x7f6b8518d0b2 ???
        ???:0
0x563a98ea81ad ???
        ???:0
0xffffffffffffffff ???
        ???:0
internal ABORT - process 0
0x7f4bf7c65707 ???
        ???:0
0x7f4bf7c656a7 ???
        ???:0
0x7f4bf7c14e2e ???
        ???:0
0x7f4bf7b5f1a7 ???
        ???:0
0x7f4bf7b5fac7 ???
        ???:0
0x55d3879ee377 ???
        ???:0
0x7f4bf793e0b2 ???
        ???:0
0x55d3879ee1ad ???
        ???:0
0xffffffffffffffff ???
        ???:0
internal ABORT - process 1
```

System information: mpich version 3.3.2-2build1 installed from the packages, on 
Ubuntu 20.04.2 LTS.

**Comment by hzhou** [comment]
Yes, we agree. This has been fixed in the current main branch, as well as the 4.0a2 release.

**Comment by hzhou** [comment]
@mquinson Can this issue be closed?

**Comment by mquinson** [comment]
Sure, if it's a known issue that is fixed in a released version, then feel free to close it.

Cheers, Mt

Le 28 juillet 2021 14:56:33 GMT+01:00, Hui Zhou ***@***.***> a écrit :
***@***.*** Can this issue be closed?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pmodels/mpich/issues/5443#issuecomment-888330128
-- 
Envoi mobile. Veuillez excuser ma brièveté.
