### ISSUE TITLE
 Fatal error in internal_Precv_init: Invalid communicator, error stack

### ISSUE THREAD

**Issue by Yiltan** [pmodels/mpich#5483]
Hi, I am having the following error when running [Example 4.2 (Equal partitioning on send-side and receive-side using threads)](https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf) from the MPI-4 standard. I example is using the communicator `MPI_COMM_WORLD` so am unsure why I am getting an error

```
yiltan@thetagpusn1:/grand/ATPESC2021/usr/yiltan/thetaGPU/ompi$ mpicc -fopenmp partitioned_cpu.c 
yiltan@thetagpusn1:/grand/ATPESC2021/usr/yiltan/thetaGPU/ompi$ mpirun -env UCX_TLS shm -np 2 ./a.out 
Abort(134879237) on node 1 (rank 1 in comm 0): Fatal error in internal_Precv_init: Invalid communicator, error stack:
internal_Precv_init(119): MPI_Precv_init(buf=0x7fff5d081b38, partitions=8, count=1, dtype=USER<contig>, 0, 1, comm=0x1c000000, info=0x44000000, request=0x7fff5d081aec) failed
internal_Precv_init(49).: Invalid communicator
Abort(1007294981) on node 0 (rank 0 in comm 0): Fatal error in internal_Psend_init: Invalid communicator, error stack:
internal_Psend_init(121): MPI_Psend_init(buf=0x7fffc2f96038, partitions=8, count=1, dtype=USER<contig>, 1, 1, comm=0x1c000000, info=0x44000000, request=0x7fffc2f95fec) failed
internal_Psend_init(49).: Invalid communicator
```

I have installed MPICH as so:
```
#! /bin/bash -l
module --force purge
module remove openmpi
module load Core/StdEnv
module load nvhpc-nompi/21.3

git clone --recursive --branch v4.0a2 https://github.com/pmodels/mpich.git

unset F90
unset F90FLAGS

cd mpich
./autogen.sh
./configure --prefix=$BUILD_DIR \
            --enable-threads=multiple \
            --enable-fortran=no \
            --with-device=ch4:ucx \
            --with-ucx=$BUILD_DIR && \
make -j 32 all && \
make install
```

**Comment by hzhou** [comment]
Looks like you info and comm parameters are swapped

**Comment by Yiltan** [comment]
Thank you, I didn't notice the mistake in the example

**Comment by raffenet** [comment]
> Thank you, I didn't notice the mistake in the example

Neither did the Forum until after it was published 😅. There is a ticket to correct the error (requires permission to view): https://github.com/mpi-forum/mpi-issues/issues/509

**Comment by Yiltan** [comment]
I've gone through the examples in standard and everything seems to work fine. I've also tested some simple send/recv with GPU buffers.

But if I use GPU buffers for partitioned communication I get:
```
[thetagpu03:85337:0:85337] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7f6bfd200000)
==== backtrace (tid:  85337) ====
=================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 85337 RUNNING AT thetagpu03
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
```

I assume as of now, MPICH's partitioned communication does not support GPUs even when using UCX?

Since it doesn't give the most helpful error message would anybody give some insight as to where in the library could be causing this problem? I'm more than happy to implement the changes myself for my application.

**Comment by raffenet** [comment]
> I assume as of now, MPICH's partitioned communication does not support GPUs even when using UCX?

You are right. I have a branch that should support partitioned comm with GPU buffers when using UCX, but it hasn't been approved yet. https://github.com/pmodels/mpich/pull/5462

**Comment by Yiltan** [comment]
Thank you, I've installed that branch my application runs with no issues.
