### ISSUE TITLE
ch4/ofi: need check libfabric versions for multi-nic feature

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5507]
Apparently older versions of libfabric doesn't have the `nic` field defined in the `struct fi_info`. I was trying to build on `Bebop`, which, according to the `/usr/include/rdma/fabric.h`, is version 1.6, and the build breaks due to missing struct field.

We need either raise the minimum version, or (more preferably) check and set macros to disable the multi-nic feature.

**Comment by wesbland** [comment]
Which version of OFI is in your distribution on that machine and how old is that distribution? Is it worth having a discussion about requiring OFI versions > 1.6? We've already said we require at least 1.5.

**Comment by wesbland** [comment]
I misread your statement. So the `nic` field was added to the `fi_info` struct in v1.7.0:

https://ofiwg.github.io/libfabric/v1.7.0/man/fi_getinfo.3.html

So we'd be updating the required version of OFI for MPICH from 1.5 to 1.7.

Technically, I don't think we have a configure time check at the moment to make sure that MPICH is being compiled with an OFI library greater than anything. We used to have some configure checks and some macros that would look for some things that changed in version 1.5, but we took those out.

We do still have the checks in the capability sets that are supposedly looking for specific versions for specific providers. For those, we have a mix of requirements between 1.6 and 1.5. So I think we could in theory bring all of those up to 1.7 and say we don't support anything older than that.

If not that, we'll need to add some `configure` magic and some macros that look for the specific features that we want (in this case, the `nic` field).

So which one do we prefer?

**Comment by wesbland** [comment]
More inconsistencies between reality and me. We do still have at least some of the 1.5ism checks:

https://github.com/pmodels/mpich/blob/a36d1be7b970cf88a3c6e4a91eb8726a02ecf9bf/src/mpid/ch4/netmod/ofi/init_settings.c#L65-L69

The check for the `nic` field would have to be done at configure time though.

**Comment by hzhou** [comment]
> So which one do we prefer?

I think I prefer to have configure-time version check and disable the multi-nic code. It feels a shame to abandon otherwise perfectly performing system libfabric for the feature that it does not need.

**Comment by raffenet** [comment]
> > So which one do we prefer?
> 
> I think I prefer to have configure-time version check and disable the multi-nic code. It feels a shame to abandon otherwise perfectly performing system libfabric for the feature that it does not need.

Agree. I'd rather the system library be used in this instance.

**Comment by hzhou** [comment]
There are more issues with the multi-nic code. The code build with `--with-libfabric=embedded`, but it fails the `MPIDI_OFI_nic_is_up(prov)` test. After I remove that check, I suspect somewhere else down the line with the nic stuff is still messing it up, since I got this from the debug output:
```
==== Capability set configuration ====
libfabric provider: (null) - (null)
...
```

**Comment by hzhou** [comment]
@wesbland ☝️

**Comment by hzhou** [comment]
It might be easier to have a configure options `--enable-ch4-ofi-multinic` and have it disabled by default. @wesbland , what do you think?

**Comment by wesbland** [comment]
That does mask the problem and mean the the code will never be compiled again, but I'd rather actually fix it. 😄

**Comment by hzhou** [comment]
It's possible that the recent libfabric psm2 provider had some digressions. @wesbland you guys always tested on psm2, right? Did you update libpsm2 at some point?

**Comment by wesbland** [comment]
I just realized that I had put in a quick fix in our internal version and forgot to upstream it. 😞 I've submitted it now in https://github.com/pmodels/mpich/pull/5512.
