### ISSUE TITLE
MPI_Initialized returns false after calling MPI_Finalize

### ISSUE THREAD

**Issue by eschnett** [pmodels/mpich#5529]
I find that `MPI_Initialized` returns false when called after calling `MPI_Finalize`. The MPI standard says it should return true. (See e.g. section 8.7 of the MPI 3.1 standard.)

The implementation of `MPI_Initialized` checks whether the current state is `MPICH_MPI_STATE__POST_INIT`. It should probably also check for `MPICH_MPI_STATE__POST_FINALIZED`.

**Comment by hzhou** [comment]
Yes, you are correct.
