### ISSUE TITLE
mpicc should not put `-flat_namespace` into linker options on macOS

### ISSUE THREAD

**Issue by eschnett** [pmodels/mpich#5530]
On macOS, `mpicc` etc. add the linker option `-flat_namespace`. I think this is wrong, because this does not only affect the way MPICH's libraries are linked; it affects the overall way an application or a plugin behaves.

In my case, I want to compile a plugin, i.e. a shared library that will be explicitly opened via `dlopen`. I want the symbol resolution in the plugin – which uses MPICH – to be independent of the main application. On Linux, I would pass the option `RTLD_DEEPBIND` when calling `dlopen` to access the plugin. The roughly equivalent mechanism on macOS is to build the plugin with the `-twolevel_namespace` option. Unfortunately, `mpicc` overrides this with its `-flat_namespace` option.

(Things work if I build without using `mpicc`.)

This issue was also discussed here <https://lists.mcs.anl.gov/pipermail/petsc-dev/2013-April/011992.html>, where the solution also was to remove the `-flat_namespace` option from `mpicc`'s options.

**Comment by hzhou** [comment]
Hi @eschnett , did you try configure mpich with `--enable-two-level-namespace`? Looks like that option was added just skip `-flat_namespace`.

**Comment by eschnett** [comment]
I did not; I didn't see that option. Thanks!

**Comment by hzhou** [comment]
@eschnett Please let us know if that option works for you, so we may close the issue.

**Comment by eschnett** [comment]
Yes, this option works for me.
