### ISSUE TITLE
ch4/ofi: assertion failure during address exchange under multi-NIC

### ISSUE THREAD

**Issue by sagarth** [pmodels/mpich#5552]
Config: psm2 + multi-nic + mult-vci (passes for single vci)
Replicated with SEP, have not tested with mutiple-domains

(error goes away with single NIC:  env: export MPIR_CVAR_CH4_OFI_MAX_NICS=1)

```
Assertion failed in file src/mpid/ch4/netmod/ofi/init_addrxchg.c at line 300: av->dest[nic][vni] == get_av_table_index(r, nic, vni)
Tests: all under multi-nic.
```

Finding: Address exchange is failing when using multiple-nics are used. Address entry returned by `get_av_table_index` is not matching an expected value. Tests run fine after removing the av table valuation/assertion.

**Comment by hzhou** [comment]
@sagarth Could you add a debug print to show which entries were mismatched? If you log `r`, `nic`, `vni`, and both mismatched values, that would be helpful.

**Comment by hzhou** [comment]
Oh, I think we neglected the SEP mode in `get_av_table_index`. With SEP, we only insert av for a single vni since they all share the address. patches coming.

**Comment by hzhou** [comment]
@sagarth Could you verify if #5558 fixes this issue?

**Comment by sagarth** [comment]
@hzhou Yes it fixes the issue.
