### ISSUE TITLE
superfluous .pc files installed for embedded libraries

### ISSUE THREAD

**Issue by carns** [pmodels/mpich#5554]
MPICH 3.4.2 installs several *.pc (pkgconfig) files in the `<prefix>/lib/pkgconfig` directory.  The mpich.pc one appears to be correct, but I also see libfabric.pc and yaksa.pc as well from a stock installation on my laptop.

Anecdotally it looks like some platforms also get json-c.pc and izem.pc.  There may be others that get installed depending on what features are enabled in MPICH?

At any rate, the problem with these auxiliary pkgconfig files is that they refer to libraries that are embedded internally within MPICH.  They are not actually available for external parties to link against, so their library paths should not be advertised to external build systems.

This is particularly problematic if those libraries are installed independently and happen to appear after MPICH in the `$PKG_CONFIG_PATH` environment variable; in that case the incorrect .pc files provided by MPICH will take precedence and prevent programs from linking successfully against the independent external libraries.

**Comment by hzhou** [comment]
Could you try the 4.0a2 release -- https://www.mpich.org/downloads/? Many of the extra .pc files has been fixed there already. Probably `yaksa.pc` is the only remaining need to be fixed.

**Comment by carns** [comment]
Thanks @hzhou !  I confirmed that at least the libfabric.pc file is no longer being installed in 4.0a2:

```
carns@carns-x1-7g ~/working> ls install-mpich-3.4.2/lib/pkgconfig/
libfabric.pc  mpich.pc  yaksa.pc
carns@carns-x1-7g ~/working> ls install-mpich-4.0a2/lib/pkgconfig/
mpich.pc  yaksa.pc
```

There is indeed still a yaksa.pc file, though I'm not likely to encounter that one in my build stack.

I'm curious about json-c.pc, but I'm not sure what would potentially trigger that to be installed in my own local build.

**Comment by wesbland** [comment]
@hzhou Do you know which patch fixed this? At least in my build, I'm still seeing this. I'd rather not reimplement a fix if you already have one.

**Comment by hzhou** [comment]
We had a patch applied to the json-c module -- https://github.com/pmodels/json-c/commit/c496a735ec7312a22c1484ac6950f12fc8712b2f

**Comment by wesbland** [comment]
I see. I might have been looking at an older build. I just recompiled and I'm only seeing pc files for izem, mpich, and yaksa, which I think is fine.
