### ISSUE TITLE
3.4.2: mpich is not autoconf 2.71 ready

### ISSUE THREAD

**Issue by kloczek** [pmodels/mpich#5557]
Exact order of some changes should be:
- s/AC_HELP_STRING/AS_HELP_STRING/ (most of the warnings are about that macro) -> commit
- run `autoupdate`
- carefouly review all `[obsoleted]` parts and make decisions about each change-> if everything will be ok commit

Correcly implemended changes will be working as well with olser autoconf.

Full log of the of the build on the system with autoconf 2.71 is in attachment
[mpich-log.txt](https://github.com/pmodels/mpich/files/7150458/mpich-log.txt)

**Comment by hzhou** [comment]
We are not going to make significant changes to the 3.4.x branch. Could you check the main branch?

**Comment by hzhou** [comment]
Close due to lack of response.
