### ISSUE TITLE
Automake-1.15 and newer perl

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#5564]
The release script (`maint/release.pl`) has a strict dependency on `automake-1.15`.  automake-1.15 and perl-5.26 (default perl on newer linux machines) are no longer compatible  with each other  (see https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated ).  

`maint/release.pl` should require `automake-1.15.1`, which fixes this interdependency,  if it is unable to cope with arbitrarily new versions of automake.

**Comment by hzhou** [comment]
Indeed, according to -- https://github.com/pmodels/mpich/blob/fa85431ceb1917ee6b1bc277d39ba8afbb6e433b/maint/release.pl#L154-L159

I would like to understand the details of the claim though.

**Comment by hzhou** [comment]
@roblatham00 Since it seems there is a good reason to keep `release.pl` with rather strict environment, I am going to mark this issue as wont fix. For your purpose -- to create convenient release tar ball, you can simply manually change into any newer version and it should work.

**Comment by roblatham00** [comment]
Isn't the fix to put a hard dependency on perl-5.22 ?  the next time someone cuts a release they are going to run into this problem...  building perl is kind of a pain but spack at least makes it  set-and-forget

**Comment by raffenet** [comment]
> Indeed, according to --
> 
> https://github.com/pmodels/mpich/blob/fa85431ceb1917ee6b1bc277d39ba8afbb6e433b/maint/release.pl#L154-L159
> 
> I would like to understand the details of the claim though.

I'm skeptical of this claim, at least for C ABI. I don't think it is actually a concern.

**Comment by hzhou** [comment]
> 
> 
> Isn't the fix to put a hard dependency on perl-5.22 ? the next time someone cuts a release they are going to run into this problem... building perl is kind of a pain but spack at least makes it set-and-forget

`perl-5.22` (and earlier versions) is a dependency of `automake-1.15`. The check is included in the automake check.

We probably will update that script to `automake-1.16` at the time we release mpich-4.0. Let me reopen this ticket as a reminder.
