### ISSUE TITLE
bug: handle leaks for predefined datatypes

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5568]
From my understanding of the MPI standard, `MPI_Type_create_f90_{integer|real|complex}()` return unnamed but nonetheless **predefined** datatypes. As they are predefined, we should not `MPI_Type_free()` them, right?.

Please consider the following code:

```python
from mpi4py import MPI
t1 = MPI.Datatype.Create_f90_integer(1)
t2 = t1.Dup()
t3 = t2.Get_contents()[-1][0]
t2.Free()
assert t3 == t1
# t3.Free()
```

So, decoding a dupe of a F90 datatype returns the same F90 datatype handle (the `assert` line confirms that). Therefore, we should not free `t3`. However, after running the code snippet abobe I get the following handle leak warning:

```
$ python test.py
In direct memory block for handle type DATATYPE, 1 handles are still allocated
[0] 64 at [0x560e68f61100], ./src/include/mpir_datatype.h[415]
[WARNING] yaksa: 1 leaked handle pool objects
```

If I uncomment the last line to do `t3.Free()`, then the warning goes away. Doing `t1.Free()` instead silences the warning as well!
However, as `t3` is the same handle as `t1`, which is a predefined datatype, I believe freeing either is technically incorrect.

I understand that fixing MPICH to error on attempts to free predefined F90 types could be quite problematic for backward compatibility reasons. Same problem if you do not increase the reference count of decoded dupes as in the example above.

Can I ask to at least add some special code to not warn about datatype leaks for these F90 datatypes? Perhaps the proper fix is to forcibly deallocate them at finalization, regardless of the reference count value?

**Comment by hzhou** [comment]
> Can I ask to at least add some special code to not warn about datatype leaks for these F90 datatypes? Perhaps the proper fix is to forcibly deallocate them at finalization, regardless of the reference count value?

I think we can do that.

**Comment by hzhou** [comment]
The same issue exists for pair types.

**Comment by hzhou** [comment]
The text in MPI specification is --
```
The datatypes returned in array_of_datatypes are handles to datatype objects that
are equivalent to the datatypes used in the original construction call. If these were derived
datatypes, then the returned datatypes are new datatype objects, and the user is responsible
for freeing these datatypes with MPI_TYPE_FREE. If these were predefined datatypes, then
the returned datatype is equal to that (constant) predefined datatype and cannot be freed.
```
I think this is problematic. How would user know whether a datatype obtained from `MPI_Type_get_contents` is a predefined type or not?

**Comment by dalcinl** [comment]
> I think this is problematic. How would user know whether a datatype obtained from `MPI_Type_get_contents` is a predefined type or not?

Of course it is! I've been dealing with this mess since MPI-2 added support for datatype decoding. 
Similar issues arise in MPI-IO, in `MPI_File_get_view()`.

> If **etype** or **filetype** are derived datatypes, the user is responsible for freeing them.

Of course, in the MPI-IO case, the wording does not force implementors to return a predefined (equal to a constant) datatype, they could choose to return a duped datatype, although that additional indirection would make decoding these datatypes more convoluted, if decoding is ever needed.

So far, the best I could figure out is to have `is_predefined` predicate/propery:
https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/Datatype.pyx#L664
That is, a datatype is predefined if its combiner value is either `MPI_COMBINER_NAMED` or `MPI_COMBINER_F90_{INTEGER|REAL|COMPLEX}`. 
Reasonably cheap way to know whether a datatype is predefined, right?

mpi4py has support to convert MPI <-> NumPy datatypes, which of course is based on datatype decoding.
In there, we check for predefined datatypes to skip freeing them, using the `is_predefined` property I mentioned above:
https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/util/dtlib.py#L325

**Comment by dalcinl** [comment]
> The same issue exists for pair types.

Yes, indeed, although note that pair types are **named** datatypes, so for the point of view of a user, they are should be handled as any other named datatype like `MPI_INT` or `MPI_DOUBLE`.
