### ISSUE TITLE
pt2pt/probe_unexp times out under multi-vci

### ISSUE THREAD

**Issue by sagarth** [pmodels/mpich#5626]
Test: `pt2pt/probe_unexp 4`

Fails under `SEP` + `multi-vci` but passes under `single vci`. 

Test prints `No-Errors` and is stuck during finalize. Out of 4 ranks, 2 ranks were stuck. One rank was stuck in `MPIDI_NM_mpi_finalize_hook` whereas another was stuck in `MPIDU_Init_shm_finalize`. 

Replicated locally with `psm2` and `netmod` on a single node. Jenkins showed problem with `auto` as well.

**Comment by hzhou** [comment]
@sagarth I am not able to reproduce this. There are too many irrelevant configure options and variables. Could you narrow it down until we find the minimum condition? That should help me pin it down.

**Comment by sagarth** [comment]
This failure was under the same config as: https://github.com/pmodels/mpich/issues/5627. I think https://github.com/pmodels/mpich/pull/5634 should have fixed this issue as well. I did some local testing with those patches and this test passed.

**Comment by hzhou** [comment]
> 
> 
> This failure was under the same config as: #5627. I think #5634 should have fixed this issue as well. I did some local testing with those patches and this test passed.

Sounds good. Feel free to close issue once you confirm with testing.

**Comment by sagarth** [comment]
It is passing. However, I noticed one difference that under vci=4 (compared to vci=1), it is taking longer to complete, after printing `No Error`.
