### ISSUE TITLE
coll tests failing during init under multi-vci + psm2

### ISSUE THREAD

**Issue by sagarth** [pmodels/mpich#5631]
Multiple coll tests failing during init.
```
## node05.36041hfp_gen1_context_open: hfi_userinit_internal: failed, trying again (3/3)
## node05.36041hfi_userinit_internal: assign_context command failed: Device or resource busy
## node05.36041PSM2 can't open hfi unit: 0 (err=23)
## Abort(874631311): Fatal error in internal_Init_thread: Other MPI error, error stack:
## internal_Init_thread(60).: MPI_Init_thread(argc=0x7ffc11be2ecc, argv=0x7ffc11be2ec0, required=0, provided=0x7ffc11be2ea0) failed
```
(Note: it has a similar underlying problem as the RMA bug(https://github.com/pmodels/mpich/issues/5591), but from different places in MPICH.)

It was observed with `Scalable Endpoints`, but it should probably replicate with `multiple domains` as well.

Tests:
```
./coll/nonblocking3 10 /coll/p_allgather 10 ./coll/bcast_comm_world_only 10 ./coll/allgather3 10 
```
```
MPIR_CVAR_ALLGATHER_DEVICE_COLLECTIVE=0 MPIR_CVAR_ALLGATHER_INTRA_ALGORITHM=nb ```
```
```
MPIR_CVAR_IALLGATHER_DEVICE_COLLECTIVE=0 MPIR_CVAR_IALLGATHER_INTRA_ALGORITHM=sched_brucks
```
Finding: the tests seemed to be trying to open too many endpoints than that were available. Therefore, they ran out the the ofi contexts. All these cases involve tests with a large number of ranks and 4 vcis. e.g., 10 ranks and 4 vcis.

Some thoughts for the resolution: 
When user tries to exceed the system limit for OFI endpoints, MPICH should probably not crash. It should instead fallback safely or exit gracefully with an informative error message.  We may need to define/track the system limit for the number of VCIs and then cap the VCI usage in MPICH to that value.

**Comment by hzhou** [comment]
Looks like psm provider limit `tx_ctx_cnt` and `rx_ctx_cnt` to the number cores on a node.

**Comment by hzhou** [comment]
Observation on Bebop, which has 36 hardware threads --

First process get `domain_attr->tx_ctx_cnt 36`, the next one gets `35`, and so on.

**Comment by hzhou** [comment]
> Some thoughts for the resolution:
> When user tries to exceed the system limit for OFI endpoints, MPICH should probably not crash. It should instead fallback safely or exit gracefully with an informative error message. We may need to define/track the system limit for the number of VCIs and then cap the VCI usage in MPICH to that value.

Note that MPICH didn't crash in this case, it is returning error and the default MPI error handler is aborting the application. 

While we could try track the system limit, but this limit is ultimately a provider specific behavior and any attempt on the MPICH side is taking assumptions that may change at some point.

We probably can update the error message to advise user that this is probably due to opening too many vci or simply launching too many processes on a single node.

**Comment by hzhou** [comment]
I am marking "wontfix" for now. Potentially we can improve the error message so user can understand the reason for failures. However, the `fi_endpoint/fi_scalable_ep` may fail for multiple reasons. In fact, libfabric itself only give very vague error message --
```
hfi_userinit_internal: assign_context command failed: Device or resource busy
```
So I am not sure we should provide a "guessed" reason to the user.

**Comment by sagarth** [comment]
> > Some thoughts for the resolution:
> > When user tries to exceed the system limit for OFI endpoints, MPICH should probably not crash. It should instead fallback safely or exit gracefully with an informative error message. We may need to define/track the system limit for the number of VCIs and then cap the VCI usage in MPICH to that value.
> 
> Note that MPICH didn't crash in this case, it is returning error and the default MPI error handler is aborting the application.
> 
> While we could try track the system limit, but this limit is ultimately a provider specific behavior and any attempt on the MPICH side is taking assumptions that may change at some point.
> 
> We probably can update the error message to advise user that this is probably due to opening too many vci or simply launching too many processes on a single node.

That's right. It is actually not a crash but we can possibly refine the error message (e.g., if we can detect that the error is coming because we crossed the system limit).

**Comment by hzhou** [comment]
I am going to close this issue. The error message is coming from lower layer due to system resource failure. To predict and control these errors at higher layer is not easy and likely adding undesirable complications -- it essentially asks to break the layer abstractions. Ultimately, this is a usage error, that we should improve our user documents to advise users.

**Comment by hzhou** [comment]
As for testing, I suggest either limit number of vcis or add those tests to xfails.
