### ISSUE TITLE
I/O Test Bigtype fails on NERSC Cori Lustre

### ISSUE THREAD

**Issue by QiaoK** [pmodels/mpich#5648]
These are the exact steps I reproduce this issue on Cori after login. In step 9, the program is copied to a Lustre folder, so the I/O driver used is Lustre. KNL node is used to run the job. Note I have tested ch4:ofi on OLCF Summit. In a GPFS folder, the same test passes. Therefore, I suspect it is a problem specific to Lustre or Cori.

0. module unload darshan
1. git clone git@github.com:pmodels/mpich.git
2. cd mpich
3. git submodule update --init
4. ./autogen.sh
5. ./configure --with-device=ch4:ofi:gni --with-file-system=lustre+ufs --with-pm=no --with-pmi=cray --enable-ugni-static CC=cc --disable-shared --prefix=$HOME/mpich_develop/mpich-install CFLAGS="-g"
6. make -j16;make install
7. cd test/mpi/io
8. make
9. srun -n 1 -c 4 --cpu_bind=cores ./bigtype
Abort(758764804) on node 0 (rank 0 in comm 0): Fatal error in internal_Irecv: Invalid tag, error stack:
internal_Irecv(123): MPI_Irecv(buf=(nil), count=1, dtype=USER<hindexed>, 0, 131100, comm=0x84000000, request=0x100001bed70) failed
internal_Irecv(79).: Invalid tag, value is 131100
srun: error: nid02665: task 0: Exited with exit code 4
srun: launch/slurm: _step_signal: Terminating StepId=49587353.11

**Comment by hzhou** [comment]
The tag `131100` (`0x2001c`) does look strange, it exceeds the safe limit mandated by MPI standard, which is 16 bits. If that tag is not due to corruption, then it must be due to the smaller tag limit on `gni`.

**Comment by wkliao** [comment]
https://github.com/pmodels/mpich/blob/180bf1d24fd9dd1f7993c9d688d064c2376b1580/src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c#L809-L810

Here is the only place that calls `MPI_Irecv` in ad_lustre driver.
For large I/O requests, two-phase I/O is performed in multiple rounds,
where `iter` is the round ID.

Argument `tag` in MPI_Irecv is of type `int`, but its value is bound by `MPI_TAG_UB`.
If the value of `iter` is large, `(myrank + i + 100 * iter)` may cause an
overflow of `MPI_TAG_UB`. Maybe it can be fixed by using the following?
```
 (myrank + i + 100 * iter) % MPI_TAG_UB
```
And of course, the same change should be applied to the two MPI_Issend calls in the file.

**Comment by hzhou** [comment]
Currently, GNI uses 20 tag_bits, but 2 bits are used for passing errors, and 1 bit used for mark collectives, so only 17 bits for users. `0x2001c` indeed exceeds that limit.

> Maybe it can be fixed by using the following?
>    (myrank + i + 100 * iter) % MPI_TAG_UB

It's worth a try. @QiaoK Could you test that?

But the formula seems a bit hacky. For example, `100` is very arbitrary.

**Comment by QiaoK** [comment]
I tried to replace all MPI_Irecv (along with MPI_Issend and MPI_Isend) calls's tag arguments with (myrank + i + 100 * iter) % MPI_TAG_UB in adio/ad_lustre/ad_lustre_wrcoll.c and adio/common/ad_read_coll.c.

Then I changed the modulus value from MPI_TAG_UB to 1024. The same issue happens. The Lustre setting is stripe count 4 and size 1M.

However, if I tune the Lustre stripe size to 16MB and count to 128. This issue disappears.

**Comment by wkliao** [comment]
I just realized the right way to get the value of `MPI_TAG_UB` is through a call to
`MPI_Comm_get_attr()`. For example,
```
int flag;
void *attribute_val;
MPI_Comm_get_attr(comm, MPI_TAG_UB, &attribute_val, &flag);
int tag_ub = *(int *) attribute_val;
```
Then use `tag_ub` in MPI_Irecv, MPI_Issend, etc.
```
(myrank + i + 100 * iter) % tag_ub
```

**Comment by wkliao** [comment]
In #3471 , `MPI_Isend` is replaced with `MPI_Issend` which limits the number
of pending send requests to one round of two-phase I/O, i.e. `nprocs`, the
number of processes. Thus we can safely change the tag to the sender's
rank `i` for MPI_Irecv and `my_rank` for MPI_Issend.
```
809     MPI_Irecv(MPI_BOTTOM, 1, recv_types[j], i, 
810                i, fd->comm, requests + j);

826     MPI_Issend(((char *) buf) + buf_idx[i], send_size[i],
827                 MPI_BYTE, i, myrank, fd->comm, send_req + j);

1027    MPI_Issend(send_buf[p], send_size[p], MPI_BYTE, p,
1028                myrank, fd->comm, requests + jj);
```

**Comment by wkliao** [comment]
> I tried to replace all MPI_Irecv (along with MPI_Issend and MPI_Isend) calls's tag arguments with (myrank + i + 100 * iter) % MPI_TAG_UB in adio/ad_lustre/ad_lustre_wrcoll.c and adio/common/ad_read_coll.c.
> 
> Then I changed the modulus value from MPI_TAG_UB to 1024. The same issue happens. The Lustre setting is stripe count 4 and size 1M.
> 
> However, if I tune the Lustre stripe size to 16MB and count to 128. This issue disappears.

The test program [bigtype.c](https://github.com/pmodels/mpich/blob/main/test/mpi/io/bigtype.c) writes 2 GIB in a single write call. When Lustre stripe size is 1 MiB and you only ran one process, the number of two-phase rounds is 2000, which makes (100 * 2000), bigger than the MPICH's limit, 131071.

**Comment by hzhou** [comment]
> In #3471 , `MPI_Isend` is replaced with `MPI_Issend` which limits the number
> of pending send requests to one round of two-phase I/O, i.e. `nprocs`, the
> number of processes. Thus we can safely change the tag to the sender's
> rank `i` for MPI_Irecv and `my_rank` for MPI_Issend.

#3471 is already merged (behind github), right? Does that mean we can safely change tag to the `rank` now? Also, do we even need set tag to the rank since different ranks are from a different sources and they won't be mismatched any way?

**Comment by wkliao** [comment]
MPI_ANY_TAG should do just fine.

**Comment by QiaoK** [comment]
By limiting the tag size, the test can pass. The problem is indeed caused by the overflow of tag values with thousands of rounds of collective loops.

**Comment by raffenet** [comment]
FWIW, MPI sets a minimum tag upper bound of 32k. If the tag value doesn't go over that, it should be portable to any implementation.
