### ISSUE TITLE
MPI_Neighbor_alltoallw() with MPI_BOTTOM

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5661]
I recently added some test to mpi4py that involve using `MPI_Neighbor_alltoallw()` and `MPI_BOTTOM`. I basically pass `MPI_BOTTOM` in the send/recv buffer arguments, and I pass the base address plus offset via the displacement array.

With current `mpich/main` (configure with `--enable-fast=none --enable-g=all`) I'm getting the following failures:

```
internal_Neighbor_alltoallw(133): MPI_Neighbor_alltoallw(sendbuf=(nil), sendcounts=0x7fa62f5862a0, sdispls=0x7fa62f586240, sendtypes=0x7fa62f5864d0, recvbuf=(nil), recvcounts=0x7fa62f586500, rdispls=0x7fa62f586350, recvtypes=0x7fa62f586670, comm=0x84000000) failed
internal_Neighbor_alltoallw(83).: Null buffer pointer
```

Looking at MPICH source code, looks like the [`MPIR_ERRTEST_USERBUFFER`](https://github.com/pmodels/mpich/blob/main/src/include/mpir_err.h#L521) macro cannot support my use case, that is, pass `MPI_BOTTOM` as buffer and an absolute address via displacements. That's the root of the problem. Is my use case invalid? I have a similar test that involves `MPI_Alltoallw()` and user-defined struct datatypes with absolute addresses, and these tests are working just fine.

PS: I have not checked the non blocking variant `MPI_Ineighbor_alltoallw()`, it could be suffering of similar issues. I have a similar problem with the MPI-4 large-count variants.

**Comment by hzhou** [comment]
We'll discuss this use case. But I think it should be allowed since MPI let users use `MPI_BOTTOM` in the first place.

**Comment by hzhou** [comment]
@dalcinl Can you check if #5663 fixes the issue?

**Comment by dalcinl** [comment]
> We'll discuss this use case.

For your reference, this [MPI tutorial form HLRS](https://www.hlrs.de/about-us/media-publications/teaching-and-training-material/MPI-course-material/) has example code using `MPI_Neighbor_alltoallw()` exactly in the way I described.
In fact, I added support for this in mpi4py (mpi4py/mpi4py#137) to properly support the Python implementation of these tutorial examples.

@RolfRabenseifner FYI.

**Comment by dalcinl** [comment]
> Can you check if #5663 fixes the issue?

I see what you are doing, but prima facie, I 'm not sure I like it. Anyway, I'll test it and report back to you.

**Comment by dalcinl** [comment]
@hzhou Wouldn't it be better to embed the `disp == 0` logics within the `MPIR_ERRTEST_USERBUFFER()` macro by passing an additional `disp` argument to it? For now, you could keep the `disp == 0` logic to decide whether to perform or not the actual check, but in the future it could be extended to properly to the absolute address out of buf, disp, lb(datatype). This change will require to change the use of the macro elsewhere to pass a `0` value when there are no displacements involved in the MPI call.

**Comment by hzhou** [comment]
> @hzhou Wouldn't it be better to embed the `disp == 0` logics within the `MPIR_ERRTEST_USERBUFFER()` macro by passing an additional `disp` argument to it? For now, you could keep the `disp == 0` logic to decide whether to perform or not the actual check, but in the future it could be extended to properly to the absolute address out of buf, disp, lb(datatype). This change will require to change the use of the macro elsewhere to pass a `0` value when there are no displacements involved in the MPI call.

The point of `MPIR_ERRTEST_USERBUFFER` is only to catch the common case that user accidentally passes `NULL` to `buf`. To allow `MPI_BOTTOM`, we are only checking the case when `buf == 0 && true_lb == 0 && disp == 0`. Having `buf + disp + true_lb == 0` but one of them non zero is not a common error and it is not our intention to catch it early -- it will segfault down the path.
