### ISSUE TITLE
use -fallow-argument-mismatch automatically when necessary

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#5727]
I think MPI Fortran bindings require this behavior, so if MPICH configure detects that it is necessary, why not just automatically set the flags, rather than fail and force the user to do it.  Given the user has no option in this case, why bother asking?

```
checking whether flang allows mismatched arguments... yes, with -fallow-argument-mismatch
configure: error: The Fortran compiler flang does not accept programs that call the same routine with arguments of different types without the option -fallow-argument-mismatch.  Rerun configure with FCFLAGS=-fallow-argument-mismatch
```

**Comment by hzhou** [comment]
Hopefully https://github.com/pmodels/mpich/pull/5685 will obviate the need of this flag.
