### ISSUE TITLE
misc: resource leak problems

### ISSUE THREAD

**Issue by ryancaicse** [pmodels/mpich#5735]
`fclose(fileh_std) ` should be put before Line 83?
https://github.com/pmodels/mpich/blob/94b1cd6f060cafbf68d6d83ea551a8bcc8fcecd4/src/mpi/romio/test/external32.c#L89-L98

**Comment by ryancaicse** [comment]
Also, it seems `fclose(fp)` is missing in the method `MPIE_ReadMachines`.
https://github.com/pmodels/mpich/blob/94b1cd6f060cafbf68d6d83ea551a8bcc8fcecd4/src/pm/util/rm.c#L244-L254

**Comment by raffenet** [comment]
> `fclose(fileh_std) ` should be put before Line 83?
> 
> https://github.com/pmodels/mpich/blob/94b1cd6f060cafbf68d6d83ea551a8bcc8fcecd4/src/mpi/romio/test/external32.c#L89-L98

The file is opened in line 89. It looks OK to me. How are you detecting the leak?

**Comment by hzhou** [comment]
It leaks when it returns on line 93 due to an unexpected eof

**Comment by raffenet** [comment]
> It leaks when it returns on line 93 (I believe OP made a typo into 83) due to an unexpected eof

Ah, OK. That makes more sense.

**Comment by ryancaicse** [comment]
Yes, I made a typo. Thank you very much.
