### ISSUE TITLE
MPI_Send:MPID_nem_tcp_connpoll(1845): Communication error with rank 1: Connection refused

### ISSUE THREAD

**Issue by ReyRen** [pmodels/mpich#5762]
## Describe

The code I used is [tutorials/mpi-send-and-receive/send_recv.c.](https://github.com/mpitutorial/mpitutorial/blob/gh-pages/tutorials/mpi-send-and-receive/code/send_recv.c) But All I get is:
```
root@node4:~/mpiLab# ./run.py  send_recv
mpirun -n 4 -f host_file ./mpi-send-and-receive/send_recv
recv and send from processor node3, rank 0 out of 4 processors
recv and send from processor node3, rank 2 out of 4 processors
Fatal error in PMPI_Send: Unknown error class, error stack:
PMPI_Send(159).............: MPI_Send(buf=0x7fff0cdc72cc, count=1, MPI_INT, dest=1, tag=0, MPI_COMM_WORLD) failed
MPID_nem_tcp_connpoll(1845): Communication error with rank 1: Connection refused
```
host_file and ssh for passwordless all done.

I commented all of MPI_Send(), and MPI_Recv(), and my program worked. In other hand, I commented either MPI_Send() or MPI_Recv(), and I still got that error,

mpiexec --version
```
root@node4:~/mpiLab# mpiexec --version
HYDRA build details:
    Version:                                 3.3.2
    Release Date:                            Tue Nov 12 21:23:16 CST 2019
    CC:                              gcc
    CXX:                             g++
    F77:
    F90:
    Configure options:                       '--disable-option-checking' '--prefix=NONE' '--disable-fortran' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= -O2' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= -I/root/mpich-3.3.2/src/mpl/include -I/root/mpich-3.3.2/src/mpl/include -I/root/mpich-3.3.2/src/openpa/src -I/root/mpich-3.3.2/src/openpa/src -D_REENTRANT -I/root/mpich-3.3.2/src/mpi/romio/include' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:
    Demux engines available:                 poll select
```
uname -a
```
root@node4:~/mpiLab# uname -a 
Linux node4 5.4.0-92-generic #103~18.04.2-Ubuntu SMP Wed Dec 1 16:50:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I really cannot figure out why error occur.

I'd appreciate any help from you, thanks!

**Comment by hzhou** [comment]
The output does not match the provided test. For example, the message "recv and send from processor node3, rank 0 out of 4 processors" is not from the given source code.

**Comment by ReyRen** [comment]
> 

Yes,it is. This source code ran executed by a python script, which is [tutorials/run.py](https://github.com/mpitutorial/mpitutorial/blob/gh-pages/tutorials/run.py). 

thanks anyway, is there any clue can help me explain this error?

**Comment by hzhou** [comment]
Please try --
```
mpicc -o send_recv send_recv.c
mpirun -n 2 ./send_recv
```

**Comment by ReyRen** [comment]
> 
**root@node4:~/mpiLab/mpi-send-and-receive# mpirun -n 2 ./send_recv**
```
recv and send from processor node4, rank 1 out of 2 processors
recv and send from processor node4, rank 0 out of 2 processors
Process 1 received <Hello, there> from process 0
```
**root@node4:~/mpiLab/mpi-send-and-receive# mpirun -n 2 -f ../host_file ./send_recv**
```
recv and send from processor node3, rank 0 out of 2 processors
Fatal error in PMPI_Send: Unknown error class, error stack:
PMPI_Send(159).............: MPI_Send(buf=0x7fffe9e0c4d0, count=13, MPI_CHAR, dest=1, tag=99, MPI_COMM_WORLD) failed
MPID_nem_tcp_connpoll(1845): Communication error with rank 1: Connection refused
```
**root@node4:~/mpiLab/mpi-send-and-receive# cat ../host_file** 
```
node3
node4
```

**Comment by hzhou** [comment]
Is there a firewall between node3 and node4?

**Comment by ReyRen** [comment]
No. I commented all of MPI_Send(), and MPI_Recv(), and my program worked. In other hand, I commented either MPI_Send() or MPI_Recv(), and I still got that error.

**Comment by ReyRen** [comment]
No. I commented all of MPI_Send(), and MPI_Recv(), and my program worked. In other hand, I commented either MPI_Send() or MPI_Recv(), and I still got that error.

**Comment by hzhou** [comment]
If you don't do communication, the process doesn't need connect to each other. The error message says that the process is not able to establish connections. You can use `MPIR_CVAR_CH3_PORT_RANGE` to control the port process use to make connections: https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_How_do_I_control_which_ports_MPICH_uses.3F

**Comment by ReyRen** [comment]
> MPIR_CVAR_CH3_PORT_RANGE

I tried, the error still there. I don't thinks this is a port usable problem. 

I catch that. The error is because the hostname I specified in `host_file`  also exist in `/etc/hosts` with "127.0.0.1/127.0.1.1 node3/node4" . So, they would communicate with themselves when they try connecting with others. 

Thanks hzhou, I will close this one.
