### ISSUE TITLE
configure fails when combining clang and gfortran

### ISSUE THREAD

**Issue by haampie** [pmodels/mpich#5768]
I tried to compile mpich 3.4.2 with clang for C / C++ and gfortran for Fortran.

In some of the Fortran tests (e.g. checking Fortran integer size) a Fortran function calls a C function. The linker fails with 
> ```relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE```

I managed to reduce it to the following MWE:

conftest.c
```c
#include <stdio.h>
int cisize_(char *,char*);
int cisize_(char *i1p, char *i2p) {
    int isize_val=0;
    FILE *f = fopen("conftestval", "w");
    if (!f) return 1;
    isize_val = (int)(i2p - i1p);
    fprintf(f,"%d\n", isize_val);
    fclose(f);
    return 0;
}
```

conftest.f
```fortran
            program main
            integer a(2)
            integer irc, cisize
            irc = cisize(a(1),a(2))
            end
```

```console
$ clang -O2 -c conftest.c && gfortran -O2 -o conftest conftest.f conftest.o
/usr/bin/ld: conftest.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

It does work when the optimization flags are dropped, or when only gcc/gfortran are used (instead of mixing compilers):

```console
$ gcc -O2 -c conftest.c && gfortran -o conftest conftest.f conftest.o
$ clang -c conftest.c && gfortran -o conftest conftest.f conftest.o
```

Tried this with gcc 7 and 10 and clang 6 and 11 and binutils 2.30, 2.34, 2.37, all the same.

So, either mpich should drop the optimization flag in this conftest when compiling the C source, or it should add the fpic flag (the configure script tests for this flag anyways, so why not use it?)

**Comment by lindsayad** [comment]
I just hit this exact issue 👍
