### ISSUE TITLE
maint: produce testsuite tarball with release.pl

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5774]
Now that testsuite can be used independently, we should release separate tarballs just as we did for hydra.

**Comment by raffenet** [comment]
The `make dist` is supposed to work for the testsuite. It should be simple enough to add it to the release script. It's actually on the release wiki checklist to verify that it works, but I don't know if it has always been strictly followed.

**Comment by hzhou** [comment]
Maintaining the `dist` target is quite a burden as we constantly adding scripts and tests. On the other hand, build the tarball in release.pl is very simple. I am amending PR #5773 to cover this issue.
