### ISSUE TITLE
Sessions info thread level

### ISSUE THREAD

**Issue by VictorEijkhout** [pmodels/mpich#5786]
Somewhere in my private notes I have that there is an info key “mpi_thread_level_support” for MPI_Session_init.

However, the standard document (September 17 2021) says “thread_level”.

But the rc3 accepts the former, not the latter.

Where does the truth lie?

The only mention I could find of the longer name is issue 332 in the forum.

**Comment by hzhou** [comment]
@VictorEijkhout The truth always lies in the standard document. Thanks for reporting. We'll fix it.
