### ISSUE TITLE
mpich-4.0 option to disable F08

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#5793]
I have a box with python2 [but not python3]. And I get the following error:

```
./configure: line 4429: python3: not found
./configure[4429]: test: argument expected
configure: error: Python 3 is required but not found
configure: error: ./configure failed for test/mpi
```

Release notes has:
```
# Configure now optionally require Python 3 (when F08 is enabled).
```
I see the relevant configure options is:
```
  --enable-fortran=option - Control the level of Fortran support in the MPICH implementation.
        yes|all   - Enable all available Fortran implementations (F77, F90+)
        no|none   - No Fortran support
```

Perhaps there should be a way to say ` --enable-fortran=f90` for `f03` so that `f08` interface  build and requirements can skipped?

**Comment by hzhou** [comment]
Use `--enable-fortran=f90` to disable `f08` is not obvious to an unfamiliar user. How about we add a separate `--enable-f08` option so users can disable f08 specifically?

**Comment by raffenet** [comment]
> Use `--enable-fortran=f90` to disable `f08` is not obvious to an unfamiliar user. How about we add a separate `--enable-f08` option so users can disable f08 specifically?

Does that even work? We used to control the fortran bindings individually, but I believe all that was removed for a simple yes/no w/ detection.

**Comment by hzhou** [comment]
> > Use `--enable-fortran=f90` to disable `f08` is not obvious to an unfamiliar user. How about we add a separate `--enable-f08` option so users can disable f08 specifically?
> 
> Does that even work? We used to control the fortran bindings individually, but I believe all that was removed for a simple yes/no w/ detection.

I am in the process of PR #5794, which become a bigger than expected clean-up, and we'll see if works :)

The simplified scheme:
   * By default, enable every fortran interface, and run checks to disable f08 if compiler missing support
   * All fortran options is to let user selectively disable features
       * --disable-fortran: disable everything fortran, no fortran compiler needed
          otherwise, FC compiler will be checked and required. We only require and always require F90 compiler. In addition --
           * --disable-f77: disable `mpif.h` interface
           * --disable-f90: disable `use mpi` interface
           * --disable-f08: disable `use mpi_f08` interface
  Currently, the f90 interface will require f77 interface, which we will check. But all other combinations should be okay.

**Comment by raffenet** [comment]
We should try to match the options that were removed in this commit e9b1a32566703e729d37530e1617d53764c1c100.

**Comment by hzhou** [comment]
> We should try to match the options that were removed in this commit [e9b1a32](https://github.com/pmodels/mpich/commit/e9b1a32566703e729d37530e1617d53764c1c100).

Previously `--enable-fortran={yes,all,f90}` means the same, and `--enable-fortran=f77` means only build `mpif.h`.

**Comment by raffenet** [comment]
In MPICH 4.0.1 (https://github.com/pmodels/mpich/releases/tag/v4.0.1), you can use `--disable-f08` and `--disable-collalgo-tests` to avoid any Python 3 dependencies at configure time.
