### ISSUE TITLE
MPI_Comm_compare fails with world/session commworld if single process

### ISSUE THREAD

**Issue by VictorEijkhout** [pmodels/mpich#5805]
The attached code works fine on more than one process, but with 1 process:
```
Abort(804863237): Fatal error in internal_Comm_compare: Invalid communicator, error stack:
internal_Comm_compare(88): MPI_Comm_compare(MPI_COMM_WORLD, comm=0x84000000, result=0x7ffee440d8d8) failed
```
[mix.zip](https://github.com/pmodels/mpich/files/7945748/mix.zip)

**Comment by hzhou** [comment]
Thanks. PR #5806 should fix this.

By the way, are you sure we are allowed to mix communicators from a session with world model? I believe the intention for session is to provide isolation. I.e. the code within a session is not supposed to interact with objects from another session or world model. Although our current implementation took a shortcut and does not enforce this isolation, future implementations may do.

**Comment by VictorEijkhout** [comment]
On , 2022Jan26, at 22:18, Hui Zhou ***@***.******@***.***>> wrote:

are you sure we are allowed to mix communicators from a session with world model?

Good question. The standard says that multiple sessions, or the world model and session model, may b active at the same time, but also that “MPI objects derive from the Sessions Model shall not be intermixed in a single MPI procedure call with MPI objects derived from the World Model”. I’ll need to ask for clarification, but maybe what I’m doing is illegal.

Victor.
