### ISSUE TITLE
Duplicate symbol linker error with versions >3.3.2

### ISSUE THREAD

**Issue by dpuleri** [pmodels/mpich#5808]
With newer versions of mpich (>3.3.2) on macOS, such as 4.0, I get linker errors that look like the following:

```
duplicate symbol '_abs_integer' in:
    ./internal/lib.a(file1.o)
    ./internal/lib.a(file2.o)
```

My colleagues who use older versions of mpich (e.g., 3.3.2) do not run into the linker error compiling the same code. Additionally, the code compiles under openMPI and under different compilers on other x86 and POWER9 systems.

My compiler configuration when using `mpixx -show` shows the following:
```
clang++ -Wno-deprecated -g -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/mpich/4.0/include -L/usr/local/Cellar/mpich/4.0/lib -lmpicxx -lmpi -lpmpi
```

I apologize for not including a minimum reproducible example. Simple programs such as an MPI hello world program do work. I am just trying to see if there was an obvious change or option that I missed during the upgrade process. If this is too vague, I can work on trying to get a smaller reproducible example working for the issue.

For what it's worth, I also experienced the same issue with 3.4.x releases, but I was able to downgrade easily and punt the linker issue.

**Comment by hzhou** [comment]
Try `--enable-two-level-namespace` when configuring mpich. Or try delete the `-Wl,-flat_namespace` from the installed `mpixx` scripts.

Reference issue: https://github.com/pmodels/mpich/issues/5530

`-Wl,-flat_namespace` is used so another Fortran dynamic library that uses MPI can have consistent MPI constants resolution. Unfortunately, this also has the side effects of sometimes users wanting to use two libraries with same symbol and do not wish them to be shared, such as the case you encountered.

We probably need re-evaluate and not to enable `-Wl,-flat_namespace` by default.

**Comment by dpuleri** [comment]
Thanks for the help and the references to those previous issues!

I deleted `-Wl,-flat_namespace` from the installed `mpicc` and `mpicxx` scripts on my machine, but that didn't seem to resolve the issue. Would it be best if I reinstalled mpich using the two-level namespace option? I originally installed from homebrew so I am not sure if I will need to build form source to enable that option.

**Comment by hzhou** [comment]
> --- quote ----
```
 duplicate symbol '_abs_integer' in:
    ./internal/lib.a(file1.o)
    ./internal/lib.a(file2.o)
```
> 

Re-reading your issue, I realize maybe this is different since apparently you are doing static linking. Is `lib.a` one of your own static library? Is it Fortran library or C library?

**Comment by dpuleri** [comment]
Yes, `lib.a` is our own static library primarily in C which we link up to our main code that is primarily in C++. There is no Fortran linked in or in the main code.

**Comment by hzhou** [comment]
How is `_abs_integer` defined?

**Comment by dpuleri** [comment]
Okay, I think I figured it out.

`_abs_integer` comes from an inline function in a C header file which is properly guarded and included in multiple C source files within our C library which we link in to the rest of our C++ code.

Looking again at output for `mpicc -show`, I saw that `-fgnu89-inline` is there for mpich 4.0.

```
clang -fgnu89-inline -Wno-deprecated -g -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/mpich/4.0/include -L/usr/local/Cellar/mpich/4.0/lib -lmpi -lpmpi
```

I tried deleting that compiler option and once I delete that from the `mpicc` script I'm able to compile the code.

When I look back at `mpicc -show` for mpich 3.2.X (and I assume it is similar for 3.3.X, which previously worked for me), it looks like the `-fgnu89-inline` option is not there:

```
clang -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/mpich/3.2_3/include -L/usr/local/Cellar/mpich/3.2_3/lib -lmpi -lpmpi
```

It seems like that option (`-fgnu89-inline`) enables some previous C inlining syntax which renders our code invalid and overrides the `-std=gnu99` option we pass to `mpicc` in our makefile.

**Comment by hzhou** [comment]
I see. I guess we enabled that as default optimization since our code's performance is significant depending on inlining. However, that CFLAGS shouldn't leaked the `mpicc` wrappers. We'll patch it. Thanks for the digging!

**Comment by dpuleri** [comment]
No problem, thank you for your patience when discussing.

**Comment by hzhou** [comment]
@dpuleri Actually I can't locate where `-fgnu89-inline` and `-wno-deprecated` flags were added. How did you configure mpich? What are your `CC` and `CFLAGS` variables?

**Comment by dpuleri** [comment]
@hzhou. I also searched the repo here and couldn't find references to `-fgnu89-inline`. I installed mpich through homebrew on macos using the [current formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mpich.rb).

I'm not sure who maintains the formula for homebrew, but now I see that it's in that formula at [line 73](https://github.com/Homebrew/homebrew-core/blob/c12a1c4fed7c93100319e21595009abbca75adc9/Formula/mpich.rb#L73) that `-fgnu89-inline` and `-wno-deprecated` are set.

According to homebrew's git blame it was added to their formula through commit [082afa9578](https://github.com/Homebrew/homebrew-core/commit/082afa95784a6f7db11e49efab93435a46ba5c23). The timing on this commit also tracks with roughly when I first noticed this breaking my builds after a fresh install of mpich via homebrew.

**Comment by hzhou** [comment]
That makes sense. Thanks for tracing it down.

**Comment by dpuleri** [comment]
Would you all mind if I submitted a pull request to homebrew to remove `-fgnu89-inline` and `-wno-deprecated` from the build configuration?

**Comment by hzhou** [comment]
> Would you all mind if I submitted a pull request to homebrew to remove `-fgnu89-inline` and `-wno-deprecated` from the build configuration?

Not at all. I am curious why they added the flags in the first place.

**Comment by dpuleri** [comment]
Perfect, thanks again! I'll close the issue here.

**Comment by carlocab** [comment]
Those flags were actually added in https://github.com/Homebrew/homebrew-core/commit/4147fa2734ee1aaae7fc3fff73a4eec832471333#diff-149934847c28be6d1b8561b848f1defe5f1d725f788493a8ca0d5f6e4fdb8b1a -- my understanding at the time was this was needed to compile MPICH on ARM macOS.

Either I was mistaken or they're no longer necessary with the newer GCC. Thanks for the fix, @dpuleri.
