### ISSUE TITLE
doc: manpages showing wrong function signature

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#5821]
Example from MPICH 4.0 HTML docs https://www.mpich.org/static/docs/latest/www3/MPI_Send.html:
```
#ifdef ENABLE_QMPI
#ifndef MPICH_MPI_FROM_PMPI
int QMPI_Send(QMPI_Context context, int tool_id, const void *buf, int count, MPI_Datatype datatype,
              int dest, int tag, MPI_Comm comm) MPICH_API_PUBLIC
```

**Comment by hzhou** [comment]
I can do a quick patch. But really, I think we should generate the man pages separately. Mixing it with code is really not providing us any benefit.
