### ISSUE TITLE
MPI_Comm_spawn in Slurm environment

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#5835]
Originated from user email https://lists.mpich.org/pipermail/discuss/2022-January/006360.html.

~1. MPICH + Hydra + PMI1 (crashes)~ Fixed in #5838
~2. MPICH + Hydra + PMI2 (works but ignores "hosts" info key)~ Fixed in #5849.
3. MPICH + srun + PMI2 (crashes)

**Comment by raffenet** [comment]
More details:
> 1. MPICH + Hydra + PMI1 (crashes)
  Crashes during `MPIDU_Init_shm_init();` in the spawned root process.
> 2. MPICH + Hydra + PMI2 (works but ignores "hosts" info key)
> 3. MPICH + srun + PMI2 (crashes)
    PMI2 Spawn is not supported. Both of these configurations will call `MPIR_Assert(0);` in src/util/mpir_pmi.c.

**Comment by hzhou** [comment]
Attach the console output

**Comment by raffenet** [comment]
From what I can tell, not all the nodes are able to launch proxies via ssh, so the processes that did launch are waiting in PMI_Barrier. I recommended `-launcher ssh` because using the default (srun) was throwing an error
```
    srun: Job 84993 step creation temporarily disabled, retrying (Requested nodes are busy)
```
It would be preferable to launch using the default, but we might be missing an option. Or there needs to be a configuration change.

**Comment by hzhou** [comment]
> From what I can tell, not all the nodes are able to launch proxies via ssh, so the processes that did launch are waiting in PMI_Barrier. I recommended `-launcher ssh` because using the default (srun) was throwing an error
> 
> ```
>     srun: Job 84993 step creation temporarily disabled, retrying (Requested nodes are busy)
> ```
> 
> It would be preferable to launch using the default, but we might be missing an option. Or there needs to be a configuration change.

When user do `mpiexec -np 20 ...`, hydra will launch 1 proxy on each of the node, right? So hydra could simply launch the new spawned process using the existing proxy rather than spawning new one, right? If the above message is from `mpiexec` launch a new `proxy`, I guess that means user's slurm setting is preventing `srun` more than 1 job on a given node.
