### ISSUE TITLE
4.0: Did not detect mismatched length or operator

### ISSUE THREAD

**Issue by Dave-Allured** [pmodels/mpich#5836]
I am trying to make a simple MPICH install on a 6-core Mac Pro running OSX 10.15.7.  This is for single-machine development, in preparation for a cluster deployment elsewhere.  I chose version 4.0 because the advertising sounded good.  Configure, make, and make install all seemed okay.  Make testing had a few failures.

Here are a few summary excerpts from **make testing**.  I have also attached a few log files with more details.  If you want more logs, please ask.

> (stdout:)  11 tests failed out of 2397
> 
> not ok  - ./errors/coll/reducelength 4 # time=0.131087064743042
> not ok  - ./errors/coll/ireducelength 4 # time=0.387104034423828
> not ok  - ./errors/coll/allreducelength 4 # time=0.14030385017395
> not ok  - ./errors/coll/iallreducelength 4 # time=0.127835035324097
> not ok  - ./errors/coll/reduceop 4 # time=0.128582000732422
> not ok  - ./errors/coll/ireduceop 4 # time=0.122575044631958
> not ok  - ./errors/coll/scatterlength 4 # time=180.111453056335
> not ok  - ./errors/coll/iscatterlength 4 # time=180.565916061401
> not ok  - ./errors/coll/allgatherlength 4 # time=0.20492696762085
> not ok  - ./errors/coll/iallgatherlength 4 # time=0.120985984802246
> not ok  - ./errors/coll/alltoalllength 4 # time=0.131322145462036

9 of these 11 cases started with "Did not detect mismatched length".
2 of these 11 cases started with:  "Did not detect mismatched operator".

Two of the length cases also resulted in assertion failure and timeout.

I assume that these are bugs worth reporting.  However, I am brand new to MPICH.  If you have any advice to avoid these errors, or to generally improve a single-machine install, please let me know.  Thanks.
[configure.mpich.0206a.path.log.txt](https://github.com/pmodels/mpich/files/8019784/configure.mpich.0206a.path.log.txt)
[make-testing.0206a.log.txt](https://github.com/pmodels/mpich/files/8019785/make-testing.0206a.log.txt)
[summary.tap.txt](https://github.com/pmodels/mpich/files/8019787/summary.tap.txt)

**Comment by Dave-Allured** [comment]
Oh, this might be relevant, although I would guess it is only a coincidence.  My selected compiler was Apple clang version 12.0.0 by default.  I had to use these configure flags to fix some compile errors.

> FCFLAGS=-fallow-argument-mismatch
> FFLAGS=-fallow-argument-mismatch

Other than a non-default prefix, these were the only special customizations that I used.  Everything else was a "default" install of MPICH.

**Comment by hzhou** [comment]
The collective length tests are known failures. These tests try to detect user errors due to inconsistent collective usage. The MPI standard does not require implementations to detect usage errors, thus we do not consider them as bugs. The tests are added to test this feature, but it is incomplete yet. We probably should disable these implementation-specific tests by default.

This has been tracked here: https://github.com/pmodels/mpich/issues/3775

**Comment by Dave-Allured** [comment]
@hzhou, thank you for the quick reply.  I should have tried harder to find these failures on Github.  Rather than disabling these tests, I suggest adding a log file comment line for each of these 11 tests, that simply informs the user that these are expected possible failures.

Knowing this, it looks like my install of MPICH 4.0 on OSX 10.15.7 is successful.
