### ISSUE TITLE
testsuite: missing include/mtest_mpix.h

### ISSUE THREAD

**Issue by phil-blain** [pmodels/mpich#5841]
Hi ! 

I'm not sure if this is actually a bug or "working as designed", but I thought I'd mention it.

I cloned the MPICH repository to run the test suite against Intel MPI. I then followed these steps:
~~~bash
cd mpich/test/mpi
# notice there is an 'autogen.sh'
./autogen.sh
./configure
make testing
~~~

The compilation of test programs then fails because of a missing `include/mtest_mpix.h`. 

I then went and read https://wiki.mpich.org/mpich/index.php/Getting_And_Building_MPICH, ran the top-level `autogen.h`, and the missing header was generated.

Is that intended ? Would it make sense for [`test/mpi/README`](https://github.com/pmodels/mpich/tree/main/test/mpi#readme) to mention that step?

Thanks for a great test suite that immediately provided us with a reproducer for a bug in Intel MPI!:D

**Comment by phil-blain** [comment]
Thanks for the quick response! :)

**Comment by hzhou** [comment]
Hi Philippe, `configure` will detect the supported mpi versions and set `MPI_VERSION` and `MPI_SUBVERSION` in the config header, and the tests use new API is supposed to guard with the version macros. Apparently, we didn't do a good job keeping consistent this practice. Please file separate issues and we will fix them.
