### ISSUE TITLE
romio: Need support large count functions

### ISSUE THREAD

**Issue by tjhei** [pmodels/mpich#5866]
I wanted to try out the new ``MPI_File_write_ordered_c`` with a ``count`` larger than the size of the maximum signed int. With release 4.0 I am hitting the assert
```
mpi-io/write_ord.c:86: PMPI_File_write_ordered_c: Assertion `count <= INT_MAX' failed
```
It still exists in master today here:
https://github.com/pmodels/mpich/blob/908c021ce04359826086518e4accf4fb603fffd8/src/mpi/romio/mpi-io/write_ord.c#L86
It looks like the code just forwards to ``MPI_File_write_ordered``, which can not handle larger count directly.

Is this known/documented somewhere, which of the "_c" set of function is implemented correctly? I am sorry if I missed this.

**Comment by hzhou** [comment]
cc @roblatham00

**Comment by jeffhammond** [comment]
I thought Rob took care of most/all the internal count issues with ROMIO when we wrote the BigMPI paper.  One can always test it for internal correctness using the BigMPI concept, i.e. user-defined datatypes that contain more than `INT_MAX` elements.

**Comment by tjhei** [comment]
Using a custom data type with more than 2^31 elements works correctly, but using the MPI_File_*_c functions with a bigger count directly does not.

**Comment by jeffhammond** [comment]
That means the asserts are _probably_ unnecessary, or mostly so.

**Comment by hzhou** [comment]
Many of the higher level internal functions are still using `int`, for example 
```
int MPIOI_File_write_ordered(MPI_File fh, const void *buf, int count,
                             MPI_Datatype datatype, MPI_Status * status);
```
Someone need spend the time convert all those signatures. Feel free ping us every once a while to give us some needed pressure :)
