### ISSUE TITLE
fortran: missing ELEMENTAL in eq/neq operator functions

### ISSUE THREAD

**Issue by sfilippone** [pmodels/mpich#5875]
Please see discussion at 
https://github.com/open-mpi/ompi/issues/10057
and 
https://lists.mpi-forum.org/pipermail/mpiwg-fortran/2022-March/003613.html

the same issue applies to MPICH (at least the versions I tried 3.4.1  from Fedora packaging, 3.4.3 from source, have not yet tried the latest)

Cheers
Salvatore

**Comment by hzhou** [comment]
@jsquyres Thanks for sharing with us. We'll take a look.

**Comment by hzhou** [comment]
@sfilippone Can you provide a simple Fortran test program?

**Comment by hzhou** [comment]
@sfilippone Thanks for the example and discussions over https://github.com/open-mpi/ompi/issues/10057. We'll fix it.

**Comment by jsquyres** [comment]
@hzhou You might want to wait for some comments from the Forum Fortran WG, per https://lists.mpi-forum.org/pipermail/mpiwg-fortran/2022-March/003613.html.  I'm not a Fortran expert, so I thought I'd ask the Rolfs of the world to see if there are any implications of adding ELEMENTAL.

**Comment by hzhou** [comment]
@jsquyres Sure. Meanwhile, it's easier to have a patch to test it out. I'll make a note to wait for the feedback before merging it.

**Comment by hzhou** [comment]
@sfilippone FWIW, I just tested the patch in PR #5876 against your example. As expected, adding `elemental` to the interface functions works as you suggested. We'll wait for the feedback from MPI Forum.
