### ISSUE TITLE
Unable to attach a debugger to a one process job.

### ISSUE THREAD

**Issue by knjmooney** [pmodels/mpich#5877]
Hi,

I'm trying to use the MPIR Acquisition Process Interface (https://www.mpi-forum.org/docs/mpir-specification-03-01-2018.pdf) to attach a debugger to a one process job.

Using the following program
``` 
#include <stddef.h>
#include<mpi.h>
int main()
{
  MPI_Init(NULL, NULL);
  MPI_Finalize();
}
```

Compile with 
```
 -> mpicc main.c
```

Launch 1 process by running the starter process to MPIR_Breakpoint, and then inspect MPIR_proctable for the pid of the MPI process.
```
 -> gdb -q -ex "break MPIR_Breakpoint" -ex "run -n 1 ./a.out" -ex "p *MPIR_proctable@1" mpirun 
Reading symbols from mpirun...done.
Breakpoint 1 at 0x456221: file ../../../../source/mpich-4.0.1/src/pm/hydra/tools/debugger/debugger.c, line 23.
Starting program: /home/user/mpich/install/bin/mpirun -n 1 ./a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Detaching after fork from child process 276114]

Breakpoint 1, MPIR_Breakpoint () at ../../../../source/mpich-4.0.1/src/pm/hydra/tools/debugger/debugger.c:23
23	    return 0;
$1 = {{host_name = 0x764590 "hostname", executable_name = 0x769a90 "./a.out", pid = 276115}}
```

With MPICH 3.2.1, I can now attach to the MPI process, with MPICH 4.0.1, the process has already run to completion before I can attach. 

If I repeat the above with more than 1 process and MPICH 4.0.1, the MPI processes are waiting inside `MPI_Init`/`MPIR_pmi_barrier` when I attach.

**Comment by knjmooney** [comment]
Hmm, I'm reproducing on multiple machines. Did you try to connect to
pid 3297984
after printing MPIR_proctable (the pid of a.out)? That's where the issue
is, a.out should be held inside MPI_Init.

**Comment by hzhou** [comment]
I see. Could you try set the environment variable `MPIR_CVAR_DEBUG_HOLD=1`? That shouuld hold the MPI process in a busy loop. Once you attach to the process, you can set `hold=0` to proceed.

**Comment by knjmooney** [comment]
That sounds promising. I'm away atm, but I will try on Monday.

Thank you,
Kevin

**Comment by knjmooney** [comment]
I tried the above. The environment variable holds the process, but unfortunately, after attaching to a.out, there are no debug symbols (I used the default configuration options), so I can't set hold to 0. 

To give some context, this is for Arm Forge, a debug and profiling tool. We'd be aiming for a solution that avoids any special configuration. If MPIR_CVAR_DEBUG_HOLD is the preferred way for a debug tool to attach, I propose we move MPII_debugger_hold out into a separate file that is always built with debug symbols.

**Comment by hzhou** [comment]
I always assumed if a user wants to debug his application, he would either build or link to a library with debug symbols. I am not sure there is a (clean) way to just add debug symbols for a single file. And even if there is, it can't prevent systems to strip their libraries. 

@knjmooney Is there a better mechanism that you may suggest to hold a process?

**Comment by hzhou** [comment]
Maybe we can expose, e.g. `MPII_Debug_continue()`?

**Comment by knjmooney** [comment]
> @knjmooney Is there a better mechanism that you may suggest to hold a process?
My understanding is that MPAI (https://www.mpi-forum.org/docs/mpir-specification-03-01-2018.pdf) is the semi-standard way to attach a tool to an MPI process. This is how we do it with other MPIs, previous versions of MPICH, and MPICH 4 when attaching to more than 1 process. I understand it's non-trivial to support MPAI, especially as there are likely no tests considering it's not working atm.

> Maybe we can expose, e.g. MPII_Debug_continue()?
This sounds like a nice and easy alternative.

**Comment by hzhou** [comment]
Looks like `MPIR_CVAR_DEBUG_HOLD` is a separate mechanism from MPAI. Did you build mpich with `--enable-debuginfo`? The debugger support is only built with that option.

**Comment by knjmooney** [comment]
Configuring with `--enable-debuginfo`
* MPIR_CVAR method still doesn't work because gdb doesn't know about `here`
* MPIR_Breakpoint method still doesn't hold the process when there's only 1.

**Comment by hzhou** [comment]
Okay, I understand the issue now.

User break on `MPIR_Breakpoint` which pauses `mpiexec`. MPI_Processes that calls PMI calls that requires response from `mpiexec` will thus be held inside a poll loop waiting for PMI replies. In ch3, we call PMI_Barrier, which is were the PMI processes are being held. We don't always do that in ch4, thus the issue.

This mechanism will rely on a proper `PMI_Barrier`.

Patches coming.
