### ISSUE TITLE
Strange behaviour with MPI_F08

### ISSUE THREAD

**Issue by sfilippone** [pmodels/mpich#5880]
Hi there,
I am experiencing a very strange bug with MPICH 
The test code: 
```
program ta2a
  use mpi_f08
  type(mpi_comm) :: comm
  integer :: me, np, minfo
  integer, allocatable :: sdsz(:), rvsz(:)
  
  call mpi_init()
  comm = mpi_comm_world
  call mpi_comm_rank(comm,me)
  call mpi_comm_size(comm,np)

  allocate(sdsz(np), rvsz(np))
  rvsz = 0
  sdsz = 0
  sdsz(me+1) = 10
  
  write(*,*) me,' ',': rbounds before ',lbound(rvsz), ubound(rvsz)
  write(*,*) me,' ',': sbounds before ',lbound(sdsz), ubound(sdsz)
  call mpi_alltoall(sdsz,1,mpi_integer4,rvsz,1,mpi_integer4,comm,minfo)
  write(*,*) me,' ',': rbounds after  ',lbound(rvsz), ubound(rvsz)
  write(*,*) me,' ',': sbounds after  ',lbound(sdsz), ubound(sdsz)
  
  
  call mpi_finalize()

end program ta2a
```

**Comment by sfilippone** [comment]
The behaviour: 
```
[sfilippo@lagrange TMPIF08]$ rpm -q mpich
mpich-3.4.1-1.fc34.x86_64
[sfilippo@lagrange TMPIF08]$ rpm -q gcc-gfortran
gcc-gfortran-11.2.1-9.fc34.x86_64
[sfilippo@lagrange TMPIF08]$ mpifort -o ta2a ta2a.f90
[sfilippo@lagrange TMPIF08]$ mpirun -np 2 ./ta2a
           0  : rbounds before            1           2
           0  : sbounds before            1           2
           1  : rbounds before            1           2
           1  : sbounds before            1           2
           0  : rbounds after             0           1
           0  : sbounds after             0           1
           1  : rbounds after             0           1
           1  : sbounds after             0           1
```

**Comment by sfilippone** [comment]
There must be something wrong in the ALLTOALL code since it is altering the vector bounds, transforming a vector with range (1:2) into a vector with range (0:1) 
For reference, the same code behaves correctly with other MPI implementations (most notably, with OpenMPI)

**Comment by hzhou** [comment]
This is a known gfortran bug. It will be fixed in the next gcc release (gcc-12). Our `mpi_f08` interface utilizes the `CFI_cdesc_t` interface, which supports Fortran array slices.

Ref: https://github.com/pmodels/mpich/issues/4170, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104100

**Comment by hzhou** [comment]
As a workaround, try Intel compilers.

**Comment by sfilippone** [comment]
>

> This is a known gfortran bug. It will be fixed in the next gcc release (gcc-12). Our `mpi_f08` interface utilizes the `CFI_cdesc_t` interface, which supports Fortran array slices.
> 
> Ref: #4170, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104100

Ah, ok, makes sense
Thanks

**Comment by hzhou** [comment]
> As a workaround, try Intel compilers.

Or, if you are willing modify the code, use 0 for lower bound -- ugly, but at least that will allow gfortran to work.

**Comment by sfilippone** [comment]
> > As a workaround, try Intel compilers.
> 
> Or, if you are willing to modify the code, use 0 for lower bound -- ugly, but at least that will allow gfortran to work.

Don't worry, I'll figure it out
