### ISSUE TITLE
jenkins/bug: Partitioned pingping fails assertion

### ISSUE THREAD

**Issue by nitbhat** [pmodels/mpich#5882]
I saw this issue during our jenkins run and also locally. This was seen for a `ofi-psm2-gnu-noam-netmod-debug-nogpu-cpu-gpu-runtime-vci1-async-single-nopmix` build. 

Mpich configure line: `+ ./configure -C --prefix=/tmp/jenkins.tmp.pYXPlMO6/_inst --with-custom-version-string=drop45 --disable-ofi-domain -with-fwrapname=mpigf -with-file-system=ufs+nfs -enable-timer-type=linux86_cycle -with-assert-level=0 -enable-shared -enable-static -enable-error-messages=yes -enable-strict -enable-izem-queue -with-zm-prefix=yes -enable-fast=none -enable-g=all -enable-timing=runtime -enable-error-checking=all -enable-debuginfo -with-device=ch4:ofi -enable-handle-allocation=default -enable-threads=multiple -enable-ch4-netmod-inline=no -enable-ch4-shm-inline=no -enable-mpit-pvars=all --with-ch4-shmmods=none --enable-ch4-mt=runtime --enable-thread-cs=per-vci --with-libfabric=/opt/intel/csr/ofi/psm2-dynamic --disable-spawn --with-ch4-max-vcis=1 --without-ze 'MPICHLIB_CFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -Wall -mtune=generic -std=gnu99' 'MPICHLIB_CXXFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -Wall -mtune=generic' 'MPICHLIB_FCFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -mtune=generic -ffree-line-length-256' 'MPICHLIB_F77FLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -mtune=generic -ffree-line-length-256' 'MPICHLIB_LDFLAGS=-O0 -L/opt/intel/csr/ofi/psm2-dynamic/lib -L/opt/intel/csr/ofi/psm2-dynamic/lib64 -L/opt/intel/csr/lib64 -L/usr/lib64 -L/usr/lib64 -L/lib64 -msse2 -msse4.2 -mcrc32 -mavx512f -mtune=generic'`

Tests configure line: `./configure -C --with-mpi=/tmp/jenkins.tmp.pYXPlMO6/_inst --disable-perftest --disable-ft-tests --enable-collalgo-tests --enable-large-tests --disable-spawn --with-ch4-max-vcis=1 --without-ze 'MPICHLIB_CFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -Wall -mtune=generic -std=gnu99' 'MPICHLIB_CXXFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -Wall -mtune=generic' 'MPICHLIB_FCFLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -mtune=generic -ffree-line-length-256' 'MPICHLIB_F77FLAGS=  -msse2 -msse4.2 -mcrc32 -mavx512f -ggdb -mtune=generic -ffree-line-length-256' 'MPICHLIB_LDFLAGS=-O0 -L/opt/intel/csr/ofi/psm2-dynamic/lib -L/opt/intel/csr/ofi/psm2-dynamic/lib64 -L/opt/intel/csr/lib64 -L/usr/lib64 -L/usr/lib64 -L/lib64 -msse2 -msse4.2 -mcrc32 -mavx512f -mtune=generic'`

```
 /home/nkbhat/mpich_anl/build/psm2-gnu/install/bin/mpiexec -n 2    ./pingping -type=MPI_INT -sendcnt=65530 -recvcnt=131060 -seed=106 -testsize=8
Unexpected output in pingping: pingping: ../../../../test/mpi/util/mtest_common.c:362: MTestAlloc: Assertion `zerr == ZE_RESULT_SUCCESS' failed.
Unexpected output in pingping: pingping: ../../../../test/mpi/util/mtest_common.c:362: MTestAlloc: Assertion `zerr == ZE_RESULT_SUCCESS' failed.
Unexpected output in pingping:
Unexpected output in pingping: ===================================================================================
Unexpected output in pingping: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
Unexpected output in pingping: =   PID 43741 RUNNING AT node01
Unexpected output in pingping: =   EXIT CODE: 134
Unexpected output in pingping: =   CLEANING UP REMAINING PROCESSES
Unexpected output in pingping: =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
Unexpected output in pingping: ===================================================================================
Unexpected output in pingping: YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
Unexpected output in pingping: This typically refers to a problem with your application.
Unexpected output in pingping: Please see the FAQ page for debugging suggestions
Program pingping exited without No Errors
```

**Comment by hzhou** [comment]
@nitbhat Please provide `test/mpi/config.log`

**Comment by nitbhat** [comment]
I ran this test again locally and through jenkins, and I am not seeing it show up. I'm wondering if there was something else that was wrong on our end. I'll keep an eye out for this bug if it shows up again. I'll close it for now.
