### ISSUE TITLE
Level Zero structures must be properly initialized

### ISSUE THREAD

**Issue by Kerilk** [pmodels/mpich#5890]
Hello,

The fields `stype` and `pNext` of level zero structures that contain them must be initialized before passing them to the runtime.
This initialization is missing here:
https://github.com/pmodels/mpich/blob/8c779ac7d973b9f1c959bf76c57a58a20ba5ba76/src/mpl/src/gpu/mpl_gpu_ze.c#L114-L115
and there:
https://github.com/pmodels/mpich/blob/2ccf789c24663d3c780e622c27643be83f95beec/test/mpi/util/mtest_common.c#L388-L389

In this particular case, adding:
```c
device_properties.stype = ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES;
device_properties.pNext = NULL;
```
before each `zeDeviceGetProperties` should fix the issue.

Thanks,
Brice

**Comment by hzhou** [comment]
@Kerilk Do you want to contribute a pull request or would you rather we patch it and acknowledge?

**Comment by Kerilk** [comment]
I can make a pull request if this fix looks good to you.

**Comment by hzhou** [comment]
@zhenggb72 Requesting your review.
