### ISSUE TITLE
romio: hint to allow avoiding extraneous MPI_File_sync calls

### ISSUE THREAD

**Issue by adammoody** [pmodels/mpich#5902]
When not running with atomicity mode enabled, MPI data consistency semantics requires one to call ``MPI_File_sync`` to expose newly written data to make those bytes visible to other processes.  However, since ``MPI_File_sync`` implies an ``fsync()``, it can be expensive.  Additionally, on POSIX-complaint file systems like Lustre, it is not actually necessary to call ``MPI_File_sync`` to expose newly written data -- the bytes are visible to other processes immediately after returning from the write call.

Could we define a new MPI I/O hint that an application can use to query whether ``MPI_File_sync`` is required to expose data on a particular file system?

To write a portable MPI I/O application, the user would need to call ``MPI_File_sync`` either if the hint indicates that the underlying file system requires it or if the hint is not supported by the MPI library.  For a file system like Lustre, this hint could indicate to the user that it is not necessary to call ``MPI_File_sync`` to expose data.

The idea here is similar to the ``MPI_WIN_MODEL=SEPARATE/UNIFIED`` property defined in the MPI one-sided chapter, which one can use to avoid making window synchronization calls if the underlying system doesn't require it.

Regardless of the hint, it would always be required for one to call ``MPI_File_sync`` to actually sync data to disk for persistence.

**Comment by adammoody** [comment]
@roblatham00 , they can confirm, but I think this is something that I think the HDF team could use.

**Comment by houjun** [comment]
> @roblatham00 , they can confirm, but I think this is something that I think the HDF team could use.

Yes, I think a new hint indicating whether HDF5 should call MPI_File_sync after a write (e.g. when using UnifyFS ROMIO driver) is necessary to support UnifyFS in HDF5.

**Comment by roblatham00** [comment]
see https://github.com/pmodels/mpich/blob/main/src/mpi/romio/adio/common/ad_hints.c#L129  for one approach:  client code sets the hint, and ROMIO will respond either with "i don't know what that is" (by not adding it to the returned info object) or give the green light by setting it to "enabled"

Does the read-only hint  `romio_visibility_immediate`  (`true` or `false`) work for you?  Prefer a different name?

**Comment by adammoody** [comment]
Thanks, @roblatham00 .  That sounds good to me.  It makes sense to be a read-only hint with a ``true/false`` value.

Regarding a hint name, "visibility" matches well with the MPI text:

> Calling MPI_File_sync with fh causes all previous writes to fh by the calling process to be transferred to the storage device.  If other processes have made updates to the storage device, then all such updates become visible to subsequent reads of fh by the calling process.

@houjun , you could be the first to actually use this new hint.  What do you think?

**Comment by houjun** [comment]
Sounds good!

**Comment by hzhou** [comment]
Is this issue resolved?

**Comment by adammoody** [comment]
I think we're settled on a solution.  Should we keep the issue open until the hint is added?  I'm fine either way.

**Comment by hzhou** [comment]
@roblatham00 I thought the hint was already added. No?

**Comment by roblatham00** [comment]
@hzhou this is a separate issue.  We have a hint for the "synchronizing sync" behavior.  This hint would allow us to further separate "visibility" from "durability" .  As Adam points out, POSIX file systems provide more aggressive visibility than the MPI standard dictates.    If we're going to be stuck with stupid POSIX and its stupid consistency semantics, let's make some lemonade out of those lemons. 

When I land the new hint I'll close this issue.

**Comment by hzhou** [comment]
> @hzhou this is a separate issue. We have a hint for the "synchronizing sync" behavior. This hint would allow us to further separate "visibility" from "durability" . As Adam points out, POSIX file systems provide more aggressive visibility than the MPI standard dictates. If we're going to be stuck with stupid POSIX and its stupid consistency semantics, let's make some lemonade out of those lemons.
> 
> When I land the new hint I'll close this issue.

👍 Sounds good!

**Comment by adammoody** [comment]
While we're at it, the standard also says that ``MPI_File_close`` implies an ``MPI_File_sync``, which means closing the file also requires an ``fsync``.  It would be useful if we had a way to let a user declare that they don't actually require an ``fsync`` during ``MPI_File_close``.  Maybe another hint?

**Comment by roblatham00** [comment]
ADIO drivers are welcome to implement `ADIOI_xxx_Close` if they have a file system specific way of pushing cached items to the file system.    PVFS2 for example implements an empty function

**Comment by adammoody** [comment]
Oh, I was thinking the Lustre ADIO path had an ``fsync``, which is what I was trying to avoid with this "no-fsync-on-close" hint.

Though, I don't see an fsync in either:
https://github.com/pmodels/mpich/blob/main/src/mpi/romio/adio/common/ad_close.c
or:
https://github.com/pmodels/mpich/blob/main/src/mpi/romio/adio/common/adi_close.c

So nevermind.

**Comment by adammoody** [comment]
Just to spell out my reasoning that led to that confusion, the standard says that ``MPI_File_close`` implies an ``MPI_File_sync``:

> Both opening and closing a file implicitly perform an MPI_FILE_SYNC.

And I know the ``MPI_File_sync`` on Lustre calls ``fsync``.

**Comment by roblatham00** [comment]
@adammoody take a peek at https://github.com/roblatham00/mpich/commit/285c7805714984c25db9700ea50bd6d6071e5d0f and if it looks good to you i'll merge to mpich main

**Comment by adammoody** [comment]
Looks good to me.  Thanks, @roblatham00 .
