### ISSUE TITLE
unknown type name ‘regex_t’ compiling slurm_query_node_list.c

### ISSUE THREAD

**Issue by Mengjintao** [pmodels/mpich#5936]
I download mpich-3.3.2.tar.gz and configure it with "./configure --enable-fortran=no". 
the "make" command is terminated with the following information.   Can you help me to fix this install issue? 

 CC       tools/bootstrap/external/slurm_query_node_list.lo
tools/bootstrap/external/slurm_query_node_list.c: In function ‘list_to_nodes’:
tools/bootstrap/external/slurm_query_node_list.c:55:5: error: unknown type name ‘regex_t’; did you mean ‘gregset_t’?
   55 |     regex_t gmatch_old[2];
      |     ^~~~~~~
      |     gregset_t
tools/bootstrap/external/slurm_query_node_list.c:56:5: error: unknown type name ‘regex_t’; did you mean ‘gregset_t’?
   56 |     regex_t gmatch_new[2];
      |     ^~~~~~~
      |     gregset_t
tools/bootstrap/external/slurm_query_node_list.c:57:5: error: unknown type name ‘regex_t’; did you mean ‘gregset_t’?
   57 |     regex_t rmatch_old;
      |     ^~~~~~~
      |     gregset_t

**Comment by hzhou** [comment]
Could you attach `src/pm/hydra/config.log`?

**Comment by Mengjintao** [comment]
Hi hzhou, 
     I just attached src/pm/hydra/config.log[config.log](https://github.com/pmodels/mpich/files/8469348/config.log)
     Please check, thanks for your reply. 

Jintao

**Comment by hzhou** [comment]
Try edit `src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c` line `12` , replace "HAVE_SLURM_SLURM_H" with "HAVE_LIBSLURM".

The later versions should have this fixed already.

**Comment by hzhou** [comment]
@Mengjintao Did you resolve this issue?

**Comment by hzhou** [comment]
Close due to lack of response.

**Comment by WwkChina** [comment]
> @Mengjintao Did you resolve this issue?

Hello, thank you for your method. This problem I have solved. Thanks very much.
