### ISSUE TITLE
Debug Event Logging Issue

### ISSUE THREAD

**Issue by Samg381** [pmodels/mpich#5964]
Hello all,

I have just built MPI from scratch in Linux with the -enable-g  flag enabled, and am looking to obtain the MPI log file for a python program I wrote.

Unfortunately, I receive the error “Could not open log file log/templog…” when using mpiexec to run the program.

I am executing the program with the following arguments: mpiexec -n 4 python3 test.py

Any assistance would be appreciated.

**Comment by hzhou** [comment]
Please read the guide on [debug event logging](https://wiki.mpich.org/mpich/index.php/Debug_Event_Logging). 

Did you set `MPICH_DBG_FILENAME` to `log/templog`? If so, make sure you have or create the `log` directory.

**Comment by Samg381** [comment]
Thank you for the prompt reply! I did read the guide, and I changed the `MPICH_DBG_FILENAME` environment variable to `log/templog`, however I do not know where to check for / create the `log` directory - could you point me to the right location? I am using Debian linux.

**Comment by hzhou** [comment]
You should create the `log` directory from your working directory -- where you launch `mpiexec`. You also could simply set `MPICH_DBG_FILENAME` to `templog`, then it should dump the log file to your current working directory.

**Comment by Samg381** [comment]
Thank you so much- very silly error on my part. I set the `MPICH_DBG_FILENAME` environment variable to `templog` and got the log file I was looking for! Really appreciate the help.

Now to dissect these logs...
