### ISSUE TITLE
Segmentation fault on Mrecv()

### ISSUE THREAD

**Issue by Piccions** [pmodels/mpich#5977]
MPICH 4.0.2 segfaults when Mrecv-ing an asynchronously sent message whose request has been freed.
I reproduced the bug both on MacOS Catalina and Ubuntu 20.

Here I include a minimal reproducer program.

```
#include <assert.h>
#include <mpi.h>
#include <stddef.h>

int main()
{
	int thread_lvl = MPI_THREAD_SINGLE;
	MPI_Init_thread(NULL, NULL, MPI_THREAD_MULTIPLE, &thread_lvl);
	assert(thread_lvl >= MPI_THREAD_MULTIPLE);

	const int dummy_data = 42;

	MPI_Request req;	
	MPI_Isend(&dummy_data, 1, MPI_INT, 0, 0, MPI_COMM_WORLD, &req);

	MPI_Request_free(&req);

	MPI_Message mpi_msg;
	MPI_Mprobe(0, 0, MPI_COMM_WORLD, &mpi_msg, MPI_STATUS_IGNORE);
	
	int recvd_data = 0;
	MPI_Mrecv(&recvd_data, 1, MPI_INT, &mpi_msg, MPI_STATUS_IGNORE);

	assert(recvd_data == dummy_data);
	
	MPI_Finalize();
}
```

**Comment by raffenet** [comment]
I'm pretty sure the bug is in the ch4 "self" protocol. If you send-recv between 2 different ranks, does the test succeed?

**Comment by Piccions** [comment]
Hello! Yes, the test does indeed succeed between two ranks.

**Comment by raffenet** [comment]
@Piccions thanks for the report and follow-up. I have created a PR that should fix the issue in `main`.

Would you allow us to adapt your reproducer code to our test suite? We'd require a signed contributors agreement, if so. See https://www.mpich.org/documentation/contributor-docs/.

**Comment by Piccions** [comment]
Sure, I just sent the completed form via email. Please, do as you wish with that small snippet of code.
Thanks for the extremely quick fix!
