### ISSUE TITLE
Some bugs when running mpiexec

### ISSUE THREAD

**Issue by pistachio-xin** [pmodels/mpich#5982]
Hi, everyone,
When I run the code 'mpiexec - n 90 ./lcode sampler.cfg', there are some bugs as following.
![image](https://user-images.githubusercontent.com/81011698/165917947-eedf9cc1-17c4-402e-993d-08099c7cce67.png)
Thank you very much If anyone can help me.

**Comment by hzhou** [comment]
Which MPICH release is this? Does it work with less processes? Could you try with the latest release (https://www.mpich.org/downloads/)?

**Comment by pistachio-xin** [comment]
Thank you a lot!
I will try the latest MPICH as you share.
Here is my MPICH release,
![image](https://user-images.githubusercontent.com/81011698/165954260-4f0f6234-1f83-422d-9145-3511a726db1f.png)
And maybe it is the main error:
![image](https://user-images.githubusercontent.com/81011698/165954432-dee3c93e-5667-4c45-9527-6e1ac6facd0f.png)

**Comment by hzhou** [comment]
You should contact Intel support for Intel MPI. We can help but we won't be able to resolve your issue.
