### ISSUE TITLE
[mpi4py] Regression in ch3 builds with indexed datatype test

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5995]
All builds: https://github.com/mpi4py/mpi4py-testing/actions/runs/2285899461

From one of the failing ch3 build logs:

```
testCreateIndexed (test_datatype.TestDatatype) ... Assertion failed in file src/mpi/datatype/typerep/dataloop/dataloop_create_indexed.c at line 253: cur_idx == contig_count - 1
```

**Comment by hzhou** [comment]
FYI: there were no changes to ch3 or datatype related last week in MPICH. Also, our nightly tests are clean -- https://jenkins-pmrs.cels.anl.gov/job/mpich-main-mpi4py/label=centos64,netmod=ch3-tcp/
We test from the default branch in https://github.com/mpi4py/mpi4py.

**Comment by dalcinl** [comment]
I found the problem, and I believe it is not mpi4py's fault.

My CI builds configure MPICH with `--disable-fortran`. However, in the installed `mpi.h` header file, I see the following:

```C
...
/* Fortran types */
#define MPI_COMPLEX           ((MPI_Datatype)MPI_DATATYPE_NULL)
#define MPI_DOUBLE_COMPLEX    ((MPI_Datatype)MPI_DATATYPE_NULL)
#define MPI_LOGICAL           ((MPI_Datatype)0x4c00001d)
#define MPI_REAL              ((MPI_Datatype)MPI_DATATYPE_NULL)
...
```

and there is the problem, `MPI_LOGICAL` is not the null datatype. mpi4py test suite is not prepared for non-null but non-functional predefined datatype with size zero:

```python
>>> from mpi4py import MPI
>>> MPI.LOGICAL == MPI.DATATYPE_NULL
False
>>> MPI.LOGICAL.Get_size()
0
```

Any chance this regression is an consequence of your changes in #5990 ?

**Comment by dalcinl** [comment]
Also, this probably means that something in ch3 is broken in `MPI_Type_indexed_c` for the case of zero-size datatypes. 

Here you have a reproducer:

```python
>>> from mpi4py import MPI
>>> tc = MPI.INT.Create_contiguous(0)
>>> ti = tc.Create_indexed([0, 1, 2, 3], [0, 1, 2, 3])
>>> ti.Commit()
Assertion failed in file ../src/mpi/datatype/typerep/dataloop/dataloop_create_indexed.c at line 253: cur_idx == contig_count - 1
```

**Comment by hzhou** [comment]
Ahh, indeed, the fault (with logical) is on us :) 

> Also, this probably means that something in ch3 is broken in MPI_Type_indexed_c for the case of zero-size datatypes.

I'll check. My gut feeling is that zero-size datatype shouldn't be allowed.

**Comment by hzhou** [comment]
Other than `MPI_Type_create_resized`, I think creating any other derived datatype based on a zero-sized datatype should result in a zero-sized datatype. I.e.  in `src/mpi/datatype/type_create.c`, we should check for base datatype size and return `MPII_Type_zerolen(newtype)` when base size is 0. @raffenet What do you think?

**Comment by dalcinl** [comment]
> Other than `MPI_Type_create_resized` ...

What about datatype decoding?

**Comment by hzhou** [comment]
> > Other than `MPI_Type_create_resized` ...
> 
> What about datatype decoding?

I guess you are referring to `MPI_Type_get_content`? That is separately maintained, and should be not be affected.
