### ISSUE TITLE
pt2pt: MPI_Isendrecv with MPI_PROC_NULL

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6004]
I'm adding missing tests for the MPI-4 `Comm.Isendrecv[_replace]` methods in mpi4py. 

Looks like the new MPI-4 routines `MPI_Isendrecv[_replace]_c`  from MPICH (maint branch) do not handle `MPI_PROC_NULL` properly. 

If you try to run the reproducer below, it deadlocks at the `Wait()` for the requests. If you comment out the line `src = dst = MPI.PROC_NULL`, the script finishes to completion.

```python
from mpi4py import MPI

comm = MPI.COMM_SELF

src = dst = 0
src = dst = MPI.PROC_NULL
comm.Isendrecv(bytearray(0), dst, 0, bytearray(0), src, 0).Wait()
print('Isendrecv OK')

comm.Isendrecv_replace(bytearray(0), dst, 0, src, 0).Wait()
print('Isendrecv_replace OK')
```

Carification: After gaining support for MPI-4,  mpi4py uses the large count APIs exclusively. Therefore, I do not know whether the issue I'm reporting also affect to the small count `MPI_Isendrecv[_replace]` routines.

**Comment by dalcinl** [comment]
Looks like the gforker+ch3 combination works, but not the others.
https://github.com/mpi4py/mpi4py-testing/actions/runs/2313993117

**Comment by hzhou** [comment]
Looks like we missed the case when both `src` and `dst` are `MPI_PROC_NULL`.
