### ISSUE TITLE
configure: automatically add -std=legacy to FFLAGS & FCFLAGS

### ISSUE THREAD

**Issue by ghost** [pmodels/mpich#6040]
Good afternoon,
Not sure if this has occurred or been talked about yet but on Ubuntu 22.04 there is a compiler error that occurs when using mpich 4.0.2
The error is:
"Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make: *** [Makefile:40: bio_emiss.o] Error 1"
The fix to this is to add the flag -std=legacy to FFLAGS & FCFLAGS.  

https://www.scivision.dev/gcc-gfortran-std-legacy/

This command allows FORTRAN to use old commands and syntax and changes it from a fatal error to just a warning.  It should be noted that with gfortran/gcc/g++ version 10 the new flag called -fallow-argument-mismatch was added that does a similar job.

https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html

However, this flag is only available to version 10 and above.  For older version of gfortran/gcc/g++ this flag will throw an error.

So my fix is to enter this command when configuring mpich
./configure --prefix=$DIR/MPICH --with-device=ch3 FFLAGS=-std=legacy FCFLAGS=-std=legacy

Not sure if this flag can be added in future release or a patch.

Regards,Will

**Comment by hzhou** [comment]
Which function in `bio_emiss` triggers the error? Is it using `include 'mpif.h'` or `use mpi`? Could you also verify `mpif77 -show` and `mpifort -show`?

**Comment by whatheway** [comment]
Not 100% certain what you are asking but I will include what I think you are asking...sorry not a programmer just a meteorologist.

My version of mpich is 4.0.2.

compilers: gfortran/gcc/g++ version 11.2.0
mpich built in directory $HOME/WRF/Libs
zlib v1.2.12
jasper 1.900.1 (only version supported by WRF)
libpng 1.6.37 (only version supported by WRF)

./make_util megan_bio_emiss

**Comment by whatheway** [comment]
Correction bio_emiss is for a different bug.  The one related to this topic.  Let me post the correct bug. I apologize

**Comment by whatheway** [comment]
[configure.output.txt](https://github.com/pmodels/mpich/files/8818893/configure.output.txt)

**Comment by whatheway** [comment]
However, I found that -fallow-argument-mismatch is only a GCC10 and above flag.  For GCC9 or less -std=legacy is the flag.  Also -std=legacy also is available in GCC10 and above.

**Comment by hzhou** [comment]
Also find `mpif77` and `mpifort` from your mpich installation directory then run
`path/to/mpif77 -show`
`path/to/mpifort -show`
and show the output.

**Comment by whatheway** [comment]
```
will@will-XPS-8940:~$ /home/will/WRFCHEM/Libs/MPICH/bin/mpif77 -show
gfortran -std=legacy -L/home/will/WRFCHEM/Libs/grib2/lib -I/home/will/WRFCHEM/Libs/MPICH/include -I/home/will/WRFCHEM/Libs/MPICH/include -L/home/will/WRFCHEM/Libs/MPICH/lib -lmpifort -Wl,-rpath -Wl,/home/will/WRFCHEM/Libs/MPICH/lib -Wl,--enable-new-dtags -lmpi
```
```
will@will-XPS-8940:~$ /home/will/WRFCHEM/Libs/MPICH/bin/mpifort -show
gfortran -std=legacy -L/home/will/WRFCHEM/Libs/grib2/lib -I/home/will/WRFCHEM/Libs/MPICH/include -I/home/will/WRFCHEM/Libs/MPICH/include -L/home/will/WRFCHEM/Libs/MPICH/lib -lmpifort -Wl,-rpath -Wl,/home/will/WRFCHEM/Libs/MPICH/lib -Wl,--enable-new-dtags -lmpi
will@will-XPS-8940:~$ 
```

**Comment by hzhou** [comment]
> [configure.output.txt](https://github.com/pmodels/mpich/files/8818893/configure.output.txt)

Oh, you are referring to the error in configure. Just rerun the configure as prompoted:
>> configure: error: The Fortran compiler gfortran does not accept programs that call the same routine with arguments of different types without the option -fallow-argument-mismatch.  Rerun configure with FFLAGS=-fallow-argument-mismatch and FCFLAGS=-fallow-argument-mismatch

**Comment by whatheway** [comment]
> > [configure.output.txt](https://github.com/pmodels/mpich/files/8818893/configure.output.txt)
> 
> Oh, you are referring to the error in configure. Just rerun the configure as prompoted:
> 
> > > configure: error: The Fortran compiler gfortran does not accept programs that call the same routine with arguments of different types without the option -fallow-argument-mismatch.  Rerun configure with FFLAGS=-fallow-argument-mismatch and FCFLAGS=-fallow-argument-mismatch

Sorry for the confusion.  I found that -fallow-argument-mismatch works only with gfortran/g++/gcc10+ for my gfortran/g++/gcc9 build I have to use -std=legacy.  

-std=legacy is compatible with all version of gfortran/gcc/g++ so my request is that be added to the FFLAGS & FCFLAGS by default so it runs without having to rerun the configure.

Again sorry for all the confusion.

**Comment by hzhou** [comment]
Adding these flags have consequences of compiling user Fortran code, not just mpich, that's why we do not automatically add these flags. User have to explicitly add them so they are aware of the consequence -- ignoring the argument checking.

We improved the logic in mpich-4.1a1 that we automatically add this flag in `mpif77` and removed the need of adding this flag in `mpifort`. If your source code is using the `mpif.h` interface , then you should compile your code using `mpif77`. If you are using `use mpi`, then you should use `mpifort`. The former is for legacy support, commonly in old F77 form. F90 code should use the `use mpi` module interface.
