### ISSUE TITLE
hydra: cannot build with PBS support

### ISSUE THREAD

**Issue by BenWibking** [pmodels/mpich#6049]
I tried to configure MPICH with `./configure --with-device=ch4:ucx --with-ucx=/apps/ucx/1.12.0 --with-pbs=/opt/pbs/default`, but it fails with:

```
checking for tm.h... yes
checking for tm_init in -ltorque... no
configure: error: --with-pbs is given but not found
```

This cluster uses PBS Pro... is that supported, or does PBS support in MPICH actually mean PBS/torque?

**Comment by BenWibking** [comment]
It looks like changing `torque` to `pbs` on this line https://github.com/pmodels/mpich/blob/dad7946b2df04f26f7edcb01e1da1bb01f4bfa2e/src/pm/hydra/configure.ac#L256

allows `configure` to succeed. This builds and appears to work fine with PBS Pro.

**Comment by hzhou** [comment]
> This cluster uses PBS Pro... is that supported, or does PBS support in MPICH actually mean PBS/torque?

As you discovered, that is the case. I guess we should probe both `-lpbs` and `-ltorque`.

**Comment by hzhou** [comment]
@BenWibking Would you be able to verify the fix in #6050?

**Comment by BenWibking** [comment]
It configures successfully:
```
checking tm.h usability... yes
checking tm.h presence... yes
checking for tm.h... yes
checking for library containing tm_init... -lpbs
```

but it also emits a spurious (?) warning message:
`configure: WARNING: unrecognized options: --with-pbs`

The build then fails:
```
gcc: error: pbs: No such file or directory
gcc: error: pbs: No such file or directory
gcc: error: pbs: No such file or directory
make[3]: *** [Makefile:1124: hydra_nameserver] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1137: hydra_persist] Error 1
make[3]: *** [Makefile:1157: hydra_pmi_proxy] Error 1
gcc: error: pbs: No such file or directory
make[3]: *** [Makefile:1185: mpiexec.hydra] Error 1
```

**Comment by hzhou** [comment]
@BenWibking The warning message of unrecognized options is spurious since that is passed down to `hydra`'s configure. I updated the patch in PR #6050, could you give it another try?

**Comment by BenWibking** [comment]
I still get:

```
configure: WARNING: unrecognized options: --with-pbs, --without-cuda
*****************************************************
***
*** device      : ch4:ucx
*** shm feature : auto xpmem
*** gpu support : disabled
***
*****************************************************
Configuration completed.
```

**Comment by hzhou** [comment]
That looks fine. Does `make` succeed?

**Comment by BenWibking** [comment]
Yes, it builds now.
