### ISSUE TITLE
mpich error in WRF installing

### ISSUE THREAD

**Issue by samyaghoubi** [pmodels/mpich#6053]
Hi 
I tried for installing mpich 4.0.2 but there was a configure error and was not built makefile for installing. my ubuntu version is 22.04 LTS. i have sent our error photo.
thanks
sam

[error-terminal.zip](https://github.com/pmodels/mpich/files/8883343/error-terminal.zip)

**Comment by hzhou** [comment]
Please try 
```
./configure FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch --prefix=...
```

**Comment by samyaghoubi** [comment]
Hi, dear hzhou
thanks so much. my problem was solved.you are excellent. where i can acquire information about this problem?
the best
sam

**Comment by hzhou** [comment]
The requirement of setting these flags has been removed in the development branch. For stable release, the error message should have stated what needs to do.

**Comment by hzhou** [comment]
@samyaghoubi Shall we close this issue?
