### ISSUE TITLE
bug: Memory leak in MPI_Irecv with strided datatype and MPI_ANY_SOURCE

### ISSUE THREAD

**Issue by oshkosher** [pmodels/mpich#6056]
In mpich-4.0.2 there seems to be a memory leak in MPI_Irecv when using
a strided datatype and MPI_ANY_SOURCE.

ZIP file with sample program, config, make, and make install logfiles (c.txt, m.txt, mi.txt) attached:
[irecv_leak.zip](https://github.com/pmodels/mpich/files/8919310/irecv_leak.zip)

This is happening when running test jobs on a single Linux machine.

I noticed it first from some automatic leak checker output on stderr
in MPI_Finalize() (this MPICH build was configured with --enable-g=most):

[0] 500000 at [0x7f5b571a00b0], ./src/include/mpir_gpu.h[98]
[0] 500000 at [0x7f5b5721b0b0], ./src/include/mpir_gpu.h[98]

Here's the stack trace as reported by valgrind:
500,168 bytes in 1 blocks are still reachable in loss record 11 of 12
   at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4E0A9A8: trmalloc (in /usr/local/mpich-4.0.2/lib/libmpi.so.12.2.2)
   by 0x4E0B267: MPL_trmalloc (in /usr/local/mpich-4.0.2/lib/libmpi.so.12.2.2)
   by 0x499DC92: MPIR_gpu_malloc_host (mpir_gpu.h:98)
   by 0x499DC92: MPIDI_OFI_do_irecv.constprop.0 (ofi_recv.h:214)
   by 0x49A1E5B: MPIDI_NM_mpi_irecv.constprop.0 (ofi_recv.h:341)
   by 0x49A2AE6: anysource_irecv (ch4_recv.h:34)
   by 0x49A2AE6: MPIDI_irecv (ch4_recv.h:124)
   by 0x49A2AE6: MPID_Irecv.constprop.0 (ch4_recv.h:331)
   by 0x49A37AF: internal_Irecv (irecv.c:98)
   by 0x49A37AF: PMPI_Irecv (irecv.c:192)
   by 0x1096A2: main (irecv_leak.c:55)

The leak seems to happen in each call to MPI_Irecv, not just in the
first call.

This leak does not occur when using MPICH 3.4.3.

Expected output when run with 2 processes:
Iteration 0
[0] isend 500000 bytes to 0
[0] irecv 500000 bytes from 0
[0] irecv 500000 bytes from 1
[1] isend 500000 bytes to 0
done

Output when run with 2 processes on MPICH-4.0.2:
Iteration 0
[0] isend 500000 bytes to 0
[0] irecv 500000 bytes from 0
[0] irecv 500000 bytes from 1
[1] isend 500000 bytes to 0
done
[0] 500000 at [0x7f9bd476f0b0], ./src/include/mpir_gpu.h[98]
[0] 500000 at [0x7f9bd47ea0b0], ./src/include/mpir_gpu.h[98]

**Comment by hzhou** [comment]
We issue both a shm receive and netmod receive. Upon shm matching, we internally cancel the netmod receive. There is more clean up missing in the ofi cancel path, causing the leaks.

Thanks for reporting! @oshkosher
