### ISSUE TITLE
Error in building MPICH

### ISSUE THREAD

**Issue by D-teg** [pmodels/mpich#6068]
my platform and prerequisites：
mpich-4.0.2
Ubuntu：5.4.0
Gcc，G++，GNU Fortran：10.3.0
 
I use the 
` ./configure --prefix=/home/.../mpich-4.0.2/mpich-install   FFLAGS=-fallow-argument-mismatch  FCFLAGS=-fallow-argument-mismatch --with-cross=/home/home/.../mpich-4.0.2/cross`
to configure successfully.

But when I build MPICH,error comes from the source file.
For example
`src/gpu/mpl_gpu_cuda.c: In function ‘MPL_gpu_query_pointer_attr’:
src/gpu/mpl_gpu_cuda.c:50:34: error: ‘MPL_gpu_device_attr’ {aka ‘struct cudaPointerAttributes’} has no member named ‘type’
   50 |         switch (attr->device_attr.type) {`

here is the error_log file
[mi.txt](https://github.com/pmodels/mpich/files/8989548/mi.txt)

**Comment by hzhou** [comment]
If you do not need cuda support, try configure with `--without-cuda`.

**Comment by hzhou** [comment]
@D-teg As for the cuda error, it is possible that cuda version mismatch. What is your cuda version?

**Comment by D-teg** [comment]
> @D-teg As for the cuda error, it is possible that cuda version mismatch. What is your cuda version?

Thank you for your advise, I use `--without-cuda` when configuring and then build MPICH successfully.
My cuda is V7.5.17. And what what kind of version is appropriate？

**Comment by hzhou** [comment]
> And what what kind of version is appropriate？

MPICH is tested with cuda 10.0 and above.
