### ISSUE TITLE
Possible minor regression: singleton MPI initializatino and MPI_APPNUM

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6084]
This is with MPICH 3.4.3:
```
$ python -q
>>> from mpi4py import MPI
>>> print(MPI.COMM_WORLD.Get_attr(MPI.APPNUM))
None
```
Note: mpi4py returns `None` when an attribute is not set.

This is with mpich/main:
```
$ python -q
>>> from mpi4py import MPI
>>> print(MPI.COMM_WORLD.Get_attr(MPI.APPNUM))
0
```
This time, the attribute is set to zero.

I personally like the former behavior, as it allowed users to know whether the the process was running under singleton MPI initialize mode.

PS: Sorry for being so picky. Some mpi4py tests relied on APPNUM not being set to figure out whether the process was running singleton MPI init to disable broken tests. After the recent singleton MPI init fixes, maybe this is no longer relevant, but the former behavior may be still useful. Moreover, if no one has complained about it, why not preserving it?

**Comment by dalcinl** [comment]
For example, name publishing with singleton MPI init is not working:

```
$ python -q
>>> from mpi4py import MPI
>>> MPI.Publish_name("foo", MPI.Open_port())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mpi4py/MPI/Comm.pyx", line 3337, in mpi4py.MPI.Publish_name
mpi4py.MPI.Exception: Invalid service name (see MPI_Publish_name), error stack:
internal_Publish_name(86): MPI_Publish_name(service_name=foo, MPI_INFO_NULL, port_name=tag#0$connentry#0200A1270A443A090000000000000000$) failed
MPID_NS_Publish(50)......: Lookup failed for service name foo
```

Then, in my testing for singleton MPI init support, I could figure out that I have to disable name publishing tests if the `MPI_APPNUM` attribute is not set.

**Comment by dalcinl** [comment]
On a somewhat related issue, under singleton MPI init, now MPICH sets the `MPI_UNIVERSE_SIZE` of `MPI_COMM_WORLD` to `1`. This could quite misleading. Perhaps it is better not to set the attribute at all? 

I do have code depending on whether the attribute is set or not [[link]](https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/futures/_lib.py#L951). Although this code uses a fallback value of `1` if the universe size is not set, a different fallback value would also make sense (e.g. `os.cpu_count()`). Once again, not setting the attribute is a way to telling the caller "I do not have enough information to provide a meaningful value".

**Comment by hzhou** [comment]
Hmm, I am not seeing it.

```
~/work/pull_requests/mpich-main$ cat appnum.c
#include "mpi.h"
#include "stdio.h"

int main() {
    MPI_Init(NULL, NULL);

    void *v;
    int flag;
    MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_APPNUM, &v, &flag);
    if (flag) {
        int vval = *(int *)v;
        printf("Got MPI_APPNUM - %d\n", vval);
    } else {
        printf("MPI_APPNUM is NULL\n");
    }

    MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_UNIVERSE_SIZE, &v, &flag);
    if (flag) {
        int vval = *(int *)v;
        printf("Got MPI_UNIVERSE_SIZE - %d\n", vval);
    } else {
        printf("MPI_UNIVERSE_SIZE is NULL\n");
    }

    MPI_Finalize();
    return 0;
}
~/work/pull_requests/mpich-main$ mpicc -o t appnum.c
~/work/pull_requests/mpich-main$ ./t
MPI_APPNUM is NULL
MPI_UNIVERSE_SIZE is NULL
~/work/pull_requests/mpich-main$ mpirun -n 1 ./t
Got MPI_APPNUM - 0
MPI_UNIVERSE_SIZE is NULL
```

**Comment by dalcinl** [comment]
@hzhou Sorry, you are definitely right, I screwed up. I was probably using an mpi4py build linked with Open MPI.
