### ISSUE TITLE
C++ datatype availability coupled to C++ binding support

### ISSUE THREAD

**Issue by brandongc** [pmodels/mpich#6094]
From MPI 4.0

```
If there is an accompanying C++ compiler then the datatypes in Table 3.4 are also supported in C and Fortran.
```
Table 3.4 lists
`MPI_CXX_{BOOL|FLOAT_COMPLEX|DOUBLE_COMPLEX|LONG_DOUBLE_COMPLEX}`

In `configure.ac` the flag to enable the C++ bindings

```
AC_ARG_ENABLE(cxx,
	AS_HELP_STRING([--enable-cxx], [Enable C++ bindings]),,enable_cxx=yes)
```

Also controls if those datatypes are enabled

```
    # set following sizes to 0 to disable the corresponding datatypes
    ac_cv_sizeof_bool=0
    ac_cv_sizeof_Complex=0
    ac_cv_sizeof_DoubleComplex=0
    ac_cv_sizeof_LongDoubleComplex=0
```

Should the availability of those data types be decoupled from support of the C++ bindings?

**Comment by hzhou** [comment]
I personally agree. We'll have a discussion on this.

**Comment by jjellio** [comment]
Sandia Lab's Trilinos has hit this - and we absolutely would like C++ interop to work - and we have no desire for the deprecated C++ bindings. (we hit it through Cray's mpich)

@lukebroskop @alanw0 @JaredCrean2

**Comment by hzhou** [comment]
We have discussed and we are on board with the proposal. Expect pull request soon.

**Comment by jjellio** [comment]
Great! Thanks. I mentioned our HPE rep (luke) - as well as the code team that hit it on our end. Thanks for the quick response!
