### ISSUE TITLE
ROMIO and MPI-4: Broken large-count datatype decoding

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6121]
### Description
Current mpi4py@master use the large-count MPI-4 APIs exclusively for all operations, including the construction of user-defined datatypes. However, looks like the datatype decoding infrastructure in ROMIO was not updated to cope with datatypes created via the large-count MPI-4 APIs. 

### Reproducer
```python
import numpy as np
from mpi4py import MPI
from mpi4py.util import dtlib

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

mode = 0
mode |= MPI.MODE_RDWR
mode |= MPI.MODE_CREATE
mode |= MPI.MODE_DELETE_ON_CLOSE
file = MPI.File.Open(comm, "/tmp/data", mode)
file.Set_size(0)

datatype = MPI.DOUBLE
subarray = datatype.Create_subarray(
    sizes=[size, 3],
    subsizes=[1, 3],
    starts=[rank, 0],
    order=MPI.ORDER_C,
).Commit()

dtype = dtlib.to_numpy_dtype(datatype)
data = np.full((1, 3), rank, dtype=dtype)

file.Set_view(0, datatype, subarray)
file.Write_all(data)

comm.Barrier()
file.Sync()
comm.Barrier()

file.Set_view(0, datatype, subarray)
file.Read_all(data)
assert np.allclose(data, rank)

subarray.Free()
file.Close()
```

```
$ mpiexec --prepend-rank -n 2 python test_io_array.py
[0] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 944
[0] Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[0] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 946
[0] Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[0] 
[0] python:788935 terminated with signal 11 at PC=7f9bc47e9c3c SP=7ffcb6ceabe0.  Backtrace:
...
[0] /home/devel/mpi/mpich/dev/lib/libmpi.so.0(PMPI_File_set_view+0x5f6)[0x7f9bc47b59d8]
...
[1] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 944
[1] Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
[1] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 946
[1] Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
[1] 
[1] python:788936 terminated with signal 11 at PC=7f45e031bc3c SP=7ffe9bc3d930.  Backtrace:
...
[1] /home/devel/mpi/mpich/dev/lib/libmpi.so.0(PMPI_File_set_view+0x5f6)[0x7f45e02e79d8]
...
```

CC: @mengaldo

**Comment by hzhou** [comment]
The error seems familiar -- https://github.com/pmodels/mpich/issues/2182

We'll look into it.

**Comment by dalcinl** [comment]
I'm not sure... Please note the test I posted uses really small arrays.

**Comment by dalcinl** [comment]
I patched my working copy with the following:

```diff
diff --git a/src/mpi/romio/adio/common/flatten.c b/src/mpi/romio/adio/common/flatten.c
index cda26ba94..da8cbecae 100644
--- a/src/mpi/romio/adio/common/flatten.c
+++ b/src/mpi/romio/adio/common/flatten.c
@@ -3,6 +3,7 @@
  *     See COPYRIGHT in top-level directory
  */
 
+#include <assert.h>
 #include "adio.h"
 #include "adio_extern.h"
 
@@ -940,7 +941,7 @@ MPI_Count ADIOI_Count_contiguous_blocks(MPI_Datatype datatype, MPI_Count * curr_
     MPI_Aint *adds;             /* Make no assumptions about +/- sign on these */
     MPI_Datatype *types;
 
-    MPI_Type_get_envelope(datatype, &nints, &nadds, &ntypes, &combiner);
+    int ierr = MPI_Type_get_envelope(datatype, &nints, &nadds, &ntypes, &combiner); assert(ierr == MPI_SUCCESS);
     ints = (int *) ADIOI_Malloc((nints + 1) * sizeof(int));
     adds = (MPI_Aint *) ADIOI_Malloc((nadds + 1) * sizeof(MPI_Aint));
     types = (MPI_Datatype *) ADIOI_Malloc((ntypes + 1) * sizeof(MPI_Datatype));
```

and next run again my reproducer:

```
$ mpiexec --prepend-rank -n 2 python test_io_array.py
[0] python: ../../../../src/mpi/romio/adio/common/flatten.c:944: ADIOI_Count_contiguous_blocks: Assertion `ierr == MPI_SUCCESS' failed.
[1] python: ../../../../src/mpi/romio/adio/common/flatten.c:944: ADIOI_Count_contiguous_blocks: Assertion `ierr == MPI_SUCCESS' failed.
...
```

I'm running this under mpi4py. By default, mpi4py sets the error handler of `COMM_WORLD` to `ERRORS_RETURN`. That's the reason I was not getting a proper failure. I was not aware the ROMIO implementation doesn't check return values in some MPI calls :disappointed:.

After this evidence, I believe my initial diagnostic was correct: ROMIO has to be updated to account for datatypes created with large-count APIs.

**Comment by dalcinl** [comment]
@jsquyres Just FYI. I'm not sure whether you still support the ROMIO backed in Open MPI. If yes, you guys may need to eventually update it to properly support MPI-4.

**Comment by hzhou** [comment]
For large count created datatypes, we need use `MPI_Type_get_envelope_c`. Maybe we should return a special `combiner` to indicate that rather than return error, which may abort the application by default.

**Comment by hzhou** [comment]
Well, `MPI_Type_get_envelope_c` should always work. I guess that makes `MPI_Type_get_envelope` useless now.

**Comment by dalcinl** [comment]
> `MPI_Type_get_envelope_c` should always work.

Indeed. And depending on whether `num_counts > 0`, you have to chance the way to parse the arrays, see [mpi4py sources](https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/Datatype.pyx#L576) for most of the rules.

**Comment by dalcinl** [comment]
I managed to put a fix together. It is not the definitive solution, as my implementation just translates the large-count datatypes to the small-count format, checking in the process for overflow in the `MPI_Count` -> `int|MPI_Aint` conversion via assertion. 

My work is in the following branch: [dalcinl/mpich@dalcinl/romio](https://github.com/dalcinl/mpich/commits/dalcinl/romio).
New tests added to mpi4py are in the following branch: [mpi4py/mpi4py@testing/io-view](https://github.com/mpi4py/mpi4py/commits/testing/io-view)
mpi4py testsuite runs are all green: [[link]](https://github.com/mpi4py/mpi4py-testing/runs/8034216241?check_suite_focus=true)

PS: I'm running `make testing` in `test/mpi`, it is taking longer than I expected. Once done, I'll submit a PR.

**Comment by dalcinl** [comment]
I'm getting this following output from `make testing`, most likely unrelated to my fixes.

```
Running tests in ./pt2pt [00:25:10]
Unexpected output in rqfreeb: In direct memory block for handle type REQUEST, 1 handles are still allocated
Unexpected output in rqfreeb: In direct memory block for handle type COMM, 1 handles are still allocated
Unexpected output in rqfreeb: [1] 360 at [0x1ffc920], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 360 at [0x1ffc700], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 360 at [0x1ffc4e0], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 360 at [0x205db10], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 360 at [0x205d8f0], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 360 at [0x205d6d0], ../mpich/src/mpi/coll/src/csel.c[688]
Unexpected output in rqfreeb: [1] 16 at [0x1fd3d30], ../mpich/src/util/mpir_localproc.c[160]
Unexpected output in rqfreeb: [1] 16 at [0x205dfa0], ../mpich/src/util/mpir_localproc.c[50]
Unexpected output in rqfreeb: [1] 16432 at [0x1fc8fe0], ../mpich/src/mpid/ch4/src/ch4_proc.c[168]
```

**Comment by hzhou** [comment]
> I'm getting this following output from `make testing`, most likely unrelated to my fixes.
> 
> ```
> Running tests in ./pt2pt [00:25:10]
> Unexpected output in rqfreeb: In direct memory block for handle type REQUEST, 1 handles are still allocated
> Unexpected output in rqfreeb: In direct memory block for handle type COMM, 1 handles are still allocated
> Unexpected output in rqfreeb: [1] 360 at [0x1ffc920], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 360 at [0x1ffc700], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 360 at [0x1ffc4e0], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 360 at [0x205db10], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 360 at [0x205d8f0], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 360 at [0x205d6d0], ../mpich/src/mpi/coll/src/csel.c[688]
> Unexpected output in rqfreeb: [1] 16 at [0x1fd3d30], ../mpich/src/util/mpir_localproc.c[160]
> Unexpected output in rqfreeb: [1] 16 at [0x205dfa0], ../mpich/src/util/mpir_localproc.c[50]
> Unexpected output in rqfreeb: [1] 16432 at [0x1fc8fe0], ../mpich/src/mpid/ch4/src/ch4_proc.c[168]
> ```

Yeah, the issue is known  - https://github.com/pmodels/mpich/issues/3469
