### ISSUE TITLE
I have executed MPI_Init() and it succeeded, but the program says it is not initialized

### ISSUE THREAD

**Issue by Maple-yhj** [pmodels/mpich#6129]
The code of my program is as follows:
`  int process_id =0 , process_size=0;`
`int Init_code=MPI_Init(&argc, &argv); `
`if(Init_code == MPI_SUCCESS)`
  ` std::cout<<"MPI SUCCESS"<<std::endl;`
`MPI_Comm_size(MPI_COMM_WORLD, &process_size);`
`MPI_Comm_rank(MPI_COMM_WORLD, &process_id);`
The result are as follows:
`MPI SUCCESS`
`Attempting to use an MPI routine (internal_Comm_size) before initializing or after finalizing MPICH`

My os is CentOS,Mpich's version is 4.0.2
I want to know how to solve this problem

**Comment by hzhou** [comment]
Could you upload your complete test code?

**Comment by Maple-yhj** [comment]
> Could you upload your complete test code?

It's a big complete project so I can't upload the whole thing.

I didn't have the problem when I ran the separate test code, but I used the `ldd` command to see that there was no difference between the two linked libraries

**Comment by hzhou** [comment]
Is your application multithreaded? I suspect you have called `MPI_Finalize` in one thread thus resulting in another thread accessing MPI after `MPI_Finalize`. Make sure to run a thread barrier before `MPI_Finalize`.

**Comment by Maple-yhj** [comment]
> Is your application multithreaded? I suspect you have called `MPI_Finalize` in one thread thus resulting in another thread accessing MPI after `MPI_Finalize`. Make sure to run a thread barrier before `MPI_Finalize`.
> 
> Also, make sure to either spawn your threads after `MPI_Init` or run a thread barrier after `MPI_Init`.

The same program works fine for me on the other server, so I think it's an environment problem, but I can't find out the difference in the environment between the two servers

**Comment by hzhou** [comment]
Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
```
export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
export MPICH_DBG_CLASS=ALL
export MPICH_DBG_LEVEL=VERBOSE
```

Could you upload the log files?

**Comment by Maple-yhj** [comment]
> Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
> 
> ```
> export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
> export MPICH_DBG_CLASS=ALL
> export MPICH_DBG_LEVEL=VERBOSE
> ```
> 
> Could you upload the log files?

![image](https://user-images.githubusercontent.com/71971448/186590043-fe26caba-7788-4d80-b4b3-cec70cfb6877.png)
I would like to know where to configure it with --enable-g=all.
Thank you for your time

**Comment by Maple-yhj** [comment]
> Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
> 
> ```
> export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
> export MPICH_DBG_CLASS=ALL
> export MPICH_DBG_LEVEL=VERBOSE
> ```
> 
> Could you upload the log files?

`./configure --prefix=/home/<USERNAME>/mpich-install  --enable-g=all`
Is this way to use it?

**Comment by Maple-yhj** [comment]
> Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
> 
> ```
> export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
> export MPICH_DBG_CLASS=ALL
> export MPICH_DBG_LEVEL=VERBOSE
> ```
> 
> Could you upload the log files?
![1661417654774](https://user-images.githubusercontent.com/71971448/186621061-6809aac7-87b5-4b48-8c35-a9b922243bc8.png)

This is the result of a new run of my program after configuring logging for mpich, which does not collect on error messages. I have used this command in a test program to ensure that it generates logs to the .exe file directory.
I implore you to get back to me when you receive.Thank you for your time.

**Comment by Maple-yhj** [comment]
> Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
> 
> ```
> export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
> export MPICH_DBG_CLASS=ALL
> export MPICH_DBG_LEVEL=VERBOSE
> ```
> 
> Could you upload the log files?

![1661418173055](https://user-images.githubusercontent.com/71971448/186622981-408b7146-4c1b-4998-a3a8-0a719f12eebc.png)

This is my main function

**Comment by hzhou** [comment]
> > Try to build mpich with `--enable-g=all` (configure option). Then set environment variables (ref: https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Debug_Event_Logging.md):
> > ```
> > export MPICH_DBG_FILENAME="log/dbg-%w-%d.log"
> > export MPICH_DBG_CLASS=ALL
> > export MPICH_DBG_LEVEL=VERBOSE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you upload the log files?
> > ![1661417654774](https://user-images.githubusercontent.com/71971448/186621061-6809aac7-87b5-4b48-8c35-a9b922243bc8.png)
> 
> This is the result of a new run of my program after configuring logging for mpich, which does not collect on error messages. I have used this command in a test program to ensure that it generates logs to the .exe file directory. I implore you to get back to me when you receive.Thank you for your time.

This does not look like MPICH messages. Were you running OpenMPI by accident?

**Comment by hzhou** [comment]
> 

That looks fine. If you search `MPI_Finalize` over your entire project code, do you see any other instances?

**Comment by Maple-yhj** [comment]
> > 
> 
> That looks fine. If you search `MPI_Finalize` over your entire project code, do you see any other instances?

![image](https://user-images.githubusercontent.com/71971448/186794271-01c15859-8568-4509-9f04-db801e98f06d.png)

My program did accidentally use Openmpi, here is the result of my corrected run. I have searched my entire project to make sure that only MPI_Finalize() and MPI_Init() are called in the main function. My program also doesn't output a log file, which bothers me.
Thank you for your time.

**Comment by Maple-yhj** [comment]
> > 
> 
> That looks fine. If you search `MPI_Finalize` over your entire project code, do you see any other instances?
![image](https://user-images.githubusercontent.com/71971448/186796282-aee8327c-b375-4de0-8953-5d6a0d937980.png)

This is the result of the execution of my ldd command

**Comment by hzhou** [comment]
> My program also doesn't output a log file, which bothers me.

Likely you didn't configure it correctly. What is your `mpichversion` output?

**Comment by hzhou** [comment]
> This is the result of the execution of my ldd command

If your code is under git, what is your `git grep MPI_Finalize`?

**Comment by Maple-yhj** [comment]
> > This is the result of the execution of my ldd command
> 
> If your code is under git, what is your `git grep MPI_Finalize`?
![image](https://user-images.githubusercontent.com/71971448/186803146-260a5ac5-8eb3-4584-b357-211b8bb12375.png)

**Comment by hzhou** [comment]
@Maple-yhj Your `ldd` shows it is dynamically linked to `/data/yehj/mpich-install`, but your `mpichversion` shows it should be `/data/yehj/mpi-install`. Make sure you are using the right binary by double check your `LD_LIBRARY_PATH`.

You `git grep` results are weird, did you put binary DLLs in git but the source code are not? For example, your `main` source code should contain `MPI_Finalize` but was not found in the repository. Try search for all source code then, for example `find . -name '*.cpp' |xargs grep MPI_Finalize`. You may want to include `.c` and `.h` files as well if you have them

**Comment by Maple-yhj** [comment]
> 
That's because I changed the folder name from mpi-install to mpich-install after the MPICH installation was complete.

**Comment by Maple-yhj** [comment]
> @Maple-yhj Your `ldd` shows it is dynamically linked to `/data/yehj/mpich-install`, but your `mpichversion` shows it should be `/data/yehj/mpi-install`. Make sure you are using the right binary by double checking your `LD_LIBRARY_PATH`.
> 
> Your `git grep` results are weird, did you put binary DLLs in git but the source code are not? For example, your `main` source code should contain `MPI_Finalize` but was not found in the repository. Try to search for all source code then, for example `find . -name '*.cpp' |xargs grep MPI_Finalize`. You may want to include `.c` and `.h` files as well if you have them

That's because I changed the folder name from mpi-install to mpich-install after the MPICH installation was complete.

**Comment by hzhou** [comment]
> That's because I changed the folder name from mpi-install to mpich-install after the MPICH installation was complete.

You should not do that. The prefix is hard coded into the scripts and binary during configuration. Changing them after installation often has mysterious glitches.

**Comment by Maple-yhj** [comment]
> You should not do that. The prefix is hard coded into the scripts and binary during configuration. Changing them after installation often has mysterious glitches.

Is it OK for me to change it to mpi-install and change the environment variables now?

**Comment by hzhou** [comment]
> > You should not do that. The prefix is hard coded into the scripts and binary during configuration. Changing them after installation often has mysterious glitches.
> 
> Is it OK for me to change it to mpi-install and change the environment variables now?

You can try that.

At this point, I am fairly certain that you have code calling `MPI_Comm_size` outside `MPI_Init/MPI_Finalize`. There are two possibilities. You have code in a different thread calling extra `MPI_Finalize`. Or you have code after the `MPI_Finalize` in `main` that still uses MPI. Producing call logs is just one way to confirm the fact. Searching the code base is another way. Or you could use debugger, and trying to produce a backtrace from the offending call. You need skip the first a few `MPI_Comm_size` because I am sure those are fine.

**Comment by Maple-yhj** [comment]
> > > You should not do that. The prefix is hard coded into the scripts and binary during configuration. Changing them after installation often has mysterious glitches.
> > 
> > 
> > Is it OK for me to change it to mpi-install and change the environment variables now?
> 
> You can try that.
> 
> At this point, I am fairly certain that you have code calling `MPI_Comm_size` outside `MPI_Init/MPI_Finalize`. There are two possibilities. You have code in a different thread calling extra `MPI_Finalize`. Or you have code after the `MPI_Finalize` in `main` that still uses MPI. Producing call logs is just one way to confirm the fact. Searching the code base is another way. Or you could use debugger, and trying to produce a backtrace from the offending call. You need skip the first a few `MPI_Comm_size` because I am sure those are fine.

I initially agreed with you, but after checking the source code I don't think I made this mistake and I will double check it again later. Now after changing the filename and environment variables, my program is reporting a new error as follows.

![image](https://user-images.githubusercontent.com/71971448/186811310-43a603a3-84af-4634-a656-e0bbfc4169ce.png)

**Comment by hzhou** [comment]
Your `YikeSim_parallel` is in your current directory, not in `out/build/mingw-build/`, the error message is telling you that.

**Comment by hzhou** [comment]
Okay, here is one way that may be easier for you to try. Find `src/mpi/errhan/errutil.c` and locate `MPIR_Err_uninitialized` function, insert `MPIR_Assert(0);` before `exit(1);`, rebuild and install. This time `MPIR_Assert` may show a backtrace that may offer some clues.

**Comment by Maple-yhj** [comment]
> Okay, here is one way that may be easier for you to try. Find `src/mpi/errhan/errutil.c` and locate `MPIR_Err_uninitialized` function, insert `MPIR_Assert(0);` before `exit(1);`, rebuild and install. This time `MPIR_Assert` may show a backtrace that may offer some clues.

I tried this method you mentioned, but the output did not change. I think it was a problem with my system environment and I decided to reinstall my system and try again. Thank you very much for taking the time out of your busy schedule to give me a reply!

**Comment by hzhou** [comment]
I am closing this issue since the last response is a few months ago. @Maple-yhj If you still need help, please feel free to re-open the issue.
