### ISSUE TITLE
autoconf `subsys_include.m4': No such file or directory

### ISSUE THREAD

**Issue by liam-clink** [pmodels/mpich#6138]
I'm trying to build the most recent release (4.0.2, also tried with most current commit) of MPICH on windows using MSYS2, and when I run autoconf, it fails

```
$ autoconf configure.ac
/usr/bin/m4:configure.ac:321: cannot open `subsys_include.m4': No such file or directory
autom4te-2.71: error: /usr/bin/m4 failed with exit status: 1
```

After all, this file does not exist like it does in [this MPICH project](https://github.com/ultrarisc/mpich/blob/master/subsys_include.m4)

Why is this file being included when it doesn't exist? Well in this different project, the instructions include direction to run ```./maint/gen_subcfg_m4``` which does generate the missing file in this project, but doing this is not included in the README for this project.

Also, the README says to run make, but the Makefile.am is written for use by Automake. Running make gives "nothing to do for this target", running automake mostly works if ```--add-missing``` is used to get some more missing files, but even then this doesn't get everything and there is an error:

```
$ automake --add-missing
configure.ac:660: error: required file 'confdb/ltmain.sh' not found
automake-1.16: error: cannot open < src/binding/c/Makefile.mk: No such file or directory
```

**Comment by hzhou** [comment]
The README is targeting users build MPICH from distributed release tarballs, which already all files generated. To build from fresh git checkout, run 
```
./autogen.sh
```

We have more files are generated than just autoconf.
