### ISSUE TITLE
Is there no IB channel in the mpich3 release?

### ISSUE THREAD

**Issue by cs0731** [pmodels/mpich#6157]
I tried to deploy mpich3 in the Infiniband HDR network. Everything was normal in the deployment process, but the point-to-point bandwidth test program(osu benchmark) was only 170MB/s. If the test bandwidth is used through UCX + mpich3, it is expected. Is there no IB channel in the mpich3 release?

**Comment by hzhou** [comment]
Which MPICH release are you referring? If you are using mpich-3.2, you may try `--with-device=ch3:nemesis:ofi`. `ch4:ucx` should be available in mpich-3.3 and newer.

**Comment by cs0731** [comment]
> Which MPICH release are you referring? If you are using mpich-3.2, you may try `--with-device=ch3:nemesis:ofi`. `ch4:ucx` should be available in mpich-3.3 and newer.

I try to deploy mpich-3.3.2. The OFED version installed in the current host environment is 5.1-2.5.8, the operating system is CentOS 7.4, and the kernel version is 3.10.0. Then use  --with-device=ch3: nemesis:ofi. After executing configure, the system prints error: "RDMA/fabric.h or libfabric library not found."

**Comment by cs0731** [comment]
> Which MPICH release are you referring? If you are using mpich-3.2, you may try `--with-device=ch3:nemesis:ofi`. `ch4:ucx` should be available in mpich-3.3 and newer.

I deployed mpich-3.3.2 and libfabric version 1.15.2. Then I tried to use "-- with device=ch3: nemesis: ofi". The measured bandwidth of osu_bw is only 5GB/s, far below the expected performance.

**Comment by hzhou** [comment]
@cs0731 ch3 is in maintenance mode. Is it possible for you try ch4 using later MPICH releases?

**Comment by cs0731** [comment]
> @cs0731 ch3 is in maintenance mode. Is it possible for you try ch4 using later MPICH releases?

Thank you! I have deployed mpich-3.3.2. Using ch4: ucx, the network performance test is normal.
