### ISSUE TITLE
build: wl variable set wrong for mpif90 when building with oneapi

### ISSUE THREAD

**Issue by stevenrbrandt** [pmodels/mpich#6167]
Hello. I attempted to build mpich 4.0.2. using Intel oneapi via spack (spack install intel-oneapi-compilers). The "mpif90" script that gets generated has `wl=""` instead of `wl="-Wl,"`. Manually editing the script to fix this allows mpif90 to work. Any idea what is going wrong here? Thanks.

**Comment by raffenet** [comment]
You need this patch, which is only in `main` at the moment. I'll add it on the list of backports to 4.0.x.

c4e999add5017f57f0bf20010dfc31e952174ccb

**Comment by raffenet** [comment]
Yes, this patch was added to the MPICH Spack file in https://github.com/spack/spack/issues/31678.

**Comment by raffenet** [comment]
> Yes, this patch was added to the MPICH Spack file in [spack/spack#31678](https://github.com/spack/spack/issues/31678).

Sorry, that was the issue. The PR that added it was https://github.com/spack/spack/pull/31740
