### ISSUE TITLE
hydra: Singleton mode and hydra_pmi_proxy

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6181]
I'm having issues with mpi4py's singleton tests on GitHub Actions if using `ch4:ofi|ucx`. Here you have the [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3071820934), but they are not really informative, everything seems to be fine but things eventually fail in VM cleanup stages that I do not have control of as a user.

After some spending some time enabling and disabling tests, I believe found what could be the issue, although I'm not 100% sure. In any case, what I'll describe in the following may be questionable behavior anyway.

If invoking `MPI_Comm_spawn()` in singleton mode, after both the parent and child process finish, a `hydra_pmi_proxy` process is left running. This process is resistant to SIGTERM, and looks like SIGKILL is the only way to get rid of it.

### Reproducer
```c
#include <mpi.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  MPI_Comm parent, intercomm;

  MPI_Init(NULL, NULL);

  MPI_Comm_get_parent(&parent);
  if (parent != MPI_COMM_NULL)
    MPI_Comm_disconnect(&parent);
  
  if (argc > 1) {
    MPI_Comm_spawn(argv[1], MPI_ARGV_NULL,
                   1, MPI_INFO_NULL, 0, MPI_COMM_SELF,
                   &intercomm, MPI_ERRCODES_IGNORE);
    MPI_Comm_disconnect(&intercomm);
  }

  MPI_Finalize();
}
```

### Behavior
First I try running with `mpiexec`. All is good:
```
$ mpicc spawn.c

$ mpiexec -n 1 ./a.out ./a.out 

$ pgrep a.out
# no output

$ pgrep hydra_pmi_proxy
# no output
```
So parent, child, and hydra_pmi_proxy processes are all gone.

Now I try using singleton MPI init mode:
```
$ ./a.out ./a.out 
```
Afterwards, the parent and child are gone, but `hydra_pmi_proxi` is still alive
```
$ pgrep -a a.out
# no output

$ pgrep -a hydra_pmi_proxy
187570 /home/devel/mpi/mpich/dev/bin/hydra_pmi_proxy --control-port kw61149:43279 --rmk user --launcher ssh --demux poll --pgid 0 --retries 10 --usize -2 --pmi-port 0 --gpus-per-proc -2 --singleton-port 49687 --singleton-pid 187569 --proxy-id 0
```
Gentle requests for termination seem to be ignored:
```
$ kill -TERM 187570
$ pgrep -a hydra_pmi_proxy
187570 /home/devel/mpi/mpich/dev/bin/hydra_pmi_proxy ...

$ kill -TERM 187570
$ pgrep -a hydra_pmi_proxy
187570 /home/devel/mpi/mpich/dev/bin/hydra_pmi_proxy ...

$ kill -TERM 187570
$ pgrep -a hydra_pmi_proxy
187570 /home/devel/mpi/mpich/dev/bin/hydra_pmi_proxy ...
```
and only SIGKILL gets rid of the process:
```
$ kill -KILL 187570
[mpiexec@localhost] control_cb (../../../../mpich/src/pm/hydra/mpiexec/pmiserv_cb.c:206): assert (!closed) failed
[mpiexec@localhost] HYDT_dmxu_poll_wait_for_event (../../../../mpich/src/pm/hydra/lib/tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@localhost] HYD_pmci_wait_for_completion (../../../../mpich/src/pm/hydra/mpiexec/pmiserv_pmci.c:184): error waiting for event
[mpiexec@localhost] main (../../../../mpich/src/pm/hydra/mpiexec/mpiexec.c:221): process manager error waiting for completion

$ pgrep -a hydra_pmi_proxy
# no output
```

**Comment by dalcinl** [comment]
@hzhou This may be related to your changes in #6172. I first noticed this regression within mpi4py about 2 days ago [[link]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3071820934), 9 days ago everything was OK [[link]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3026446183).

**Comment by hzhou** [comment]
As far as I can tell, the bug was always here since we re-enabled the singleton init. PR #6183 should fix it.

**Comment by dalcinl** [comment]
> As far as I can tell, the bug was always here since we re-enabled the singleton init

OK. Then this is probably some sort of regression in GitHub Actions. It is a bit weird that a rogue process would not allow the runner to properly shutdown. On the good side, this issue allowed you to quickly spot the flaw and promptly address it :smile:.

**Comment by hzhou** [comment]
Yes, the failures are good. :) Thanks for testing the singleton init. I was planning to add some of our own tests but never get to it :(. 

PS: looks like I will be able to fix the ch3-singleton init as well

**Comment by dalcinl** [comment]
All mpi4py test [passed](https://github.com/mpi4py/mpi4py-testing/actions/runs/3084965848) with your first commit.

> PS: looks like I will be able to fix the ch3-singleton init as well

I did not test this one, but as ch3 was not failing, I'm not sure whether it would make sense to run it again. Should I?

**Comment by hzhou** [comment]
> > PS: looks like I will be able to fix the ch3-singleton init as well
> 
> I did not test this one, but as ch3 was not failing, I'm not sure whether it would make sense to run it again. Should I?

I was referring to issue #6154 . I see you have ch3 singleton tests disabled at the moment. It'll be good if you can confirm with the tests.

**Comment by dalcinl** [comment]
> I was referring to issue #6154

Oh, sorry. Yes, I can check the fixes in a branch and run a build. You will get the results by tomorrow.

**Comment by dalcinl** [comment]
> I see you have ch3 singleton tests disabled at the moment

I enabled the ch3 tests. It is all [green](https://github.com/mpi4py/mpi4py-testing/actions/runs/3087746784) now!
