### ISSUE TITLE
hydra: pmi wire buffer not large enough

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#6191]
I tried running an MPI program fully subscribed on two nodes of JLSE skylake.
```
mpiexec -bind-to core -n 112 -ppn 56 ./examples/cpi
mpiexec: src/pmi_wire.c:580: PMIU_cmd_output_v1: Assertion `buflen + 1 < MAX_TMP_BUF_SIZE' failed.
[1]    21311 abort (core dumped)  mpiexec -bind-to core -n 112 -ppn 56 ./examples/cpi
```

**Comment by raffenet** [comment]
MPICH configure (main branch):

> ./configure --prefix=/home/raffenet/proj/ixpug-2022/mpich/i --disable-fortran --with-device=ch4:ucx --with-ucx=/soft/compilers/nvhpc/Linux_x86_64/2022/comm_libs/hpcx/hpcx-2.11/ucx --disable-romio --without-cuda --enable-thread-cs=per-vci --disable-fast --enable-g=dbg

**Comment by hzhou** [comment]
For now try manually increase `MAX_TMP_BUF_SIZE`. I am going to address it after the pmi_msg refactor, something like this one https://github.com/pmodels/mpich/pull/6168/commits/6d09656ccb9dd8cc4bdd055a067f414919258559
