### ISSUE TITLE
MPI_Pready_list: missing const in declaration

### ISSUE THREAD

**Issue by gcorbin** [pmodels/mpich#6195]
The Standard specifies the C-binding as

`int MPI_Pready_list(int lenght, const int array_of_partitions[], MPI_Request request)`

but `mpi_proto.h` defines it without the const specifier, i.e.:

`int MPI_Pready_list(int lenght, int array_of_partitions[], MPI_Request request)`.

**Comment by raffenet** [comment]
@gcorbin thanks for the report! #6196 should fix.

**Comment by raffenet** [comment]
If you want to test the patch locally, you can run `./autogen.sh -do=gen_binding_c` after applying it.

**Comment by raffenet** [comment]
> If you want to test the patch locally, you can run `./autogen.sh -do=gen_binding_c` after applying it.

Actually now you also need to run `./autogen.sh -do=ch4_api`. Or you can just run `./autogen.sh` with no options.
