### ISSUE TITLE
Q: How to get the process status on compute node

### ISSUE THREAD

**Issue by cathaysia** [pmodels/mpich#6198]
Hello, I use mpich to execute my program on a compute node. I now need to write a program to display the execution status of processes on each node, is there anything I can do?

I know that hydra is mpich's process manager, so can I get the status of a process from hydra? Or is hydra not exposing the interface, and I have to modify hydra to achieve this?

**Comment by hzhou** [comment]
There is a debugger interface, documented in the [MPIR Process Acquisition Interface, Version 1.1](https://www.mpi-forum.org/docs/mpir-specification-03-01-2018.pdf) and https://www.mpi-forum.org/docs/msgq.5.pdf. If you have access to a parallel debugger such as [Arm DDT](https://www.arm.com/products/development-tools/server-and-hpc/forge), the debugger should have those information.

You also can try turn on the `-v` option in hydra, e.g. `mpirun -v ...`, but it probably will show too much internal details for your purpose.

**Comment by cathaysia** [comment]
Thanks, please give some to read these documents.

**Comment by cathaysia** [comment]
I was told that a protocol called pmi is used to hydra get information about the process, but this protocol does not appear to be public. I'll continue to look at the MPIR protocol today, but if you're interested, can you talk to me about the pmi protocol?

**Comment by hzhou** [comment]
Sure. You can read the PMI documentation here: https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_13.html

PMI protocol is used by MPI internally and it is between MPI process and Process manager during init.

**Comment by cathaysia** [comment]
Thanks. I have a few days off next. If you don't mind, can you please leave the question off？:)

**Comment by cathaysia** [comment]
Hello, today I took a closer look at the PMI protocol and the MPIR protocol. But the PMI protocol is too simple to function, and MPIR is too complex (after all, I don't want to write a debugger). I think it's easier to modify the source code directly. I want to do this by modifying the proxy's code so that it periodically sends information about processes on the current node. But I don't know where to add in the source code, can you give me some help?

I want to clarify two issues:

- What functions does proxy use to get the state of a node and what status can I get?
- Where is the entry function for the proxy?

**Comment by hzhou** [comment]
@cathaysia Could you describe more on your application? In particular, what execution status you are looking for?

**Comment by cathaysia** [comment]
My program needs to get the following information: 

- the running status of processes on compute nodes
- the number of processes on each compute node
- the startup information of processes.

Since my program may start later than mpich, my plan is for the proxy to send this information periodically.

**Comment by hzhou** [comment]
The `main` function of proxy is here: https://github.com/pmodels/mpich/blob/main/src/pm/hydra/proxy/pmip.c. I don't think hacking hydra is the easy way, but good luck.

**Comment by cathaysia** [comment]
yes, hack hydra is not the easy way, but I cannot find another better way. :(
Thanks for your help. :)
