### ISSUE TITLE
Issues Building with AOCC (AMD Optimising C Compilers) --- Linking to Flang

### ISSUE THREAD

**Issue by ocelotStride** [pmodels/mpich#6206]
The build itself proceeds without issue, but libtool cannot link to flang during the install step. How can this be corrected? I found an issue from 2018 regarding this issue but some of the changes described in that post do not match what is currently in the files. The AMD compiler typically installs into /opt and is loaded by exporting the path to the environment.

Update: I was able to bypass this by editing libtool to include the full path on each 'CC=' variable. This doesn't seem to be the intended method though

**Comment by hzhou** [comment]
Could you paste some console log? I am not sure I fully understand the issue. Is it missing an LD_LIBRARY_PATH?

**Comment by ocelotStride** [comment]
> Could you paste some console log? I am not sure I fully understand the issue. Is it missing an LD_LIBRARY_PATH?

The LD_LIBRARY_PATH is pulled from my environment. The issue occurs during `sudo -E make install`. The libtool linking steps for clang, clang++, and flang fail to find the command and I had to manually change the path in libtool to `/opt/AMD/.../bin/clang` and so on

**Comment by hzhou** [comment]
I see. I guess that is due to clang's path was not in `root` user's environment. You also can set `CC`, `CXX`, `FC` to the full path during the configure step.

**Comment by ocelotStride** [comment]
> I see. I guess that is due to clang's path was not in `root` user's environment. You also can set `CC`, `CXX`, `FC` to the full path during the configure step.

Is this not the purpose of `sudo -E`? It is strange that it picks up the other environment variables like the LD for example. Is putting the full path during configure the intended solution?

**Comment by hzhou** [comment]
Generally, automake does not use full paths in Makefile. So if there is a particular reason to use the full path, we need explicitly do so.
