### ISSUE TITLE
[Question] Is there an alternative version of MPIR_Reduce_local?

### ISSUE THREAD

**Issue by WHMHammer** [pmodels/mpich#6223]
The [`MPIR_Reduce_local(inbuf, inoutbuf, ...)`](https://github.com/pmodels/mpich/blob/main/src/mpi/coll/reduce_local/reduce_local.c#L48) function stores the result of `inbuf ⨂ inoutbuf` (where ⨂ represents the operation) into the `inoutbuf`. Is there a version that stores the result of `inoutbuf ⨂ inbuf` (which is potentially different from `inbuf ⨂ inoutbuf` when `⨂` is non-commutative) into the `inoutbuf` without additional localcopy? What is the reason for not having one if the answer is no? Thank you.

**Comment by WHMHammer** [comment]
Thank you for your reply @hzhou. I understand that `MPIR_Reduce_local` assumes ***associativity***, and thus `(a⨂b)⨂c` and `a⨂(b⨂c)` are equivalent. However, to my understanding, `MPIR_Reduce_local` does assume ***commutativity***, so `a⨂b` and `b⨂a` can not be assumed to be equivalent. The current (only) version of `MPIR_Reduce_local` always stores the result of the operation in the second operand's buffer (that is, storing `a⨂b` in `b`'s buffer), but I want to store the results in the first operand's buffer (storing `a⨂b` in `a`'s buffer) in my algorithm. Is there a way to do that without additional memory copy? Thank you.

**Comment by hzhou** [comment]
If you are hacking, nothing prevents you from cloning an MPIR_Reduce_local that reverses the accumulation buffer. That said, an algorithm can always pick a variation that works with one of the MPIR_Reduce_local accumulation directions.
