### ISSUE TITLE
bug: MPI_Reduce for large derived datatype causes FPE exception

### ISSUE THREAD

**Issue by sergey-v-kuznetsov** [pmodels/mpich#6239]
We've been trying to test ScaLAPACK 2.2.0 and ScaLAPACK  2.1.0  https://netlib.org/scalapack and we found out that BLACS tests crash with MPICH 4.0.2. Our investigation showed that seg faults happen while calling MPI_reduce for  MPI_DOUBLE_COMPLEX  for computing max or min absolute value of a double complex precision.  Here are steps to reproduce: 
1. Download ScaLAPACK 2.2.0 or ScaLAPACK 2.1.0
2.  Unpack and build it (cd scalapack-2.2.0/;  cp SLmake.inc.example SLmake.inc and type make)
3.  Then cd BLACS/TESTING and try to execute xCbtest  or xFbtest by the command:
   $mpiexec -n 4 ./xCbtest  
  On our system we always got:
....
 DOUBLE COMPLEX AMX TESTS: BEGIN.
 
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 
We've been using MPICH 4.0.2  
$ mpiexec --version
HYDRA build details:
    Version:                                 4.0.2
    Release Date:                            Thu Apr  7 12:34:45 CDT 2022
    CC:                              gcc      
    Configure options:                       '--disable-option-checking' '--prefix=/export/users/skuznets/mpich402' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= ' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= '
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select

where 
]$ gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)

was used for building MPICH 4.0.2 and ScaLAPACK 2.1.0 -2.2.0

**Comment by hzhou** [comment]
Thanks for reporting the issue. We'll look into it.

**Comment by hzhou** [comment]
Reproduced the bug. Backtrace:
```
DOUBLE COMPLEX AMX TESTS: BEGIN.

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f2d68a9ed21 in ???
#1  0x7f2d68a9def5 in ???
#2  0x7f2d6876508f in ???
        at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x7f2d68f9fe7f in MPIR_Algo_calculate_pipeline_chunk_info
        at ./src/mpi/coll/algorithms/common/algo_common.h:48
#4  0x7f2d68f9fe7f in MPIR_Algo_calculate_pipeline_chunk_info
        at ./src/mpi/coll/algorithms/common/algo_common.h:24
#5  0x7f2d68f9fe7f in MPIDI_POSIX_mpi_allreduce_release_gather
        at ./src/mpid/ch4/shm/src/../posix/posix_coll_release_gather.h:329
#6  0x7f2d68fc25b1 in MPIDI_POSIX_mpi_allreduce_release_gather
        at ./src/mpid/ch4/src/ch4_coll_impl.h:345
#7  0x7f2d68fc25b1 in MPIDI_POSIX_mpi_allreduce
        at ./src/mpid/ch4/shm/src/../posix/posix_coll.h:273
#8  0x7f2d68fc25b1 in MPIDI_SHM_mpi_allreduce
        at ./src/mpid/ch4/shm/src/shm_coll.h:47
#9  0x7f2d68fc25b1 in MPIDI_Allreduce_intra_composition_gamma
        at ./src/mpid/ch4/src/ch4_coll_impl.h:391
#10  0x7f2d68fc25b1 in MPIDI_Allreduce_allcomm_composition_json
        at ./src/mpid/ch4/src/ch4_coll.h:362
#11  0x7f2d68fc25b1 in MPID_Allreduce
        at ./src/mpid/ch4/src/ch4_coll.h:470
#12  0x7f2d68fc25b1 in MPIR_Allreduce
        at src/mpi/coll/mpir_coll.c:4803
#13  0x7f2d68e23333 in internal_Allreduce
        at src/binding/c/c_binding.c:3837
#14  0x7f2d68e23333 in PMPI_Allreduce
        at src/binding/c/c_binding.c:3889
#15  0x558e3d96562c in ???
#16  0x558e3d8f6e8e in ???
#17  0x558e3d8ec25f in ???
#18  0x558e3d94ed4f in ???
#19  0x558e3d94f12b in ???
#20  0x7f2d68746082 in __libc_start_main
        at ../csu/libc-start.c:308
#21  0x558e3d8e350d in ???
#22  0xffffffffffffffff in ???

```

**Comment by hzhou** [comment]
@sergey-v-kuznetsov Could you try to apply the patch in #6240 and rebuild MPICH?

**Comment by sergey-v-kuznetsov** [comment]
Unfortunately I was unable to check out the git branch due to a  security problem on our side.  And I got compilation errors if the pull request's changes are incorporated into the mpich 4.0.2 package. Sorry, I'll  have to wait for a mpich release.
