### ISSUE TITLE
mpi4py: Regression running testsuite on GitHub Actions

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6269]
* All build using `hydra` fail in singleton init mode [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3449138542). Unfortunately, the failure prevented GH Actions for generating a proper, informative logs.
* The build using `gforker` and `ch4:ofi` failed with the following assertion:
```
...
testGetAccumulate (test_rma_nb.TestRMASelf) ... Assertion failed in file ./src/include/mpir_request.h at line 380: equal_ && (*(MPID_Thread_mutex_t *) MPIR_Request_mem[pool].lock).count >= 1
```

It is not easy for me right now to try to reproduce these issues with local builds.

**Comment by hzhou** [comment]
I'll look into it

**Comment by hzhou** [comment]
We also see the failure in our Jenkins:
```
testAcceptConnect (test_dynproc.TestDPM) ... skipped 'mpi-world-size<2'
testConnectAccept (test_dynproc.TestDPM) ... skipped 'mpi-world-size<2'
testJoin (test_dynproc.TestDPM) ... skipped 'mpi-world-size<2'
testNamePublishing (test_dynproc.TestDPM) ... skipped 'mpi-world-size<2'
testGetLibraryVersion (test_environ.TestEnviron) ... ok
testGetProcessorName (test_environ.TestEnviron) ... ok
testGetVersion (test_environ.TestEnviron) ... ok
testIsFinalized (test_environ.TestEnviron) ... ok
testIsInitialized (test_environ.TestEnviron) ... ok
testPControl (test_environ.TestEnviron) ... ok
testWTick (test_environ.TestEnviron) ... ok
testWTime (test_environ.TestEnviron) ... ok
testAppNum (test_environ.TestWorldAttrs) ... ok
testHostPorcessor (test_environ.TestWorldAttrs) ... ok
testIOProcessor (test_environ.TestWorldAttrs) ... ok
testLastUsedCode (test_environ.TestWorldAttrs) ... ok
testUniverseSize (test_environ.TestWorldAttrs) ... FATAL: command execution failed
java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:101)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Backing channel 'pmrs-centos64-240-03' is disconnected.
...
```
However, when I manually (logged on to the server and using the same build) run `python3 runtests.py`, it always complete successfully. Puzzling...

**Comment by hzhou** [comment]
This one has more error message:
```
testUniverseSize (test_environ.TestWorldAttrs) ... [unset]: PMIU_write error; fd=5 buf=:cmd=abort exitcode=-1 message=PMI_Init failed
:
system msg for write_line failure : Broken pipe
[unset]: PMIU_write error; fd=5 buf=:cmd=put kvsname=kvs_296700_0_633360670_pmrs-centos64-240-02.cels.anl.gov key=P0-businesscard value=description#pmrs-centos64-240-02.cels.anl.gov$port#50584$ifname#10.140.36.4$
:
system msg for write_line failure : Broken pipe
[unset]: PMIU_write error; fd=5 buf=:cmd=barrier_in
:
system msg for write_line failure : Broken pipe
[unset]: [proxy:0:0@pmrs-centos64-240-02.cels.anl.gov] HYDU_sock_read (lib/utils/sock.c:206): PMIU_write error; fd=5 buf=:cmd=get_universe_size
:
system msg for write_line failure : Broken pipe
read error (Bad file descriptor)
[proxy:0:0@pmrs-centos64-240-02.cels.anl.gov] pmi_cb (proxy/pmip_cb.c:291): unable to read PMI command
[proxy:0:0@pmrs-centos64-240-02.cels.anl.gov] HYDT_dmxu_poll_wait_for_event (lib/tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@pmrs-centos64-240-02.cels.anl.gov] main (proxy/pmip.c:127): demux engine error waiting for event
FATAL: command execution failed
```

**Comment by hzhou** [comment]
At least Jenkins can reliably reproduce the singleton init failure: https://jenkins-pmrs.cels.anl.gov/job/mpich-review-custom/990/console

**Comment by hzhou** [comment]
@dalcinl The `hydra+ch4:ofi` failure is strange, there isn't any log? The singleton init is only triggered by the test to get unversize_size, so it should show some log before then. And as far as hydra goes, its singleton init is working as the other tests succeeded. Let's see if this failure reproduces.

Could you open a separate ticket for the TestRMASelf failure?

**Comment by hzhou** [comment]
@dalcinl For your reference, here is the result of our nightly test: 
https://jenkins-pmrs.cels.anl.gov/job/mpich-main-mpi4py/335/

The 64-bit tests are clean. The 32-bit tests fails with ---
```
======================================================================
ERROR: testCodeCharStr (test_datatype.TestDatatype) (datatype='MPI_REAL16')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "mpi4py/MPI/Datatype.pyx", line 1020, in mpi4py.MPI.Datatype.fromcode
KeyError: 'f16'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins-slave/workspace/mpich-main-mpi4py/label/centos32/netmod/ch3-tcp/mpi4py/test/test_datatype.py", line 401, in testCodeCharStr
    mpitype = MPI.Datatype.fromcode(code)
  File "mpi4py/MPI/Datatype.pyx", line 1022, in mpi4py.MPI.Datatype.fromcode
ValueError: cannot map code 'f16' to MPI datatype
```

**Comment by dalcinl** [comment]
@hzhou Sorry for the slow response.

> The `hydra+ch4:ofi` failure is strange, there isn't any log? 

Sorry, GitHub actions is indeed not producing any logs.

> The singleton init is only triggered by the test to get unversize_size, so it should show some log before then. And as far as hydra goes, its singleton init is working as the other tests succeeded. Let's see if this failure reproduces.

May be the hang is somehow related to the RMA issue?
With this [patch ](https://github.com/mpi4py/mpi4py/commit/612519390a23bae2b99f5632f112bfeb53bd39be) to skip tests, the standard mpi4py singleton tests that were failing before now run to completion for all build variants [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3497614200).

HOWEVER, the `hydra/gforker` + `ch4:ofi` tests for the `mpi4py.futures` package deadlock, as you can see in the same [logs](https://github.com/mpi4py/mpi4py-testing/actions/runs/3497614200). These tests do rely on dynamic process management, in particular MPI spawn and getting the universe size.

> Could you open a separate ticket for the TestRMASelf failure?

Done in #6292.

> The 64-bit tests are clean. The 32-bit tests fails with ---

Sorry, I don't have any 32bit builds in my CI infrastructure!
I've pushed a [ fix](https://github.com/mpi4py/mpi4py/commit/d8eb0b50568e1a64662786c3e953042283fa2618) to the master branch, I hope I got it right.
