### ISSUE TITLE
Fortran MPI_Waitany uses 0-based indexing

### ISSUE THREAD

**Issue by jacobrking** [pmodels/mpich#6270]
I'm using mpich 4.0.2 and the mpi_f08 module. The output request index from MPI_Waitany is now 0-based, instead of 1-based. This differs from mpich 3.4 and other mpi implementations.  

This is reflected as a change in the documentation to omit that Fortran uses 1-based indexing in the output indx:
https://www.mpich.org/static/docs/v3.4/www3/MPI_Waitany.html
https://www.mpich.org/static/docs/v4.0/www3/MPI_Waitany.html

I couldn't find any information on this change in the changelog or other issues. If this is intentional, it will require the user to check the mpi implementation and version and adjust accordingly. However, it seems like it may be an oversight. Please advise. Thanks!

**Comment by hzhou** [comment]
I believe this was fixed by https://github.com/pmodels/mpich/pull/5763. Unfortunately, this patch didn't make into 4.0.3 release. Could you try the 4.1b1 release (https://www.mpich.org/downloads/)?

**Comment by jacobrking** [comment]
I can confirm that it works in 4.1a1. Thanks for pointing out the patch.
