### ISSUE TITLE
testsuite: ./datatype/struct_no_real_types.c and MPI_LB

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6284]
./datatype/struct_no_real_types.c uses MPI_LB, which was deleted.  I have no idea what this test is supposed to do, but it shouldn't do this.

```c
    MPI_Datatype type = MPI_LB;
    MPI_Datatype newtype;

    int size;
    MPI_Aint extent;

    err = MPI_Type_create_struct(count, &len, &disp, &type, &newtype);
    if (err != MPI_SUCCESS) {
        if (verbose) {
            fprintf(stderr, "error creating struct type no_real_types_test()\n");
        }
        MTestPrintError(err);
        errs++;
    }
```

**Comment by hzhou** [comment]
`MPI_LB` (and `MPI_UB`) is allowed in a struct and it defines its lower bound (and upper bound). The code in the test is defining an empty datatype, which is non-sensical, but it is allowed by the standard. You'll be surprised that there are plenty of real code do that. Having empty datatypes on some processes allow the application to write one code for all processes.

**Comment by jeffhammond** [comment]
MPI_LB and MPI_UB were deleted.  I do not see how one can use them in MPI 3+.

**Comment by hzhou** [comment]
I see. We can guard the tests from `--enable-strictmpi`. There are too many legacy applications using explicit MPI_LB/MPI_UB, thus we are likely to keep supporting it.

**Comment by hzhou** [comment]
PR #6414 fixes this. `--enable-strictmpi` will not build those tests with legacy APIs.
