### ISSUE TITLE
testsuite: f77/pt2pt/issendf.f and f90/pt2pt/issendf90.f90

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6287]
There is a problem in these tests, but I cannot figure out how to resolve it.

The signature of `MPI_TESTANY` requires an array of requests and a single status object, which of course in F77/F90 means an an `INTEGER` array of dimension `MPI_STATUS_SIZE`.

The test works fine with F77.  With F90, specifically Open-MPI's module, gfortran 12.2.0 fails to find a matching procedure.

The first fix is to pass `requests` rather than `requests(1)`, which is correct in both F77 and F90.

The second fix, which is only legal in F90, is to pass `statuses(:,1)` instead of `statuses(1,1)`.

At this point, I don't think it is likely to find a pure and strict F77 compiler that does not support colon notation, but of course, `MPI_WAITANY` isn't compliant with F77 anyways, due to the length of the symbol name.

I would argue to resolve this by using the syntax that works with F90, since that also works with F77.

```
% make V=1
/opt/homebrew/Cellar/open-mpi/4.1.4_2/bin/mpifort  -g -O2 -fcray-pointer -c -o issendf90.o  issendf90.f90
issendf90.f90:99:50:

   99 |       &                       statuses(1,1), ierr)
      |                                                  1
Error: There is no specific subroutine for the generic 'mpi_testany' at (1)
```

**Comment by hzhou** [comment]
It seems there is a separate variable `status` and it should be used in `MPI_Testany` instead
