### ISSUE TITLE
Overly aggressive leak check for parent communicator

### ISSUE THREAD

**Issue by jedbrown** [pmodels/mpich#6319]
MPICH currently generates leak warnings if a child process (created using `MPI_Comm_spawn`) does not free the parent communicator (as returned by `MPI_Comm_get_parent`). For example, `test/mpi/spawn/spawnintra.c` currently has
```c
  /* It isn't necessary to free the intercomm, but it should not hurt */
  MPI_Comm_free(&intercomm);
```
and if this is changed to
```c
  if (!isChild) MPI_Comm_free(&intercomm);
```
then we get the following leak warning.

```
leaked context IDs detected: mask=0x7f5d4cf80560 mask[0]=0x7fffffff
In direct memory block for handle type COMM, 4 handles are still allocated
leaked context IDs detected: mask=0x7f9212980560 mask[0]=0x7fffffff
In direct memory block for handle type COMM, 3 handles are still allocated
[0] 360 at [0x5647a23da870], src/mpi/coll/src/csel.c[688]
[0] 360 at [0x5647a23da650], src/mpi/coll/src/csel.c[688]
[0] 360 at [0x5647a23ea160], src/mpi/coll/src/csel.c[688]
[0] 8 at [0x5647a23e9110], src/util/mpir_localproc.c[160]
[0] 8 at [0x5647a240d2c0], src/util/mpir_localproc.c[50]
[0] 360 at [0x5647a23da1f0], src/mpi/coll/src/csel.c[688]
[0] 24 at [0x5647a23e9fc0], src/mpid/ch3/src/mpid_vc.c[65]
[0] 32 at [0x5647a240c560], src/mpid/ch3/src/mpid_vc.c[65]
[1] 360 at [0x5596feffd380], src/mpi/coll/src/csel.c[688]
[1] 360 at [0x5596feffd160], src/mpi/coll/src/csel.c[688]
[1] 8 at [0x5596feffcf20], src/util/mpir_localproc.c[160]
[1] 8 at [0x5596feffcda0], src/util/mpir_localproc.c[50]
[1] 360 at [0x5596feffc9d0], src/mpi/coll/src/csel.c[688]
[1] 24 at [0x5596ff00d270], src/mpid/ch3/src/mpid_vc.c[65]
[1] 32 at [0x5596ff00b1f0], src/mpid/ch3/src/mpid_vc.c[65]
```

I notice that MPI-4.0 Example 11.20 does not free the parent communicator and that page 527 (regarding `MPI_Comm_get_parent`) is fairly clear that explicitly disconnecting is not required and is potentially hazardous.
> Advice to users.
> MPI_COMM_GET_PARENT returns a handle to a single inter-
> communicator. Calling MPI_COMM_GET_PARENT a second time returns a handle
> to the same inter-communicator. Freeing the handle with MPI_COMM_DISCONNECT
> or MPI_COMM_FREE will cause other references to the inter-communicator to become
> invalid (dangling). Note that calling MPI_COMM_FREE on the parent communicator
> is not useful. (End of advice to users.)
> Rationale.
> The desire of the Forum was to create a constant
> MPI_COMM_PARENT similar to MPI_COMM_WORLD. Unfortunately such a constant
> cannot be used (syntactically) as an argument to MPI_COMM_DISCONNECT, which
> is explicitly allowed. (End of rationale.)

I ran into this when implementing dynamic process management for Rust (rsmpi). Regardless of whether MPICH chooses to "fix" this, what would you recommend I do? Should I always explicitly disconnect the parent communicator (if it exists) prior to `MPI_Finalize`?

Cc: @jczhang07

**Comment by hzhou** [comment]
We probably can enhance it by automatically free the parent intercomm in `MPI_Finalize`, essentially treating it as a built-in comm -- seems to be the intention of the standard. And for `rsmpi`, the standard does permit "always explicitly disconnect the parent communicator (if it exists) ", right?

**Comment by hzhou** [comment]
I do not disagree.

**Comment by jczhang07** [comment]
@hzhou  Why does the standard allow `MPI_Comm_disconnect()` on the parent communicator?  In the manual of `MPI_Comm_disconnect` , it is said
> It may not be called with the communicator MPI_COMM_WORLD or MPI_COMM_SELF.

Also, what does the standard say
> Note that calling MPI_COMM_FREE on the parent communicator is not useful.

**Comment by hzhou** [comment]
The parent intercommunicator can go away. For example, parent call MPI_Comm_spawn, then exit. After which, the children no longer can use the parent intercommunicator. Thus, semantically the parent intercommunicator is different from other built-in comms such as MPI_COMM_WORLD and MPI_COMM_SELF.

It is subjective to comment on "usefulness". I guess since the implementation could make `MPI_Comm_free` on parent intercomm *unnecessary*, that make it "not useful".

**Comment by jczhang07** [comment]
Thanks. It seems the inter-communicator returned in `MPI_Comm_spawn()` or `MPI_Comm_get_parent()` are like MPI_COMM_WORLD in the sense that users do not need to free/disconnect it.

But users indeed can free/disconnect it, but it is not ref-counted in MPI_Comm_get_parent(). It is user's responsibility to not have dangling communicators. 

Am I right? @hzhou

**Comment by hzhou** [comment]
Reopen due to  https://github.com/pmodels/mpich/pull/6321#discussion_r1041278775
