### ISSUE TITLE
Using MPI_DATATYPE_NULL in MPI_ALLTOALLW

### ISSUE THREAD

**Issue by jedwards4b** [pmodels/mpich#6323]
I think that this issue is similar to https://github.com/pmodels/mpich/issues/4659
We have found in mpich4.0 that calling MPI_ALLtoALLW with MPI_DATATYPE_NULL 
generates an error even when the send or recv count is 0.   I think that the standard
is unclear on whether MPI_DATATYPE_NULL should be allowed here, but it just seems to
make sense that if the send or receive count is 0 the datatype should not even be checked.

**Comment by hzhou** [comment]
I think this is fixed by https://github.com/pmodels/mpich/pull/5859. Could you test the [4.1b1](https://www.mpich.org/downloads/) release?

**Comment by jedwards4b** [comment]
I will test this and let you know.  Thanks

**Comment by raffenet** [comment]
FYI, the fix should also be in MPICH 4.0.1 and later releases in that series.

**Comment by hzhou** [comment]
I believe this issue is resolved.
