### ISSUE TITLE
MPI_Reduce: Bad NULL buffer checks for intercommunicators

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6351]
When used with intercommunicators, the `MPI_Reduce` routine should ignore `sendbuf` if `root in {MPI_ROOT, MPI_PROC_NULL}` and should ignore `recvbuf` if `root >= 0` (See MPI-4 document, pp. 266 lines 16-18). MPICH seems to be performing some NULL checks that IMHO are wrong. 

Look at the following compute-pi reproducer:
```
git clone https://github.com/mpi4py/mpi4py.git
$ make LANGS=c -C mpi4py/demo/spawning/
make: Entering directory '/home/dalcinl/Devel/mpi4py/demo/spawning'
./cpi-master-c.exe -> ./cpi-worker-c.exe
Fatal error in internal_Reduce: Invalid buffer pointer, error stack:
internal_Reduce(150): MPI_Reduce(sendbuf=(nil), recvbuf=0x7ffd23a8dcb0, count=1, MPI_DOUBLE, MPI_SUM, MPI_ROOT, comm=0x84000000) failed
internal_Reduce(114): Null buffer pointer
make: *** [makefile:14: test] Error 1
make: Leaving directory '/home/dalcinl/Devel/mpi4py/demo/spawning'
```

I have not checked all the other variants (non blocking, persistent, large count) of `MPI_Reduce`, but they may have the same issue. This is the list of all routines to check:
* [x] `MPI_Reduce`
* [ ] `MPI_Ireduce`
* [ ] `MPI_Reduce_init`
* [ ] `MPI_Reduce_c`
* [ ] `MPI_Ireduce_c`
* [ ] `MPI_Reduce_init_c`

**Comment by hzhou** [comment]
@dalcinl Give #6354 a try?

**Comment by dalcinl** [comment]
@hzhou Your change works fine with my reproducer.  Looking at the Python script, it is not obvious this fix will apply to the MPI-4 large-count variant. However, after inspecting the generated C code, it looks like everything is OK. Just in case, please confirm on your side.

**Comment by raffenet** [comment]
Can confirm this applies to all the routines listed. I'd like to pull this patch into 4.1.x for the upcoming GA release.
