### ISSUE TITLE
debugger: MPIR_proctable reporting identical pids for all processes

### ISSUE THREAD

**Issue by RichardABunt** [pmodels/mpich#6363]
Hi!

I am currently performing integration testing between MPICH 4.1rc2 and DDT, a parallel debugger for MPI-based applications.

Our internal test suite has highlighted a difference in behaviour around the MPIR interface. 

Reproducer:
1. Start a MPI session
`mpirun -np 2 $(which sleep) 20 &`
2. Attach to mpirun with GDB and print the proc table.
`gdb -p $! -ex "print MPIR_proctable[0]@2"`
3. Observe the proc table with the same pid
`$1 = {{host_name = 0x1fb3170 "e121689", executable_name = 0x1fb3190 "/bin/sleep", pid = 10280}, {host_name = 0x1fb3170 "e121689", executable_name = 0x1fb3190 "/bin/sleep", pid = 10280}}`

I would expect the pid entries to reflect the actual pids of the two separate sleep processes.

Happy to provide more detail if needed.

Many thanks,

Rich.

**Comment by raffenet** [comment]
Thank you for the report. I have confirmed this bug on my system. Must be a bug with the way the pids are retrieved from the proxy list. I hope to have a fix soon.

**Comment by raffenet** [comment]
@RichardABunt I have posted a proposed fix in #6365. If you could apply it to your testing and confirm it is working, that would be great.

**Comment by RichardABunt** [comment]
Thanks for the quick response @raffenet ! 

I have added your patch to our local MPICH 4.1 RC2 package and have submitted it through our CI. Should have some feedback tomorrow GMT.

**Comment by RichardABunt** [comment]
I can confirm that your patch has fixed this issue.

Many thanks,

Rich.

**Comment by RichardABunt** [comment]
@raffenet Do you have a read on whether this fix will make it in to the next 4.1 RC or release?

**Comment by raffenet** [comment]
> @raffenet Do you have a read on whether this fix will make it in to the next 4.1 RC or release?

Yes. Once approved I will backport to 4.1.x and cut a 4.1rc3 release. Thanks again for the report!
