### ISSUE TITLE
Potential segfault in `MPIR_Attr_delete_list`

### ISSUE THREAD

**Issue by giordano** [pmodels/mpich#6364]
In https://github.com/JuliaParallel/MPI.jl/issues/684 we experienced some segmentation faults using MVAPICH 2 on [Ookami](https://www.stonybrook.edu/ookami/).  This [was reported](https://lists.osu.edu/pipermail/mvapich-discuss/2022-December/009070.html), with a reproducer, in the MVAPICH mailing list and [a patch](https://lists.osu.edu/pipermail/mvapich-discuss/2023-January/009279.html)
```diff
diff --git a/src/mpi/attr/attrutil.c b/src/mpi/attr/attrutil.c
index b9abbe6..5af452a 100644
--- a/src/mpi/attr/attrutil.c
+++ b/src/mpi/attr/attrutil.c
@@ -266,6 +266,7 @@ int MPIR_Attr_delete_list( int handle, MPID_Attribute **attr )
           corresponding keyval */
        /* Still to do: capture any error returns but continue to
           process attributes */
+    if (p->keyval) {
        mpi_errno = MPIR_Call_attr_delete( handle, p );
​
        /* We must also remove the keyval reference.  If the keyval
@@ -282,6 +283,7 @@ int MPIR_Attr_delete_list( int handle, MPID_Attribute **attr )
                MPIU_Handle_obj_free( &MPID_Keyval_mem, p->keyval );
            }
        }
+    }
​
        MPIU_Handle_obj_free( &MPID_Attr_mem, p );
```
is available to fix the segmentation fault, which I can confirm is working for me.

I don't have an MPICH build so I couldn't check whether I could reproduce the same segmentation fault with MPICH, but the code of `MPIR_Attr_delete_list` https://github.com/pmodels/mpich/blob/2bc425863a7387ce831380f9f7230c279c567e8a/src/mpi/attr/attrutil.c#L219-L278 looks more or less the same as the one in MVAPICH, in particular the unguarded use of `p->keyval`, so you may want to apply a similar patch.

CC: @simonbyrne.

**Comment by raffenet** [comment]
The reproducer:
```c
#include <mpi.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    MPI_Datatype dup_type;
    MPI_Type_dup(MPI_UINT32_T, &dup_type);

    MPI_Type_commit(&dup_type);

    int keyval;
    MPI_Type_create_keyval(MPI_TYPE_NULL_COPY_FN,
                           MPI_TYPE_NULL_DELETE_FN,
                           &keyval, NULL);

    MPI_Type_set_attr(dup_type, keyval, NULL);

    MPI_Finalize();
    return 0;
}
```
FWIW, this does not segfault for me with MPICH 4.1rc2. I also configured with AddressSanitizer enabled and did not receive any warnings.

**Comment by giordano** [comment]
For what is worth, I couldn't reproduce with MVAPICH on x86_64 either, the only system where I bumped into the segfault so far is Ookami.

**Comment by raffenet** [comment]
Got it. I'll give this a try on one of our A64FX nodes and see how it goes. Any special compiler or configuration options?

**Comment by giordano** [comment]
Nothing too special, this is the configuration used for MVAPICH:
```
MVAPICH2 2.3.7 Wed March 02 22:00:00 EST 2022 ch3:mrail

Compilation
CC: gcc    -DNDEBUG -DNVALGRIND -O2
CXX: g++   -DNDEBUG -DNVALGRIND -O2
F77: gfortran -w -fallow-argument-mismatch -O2  -O2
FC: gfortran   -O2

Configuration
--prefix=/lustre/software/mvapich2/gcc12/2.3.7 --with-knem=/opt/knem-1.1.4.90mlnx1 --with-hcoll=/opt/mellanox/hcoll --enable-fortran=all --enable-cxx --with-file-system=lustre --with-slurm=/cm/shared/apps/slurm/current --with-pm=slurm --with-device=ch3:mrail --with-pmi=pmi1 -with-rdma=gen2
```

**Comment by hzhou** [comment]
Close this issue due to non-reproducible. Re-open if it can be reproduced with recent MPICH.
