### ISSUE TITLE
semantic version of release number

### ISSUE THREAD

**Issue by scivision** [pmodels/mpich#6381]
Was the new "v4.1" release intended to be "v4.1.0" to continue the semantic versioning of earlier MPICH releases?

**Comment by raffenet** [comment]
MPICH has traditionally named initial releases in a series with a two digit version number.
```
bash-3.2$ git tag | grep "v[3-4].[0-9]$"
v3.0
v3.1
v3.2
v3.3
v3.4
v4.0
v4.1
```
 I don't know the reasoning behind this, as it was done this way before I joined the project. Perhaps 3 digits would be more consistent going forward.
