### ISSUE TITLE
libtool threw an error that 'src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo' is not a valid libtool object when running make

### ISSUE THREAD

**Issue by ChaunceyWang2021** [pmodels/mpich#6383]
I was trying to configure and make mpich4.1 with a CUDA GPU support in Deepin Stable 20.8 (a linux distribution based on Debian) but threw an error by libtool:

```
libtool:   error: 'src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo' is not a valid libtool object
```

This was the reason why PETSc with CUDA support always failed to configure.

**Comment by raffenet** [comment]
Thanks for the report. I will take a look.

**Comment by hzhou** [comment]
@ChaunceyWang2021 Could you dump `src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo` and the output of `./libtool --version`?

**Comment by ChaunceyWang2021** [comment]
> @ChaunceyWang2021 Could you dump `src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo` (it's a text file) and the output of `./libtool --version`?

I ran `./libtool --version` and it showed me the following:
```
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And the file `yaksuri_cudai_pup__Bool.lo` shows in the following:

```
# src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo - a libtool object file
# Generated by 
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# Name of the PIC object.
pic_object=".libs/yaksuri_cudai_pup__Bool.o"

# Name of the non-PIC object.
non_pic_object="yaksuri_cudai_pup__Bool.o"
```

**Comment by hzhou** [comment]
Thanks @ChaunceyWang2021 Could you try locate `modules/yaksa/src/backend/cuda/cudalt.sh` and apply this patch https://github.com/pmodels/yaksa/pull/242/commits/989132c63d3d5d17082fb56295da2ff85c507f8d ?

**Comment by ChaunceyWang2021** [comment]
> Thanks @ChaunceyWang2021 Could you try locate `modules/yaksa/src/backend/cuda/cudalt.sh` and apply this patch [pmodels/yaksa@989132c](https://github.com/pmodels/yaksa/commit/989132c63d3d5d17082fb56295da2ff85c507f8d) ?

I applied your patch and the error does not appear any more! Thank you very much!
