### ISSUE TITLE
`MPIX_*_enqueue` manpages broken

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#6391]
The synopsis portion of the manpage is not rendered correctly. Ex:
```
MPIX_Allreduce_enqueue(3)                     MPI                     MPIX_Allreduce_enqueue(3)



NAME
       MPIX_Allreduce_enqueue -  Synopsis: .vb int MPIX_Allreduce_enqueue(const void *sendbuf,
       void *recvbuf, int count, MPI_Datatype datatype, MPI_Op op, MPI_Comm comm) .ve .vb int
       MPIX_Allreduce_enqueue_c(const void *sendbuf, void *recvbuf, MPI_Count count,
       MPI_Datatype datatype, MPI_Op op, MPI_Comm comm) .ve
```
https://www.mpich.org/static/docs/v4.1/www3/MPIX_Allreduce_enqueue.html

**Comment by hzhou** [comment]
> It looks like this is due to missing `.desc` fields in `stream_api.txt`. We can add `.desc` for all the functions where it is missing...or maybe just use the function name if there is no description?

Let's do both. I'll make a patch.
