### ISSUE TITLE
MPI_Waitany in fortran does not return MPI_UNDEFINED

### ISSUE THREAD

**Issue by mduponch** [pmodels/mpich#6402]
Hello,

I encountered an issue in Fortran programs using mpich-4.1 compiled with GNU Fortran (GCC) 11.3.0. 

MPI_Waitany does not return MPI_UNDEFINED=-32766  but  -32765. I was able to reproduce the behavior with the following simple fortran example :

```fortran
program test_waitany

use mpi 

implicit none

integer :: idx = 0 
integer :: err 
integer :: nreqs = 0
INTEGER, DIMENSION(:), POINTER :: recvreqs=> NULL()

call MPI_Init(err) 
call MPI_Waitany(nreqs, recvreqs, idx, MPI_STATUS_IGNORE, err) 
write(*,*) 'index = ', idx , 'MPI_UNDEFINED = ', MPI_UNDEFINED
call MPI_Finalize(err)

end program
``` 

mpich-4.1 was compiled with ./configure --prefix=... --enable-fast=03,ndebug,alwaysinline --with-device=ch4:ucx --with-ucx=.../UCX-1.13.1

Thanks in advance !

**Comment by hzhou** [comment]
Thanks for the report. Indeed, there is a bug! Fix coming...

**Comment by hzhou** [comment]
@mduponch  Please check whether patch in #6403 fixes the issue.

**Comment by mduponch** [comment]
I think there is a small bug in the fix. See PR.

**Comment by mduponch** [comment]
Now it works for me. Thanks !
