### ISSUE TITLE
rget_testall.c should use STATUS_IGNORE

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6420]
This test passes a status argument that it never uses.

```c
    MPI_Rget(&val1, 1, MPI_INT, 0, 0, 1, MPI_INT, win, &reqs[0]);
    MPI_Rget(&val2, 1, MPI_INT, 0, 1, 1, MPI_INT, win, &reqs[1]);

    do {
        mpi_errno = MPI_Testall(2, reqs, &flag, stats);
    } while (flag == 0);
```

> Upon returning from a completion call in which an RMA operation completes, all fields of the status object, if any, and the results of status query functions (e.g., MPI_GET_COUNT) are undefined with the exception of MPI_ERROR if appropriate (see Section 3.2.5). 

The motivation here is that Mukautuva has to convert status objects and it does not know that the RMA request fields are undefined, and it gets confused by the nonsense value of the `MPI_SOURCE` argument.

**Comment by hzhou** [comment]
So the test is within legal usages, right?

**Comment by jeffhammond** [comment]
It's not violating anything.  But passing status and not doing anything with it is an anti-pattern and I'd hate to have users learn bad practices from code like this.

**Comment by hzhou** [comment]
A correct implementation needs to deal with all user patterns as long as it does not violate anything. I think it is a good test to have.

**Comment by jeffhammond** [comment]
the test is fine.  i am merely suggesting MPI_STATUS_IGNORE be used, since that the correct way to implement it, because status is unused.

if you want to verify standard compliance, then a test that does request-based RMA that generates an errors and completes those RMA operations with a bulk operation is required.

**Comment by hzhou** [comment]
I see. I agree that we need to enhance the test by checking the status `MPI_ERROR` field. Yeah, the way MPI standard exposes the status fields are messy. It is difficult for Mukautuva to handle all cases. Why does Mukautuva need to check MPI_SOURCE value rather than blindly copy in/out? In my current PR, I simply use the ABI defined MPI_Status struct to build libmpi_abi.so, thus avoided the status conversion business.

**Comment by jeffhammond** [comment]
Mukautuva has to convert all the "special" values, such as `MPI_ANY_SOURCE` and `MPI_PROC_NULL`, so it is not a blind copy anyways, and I decided to make the `else` case issue a warning because that often means something has gone wrong.

You will also have to do this at some point, unless the MPI Forum agrees to define `MPI_ANY_SOURCE` and `MPI_PROC_NULL` as MPICH does today.  Fortunately, OMPI and MPICH agree on `MPI_UNDEFINED` and `MPI_ANY_TAG` so there is a good chance we can just standardize those as-is and avoid conversions.

Perhaps someday I will trust myself enough to have implemented everything correctly and then I can silence the warning.  For now, I just catch the MPICH debug case (https://github.com/pmodels/mpich/issues/6421) so there is no warning.

https://github.com/jeffhammond/mukautuva/blob/main/impl-status.h#L108
https://github.com/jeffhammond/mukautuva/blob/main/impl-constant-conversions.h#L90

**Comment by hzhou** [comment]
> You will also have to do this at some point, unless the MPI Forum agrees to define `MPI_ANY_SOURCE` and `MPI_PROC_NULL` as MPICH does today.

Yeah, I think I have hit the same issue. Initially, I was doing a shim layer approach -- as Mukautuva does. Then it gets pushed into a binding layer -- similar to how MPI/PMPI worked. Both approaches need to translate constants. And when it gets too messy, such as the issue you just hit, I realized that I can go deeper, and simply recompile every internal code by replacing the constants and status struct from the ABI header. It become significantly easier as I deleted most of the translation code.

The lesson: ABI can choose most of these constant values without concern of what currently MPICH chooses, and there will be little impact to how MPICH will support this ABI.

**Comment by jeffhammond** [comment]
That's really good news. I agree that for the integer and address constants that recompiling the guts is ideal. I don't think it's an unreasonable cost in mukautuva but of course MPICH and OMPI will both prefer to shift runtime costs to compile time costs if at all possible.

**Comment by hzhou** [comment]
Close as wontfix
