### ISSUE TITLE
question about rank -269488145 with debug builds

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6421]
I built MPICH with the following abundant debug flags, and I get a warning from Mukautuva because the `MPI_SOURCE` field of status has the value -269488145 (`%d`), or efefefef (`%x`), which seems like an obvious magic value for debugging.  However, I cannot find either of the above values in the source code and thus I wonder where it comes from.  I assume I'm just not looking for the right string representation of it.

```
--enable-g=all,handle,handlealloc,mem,meminit,memarena --enable-versioning --enable-debuginfo --without-ze --prefix=/opt/mpich/gcc/debug-ch4ucx --with-device=ch4:ucx
```

**Comment by raffenet** [comment]
This you're looking for this https://github.com/pmodels/mpich/blob/38552cfab7ac139754066e09f2a85e8b5a7d3df7/src/include/mpir_handlemem.h#L337

**Comment by raffenet** [comment]
Somewhat shockingly, it's even documented on the wiki! 😂 
https://github.com/pmodels/mpich/blob/main/doc/wiki/design/Support_for_Debugging_Memory_Allocation.md#handle-allocation-debugging

**Comment by jeffhammond** [comment]
Yeah I didn't think to look at the docs based on last experience 😳
