### ISSUE TITLE
Error reported using CESM software

### ISSUE THREAD

**Issue by nicodgomez** [pmodels/mpich#6426]
Hello I have recently compiled and installed mpich 4.0 along with the software CESM. I was succesfull in compiling and running CESM using OpenMPI but when I use MPICH 4.0 the running of CESM stops with the following error message

The MPI_Info_f2c() function was called before MPI_INIT was invoked.

I do not know the origin of the error. I have contacted support from CESM forum but I did not get any answer for know. 

I do not know if I am making an error in CESM configuration in order to use MPICH, or if I am not compiling MPICH correctly.

Thancks.

**Comment by hzhou** [comment]
`MPI_Info_f2c` in MPICH is just a macro defined in `mpi.h`. Could you paste the console log showing the error messages?

**Comment by nicodgomez** [comment]
Hello, here I attach the full output of the running of CESM.


User-specified PIO rearranger comm max pend req (comp2io),            0  (value will be reset as requested) 
 Resetting PIO rearranger comm max pend req (comp2io) to           64
 PIO rearranger options:
   comm type     = p2p
   comm fcd      = 2denable
   max pend req (comp2io)  =           64
   enable_hs (comp2io)     =  T
   enable_isend (comp2io)  =  F
   max pend req (io2comp)  =           64
   enable_hs (io2comp)    =  F
   enable_isend (io2comp)  =  T
(seq_comm_setcomm)  init ID (  1 GLOBAL          ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_setcomm)  init ID (  2 CPL             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_setcomm)  init ID (  5 ATM             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID (  6 CPLATM          ) join IDs =     2     5       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID (  3 ALLATMID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID (  4 CPLALLATMID     ) join IDs =     2     3       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID (  9 LND             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 10 CPLLND          ) join IDs =     2     9       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID (  7 ALLLNDID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID (  8 CPLALLLNDID     ) join IDs =     2     7       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 13 ICE             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 14 CPLICE          ) join IDs =     2    13       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 11 ALLICEID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 12 CPLALLICEID     ) join IDs =     2    11       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 17 OCN             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 18 CPLOCN          ) join IDs =     2    17       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 15 ALLOCNID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 16 CPLALLOCNID     ) join IDs =     2    15       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 21 ROF             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 22 CPLROF          ) join IDs =     2    21       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 19 ALLROFID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 20 CPLALLROFID     ) join IDs =     2    19       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 25 GLC             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 26 CPLGLC          ) join IDs =     2    25       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 23 ALLGLCID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 24 CPLALLGLCID     ) join IDs =     2    23       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 29 WAV             ) pelist   =     0     3     1 ( npes =     4) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 30 CPLWAV          ) join IDs =     2    29       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 27 ALLWAVID        ) join multiple comp IDs       ( npes =     4) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 28 CPLALLWAVID     ) join IDs =     2    27       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 33 ESP             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 34 CPLESP          ) join IDs =     2    33       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 31 ALLESPID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 32 CPLALLESPID     ) join IDs =     2    31       ( npes =     4) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 37 IAC             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 38 CPLIAC          ) join IDs =     2    37       ( npes =     4) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 35 ALLIACID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 36 CPLALLIACID     ) join IDs =     2    35       ( npes =     4) ( nthreads =  1)
(seq_comm_printcomms)     1     0     4     1  GLOBAL:
(seq_comm_printcomms)     2     0     4     1  CPL:
(seq_comm_printcomms)     3     0     4     1  ALLATMID:
(seq_comm_printcomms)     4     0     4     1  CPLALLATMID:
(seq_comm_printcomms)     5     0     4     1  ATM:
(seq_comm_printcomms)     6     0     4     1  CPLATM:
(seq_comm_printcomms)     7     0     4     1  ALLLNDID:
(seq_comm_printcomms)     8     0     4     1  CPLALLLNDID:
(seq_comm_printcomms)     9     0     4     1  LND:
(seq_comm_printcomms)    10     0     4     1  CPLLND:
(seq_comm_printcomms)    11     0     4     1  ALLICEID:
(seq_comm_printcomms)    12     0     4     1  CPLALLICEID:
(seq_comm_printcomms)    13     0     4     1  ICE:
(seq_comm_printcomms)    14     0     4     1  CPLICE:
(seq_comm_printcomms)    15     0     4     1  ALLOCNID:
(seq_comm_printcomms)    16     0     4     1  CPLALLOCNID:
(seq_comm_printcomms)    17     0     4     1  OCN:
(seq_comm_printcomms)    18     0     4     1  CPLOCN:
(seq_comm_printcomms)    19     0     4     1  ALLROFID:
(seq_comm_printcomms)    20     0     4     1  CPLALLROFID:
(seq_comm_printcomms)    21     0     4     1  ROF:
(seq_comm_printcomms)    22     0     4     1  CPLROF:
(seq_comm_printcomms)    23     0     4     1  ALLGLCID:
(seq_comm_printcomms)    24     0     4     1  CPLALLGLCID:
(seq_comm_printcomms)    25     0     4     1  GLC:
(seq_comm_printcomms)    26     0     4     1  CPLGLC:
(seq_comm_printcomms)    27     0     4     1  ALLWAVID:
(seq_comm_printcomms)    28     0     4     1  CPLALLWAVID:
(seq_comm_printcomms)    29     0     4     1  WAV:
(seq_comm_printcomms)    30     0     4     1  CPLWAV:
(seq_comm_printcomms)    31     0     1     1  ALLESPID:
(seq_comm_printcomms)    32     0     4     1  CPLALLESPID:
(seq_comm_printcomms)    33     0     1     1  ESP:
(seq_comm_printcomms)    34     0     4     1  CPLESP:
(seq_comm_printcomms)    35     0     1     1  ALLIACID:
(seq_comm_printcomms)    36     0     4     1  CPLALLIACID:
(seq_comm_printcomms)    37     0     1     1  IAC:
(seq_comm_printcomms)    38     0     4     1  CPLIAC:
 (t_initf) Read in prof_inparm namelist from: drv_in
 (t_initf) Using profile_disable=          F
 (t_initf)       profile_timer=                      4
 (t_initf)       profile_depth_limit=                4
 (t_initf)       profile_detail_limit=               2
 (t_initf)       profile_barrier=          F
 (t_initf)       profile_outpe_num=                  1
 (t_initf)       profile_outpe_stride=               0
 (t_initf)       profile_single_file=      F
 (t_initf)       profile_global_stats=     T
 (t_initf)       profile_ovhd_measurement= F
 (t_initf)       profile_add_detail=       F
 (t_initf)       profile_papi_enable=      F
           4 pes participating in computation
 -----------------------------------
 TASK#  NAME
  0  DESKTOP-KSVJLVA
  1  DESKTOP-KSVJLVA
  2  DESKTOP-KSVJLVA
  3  DESKTOP-KSVJLVA
*** The MPI_Info_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
*** The MPI_Info_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[DESKTOP-KSVJLVA:21529] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[DESKTOP-KSVJLVA:21531] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by nicodgomez** [comment]
The error appears at the end of the log file.

**Comment by nicodgomez** [comment]
The MPI_Info_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.

**Comment by hzhou** [comment]
That particular error message is from Open MPI, not MPICH.

**Comment by hzhou** [comment]
Close the issue as it is an Open MPI issue. Please feel free to re-open if it is believed otherwise.
