### ISSUE TITLE
configure: --with-pmi=cray no longer needed

### ISSUE THREAD

**Issue by RaymondMichael** [pmodels/mpich#6428]
As of CPE 23.02, the --with-pmi=cray option is no longer needed in MPICH. HPE's pmi2.h uses PMI2_keyval_t instead of PMI_keyval_t now. HPE's PMI2 also supports PMI2_Set_threaded(). The use of --with-pmi=cray causes mpir_pmi.c to be compiled expecting pmi2.h to use PMI_keyval_t instead of PMI2_keyval_t, which causes compilation errors. HPE's PMI headers should be expected to be the same as MPICH's.

When people read the configure --help message and see "cray", they're getting confused and think they should still use it. They likely just need to tell configure where to find the appropriate header and library.

**Comment by hzhou** [comment]
I'll be glad to get rid of that option :)

**Comment by RaymondMichael** [comment]
In the last few months I've fixed numerous problems with our headers and with functions that didn't actually exist or weren't supported. If you find that our PMI-1 support is still broken, please let me know.
I agree with your course of action.
