### ISSUE TITLE
Compilation of `--enable-fast=all --with-device=ch4` takes exceedingly long

### ISSUE THREAD

**Issue by giordano** [pmodels/mpich#6434]
To reproduce: configure MPICH with
```
./configure --enable-fast=all --with-device=ch4 --enable-shared=yes --enable-static=no --disable-dependency-tracking --disable-opencl
```
then run `make`.  Compilation can take between ~10 minutes  and several *hours*, depending on the target.  It always consistently gets stuck at `src/mpi/coll/mpir_coll.c`, if you look at `top`/`htop` you can see the `cc1` process taking a very long time to compile this single file.

Screenshot of `htop` showing the `cc1` processes for different targets running for over one hour
![image](https://user-images.githubusercontent.com/765740/224170181-05d7543e-6fcc-4877-bb44-88dba0b8c872.png)

This is reproducible with MPICH 4.1.1, and current `main` (https://github.com/pmodels/mpich/commit/86660aebf24473f43209a63cfdaa481472618122).  I could reproduce this long compilation with GCC 4.8.5, 7.1.0, 8.1.0, 11.3.0, 12.1.0, and Clang 13.0.1, for basically all targets you can see listed in https://buildkite.com/julialang/yggdrasil/builds/1279.  Note that some jobs exceeded the 3-hour timeout, repeatedly.

Probably not all options I showed in the `./configure` line above are necessary, but my bet is on the combination `--enable-fast=all --with-device=ch4`.  When we were using `--with-device=ch3` compilation times were much more reasonable on all targets, of the order of 2-4 minutes (see for example https://buildkite.com/julialang/yggdrasil/builds/1277#0186bd4f-ec08-4c6a-9233-fa66cb8cfb3e).  To be clear, while the build jobs I showed are from [BinaryBuilder.jl](https://binarybuilder.org/), I could reproduce the long compilation of `src/mpi/coll/mpir_coll.c` outside of it, on Ubuntu 22.04 (this is the GCC 11.3.0 I mentioned above).

First spotted in https://github.com/JuliaPackaging/Yggdrasil/pull/6355

**Comment by hzhou** [comment]
`--enable-fast=all` is the same as `--enable-fast=O2,ndebug,alwaysinline`. It is the `alwaysinline` option makes the compilation extremely slow, and honestly, with arguable benefits. I would suggest replace the option with `--enable-fast=O2,ndebug`. You may also consider higher optimization levels than `O2`.

**Comment by giordano** [comment]
Thanks, I can confirm that `--enable-fast=O3,ndebug --with-device=ch4` has a much more reasonable build time, around ~5 minutes for basically all platforms.  Wow, `alwaysinline` is quite a big performance hit with the default device configuration.  I noticed that `alwaysinline` (eventually) produces a 50% larger libmpi (~75 MB vs ~50 MB), too.

**Comment by hzhou** [comment]
> Wow, `alwaysinline` is quite a big performance hit with the default device configuration.

You mean a big hit to build time.

**Comment by giordano** [comment]
Yes, _build_ performance.
