### ISSUE TITLE
Different g++ for host and CUDA sources

### ISSUE THREAD

**Issue by prj-** [pmodels/mpich#6447]
I would like to compile host C++ sources with `g++-12` and CUDA sources with `nvcc -ccbin g++-11`. That does not work if I pass `NVCC="nvcc -ccbin g++-11"` to configure. I see during configure:
```
[...]
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking for cudaStreamSynchronize in -lcudart... yes
configure: WARNING: Using user-provided nvcc: 'nvcc -ccbin g++-11'
checking whether nvcc works... yes
checking if gcc can link libstdc++... yes
[...]
```
But during make, I get:
```
[...]
  132 | #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
gmake[2]: *** [Makefile:14165: src/backend/cuda/pup/yaksuri_cudai_pup_blkhindx__Bool.lo] Error 1
[...]
```
which suggests that the flag is not being used. What's the proper way to proceed to get the build going, please?

**Comment by hzhou** [comment]
@prj- How about set `NVCC="nvcc -allow-unsupported-compiler` ?

**Comment by prj-** [comment]
Of course, that doesn't work. Otherwise, it would mean that the option after the compiler is being properly passed to the submodule, but if that where the case, then there would have been no issue in the first place since g++-11 is compatible with CUDA 11.8.
```
$ ./configure [...] NVCC="/software/cuda/11.8/bin/nvcc -allow-unsupported-compiler"
[...]
/software/cuda/11.8/bin/../targets/x86_64-linux/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
gmake[2]: *** [Makefile:14165: src/backend/cuda/pup/yaksuri_cudai_pup__Bool.lo] Error 1
```

**Comment by hzhou** [comment]
@prj- Could you confirm the MPICH version you are using? There is a commit (https://github.com/pmodels/mpich/pull/6384) in the latest main branch should have fixed this behavior. Could you testing by checking out mpich from github?

**Comment by prj-** [comment]
I was using `mpich-4.1.1`, the problem remains the same with a fresh clone of `main` (`86910e2d044b36895977dd25846502bbaf8ba60a`).

**Comment by hzhou** [comment]
Ref: https://github.com/pmodels/yaksa/pull/243

**Comment by hzhou** [comment]
@prj- Thanks you for reporting the issue and for your patience. I believe https://github.com/pmodels/yaksa/pull/243 should fix the behavior. For the meanwhile, as @raffenet pointed out, you can try set `NVCC_FLAGS=-allow-unsupported-compiler` to work around.

**Comment by prj-** [comment]
No problem, thank you for your troubleshooting! I can confirm that `NVCC="/software/cuda/11.8/bin/nvcc -ccbin g++-11" NVCC_FLAGS=" -ccbin g++-11"` gets the build going with `CXX=g++-12`.
