### ISSUE TITLE
-Werror passed to UCX module

### ISSUE THREAD

**Issue by prj-** [pmodels/mpich#6448]
I'm configuring with `CFLAGS="-Wextra -Wpedantic -Wno-unused-parameter -Wno-cast-function-type -g -fPIC"`. For a reason I'm not sure I understand, `-Werror` is added for the compilation of UCX, which results in compilation failure. Here is one example
```
petsc/arch-linux-c-debug/externalpackages/mpich-4.1.1/modules/ucx/src/ucm/util/log.h:21:39: error: ISO C does not support ‘__FUNCTION__’ predefined identifier [-Werror=pedantic]
   21 |         __ucm_log(__FILE__, __LINE__, __FUNCTION__, (_level), _message, \
      |                                       ^~~~~~~~~~~~
```
Is it possible not to add the flag `-Werror` in combination with the other MPICH `CFLAGS`? I'm currently bypassing the issue by adding `-Wno-error` to `CFLAGS`.

**Comment by raffenet** [comment]
UCX puts `-Werror` in `CFLAGS` at the beginning of configure. We should patch our submodule to remove it because it causes too much trouble. https://github.com/openucx/ucx/issues/8898#issuecomment-1441126808

I'll make a PR.
