### ISSUE TITLE
[QUESTION] Is there an analog of ompi_info in MPICH?

### ISSUE THREAD

**Issue by YarShev** [pmodels/mpich#6476]
Hi there,

There is ompi_info command, which provides detailed information about the Open MPI installation. I wonder if there is an analog of that command in MPICH?

Thanks in advance!

**Comment by raffenet** [comment]
Try `mpichversion`.

**Comment by YarShev** [comment]
I installed `mpi4py-mpich` from PyPI and tried `mpichversion`. Got the following.

```bash
Command 'mpichversion' not found, but can be installed with:
sudo apt install mpich
```

Should I ask for the command in mpi4py repo?

**Comment by raffenet** [comment]
Why not do what the error message suggests?
```
sudo apt install mpich
```
Then try again.

**Comment by hzhou** [comment]
Is this what you looking for?
```
$ src/env/mpivars
387 MPI Control Variables
        MPIR_CVAR_BARRIER_INTRA_ALGORITHM=0     SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    Variable to select barrier algorithm
auto - Internal algorithm selection (can be overridden with MPIR_CVAR_COLL_SELECTION_TUNING_JSON_FILE)
nb            - Force nonblocking algorithm
smp           - Force smp algorithm
k_dissemination - Force high radix dissemination algorithm
recexch       - Force recursive exchange algorithm
        MPIR_CVAR_BARRIER_INTER_ALGORITHM=0     SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    Variable to select barrier algorithm
auto - Internal algorithm selection (can be overridden with MPIR_CVAR_COLL_SELECTION_TUNING_JSON_FILE)
bcast - Force bcast algorithm
nb    - Force nonblocking algorithm
        MPIR_CVAR_BARRIER_DISSEM_KVAL   =2      SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    k value for dissemination exchange based barrier algorithm
        MPIR_CVAR_BARRIER_RECEXCH_KVAL  =2      SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    k value for recursive exchange based allreduce based barrier
        MPIR_CVAR_BARRIER_RECEXCH_SINGLE_PHASE_RECV=0   SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    This CVAR controls whether the recv is posted for one phase or two phases in recexch algos. By default, we post the recvs for 2 phases.
        MPIR_CVAR_IBARRIER_RECEXCH_KVAL =2      SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    k value for recursive exchange based ibarrier
        MPIR_CVAR_IBARRIER_DISSEM_KVAL  =2      SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    k value for dissemination exchange based ibarrier
        MPIR_CVAR_IBARRIER_INTRA_ALGORITHM=0    SCOPE_ALL_EQ    No-object       MPI_INT VERBOSITY_USER_BASIC    Variable to select ibarrier algorithm
...
```

**Comment by YarShev** [comment]
This is probably the case. I do not see any of CMA related env vars. Is CMA enabled by default? Also, which env vars would you recommend me to set in order to get best performance?

**Comment by hzhou** [comment]
MPICH does not support CMA at the moment. We support XPMEM (https://github.com/hpc/xpmem) for 1-copy interprocess communication. Performance tuning is often application specific. Unless you are doing specific tuning studies, we recommend using the default. If certain CVARs will *always* result in better performance, we certainly will set that to default. FYI, the 1-copy algorithm is only good for large messages. In addition, the shared memory based 2-copy algorithm uses pipeline mechanism and the "2-" copy may concurrently take place in sender/receiver processes respectively, so the overall performance gain from 1-copy algorithm is limited.

**Comment by YarShev** [comment]
@raffenet, @hzhou, thank you for answering my questions. That makes sense to me so closing the issue.

**Comment by YarShev** [comment]
@hzhou, just a friendly reminder regarding the question above.

**Comment by hzhou** [comment]
@YarShev Sorry about the delayed response. The large message threshold typically depends on the overhead of mapping virtual addresses across the processes. Our current XPMEM threshold is set at 16KB. There is also a caching mechanism to amortize the overhead. So if the application is repeatedly sending messages from the same buffer, it may be beneficial to use a lower threshold.

**Comment by YarShev** [comment]
@hzhou, i.e. if the application is repeatedly sending messages from the same buffer, it may be beneficial to use interim shared memory (aka the shared memory based 2-copy algorithm), right?

**Comment by hzhou** [comment]
If the application is repeatedly sending messages from the same buffer, the inter-process mapping (IPC such as CMA/XPMEM) should provide better performance because the mapping overhead is amortized over many repetitions. Shared-memory 2-copy algorithm is good generally.

**Comment by YarShev** [comment]
> In addition, the shared memory based 2-copy algorithm uses pipeline mechanism and the "2-" copy may concurrently take place in sender/receiver processes respectively, so the overall performance gain from 1-copy algorithm is limited.

Just to clarify one thing. I understand that the "2-" copy may concurrently take place in sender/receiver processes respectively but if the application is repeatedly sending messages from the same buffer in "2-" copy algorithm, is it possible that the sender may not copy the data into the shared memory so the receiver just reads the data out of the shared memory right away?

**Comment by hzhou** [comment]
No, the cells (intermediate shared memory buffers in the 2-copy algorithm) are not persistent.
