### ISSUE TITLE
snprintf's return value

### ISSUE THREAD

**Issue by wkliao** [pmodels/mpich#6489]
https://github.com/pmodels/mpich/blob/16da9c756c7e8e51d2ac40b3a0add1c4960439b2/src/mpl/src/str/mpl_str.c#L159

I assume MPL_snprintf mimics snprintf. According to the manual of
snprintf, `out_str` should not advance one space.
```
      These functions return the number of characters printed (not including
      the trailing `\0' used to end output to strings), except for snprintf()
      and vsnprintf(), which return the number of characters that would have
      been printed if the size were unlimited (again, not including the final
      `\0').  These functions return a negative value if an error occurs.
```

Here is a test program where snprintf returns 2, but MPL_snprintf return 3.
```
#include <stdio.h>
int main(int argc, char *argv[])
{
    char value[64], *p;
    int i, remain, incr, ranklist[4]={0,1,2,3};

    p = value;
    for (i=0; i<4; i++) {
        remain = 64 - (p - value);
        incr = MPL_snprintf(p, remain, "%d ", ranklist[i]);
        // incr = snprintf(p, remain, "%d ", ranklist[i]);
        if (incr >= remain)
            break;
        p += incr;
    }
    printf("value=%s\n",value);
    return 0;
}
```

**Comment by raffenet** [comment]
Would folks be opposed to removing `MPL_snprintf` entirely? `snprintf` is a C99 feature which we now require from the C environment. I had a branch for at some point that I can dig up and rebase.

**Comment by raffenet** [comment]
@wkliao what system/compiler are you using that triggers the use of the fallback `MPL_snprintf`? Can you share `src/mpl/config.log`?
