### ISSUE TITLE
SEGFAULT error when building mpich 4.1.1 with more than 16 cores

### ISSUE THREAD

**Issue by HathewayWill** [pmodels/mpich#6491]
Commands Used:
```
  cd $WRF_FOLDER/Downloads
  tar -xvzf mpich-4.1.1.tar.gz
  cd mpich-4.1.1/
  F90= ./configure --prefix=$DIR/MPICH --with-device=ch3 --enable-g FFLAGS=$fallow_argument FCFLAGS=$fallow_argument

  make -j $CPU_HALF_EVEN 2>&1 | tee make.log
  make -j $CPU_HALF_EVEN install 2>&1 | tee make.install.log
```

CPU_HALF_EVEN = 16 
CPU_HALF_EVEN = 32

16 cores are successfully built.  Anything greater fails.
[config16core.log](https://github.com/pmodels/mpich/files/11304905/config16core.log)
[config32core.log](https://github.com/pmodels/mpich/files/11304906/config32core.log)
[make16core.log](https://github.com/pmodels/mpich/files/11304907/make16core.log)
[make32core.log](https://github.com/pmodels/mpich/files/11304908/make32core.log)

See attached documents for configure log and  make log.

**Comment by hzhou** [comment]
> How do you know about the diminishing returns. I'm still very new to using multi-core processing commands, so any information you can provide about how 16 is about the same as 32 would be great.

We build MPICH many times so have some experience. 😃

**Comment by HathewayWill** [comment]
Does the same apply for MPI run?

**Comment by hzhou** [comment]
The parallel make only affects build time, it has no effect on the built binaries or runtime.
