### ISSUE TITLE
Bogus `-Wtype-safety` warnings with clang when using const buffers

### ISSUE THREAD

**Issue by msimberg** [pmodels/mpich#6496]
MPICH uses attributes from clang that are supposed to help catch type errors where the type of a buffer is not the same as the `MPI_Datatype` passed in to a function (https://clang.llvm.org/docs/AttributeReference.html#type-safety-checking). In functions that take a `const void*` buffer clang reports bogus (as far as I can tell) warnings where the data type is correct, but the constness is different. E.g.
```
const int x;
MPI_Send(&x, 1, MPI_INT, 1, 0, MPI_COMM_WORLD);
```
reports `warning: argument type 'const int *' doesn't match specified 'MPI' type tag that requires 'int *' [-Wtype-safety]`. The only difference is `const` and this call should not trigger a warning.

Workarounds include:
- Disabling `-Wtype-safety` either locally or globally. This is not satisfying because it completely turns off checking and mismatches are not at all reported. E.g.
```
int x;
MPI_Send(&x, 1, MPI_CHAR, 1, 0, MPI_COMM_WORLD);
```
would not produce a warning.
- `const_cast` because we know `MPI_Send` anyway takes a `const` pointer but this is verbose and requires repeating the type:
```
const int x;
MPI_Send(const_cast<int*>(&x), 1, MPI_INT, 1, 0, MPI_COMM_WORLD);
```
- Making a const `MPI_INT`. This is again verbose and requires repeating the type:
```
auto const MPI_CONST_INT = MPI_INT;
const int x;
MPI_Send(&x, 1, MPI_CONST_INT, 1, 0, MPI_COMM_WORLD);
```
- Disable the attribute when configuring MPICH. This is not always an option.

Here's a short reproducer on godbolt (without MPICH, but using the attributes): https://godbolt.org/z/M8P1oqz44.

I'm not intimately familiar with neither the MPICH codebase nor the clang attributes so these questions are a bit naive:
- Is this expected or can I avoid this warning without workarounds?
- Do you think this warning can be silenced in MPICH itself?
- Do you think this is a clang issue (the attribute needs additional properties to consider `int*` and `const int*` the same)?

**Comment by hzhou** [comment]
I believe this is a clang issue.

**Comment by msimberg** [comment]
Fair enough, I'll open an issue there as well and link to it here. Thanks for the response.

**Comment by msimberg** [comment]
I cross-posted the issue over here: https://github.com/llvm/llvm-project/issues/62512.

**Comment by hzhou** [comment]
Refer to `configure` https://github.com/pmodels/mpich/blob/11eff4f158b6aaf9a65e2b6225f88d4c5446fb69/configure.ac#L3521-L3544. We actually check for this exact issue when we configure MPICH. I think in this case the compiler used for compiling mpi code is not the same compiler that was used for building MPICH. 

Anyway, try pass `-DNO_TAGS_WITH_MODIFIERS` to `CFLAGS` should suppress the warnings.

**Comment by hzhou** [comment]
The above comment should resolve the issue. If not, feel free to reopen.

**Comment by msimberg** [comment]
Thanks for the response @hzhou! I wasn't aware of that config check. I suspect something isn't the way it should be. The same compiler is used for mpich and for the dependent application. Additionally, I think defining `NO_TAGS_WITH_MODIFIERS` won't work because the generated `mpi.h` header has a `#undef NO_TAGS_WITH_MODIFIERS` which will undo the definition. I will do some more digging and get back to you.

**Comment by msimberg** [comment]
@hzhou I looked into this a bit more and it turns out to be basically a problem with how spack handles `-Werror`. However, to help resolve it on the spack side, would you be open to a PR which changes the `-Werror` in https://github.com/pmodels/mpich/blob/11eff4f158b6aaf9a65e2b6225f88d4c5446fb69/configure.ac#L3521-L3544 to the more specific `-Werror=type-safety`? This would allow us to only let `-Werror=type-safety` be an error on the space side without making unrelated warnings into errors.
