### ISSUE TITLE
Have MPICH read from a global config file

### ISSUE THREAD

**Issue by RaymondMichael** [pmodels/mpich#6501]
We have customers who would like to set default values for MPICH CVARs that are difficult for their users to override. As an example, there are GPU variables that if set incorrectly, or not set at all, can result in machine hangs. They would like MPICH to check for variable settings upon launch from a file, instead of just checking the user's environment. While they could put these settings into existing files in /etc to modify user environments, they've had problems with users overriding the values they're supposed to use.
The attached patch against MPICH 3.4a2 is one way we could accomplish this. It has MPI_Init() read from /etc/mpich.conf. The files is organized as lines of text formatted as KEY=VALUE. By default, if KEY is already set, then the existing value is kept. If a line in the file is formatted as KEY:force=VALUE, then the VALUE overrides any existing value. 
[mpi.patch](https://github.com/pmodels/mpich/files/11389850/mpi.patch)

**Comment by hzhou** [comment]
I think we can support this feature. The important contribution here is the `KYE:force=VALUE` syntax, which is currently missing. My main concern is having these hidden settings can be a nightmare for user to debug. Also, the settings for one MPICH (e.g. CrayMPI) may affect testing/running of another MPICH (e.g. upstream). So I would suggest the following two additions:
* Add a configure option to set path to this config file. `/etc/mpich.conf` can be the default.
* Add debug output to `MPIR_CVAR_DEBUG_SUMMARY` to indicate that a global conf file is being read. Note that `MPIR_CVAR_DEBUG_CVARS` can be turned on to see the active cvars as they are being parsed.

**Comment by hzhou** [comment]
@RaymondMichael  Please review PR #6512
