### ISSUE TITLE
Configure fails with clang/16 as the C compiler

### ISSUE THREAD

**Issue by rgayatri23** [pmodels/mpich#6502]
I am trying to build mpich/4.1.1 with llvm/16 with fortran disabled. However I get the following issue. 
Any pointers?

```
rgayatri@pm:login:/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/src/mpich-4.1.1> clang --version
clang version 16.0.0 (git@github.com:llvm/llvm-project.git 055ee2257ff2c3a9f06a25d0acc2951d0b7e2d1f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /global/cfs/cdirs/nstaff/rgayatri/software/llvm/16/bin

rgayatri@pmr:login:/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/src/mpich-4.1.1> ./configure --prefix=$PWD/install/ CC=clang CXX=clang++ CFLAGS="--disable-f77 --disable-f90"
Configuring MPICH version 4.1.1 with  '--prefix=/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/src/mpich-4.1.1/install/' 'CC=clang' 'CXX=clang++' 'CFLAGS=--disable-f77 --disable-f90'
Running on system: Linux login18 5.14.21-150400.24.46_12.0.63_2.4_18.4__gea1b0de6bb-cray_shasta_c #1 SMP Wed Apr 26 08:37:34 UTC 2023 (ea1b0de) x86_64 x86_64 x86_64 GNU/Linux
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/src/mpich-4.1.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by raffenet** [comment]
Can you try without setting `'CFLAGS=--disable-f77 --disable-f90'`. I don't think the C compiler knows what to do with those flags. `config.log` should confirm if that is the issue.

**Comment by rgayatri23** [comment]
Ah yes thanks. That was the issue. I will just disable fortran by using the `--disable-fortran` option.

**Comment by rgayatri23** [comment]
Additionally, can I enable CUDA with llvm build? I am currently doing the following 
```
./configure --prefix=$PWD/install/ CC=clang CXX=clang++ --disable-fortran --with cuda=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7
```

But the build fails with the following error message
```
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking for cudaStreamSynchronize in -lcudart... yes
checking whether nvcc works... no
configure: error: CUDA was requested but it is not functional
configure: error: YAKSA configure failed
```

**Comment by raffenet** [comment]
Can you upload the output from `modules/yaksa/config.log`? `nvcc` has some strict compatibility requirements with the host compiler. The log might have more information.

**Comment by raffenet** [comment]
> /opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7/bin/../targets/x86_64-linux/include/crt/host_config.h:140:2: error: -- unsupported clang version! clang version must be less than 14 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
> #error -- unsupported clang version! clang version must be less than 14 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.

As I suspected, `nvcc` thinks it is not compatible with your version of `clang`. You can try adding `NVCC_FLAGS=-allow-unsupported-compiler` if you are brave.

**Comment by rgayatri23** [comment]
So it looks like this works depending on the llvm version for now: 

## llvm/13 works - as informed by the error message above. 
```
configure: WARNING: unrecognized options: --with-cuda
*****************************************************
***
*** device      : ch4:ofi (embedded libfabric)
*** shm feature : auto
*** gpu support : CUDA
***
  MPICH is configured with device ch4:ofi, which should work
  for TCP networks and any high-bandwidth interconnect
  supported by libfabric. MPICH can also be configured with
  "--with-device=ch4:ucx", which should work for TCP networks
  and any high-bandwidth interconnect supported by the UCX
  library. In addition, the legacy device ch3 (--with-device=ch3)
  is also available.
*****************************************************
Configuration completed.
```

## llvm/{14,15} - the configure command completes but does not build with cuda support
```
configure: WARNING: unrecognized options: --with-cuda
*****************************************************
***
*** device      : ch4:ofi (embedded libfabric)
*** shm feature : auto
*** gpu support : disabled
***
  MPICH is configured with device ch4:ofi, which should work
  for TCP networks and any high-bandwidth interconnect
  supported by libfabric. MPICH can also be configured with
  "--with-device=ch4:ucx", which should work for TCP networks
  and any high-bandwidth interconnect supported by the UCX
  library. In addition, the legacy device ch3 (--with-device=ch3)
  is also available.
*****************************************************
Configuration completed
```

## llvm/16 - The build fails with the same error message as before (even with the `-allow-unsupported-compiler` flag
```
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking for cudaStreamSynchronize in -lcudart... yes
checking whether nvcc works... no
configure: error: CUDA was requested but it is not functional
configure: error: YAKSA configure failed
```

The warning about `--with-cuda` option being unrecognized is an unrelated issue and is fixed now. Details are here from a previous issue #6436

**Comment by rgayatri23** [comment]
Following the conversation in #6447 , I added the option `NVCC=clang++` to the configure command and `NVCC_FLAGS=--allow-unsupported-compiler" along with the `-fPIE` LDFLAGS solved the issue.
