### ISSUE TITLE
Fortran 2008 and NVIDIA HPC Compiler

### ISSUE THREAD

**Issue by louspe-linaro** [pmodels/mpich#6505]
I was building MPICH 4.0.3 and 4.1.1 with NVHPC 23.3 and the `--disable-f08` option is now mandatory because Fortran 2008 features are being detected as supported as part of the configure script.

I previously tested with NVHPC 22.5  and this was not the case. 

MPICH will build successfully, however, when compiling an application with `mpif90` it reports an undefined reference:
```
/home/user/mpich/4.1.1/lib/libmpifort.so: undefined reference to `CFI_is_contiguous'
```

This issue is not observed when building with `--disable-f08`.

**Comment by ashterenli** [comment]
I can reproduce the issue, and confirm that `--disable-f08` helps.

**Comment by jeffhammond** [comment]
Try again with a 2024 release of the compiler.  NVHPC Fortran did not support CFI in 23.3.  The release was later in 2024.  If there are problems, please reopen the ticket (or create a new one) and tag me.
