### ISSUE TITLE
MPI_Comm_split_type with intercommunicators

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6515]
The MPI-4 standard does not explicitly say that `MPI_Comm_split_type()` cannot be used with intercommunicators. However, all or the wording and examples seem to indicate that this routine was thought as applying to intracommunicators. Moreover, I believe that for the three standard split types defined so far, intercommunicators would make little sense, as splits would be not well defined and/or be of no practical use.

MPICH does not explicitly error when `MPI_Comm_split_type()` is called with an intercommunicator. After some basic testing, in some cases (depending on the local/remote group sizes) the routine seems to work (an intercomm is returned, but have not tested beyoing that), but in other cases I'm gettin ga segmentation fault.

Before proceeding with further testing and proper reproducers, I would like to get a confirmation from your side about whether my assessment is correct, that is, `MPI_Comm_split_type()` should explicitly error (via the usual MPI error handling mechanism) if feed with an intercommunicator.

**Comment by hzhou** [comment]
Looks like we do support `MPI_Comm_split`, and by extension `MPI_Comm_split_type`, on intercomms.

**Comment by dalcinl** [comment]
`MPI_Comm_split` on intercomms is well defined and part of the MPI standard. My claim is that any support MPICH may seem to have for `MPI_Comm_split_type` on intercomms is either broken or incorrect.

For example, how is `MPI_COMM_TYPE_SHARED` supposed to work with an intercommunicator?

**Comment by hzhou** [comment]
> `MPI_Comm_split` on intercomms is well defined and part of the MPI standard. My claim is that any support MPICH may seem to have for `MPI_Comm_split_type` on intercomms is either broken or incorrect.
> 
> For example, how is `MPI_COMM_TYPE_SHARED` supposed to work with an intercommunicator?

Yeah, we do not actively considered intercomm in our current `MPI_Comm_split_type` code, but that seems to be negligence rather than an intention. Semantically, I think you can see `MPI_Comm_split_type` as an `MPI_Comm_split` with `color` value set to the instance id of the specific type, thus, should work by extension of `MPI_Comm_split`.  For example, `MPI_Comm_type_shared` effectively is `MPI_Comm_split` with `color` set to "node id" assuming each node forms a shared memory group.

**Comment by dalcinl** [comment]
So, do you agree with me on that `MPI_Comm_split_type` only makes sense with intracomms, and that the standard is not clear enough about this fact?

**Comment by hzhou** [comment]
No. I think `MPI_Comm_split_type` applies to intercomms the same way as `MPI_Comm_split` applies to intercomms.

**Comment by hzhou** [comment]
That said, practically, I don't think `MPI_Comm_split_type` on intercomm make much sense the same way that `MPI_Comm_split` make much sense over intercomm. But eitherway, the logic of `MPI_Comm_split` and `MPI_Comm_split_type` should be the same or consistent.

**Comment by dalcinl** [comment]
Then the following code segfaults if you run it on  a single node with an odd number of MPI processes. I would expect the split intercomm to be just a duplicate of the original intercomm.

```python
from mpi4py import MPI

basecomm = MPI.COMM_WORLD

size = basecomm.Get_size()
rank = basecomm.Get_rank()
if rank < size // 2 :
    color = 0
    local_leader = 0
    remote_leader = size // 2
else:
    color = 1
    local_leader = 0
    remote_leader = 0

intracomm = basecomm.Split(color, key=rank)
intercomm = intracomm.Create_intercomm(
    local_leader,
    basecomm,
    remote_leader
)

splitcomm = intercomm.Split_type(MPI.COMM_TYPE_SHARED)
if splitcomm != MPI.COMM_NULL:
    splitcomm.Free()

intracomm.Free()
intercomm.Free()
```

```
$ mpiexec -n 2 python x-inter.py
$ mpiexec -n 4 python x-inter.py
$ mpiexec -n 6 python x-inter.py
$ mpiexec -n 5 python x-inter.py

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 240130 RUNNING AT optiplex
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by hzhou** [comment]
I'll test your code later. But my initial test of following code seems working -
```
#include "mpi.h"
#include <stdio.h>

int main(void) {
    MPI_Init(NULL, NULL);

    MPI_Comm base_comm = MPI_COMM_WORLD;

    int size, rank;
    MPI_Comm_size(base_comm, &size);
    MPI_Comm_rank(base_comm, &rank);

    int color, local_leader, remote_leader;
    if (rank < size / 2) {
        color = 0;
        local_leader = 0;
        remote_leader = size/2;
    } else {
        color = 1;
        local_leader = 0;
        remote_leader = 0;
    }

    MPI_Comm split_comm, inter_comm;
    MPI_Comm_split(base_comm, color, rank, &split_comm);
    MPI_Intercomm_create(split_comm, local_leader, base_comm, remote_leader, 1234, &inter_comm);

    printf("%d/%d: split_comm = %x, inter_comm = %x\n", rank, size, split_comm, inter_comm);

    MPI_Comm type_comm;
    MPI_Comm_split_type(inter_comm, MPI_COMM_TYPE_SHARED, rank, MPI_INFO_NULL, &type_comm);

    printf("[%d] split_type: -> %x\n", rank, type_comm);

    MPI_Comm_free(&split_comm);
    MPI_Comm_free(&inter_comm);
    MPI_Finalize();
    return 0;
}

```

**Comment by dalcinl** [comment]
Yes, your code works on my side with branch main. My issues are with MPICH 4.0.3 ch3:nemesis from the Fedora 38 RPM packages.

I'll do some extra testing with the main branch and ch3 and report back the outcome. If everything is OK, then I we can close this issue.

**Comment by hzhou** [comment]
I see. Yes, I can reproduce the segfault with ch3.

**Comment by dalcinl** [comment]
More precisely, the issue is with `ch3:nemesis`, `ch3:sock` seems to work just fine.
