### ISSUE TITLE
libfabric/psm3: No HALs registered

### ISSUE THREAD

**Issue by dqwu** [pmodels/mpich#6518]
This issue has been reproduced on ANL CELS GCE nodes with Ubuntu 20 or 22.
* Not reproducible with mpich 4.0.3 (modules/libfabric/prov/psm3/VERSION is 3_1_0_0)
* Reproducible with mpich 4.1 or mpich 4.1.1 (modules/libfabric/prov/psm3/VERSION is 3_2_0_0)
* Reproducible with latest mpich main branch (modules/libfabric/prov/psm3/VERSION is 3_4_1_1)

Steps to reproduce
```
wget https://www.mpich.org/static/downloads/4.1.1/mpich-4.1.1.tar.gz
tar zxf mpich-4.1.1.tar.gz
cd mpich-4.1.1

./configure --prefix=/path/to/mpich/installation --disable-fortran --enable-static --disable-shared --with-libfabric=embedded
make -j8
make install

export PATH=/path/to/mpich/installation/bin:$PATH

cat <<EOF >> test_mpi.c
#include <mpi.h>
int main(int argc, char *argv[])
{
  MPI_Init(&argc, &argv);
  MPI_Finalize();

  return 0;
}
EOF

mpicc test_mpi.c
mpiexec -n 2 ./a.out
```
Error output
```
rank0.a.out: No HALs registered
rank1.a.out: No HALs registered
```
The error message is from modules/libfabric/prov/psm3/psm3/psm2_hal.c
```
static struct _psmi_hal_instance *psm3_hal_get_pi_inst(void)
{
	int i;
	psmi_hal_instance_t *p = NULL;

	// calls to HAL via psmi_hal_* within sysfs_init or have_active_unit
	// are not allowed.  The assert catches the resulting recursive call.
	psmi_assert(! psm3_examining_hal);
	if (psm3_hal_current_hal_instance)
		return psm3_hal_current_hal_instance;

	if (!psm3_num_hal) {
		_HFI_ERROR("No HALs registered\n");
		return NULL;
	}
	...
}
```

**Comment by raffenet** [comment]
In the meantime, you can add `--disable-psm3` to your configure line, which will pass it on to the embedded libfabric configuration and disable the psm3 provider entirely at build time.
