### ISSUE TITLE
mpirun on slurm

### ISSUE THREAD

**Issue by xixihaha1995** [pmodels/mpich#6539]
I'm testing one simple `./mpiapp.exe`  , repo [link,](https://github.com/xixihaha1995/mpich_slurm_experiments) on HPC with slurm as the recource manager.

The MPICHv3.0.4 is built by the following:
```
./configure --prefix=$DIR/mpich
```
### without slurm
if the slurm is not used, the application can be run as expected via the following script,

```
[lwu4@blog2 mpich_slurm_experiments]$ make run
mpirun -np 2 ./mpiapp.exe
Rank 0 from MPI_COMM_WORLD 1140850688 (size 2 ) at processor blog2
Rank 1 from MPI_COMM_WORLD 1140850688 (size 2 ) at processor blog2
```
### with slurm [mpirun]
```
#!/bin/bash

#SBATCH --account=communitybem
#SBATCH --time=00:01:00
#SBATCH --ntasks=3
#SBATCH --job-name=mpirun
#SBATCH --output=mpirun%j.out
#SBATCH --error=mpirun%j.err
# Set the directory where you want to install the software, Change to the source code directory
DIR="/home/lwu4/mpich_slurm_experiments"
cd $DIR
pwd
make
echo "Running on $(hostname)"
# Execute the program
mpirun ./mpiapp.exe
make clean
```

#### mpirun.out
```
/home/lwu4/mpich_slurm_experiments
make: Nothing to be done for 'all'.
Running on m199

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
rm -f mpiapp.exe
```

#### mpirun.err
```
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
```

### with slurm [srun]

The program didn't creash. 
**Howver**, it didn't run as expected.
All the running processes think themselves as `rank 0` with `MPI_Comm_World` size as 1.

#### srun.out

```
/home/lwu4/mpich_slurm_experiments
mpicc -Wall -Wextra -o mpiapp.exe mpiapp.c
Running on m199
Rank 0 from MPI_COMM_WORLD 1140850688 (size 1 ) at processor m199
Rank 0 from MPI_COMM_WORLD 1140850688 (size 1 ) at processor m199
Rank 0 from MPI_COMM_WORLD 1140850688 (size 1 ) at processor m199
rm -f mpiapp.exe
```

#### srun.err

```
[no error]
```

### MPI with slurm

It looks like special configuration is needed for WRF running on slurm.

> slurm
> -----
> Slurm is an external process manager not distributed with
> MPICH. MPICH's default process manager, hydra, has native support
> for Slurm and you can directly use it in Slurm environments (it will
> automatically detect Slurm and use Slurm capabilities). However, if
> you want to use the Slurm-provided "srun" process manager, you can use
> the "--with-pmi=slurm --with-pm=no" option with configure. Note that
> the "srun" process manager that comes with Slurm uses an older PMI
> standard which does not have some of the performance enhancements that
> hydra provides in Slurm environments.

So I tired to recompile MPICHv3.0.4 with the following:
`./configure --prefix=$DIR/mpich --with-slurm=/apps/s/slurm/latest`
However, I got the following error
```
checking for slurm/pmi.h... yes
checking for PMI_Init in -lpmi... no
configure: error: could not find the slurm libpmi.  Configure aborted
```

### ref

sample job submission script on NCAR
```
1 #! /bin/csh
2
3 #Cheyenne Submission
4 #PBS −N JOBNAME
5 #PBS −A XXX
6 #PBS −l wall tim e = 01: 00: 00
7 #PBS −q economy
8 #PBS −j oe
9 #PBS −m abe
10 #PBS −M EMAILADDRESS
11 #PBS −l select =1: ncpus=36: mpiprocs=36
12
13 ### Run the executable
14 mpiexec_mpt dplace −s 1 . / geogrid.exe
```

**Comment by raffenet** [comment]
> The MPICHv3.0.4 is built by the following:

Have you tried with a more recent version of MPICH? MPICH 3.0.4 is over 10 years old. 4.1.1 is the latest release. https://www.mpich.org/downloads/
