### ISSUE TITLE
Building MPICH4.1.1 is slow, taking almost an hour. 

### ISSUE THREAD

**Issue by fault-to1erance** [pmodels/mpich#6546]
When I build MPICH and run make, the speed is very slow. It almost takes me 1 hour.
MPICH4.1.1 is built by the following:
```tar -zxvf  mpich-4.1.1.tar.gz
./configure -prefix=/usr/local/mpich
make 
make install
```
My environment

```
Ubuntu 22.04.2 LTS
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
perl v5.34.0
GNU Make 4.3```

**Comment by hello-sources** [comment]
I also met this problem, it's too slow to build MPICH.

**Comment by fault-to1erance** [comment]
Using parallel make worked. Thanks!
