### ISSUE TITLE
MPI_Type_get_envelope for a type created by "_c" API

### ISSUE THREAD

**Issue by wkliao** [pmodels/mpich#6548]
When calling `MPI_Type_get_envelope` for a datatype created by
a datatype construct `_c` API results in an error. Below are the code
fragment used to test and the error messages.

```c
    int num_integers, num_addresses, num_datatypes, combiner;
    MPI_Count array_of_sizes[N], array_of_subsizes[N], array_of_starts[N];

    for (i=0; i<N; i++) {
        array_of_sizes[i] = 10;
        array_of_subsizes[i] = 10;
        array_of_starts[i] = 0;
    }

    MPI_Type_create_subarray_c(N, array_of_sizes, array_of_subsizes,
                               array_of_starts, MPI_ORDER_C,
                               MPI_DOUBLE, &ftype) ;
    MPI_Type_commit(&ftype);

    MPI_Type_get_envelope(ftype, &num_integers, &num_addresses,
                          &num_datatypes, &combiner);
```

Error message:
```condole
Fatal error in internal_Type_get_envelope: Other MPI error, error stack:
internal_Type_get_envelope(36206): MPI_Type_get_envelope(dtype=USER<subarray>, num_integers=0x7fffffffdbdc, num_addresses=0x7fffffffdbd8, num_datatypes=0x7fffffffdbd4, combiner=0x7fffffffdbd0) failed
MPIR_Type_get_envelope_impl(149).: use MPI_Type_get_envelope_c to query large count datatype
[unset]: PMIU_write error; fd=-1 buf=:cmd=abort exitcode=470455567 message=Fatal error in internal_Type_get_envelope: Other MPI error, error stack:
internal_Type_get_envelope(36206): MPI_Type_get_envelope(dtype=USER<subarray>, num_integers=0x7fffffffdbdc, num_addresses=0x7fffffffdbd8, num_datatypes=0x7fffffffdbd4, combiner=0x7fffffffdbd0) failed
MPIR_Type_get_envelope_impl(149).: use MPI_Type_get_envelope_c to query large count datatype
:
system msg for write_line failure : Bad file descriptor
```

**Comment by hzhou** [comment]
Replace with `MPI_Type_get_envelope_c`

**Comment by wkliao** [comment]
I understand that MPI_Type_get_envelope_c would work, but sometimes when developing a function, we do not know whether the datatype was created by `_c` constructors or not.

In addition, it would be great if MPI_Type_get_envelope can error out nicely in the above case.

**Comment by hzhou** [comment]
`MPI_Type_get_envelope_c` will work for all datatypes. For datatypes created by traditional constructors, the `num_counts` will be `0`.

**Comment by hzhou** [comment]
From MPI specification 4.0 page 159:
> If the MPI_TYPE_GET_ENVELOPE variant without num_large_counts is invoked with
> a datatype that requires an output value of num_large_counts > 0, then an error of class
> MPI_ERR_TYPE is raised.

I'll push a fix for it to return `MPI_ERR_TYPE` instead of `MPI_ERR_OTHER`

**Comment by hzhou** [comment]
> Should no error be returned if num_large_counts == 0?

For a datatype created by a datatype construct _c API, num_large_counts is always > 0.

**Comment by wkliao** [comment]
got it.
