### ISSUE TITLE
build: mpich/4.1.1 with nvhpc compilers leads to link error

### ISSUE THREAD

**Issue by rgayatri23** [pmodels/mpich#6576]
I am trying to build mpich/4.1.1 with `nvc` and `nvc++` as the C/C++ compilers.

Here is my configure command
```shell
 ./configure --prefix=install-path --enable-fast=O2 --with-pm=no --with-pmi=cray --with-xpmem=path-to-xpmem --with-wrapper-dl-type=rpath --enable-threads=multiple --enable-shared=yes --enable-static=no --with-namepublisher=file --with-libfabric=path-to-libfabric --with-device=ch4:ofi --with-cuda=path-to-cuda CC=nvc CXX=nvc++ FC=nvfortran F77=nvfortran NVCC=nvc++ NVCC_FLAGS=-allow-unsupported-compiler 'CPPFLAGS=-gpu=cc80' 'LIBS=-lpmi -lpmi2 -lfabric -lfabric -Wl,--as-needed,-lcudart,--no-as-needed -lcuda'  MPICHLIB_CFLAGS=-fPIC MPICHLIB_CXXFLAGS=-fPIC
``` 

This leads to the following error during linking stage of `make`
```shell
/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `Mcuda_compiled'
/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `__pgiLaunchKernelFromStub'
/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `__pgi_cuda_register_fat_binaryA'
/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `Mcuda_compiled'
make[2]: *** [Makefile:14864: src/env/mpivars] Error 2
```

I get the same error even when I use `nvcc` as the cuda compiler. 

Can someone take a look at the issue.

**Comment by hzhou** [comment]
I tried compiling the main branch with just setting CC=nvc and CXX=nvc++ seems to work. Could you try unset NVCC and NVCC_FLAGS see if it works? Could you save the make log?

**Comment by hzhou** [comment]
This patch may help - https://github.com/pmodels/yaksa/pull/243

**Comment by rgayatri23** [comment]
I tried without setting NVCC and NVCC_FLAGS and I hit the following error
```shell
aclocal-1.16: command not found
```

Do I need aclocal-1.16 ? The system I am testing on version 1.15.1

**Comment by hzhou** [comment]
Could you try `./atuogen.sh` first?

**Comment by hzhou** [comment]
> I also tried building the same from the main branch which has the patch you mentioned above. And that gave the following error
> 
> ```shell
> ./libtool: line 7485: cd: cray/lib: No such file or directory
> libtool:   error: cannot determine absolute directory name of 'cray/lib'
> make[2]: *** [Makefile:6707: lib/libmpi.la] Error 1
> make[2]: Leaving directory '/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/mpich_github'
> make[1]: *** [Makefile:18151: all-recursive] Error 1
> make[1]: Leaving directory '/global/cfs/cdirs/nstaff/rgayatri/prgenv/src/mpich/mpich_github'
> make: *** [Makefile:4155: all] Error 2
> ```

You may try `--with-pmi=[path]` directly where we expect to find `pmi.h` in `[path]/include` and `libpmi.so` in `[path]/lib`.
Alternatively, try `--with-pmi=oldcray` as a transitional option.

**Comment by rgayatri23** [comment]
The autogen fixed the aclocal issue but it still errors out with the `Mcuda_compiled` error as before. 
For the pmi issue, I passed the path to configure step.

**Comment by hzhou** [comment]
What is the version of `nvc`? I'll try find a system to reproduce this.

**Comment by rgayatri23** [comment]
> What is the version of `nvc`? I'll try find a system to reproduce this.
I am using nvhpc/22.7 .

**Comment by rgayatri23** [comment]
Update: I was able to get this to work with nvhpc/23.1 and `nvcc` as the CUDA compiler.

**Comment by hzhou** [comment]
Thanks for the update. I'll close this issue now. Reopen if issue persists.
