### ISSUE TITLE
regression: stdout get unexpected lines with traces pointing to PMI code.

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6592]
```
======================================================================
FAIL: testSuccess (__main__.TestRunCommand.testSuccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/mpi4py-testing/mpi4py-testing/mpi4py/demo/test-run/test_run.py", line 246, in testSuccess
    self.assertEqual(stderr, '')
AssertionError: '[0] 680 at [0x55a35136b7e0], src/util/mpir_pmi.c[303]\n' != ''
- [0] 680 at [0x55a35136b7e0], src/util/mpir_pmi.c[303]
```
Full logs can be found [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/5549556381/jobs/10137798614).
Are those memory leaks? 
Maybe a regression from #6580?

PS: I'm surprised MPICH's own test suite did not catch this issue before. Could it be that the issue is actually on mpi4py side?

**Comment by hzhou** [comment]
This commit will fix it - https://github.com/pmodels/mpich/pull/6591/commits/ab8eb7dbabb70bc7f28ab566573c8406a89a3d07.

The CI test preset the HWLOC_XMLFILE environment thus skips the code in question.

**Comment by dalcinl** [comment]
Just to confirm, the commit fixes the regression. Logs [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/5566553777).
