### ISSUE TITLE
Build error: could not determine the size of a Fortran INTEGER

### ISSUE THREAD

**Issue by daniloceano** [pmodels/mpich#6604]
Hello.

I am trying to compile MPICH 3.3.1 on Ubuntu 16.04 and I get the following:

`configure: error: Unable to configure with Fortran support because configure could not determine the size of a Fortran INTEGER.  Consider setting CROSS_F77_SIZEOF_INTEGER to the length in bytes of a Fortran INTEGER`

Configure options are:

`./configure --prefix=${LIBBASE} --with-cross=./cross_file `

I've seen on another issues that generating a cross-configure file might help but I couldn't find a way to do this.

Any help is appreciated

**Comment by hzhou** [comment]
A few questions:
* Are you cross-compiling?
* Do you need to use MPICH 3.3.1 or can you build the latest release?

**Comment by daniloceano** [comment]
@hzhou thanks for the reply.

As far as I can tell, I am not cross-compiling: I am building MPICH as it is a pre-requisite for another program.

As for the version. I do not need specifically 3.3.1 but I am not sure which versions would be compatible with the machine I am using.

**Comment by daniloceano** [comment]
@hzhou I tried and the same error occured

**Comment by hzhou** [comment]
Could you update load `config.log`?

**Comment by daniloceano** [comment]
Sure, here it is

[config.log](https://github.com/pmodels/mpich/files/12152634/config.log)

**Comment by hzhou** [comment]
> ./conftest: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory

The failure is due to not able to load `libgfortran.so`. Try locate where `libgfortran.so.5` is located on your system and add it to `LD_LIBRARY_PATH`

**Comment by daniloceano** [comment]
Thank you. I did that and now I am receiving the following:

> /p1-nemo/danilocs/mpas/MPAS-BRv8/local_software//libs/lib/libz.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> Makefile:8176: recipe for target 'lib/libmpifort.la' failed
> make[2]: *** [lib/libmpifort.la] Error 1
> make[2]: Leaving directory '/p1-nemo/danilocs/mpas/MPAS-BRv8/local_software/mpich-4.1.2'
> Makefile:31566: recipe for target 'install-recursive' failed
> make[1]: *** [install-recursive] Error 1
> make[1]: Leaving directory '/p1-nemo/danilocs/mpas/MPAS-BRv8/local_software/mpich-4.1.2'
> Makefile:31677: recipe for target 'install' failed
> make: *** [install] Error 2

Here it is the log file:
[config.log](https://github.com/pmodels/mpich/files/12162938/config.log)

**Comment by hzhou** [comment]
It says you have a bad `libz.a`. You should have a system `libz`. The one in your `/p1-nemo/danilocs/mpas/MPAS-BRv8/local_software//libs/lib/libz.a` is shadowing the system one. Try install gfortran in a separate path then you can set `LD_LIBRARY_PATH` without extra side effects.

**Comment by daniloceano** [comment]
That worked, thank you.
