### ISSUE TITLE
Shared memory usage of mpich and ucx

### ISSUE THREAD

**Issue by glory0369** [pmodels/mpich#6615]
I installed the mpich configuration statement as./configure --prefix=/root/zgy/software/mpich-4.1 --with-device=ch4:ucx - with - ucx = / opt/HPC/software/mpi/HPCX v2.7.4 / ucx_without_rocm - with - slurm = / opt/gridview/slurm
--with-ch4-shmmods=posix --disable-fortran ". The ucx version is 1.13.0. If I specify "-env MPIR_CVAR_DEVICE_COLLECTIVES none -env UCX_TLS rc,knem" at runtime, mpich specifies that shared memory is posix and ucx specifies that shared memory is knem. So what does shared memory look like at runtime?

**Comment by hzhou** [comment]
The option `--with-ch4-shmmods=posix` enables ch4-layer shared memory for intranode communication. UCX is only used for internode communication.

**Comment by hzhou** [comment]
You may set the environment variable `MPIR_CVAR_NO_LOCAL=1` to route all communication to ucx, in which case ucx will use its shared memory for on-node traffic.

**Comment by glory0369** [comment]
> 您可以设置环境变量`MPIR_CVAR_NO_LOCAL=1`以将所有通信路由到 ucx，在这种情况下，ucx 将使用其共享内存来处理节点上的流量。

Thank you for your reply. If you specify "--with-ch4-shmmods=auto" at compile time, what shared memory will mpich automatically use? Will ipc use it?

**Comment by hzhou** [comment]
> > 您可以设置环境变量`MPIR_CVAR_NO_LOCAL=1`以将所有通信路由到 ucx，在这种情况下，ucx 将使用其共享内存来处理节点上的流量。
> 
> Thank you for your reply. If you specify "--with-ch4-shmmods=auto" at compile time, what shared memory will mpich automatically use? Will ipc use it?

Currently the default when configured with ucx is to have ch4 shmmods disabled and let ucx handle intranode communications including IPC. This may change in the future.

**Comment by glory0369** [comment]
> > > 您可以设置环境变量`MPIR_CVAR_NO_LOCAL=1`以将所有通信路由到ucx，在这种情况下，ucx将使用其共享内存来处理节点上的流量。
> > 
> > 
> > 感谢你的回复。如果在编译时指定“--with-ch4-shmmods=auto”，mpich会自动使用什么共享内存？ipc会用吗？
> 
> 目前，使用 ucx 配置时的默认设置是禁用 ch4 shmmods，并让 ucx 处理包括 IPC 在内的节点内通信。这在未来可能会改变。

I have solved my doubts, thank you for your answer.
