### ISSUE TITLE
mpit: MPI_Pcontrol

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6616]
MPI_PCONTROL is specified to be a no-op unless a profiling library is running.

> The provision of MPI_PCONTROL as a no-op in the standard MPI library supports the collection of more detailed profiling information with source code that can still link against the standard MPI library.

MPICH imposes the following check.  I can't figure out if this is a valid check, but it's certainly not a no-op.

```
Attempting to use an MPI routine (internal_Pcontrol) before initializing or after finalizing MPICH
```

I am curious whether the MPICH team thinks `MPI_Pcontrol` should be callable before MPI is initialized.

**Comment by hzhou** [comment]
It is an oversight. I think MPI_Pcontrol should be allowed to be called before MPI_Init.
