### ISSUE TITLE
build: Error compiling on polaris and theta on gitlab-ci

### ISSUE THREAD

**Issue by sarich** [pmodels/mpich#6653]
Polaris and theta are both failing to compile on https://gitlab-ci.alcf.anl.gov/anl/pmodels/mpich/-/pipelines, both giving the same errors:
```
"src/util/mpir_pmi2.inc", line 219: error: identifier "PMI2_keyval_t" is undefined
                                 info_keyval_sizes, (const PMI2_keyval_t **) info_keyval_vectors,
                                                           ^

"src/util/mpir_pmi2.inc", line 220: error: identifier "PMI2_keyval_t" is undefined
                                 num_preput_keyval, (const PMI2_keyval_t *) preput_vector,
```
polaris was configured with:
```
export CC=nvc
./configure --prefix=/home/sarich/mpich-install --with-cuda=/soft/compilers/cuda
toolkit/cuda-11.4.4 --with-cuda-sm=80 --with-pmi=pmi2 --with-pmilib=oldcray --wi
th-pm=no --with-libfabric=/opt/cray/libfabric/1.11.0.4.125
```
theta with:
`./configure --prefix=/home/sarich/mpich-install --with-pmi=pmi2 --with-pmilib=oldcray --with-pm=no
`            

I believe the failure originated in commit 229b9a969 (@hzhou) . There was previously some logic for configuring with --with-pmilb=oldcray
and a section in src/util/mpir_pmi.c:
```
#elif defined(USE_PMI2_CRAY)
#define INFO_TYPE PMI_keyval_t
#define INFO_TYPE_KEY(kv) (kv).key
#define INFO_TYPE_VAL(kv) (kv).val
```
Removing the --with-pmilib=oldcray will let the code compile, but I don't understand it's purpose and if it's needed still.

**Comment by raffenet** [comment]
`--with-pmilib=oldcray` is legacy that we wish to deprecate and eventually delete. If the Cray PMI library can work without it, then that is the preferred configuration. I created #6655 because on at least one other system, I ran into a link issue because the oldcray option no longer guards the usage of `PMI2_Set_threaded.

**Comment by sarich** [comment]
The library built without that `--with-pmilib=oldcray` option, I didn't try to actually run anything with it. I figured it was going to need something like your #6655 edit and was hoping someone else would know how to fix it once I pointed it out. I'll try running some tests and see what happens.

**Comment by hzhou** [comment]
The ideal result is to just use `--with-pmi=path/to/cray/libpmi` or `--with-pmi2=path/to/cray/libpmi2`. Try these options first, and let us know whether it works.

**Comment by sarich** [comment]
Omitting the `--with-pmilib=oldcray` produces an executable cpi example, but submitting a job with `mpiexec -n 4 cpi` produces four separate one-processor executions.

`--with-pmi=/opt/cray/pe/pmi/6.1.2` and `--with-pmi2=/opt/cray/pe/pmi/6.1.2`
both fail to compile for the same reason as the original issue (`"PMI2_keyval_t" is undefined`)

**Comment by hzhou** [comment]
> `--with-pmi=/opt/cray/pe/pmi/6.1.2` and `--with-pmi2=/opt/cray/pe/pmi/6.1.2`
> both fail to compile for the same reason as the original issue (`"PMI2_keyval_t" is undefined`)

Okay, let's try fix this

**Comment by hzhou** [comment]
@sarich Could you give #6662 a try?

**Comment by sarich** [comment]
I'm getting the same problem as before on polaris where it's running four separate processes. I believe this ran fine using commit 713513618, I'm checking to make sure everything else with my test was the same.

**Comment by hzhou** [comment]
> I'm getting the same problem as before on polaris where it's running four separate processes. I believe this ran fine using commit [7135136](https://github.com/pmodels/mpich/commit/713513618f7f6f46dac513560c6919fe81dbf582), I'm checking to make sure everything else with my test was the same.

Make sure you configure with `--with-pmi=/opt/cray/pe/pmi/6.1.2` or `--with-pmi2=/opt/cray/pe/pmi/6.1.2`

**Comment by sarich** [comment]
No, I used --with-pmi=pmi2. I'll try again.

**Comment by jason-sarich** [comment]
Using --with-pmi=/opt/cray/pe/pmi/6.1.2 raises the configure error: 
configure: error: pmi.h or libpmi library not found. Did you specify --with-pmi= or --with-pmi-include= or --with-pmi-lib=?

Using --with-pmi2=/opt/cray/pe/pmi/6.1.2 I get a linking error:

/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `PMI2_Set_threaded'

**Comment by hzhou** [comment]
@sarich I updated #6662 adding a commit to fix `PMI2_Set_threaded`. Could you try it again?

**Comment by sarich** [comment]
OK, mpich is building now and cpi runs correctly on polaris
________________________________
