### ISSUE TITLE
Compile MPI app without CUDA using mpich built with CUDA support

### ISSUE THREAD

**Issue by rgayatri23** [pmodels/mpich#6667]
I am trying to compile a simple MPI code with no CUDA calls using mpich that was built with CUDA support.

```cpp 
#include <mpi.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char **argv)
{
  int rank, nprocs;
  char hostname[256];

  MPI_Init(&argc,&argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);

  gethostname(hostname,255);

  printf("Process number: %05d (out of %5d) on host %s with exe %s\n", rank, nprocs, hostname, argv[0]);

  MPI_Finalize();

  return 0;
}
```

The test compiles fine when it can find CUDA libs. Otherwise it fails at linking stage as it is looking for CUDA libs.

Isn't mpich build dynamic by default and should avoid such issues?

**Comment by hzhou** [comment]
The cuda library is dynamically linked, but not dynamically loaded (i.e. using `dlopen`).

**Comment by rgayatri23** [comment]
> The cuda library is dynamically linked, but not dynamically loaded (i.e. using `dlopen`).

So is there a way to do what I was trying?

**Comment by hzhou** [comment]
Not possible currently. You'll need to build MPICH separately without cuda in order to run on systems without cuda.

**Comment by rgayatri23** [comment]
Ah ok. Thanks for the clarification. Is there any work going on to support such a build feature?

**Comment by hzhou** [comment]
> Ah ok. Thanks for the clarification. Is there any work going on to support such a build feature?

Not currently. Thank you for the feedback. We will discuss and update.

**Comment by rgayatri23** [comment]
Thanks. I will close this issue in that case.
