### ISSUE TITLE
when running mpi_init I get: no CUDA-capable device is detected (CPU only nodes on perlmutter)

### ISSUE THREAD

**Issue by jjepson2** [pmodels/mpich#6686]
I am getting this error when I try to run on the CPU only nodes on perlmutter (the error occurs when calling mpi_init):

CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,173): no CUDA-capable device is detected

Any thoughts of what might be causing this? Or a workaround?

Thanks.

**Comment by jjepson2** [comment]
For further clarification, I am not interested in using CUDA for my application at present, and the CPU only nodes do not have a GPU attached.

**Comment by raffenet** [comment]
You can set `MPIR_CVAR_ENABLE_GPU=0` and it should prevent any CUDA initialization from happening at runtime.

**Comment by jjepson2** [comment]
Ok.  Just submitted a job script to try that now. I'll let you know if that works.

**Comment by jjepson2** [comment]
That fixed that error.  Now i am getting another error.  I will submit another ticket.
