### ISSUE TITLE
fortran: MPI_Alloc_mem mismatch in argument

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#6691]
[From discuss mailinglist]

I'm sort of new to MPICH and I'm encountering one call that works with Open MPI but not MPICH. As such, I'm wondering if I built MPICH incorrectly or incompletely (always easy to miss a configure flag!).

To wit, I have a code like:
 ```
program main
   use mpi
   use iso_fortran_env, only: INT64
   use iso_c_binding, only: C_PTR

   integer(kind=INT64) :: sz
   type (c_ptr) :: ptr

   call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)
end program main
```
 
If I compile with GCC 12.1 + Open MPI 4.1.3, all is well:
```
$ mpifort --showme:version

mpifort: Open MPI 4.1.3 (Language: Fortran)

mathomp4@discover23 ~/MPITests/CPtr master ?25

$ mpifort support_for_mpi_alloc_mem_cptr.F90

mathomp4@discover23 ~/MPITests/CPtr master ?25

$ echo $?

0
```
I'll also say Intel MPI builds this code as well.

But with MPICH 4.1.2 I just built:
```
$ mpifort support_for_mpi_alloc_mem_cptr.F90

support_for_mpi_alloc_mem_cptr.F90:9:53:

    9 |    call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)

      |                                                     1

Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
```
 

Now, my configure lines to Open MPI and MPICH are pretty boring, so the resulting mpiforts are as well:

```
$ mpifort -show

gfortran -I/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/include -pthread -I/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/lib -L/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

$ mpifort -show

gfortran -I/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/include -I/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/include -L/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/lib -lmpifort -Wl,-rpath -Wl,/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/lib -Wl,--enable-new-dtags -lmpi
```
 
But I see Open MPI has that "mpi_usempi_ignore_tkr", is it possible that's what is doing it?

Perhaps we just need to recode the code (using transfer, etc?)

EDIT:
The option flag doesn't seem to help:
```
$ mpifort -fallow-argument-mismatch support_for_mpi_alloc_mem_cptr.F90

support_for_mpi_alloc_mem_cptr.F90:9:53:

    9 |    call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)
      |                                                     1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
```
I did test and, yes, mpi_f08 does let it work. I think the issue is I'm not sure the library this is in can assume mpi_f08 support for all supported compilers.

**Comment by mathomp4** [comment]
Note that per MPI 3.1, I think this should be supported in `use mpi`:

https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node216.htm

> If the Fortran compiler provides `TYPE(C_PTR)`, then the following generic interface must be provided in the `mpi` module and should be provided in `mpif.h` through overloading, i.e., with the same routine name as the routine with `INTEGER(KIND=MPI_ADDRESS_KIND) BASEPTR`, but with a different specific procedure name:
> 
> ```
> INTERFACE MPI_ALLOC_MEM 
>     SUBROUTINE MPI_ALLOC_MEM(SIZE, INFO, BASEPTR, IERROR) 
>         IMPORT ::  MPI_ADDRESS_KIND 
>         INTEGER INFO, IERROR 
>         INTEGER(KIND=MPI_ADDRESS_KIND) SIZE, BASEPTR 
>     END SUBROUTINE 
>     SUBROUTINE MPI_ALLOC_MEM_CPTR(SIZE, INFO, BASEPTR, IERROR) 
>         USE, INTRINSIC ::  ISO_C_BINDING, ONLY : C_PTR 
>         IMPORT ::  MPI_ADDRESS_KIND 
>         INTEGER ::  INFO, IERROR 
>         INTEGER(KIND=MPI_ADDRESS_KIND) ::  SIZE 
>         TYPE(C_PTR) ::  BASEPTR 
>     END SUBROUTINE 
> END INTERFACE 
> ```
> The base procedure name of this overloaded function is `MPI_ALLOC_MEM_CPTR`. The implied specific procedure names are described in Section [Interface Specifications, Procedure Names, and the Profiling Interface ](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node412.htm#Node412).

But then again the MPI Standard is confusing to me at times!
