### ISSUE TITLE
mpi4.1: memory allocation kinds info

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#6707]
Add `mpi_memory_alloc_kind` and `mpi_assert_memory_alloc_kind`.

https://github.com/mpi-forum/mpi-issues/issues/580
https://github.com/mpi-forum/mpi-standard/pull/714

**Comment by dalcinl** [comment]
@raffenet I believe you can close this issue.

**Comment by raffenet** [comment]
Agreed. Thanks for the reminder.
