### ISSUE TITLE
ch3/sock: shared memory window failure with ch3:sock

### ISSUE THREAD

**Issue by jczhang07** [pmodels/mpich#6729]
With this MPICH,
```
$ mpichversion 
MPICH Version:          4.0.2
MPICH Release date:     Thu Apr  7 12:34:45 CDT 2022
MPICH Device:           ch3:sock
MPICH configure:        --prefix=/nfs/gce/projects/petsc/soft/u22.04/mpich-4.0.2 --enable-shared --with-device=ch3:sock --with-pm=hydra --enable-fast=no --enable-error-messages=all --enable-g=meminit --disable-java --without-hwloc --disable-opencl FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch
```

I ran this example on a single node,
```
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

/**
 * @brief Illustrate how to create a shared window.
 * @details This application consists in creating a shared window and interact
 * with it using direct memory accesses. Two MPI processes are used, each will
 * hold an integer initialised to 100. MPI process 0 will increment MPI process
 * 1's variable, and MPI process 1 will decrement MPI process 0's variable.
 * In this application, the overall shared window uses the default configuration
 * where it is made of contiguous data.
 *
 * This can be visualised as follows:
 *
 * - Start situation:
 *         Held on MPI process 0 | Held on MPI process 1
 *                         +-----+-----+
 *                         | 100 | 100 |
 *                         +-----+-----+
 *         My element = array[0] | My element = array[0]
 *       Peer element = array[1] | Peer element = array[-1]
 *
 * - End situation:
 *         Held on MPI process 0 | Held on MPI process 1
 *                         +-----+-----+
 *                         |  99 | 101 |
 *                         +-----+-----+
 *         My element = array[0] | My element = array[0]
 *       Peer element = array[1] | Peer element = array[-1]
 *
 * This code assumes MPI processes must be able to physically share memory.
 **/

int main(int argc, char *argv[])
{
   int err;
  MPI_Init(&argc, &argv);

  // Check that only 2 MPI processes are spawn
  int comm_size;
  MPI_Comm_size(MPI_COMM_WORLD, &comm_size);
  if (comm_size != 2) {
    printf("This application is meant to be run with 2 MPI processes, not %d.\n", comm_size);
    MPI_Abort(MPI_COMM_WORLD, EXIT_FAILURE);
  }

  // Get my rank
  int my_rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

  // Create the window
  const int ARRAY_SIZE = 1;
  int      *window_buffer;
  MPI_Win   window;
  err = MPI_Win_allocate_shared(ARRAY_SIZE * sizeof(int), sizeof(int), MPI_INFO_NULL, MPI_COMM_WORLD, &window_buffer, &window);
  printf("[MPI process %d] Window created with err=%d.\n", my_rank, err);
  MPI_Win_lock_all(MPI_MODE_NOCHECK, window);

  // Initialise my element
  *window_buffer = 100;
  printf("[MPI process %d] Value before direct write from MPI process %d: %d.\n", my_rank, comm_size - 1 - my_rank, *window_buffer);

  // Modify peer's element
  MPI_Win_sync(window);
  MPI_Barrier(MPI_COMM_WORLD);
  if (my_rank == 0) {
    window_buffer[1]++;
  } else {
    window_buffer[-1]--;
  }
  MPI_Win_sync(window);
  MPI_Barrier(MPI_COMM_WORLD);

  // Check end values
  printf("[MPI process %d] Value after direct write from MPI process %d: %d.\n", my_rank, comm_size - 1 - my_rank, *window_buffer);

  MPI_Win_unlock_all(window);
  // Destroy the window
  printf("[MPI process %d] Window destroyed.\n", my_rank);
  MPI_Win_free(&window);

  MPI_Finalize();

  return EXIT_SUCCESS;
}
```

and got

```
$ mpirun -n 2 ./ex0
[MPI process 0] Window created with err=0.
[MPI process 0] Value before direct write from MPI process 1: 100.
[MPI process 1] Window created with err=0.
[MPI process 1] Value before direct write from MPI process 0: 100.
[MPI process 0] Value after direct write from MPI process 1: 100.
[MPI process 0] Window destroyed.
[MPI process 1] Value after direct write from MPI process 0: 100.
[MPI process 1] Window destroyed.
free(): invalid pointer

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2189519 RUNNING AT petsc-gpu-01
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

**Comment by jeffhammond** [comment]
```c
err = MPI_Win_allocate_shared(ARRAY_SIZE * sizeof(int), sizeof(int), MPI_INFO_NULL, MPI_COMM_WORLD, &window_buffer, &window);
```
is erroneous unless one verifies explicitly that `MPI_COMM_WORLD` is equivalent to the communicator returned by `MPI_Comm_split_type(comm_type=MPI_COMM_TYPE_SHARED)`.

If `ch3:sock` supports no shared memory communication then this would not hold.

I guess the assumption is okay if `MPI_Win_allocate_shared` did not return an error, but I wonder if that is the problem.

**Comment by hzhou** [comment]
As @jeffhammond said, and the MPI standard quote, 
< It is the user’s responsibility to ensure that the communicator comm represents a group of
MPI processes that are in the same shared memory domain, i.e., that they can create a
shared memory segment that can be accessed by all processes in the group.

And the only way for users to ensure that is via `MPI_Comm_split_type(..., comm_type=MPI_COMM_TYPE_SHARED, ...)`

The example code resulted in a `free()` error at `MPI_Win_free` because the erroneous `window_buffer[-1]--` corrupts the internal metadata. 

FWIW, MPI-4.1 allows `MPI_Win_shared_query` to be called on window that is created with `MPI_Win_create` and `MPI_Win_allocate`. Thus one could also use `MPI_Win_shared_query` to obtain/verify the shared memory accessibility. This is enabled by https://github.com/pmodels/mpich/pull/6777.

I agree that `MPI_Win_allocate_shared` should return error if it couldn't allocate shared memory since user is assuming it. I'll make fix.

**Comment by jeffhammond** [comment]
> I agree that MPI_Win_allocate_shared should return error if it couldn't allocate shared memory since user is assuming it. I'll make fix.

MPI_Win_allocate_shared on MPI_COMM_SELF should not allocate shared memory and should not return an error, even if it is a silly use case.  Similarly, MPI_COMM_WORLD won't lead to shared memory with 1 process.

I think current behavior of MPICH is correct and there is no obligation to try to infer user intent from incorrect programs.

**Comment by hzhou** [comment]
> > I agree that MPI_Win_allocate_shared should return error if it couldn't allocate shared memory since user is assuming it. I'll make fix.
> 
> MPI_Win_allocate_shared on MPI_COMM_SELF should not allocate shared memory and should not return an error, even if it is a silly use case. Similarly, MPI_COMM_WORLD won't lead to shared memory with 1 process.
> 

Those two cases do not result in error. The error case is calling `MPI_Win_allocate_shared` on a communicator with `size > 1` and it is unable to allocate shared memory between all processes.

**Comment by jeffhammond** [comment]
Sure, but unless that communicator is equivalent to one that was produced by MPI_Comm_split_type(MPI_COMM_TYPE_SHARED), the program is erroneous.  I suppose this is one way to detect erroneous programs.
