### ISSUE TITLE
mpi4.1: MPI_Remove_error_{class,code,string}

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#6760]
https://github.com/mpi-forum/mpi-issues/issues/283
https://github.com/mpi-forum/mpi-standard/pull/166

**Comment by raffenet** [comment]
We implemented these when "delete" was the proposal. Just need to rename and remove MPIX.

**Comment by hzhou** [comment]
Where was the discussion that these routines are renamed into "_Remove_"?

**Comment by raffenet** [comment]
I don't see explicit discussion, but the first commit in this PR contains remnants of the old names. https://github.com/mpi-forum/mpi-standard/pull/166

**Comment by raffenet** [comment]
Oh, it says in the commit message:
```
Make changes from 2021-09 meeting

* Rename functions from CLEAR/DELETE to REMOVE (for now).
* Correct some minor English errors.
* Add clarification about user-defined in appropriate places.
* Clarify what thread-safety is required for adding an error string
```
