### ISSUE TITLE
mpi4.1: add info key `mpi_accumulate_granularity` to specify a desired sychronization granularity of accumulate operations.

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#6773]
mpi-forum/mpi-standard#749

`mpi_accumulate_granularity` provides a hint to implementations about the desired synchronization granularity for accumulate operations, i.e., the size of memory ranges in bytes for which the implementation should acquire a synchronization primitive to ensure atomicity of updates.
If the specified granularity is not divisible by the size of the type used in an accumulate operation, it should be treated as if it was the next multiple of the element size.
For example, a granularity of 1 byte  should be treated as 8 in an accumulate operation using `MPI_UINT64_T`.
By default, this info key is set to 0, which leaves the choice of synchronization granularity to the implementation.
If specified, all mpi processes in the group of a window must supply the same value.

### User Advice
Small synchronization granularities may provide improved latencies for accumulate operations with few elements and potentially increase concurrency of updates, at the cost of lower throughput.
For example, a value matching the size of a type involved in an accumulate operation may enable implementations to use atomic memory operations instead of mutual exclusion devices.
Larger synchronization granularities may yield higher throughput of accumulate operation with large numbers of elements due to lower synchronization costs, potentially at the expense of higher latency for accumulate operations with few elements, e.g., if atomic memory operations are not employed.
By dividing larger accumulate operations into smaller segments, concurrent accumulate operations to the same window memory may update different segments in parallel.

### implementors Advice
Implementations are encouraged to avoid mutual exclusion devices in cases where the granularity is small enough to warrant the use of atomic memory operations.
For larger granularities, implementations should use this info value as a hint to partition the window memory into zones of mutual exclusion to enable segmentation of large accumulate operations.

**Comment by hzhou** [comment]
PR 6774 checks and made available this info hints. We should, as TODO, follow up to explore its performance benefit.
