### ISSUE TITLE
fortran: MPI_Type_create_f90_XXX with --disable-fortran

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6780]
If we  `./configure --disable-fortran`, then the `MPI_Type_create_f90_XXX`  symbol is missing from `libmpi.so`.

Would it be possible to generate these routines anyway?  Rationale: If for whatever reason a power user decides to build MPICH without Fortran support, a pre-built binary (e.g. mpi4py conda-forge packages and Python wheels) would not be able to load due to missing symbols in `libmpi.so`. mpi4py is a wrapper, so if has to reference all MPI symbol, but mpi4py users do not necessarily use all of MPI in their applications, nor they necessarily interact with Fortran.

The implementation is up to you. The hard way is to map the p/r arguments to a duplicate of a C datatype that fits the requested precision and range, just to produce something as a fallback that sort of work the expected way. The easy way is to generate an error, as the MPI standard says _Attempting to access an element of the array with an index (p, r) not supported by the compiler is erroneous_. Or maybe the best is to output `MPI_DATATYPE_NULL` but return `MPI_SUCCESS`, given the fact that with `--disable-fortran`, all named Fortran datatypes are defined as `MPI_DATATYPE_NULL` in `mpi.h`. 

I personally prefer the last option (output NULL and return SUCCESS). It is easy for users to detect the situation (check the output for NULL) without having to deal error handling (otherwise, users would have to override the default FATAL handler). As the output datatype is NULL, any attempt to use it unchecked will generate an error anyway, so errors do not pass silently. Finally, the behavior is is somewhat symmetric with the other Fortran datatypes being defined to NULL.

**Comment by hzhou** [comment]
I agree. We also need to generate the IO functions with `--diable-romio`.

**Comment by dalcinl** [comment]
What about `MPI_REAL2` and `MPI_COMPLEX4`? I think they should always be in `mpi.h`, but defined to `MPI_DATATYPE_NULL` if not supported by the compiler.

**Comment by dalcinl** [comment]
> Then we will need another mechanism for users to tell whether certain datatype is available. Any suggestions?

Another mechanism respect to what? The obvious mechanism is to runtime-check for equality against `MPI_DATATYPE_NULL`. Are you talking about configure-style compile-time checks?

**Comment by hzhou** [comment]
Oh, I misread. I thought those types exist but are defined as `MPI_DATATYPE_NULL` and you were suggesting them to be defined with individual constants. 

Yeah, we can add `MPI_REAL2` and `MPI_COMPLEX4` in `mpi.h`.

**Comment by dalcinl** [comment]
> Then we will need another mechanism

However, for the upcoming standard MPI ABI, we may definitely need alternative mechanism....

**Comment by hzhou** [comment]
> > Then we will need another mechanism
> 
> However, for the upcoming standard MPI ABI, we may definitely need alternative mechanism....

That's what I was thinking. Ideally, a new API e.g. `MPI_Type_query`, but maybe we can get by with `MPI_Type_size` -- unavailable if the size returned is `0`.

**Comment by hzhou** [comment]
> > with `MPI_Type_size` -- unavailable if the size returned is `0`.
> 
> That's Open MPI's behavior, and I do (ab)use that in tests.

Good to know.
