### ISSUE TITLE
Switch to semantic versioning (SemVer) with explicit patch number even if `0`.

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6790]
Would you consider switching the version scheme to SemVer for next release? Rather than `4.2b1`, the version would become `4.2.0b1` with an explicit patch entry of `0`.

Many projects have switched to such scheme over the years. Most package managers I know use at least three numbers. The lack of a `0` for the patch version is always a source of annoyance on things like deployment scripts and build recipes ([example](https://github.com/conda-forge/mpich-feedstock/blob/main/recipe/meta.yaml#L5)), which require special-cases and workarounds to cope with jumps in the minor version.

**Comment by hzhou** [comment]
Will discuss today

**Comment by dalcinl** [comment]
For reference/examples: Open MPI has always used patch=0. Python made the switch since v3.3.0, the first alpha tag https://github.com/python/cpython/tree/v3.3.0a1 from March 2012. On a personal note, mpi4py switched two the new scheme with v2.0.0 from 2015. If I'm pressed, I think I can keep adding projects to the list over and over.

**Comment by dalcinl** [comment]
> FWIW, the 4.2 GA release will be `4.2.0`. 

OH, then this is already a change for the good respect to the 4.1 release.

BTW, Please note that I'm requesting that these explict patch=0 numbers should also be in the download URL and tarball name.

> However, in `4.2b1`, the `b1` is a patch level.

It would be much better if it the tarball name had `4.2.0b1`, though.

**Comment by hzhou** [comment]
We discussed and agree that we will do `4.2.0b1`.
