### ISSUE TITLE
Feature request: Dynamic process management in CH4 with UCX

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6797]
MPICH configured `--with-device=ch4:ucx` does not currently support any of the dynamic process management features (spawn and friends) of MPI-2. https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ucx/ucx_spawn.c

@leofang and I were discussing about the feasibility of switching MPICH in conda-forge to use UCX. However, without proper spawn support, we cannot do it without harming a lot of users that rely on the `mpi4py.futures` subpackage, thus leaving them with no other option than migrate away of MPICH.

cc @jeffhammond

**Comment by dalcinl** [comment]
@hzhou Have you tried singleton init mode? mpi4py testsuite (branch testing/mpich) deadlocks [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/6956974866/job/18928938419).

**Comment by dalcinl** [comment]
> singleton init spawn is broken in many implementations. 

Lack of support for singleton init has been a source of frustration for users of mpi4py.futures parallelizing workloads within Jupyter notebooks, as the Jupyter kernel processes are usually not executed under mpiexec. Hui has been very generous of fixing outstanding issues some time ago, to the point of getting ch4:ofi working flawlesly. I added enough tests to catch regressions early.

> i am surprised that you have found it worthwhile to test it.

I'm truly annoying, indeed.

**Comment by hzhou** [comment]
> @hzhou Have you tried singleton init mode? mpi4py testsuite (branch testing/mpich) deadlocks [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/6956974866/job/18928938419).
> 
> EDIT: The gforker build has a slightly better [traceback](https://github.com/mpi4py/mpi4py-testing/actions/runs/6956974866/job/18928939517)

`gforker` does not support ucx dynamic process yet. Does `ch4:ofi` dynamic process work with `gforker`? Feel free to file an issue and I'll fix it.

I tried the `test_futures.py`, it is hanging for me even with `ch4:ofi`. In the first try it hangs on `test_map_chunksize`. In the 2nd try it went past `test_map_chunksize` and hangs on `test_map_exception`. Anyway, could you break the test down and explain to me what is the test doing?

**Comment by dalcinl** [comment]
> Does `ch4:ofi` dynamic process work with `gforker`?

Yes, even in singleton init mode.

> Feel free to file an issue and I'll fix it.

I'll do shortly.

> Anyway, could you break the test down and explain to me what is the test doing?

It is a bit hard to create a simpler reproducer. Those tests basically do the following: 1) Spawn one or more child processes from MPI_COMM_SELF. 2) communicate (synchronous-mode p2p & coll) between parent and children, and 3) disconnect spawned processes. These steps happen over an over again for each individual test execution (i.e. each line you see in the console output).
The `mpi4py.futures` stuff has been throughly tested at scale and it works flawlesly with hydra/gforker and ch4:ofi. Therefore, I'm confident the implementation is correct and follow proper MPI semantics (although you have made me aware about of some flawed progress assumptions of mine that broke under UCX).

As the tests spawn new processes in relatively rapid succession, maybe the deadlocks are somehow related to a race condition? That would explain why the hang happens at different places.
It is a bit hard to test things locally right now, but I'll try my best to do it tomorrow.
