### ISSUE TITLE
How to specify the custom SSH Port? it is not default 22

### ISSUE THREAD

**Issue by PrometheusComing** [pmodels/mpich#6799]
Newcomer Help:
1. How do I specify the port used by SSH when running the mpirun command? The sshd service I started was not using the default port 22.
2. Is there a configuration file? If so, what path is it in?

**Comment by hzhou** [comment]
Could you try set `HYDRA_LAUNCHER_EXTRA_ARGS='-p [port]'`?

**Comment by hzhou** [comment]
You also can try configure your host options in `~/.ssh/config` - https://linuxize.com/post/using-the-ssh-config-file/

**Comment by PrometheusComing** [comment]
> Could you try set `HYDRA_LAUNCHER_EXTRA_ARGS='-p [port]'`?

thank you very much，it works
