### ISSUE TITLE
build: Cannot open module file 'pmpi_base.mod'

### ISSUE THREAD

**Issue by githubweather** [pmodels/mpich#6811]
These are the steps I have followed trying to build mpich v4.1.2

1.	fetched mpich from https://github.com/pmodels/mpich
2.	i.e., git clone https://github.com/pmodels/mpich.git
3.	cd mpich
4.	./autogen.sh to create ‘configure” file
5.	ERROR indicates need to run: git submodule update –init
6.	./configure creates the Makefile

running "make"  yields the error seen below: 

```
Running “make”  MOD      src/binding/fortran/use_mpi/mpi.mod-stamp
src/binding/fortran/use_mpi/mpi.f90:8:9:

    8 |     USE PMPI_BASE
      |         1
Fatal Error: Cannot open module file 'pmpi_base.mod' for 
reading at (1): No such file or directory
compilation terminated.
1.	make[2]: *** [Makefile:22297: src/binding/fortran/use_mpi/mpi.mod-stamp] Error 1
```

If I use the --disable-fortran flag in the configure step, it compiles, however, I need the fortran component so that is not an option.  Here are the particulars for my system (i.e., output of "uname -a"):
```
Linux debian 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
```

"gfortran -v" shows this: 
```
gcc version 12.2.0 (Debian 12.2.0-14)
```

I saw in the "issues" a reference to this error seemingly being fixed.  Should I be pulling a different branch?

**Comment by hzhou** [comment]
Could you try re-run `./autogen.sh` followed with `./configure` and `make`?

**Comment by githubweather** [comment]
I just re-ran those steps, this time not needing this step (git submodule
update –init) because it was already done.  I am still getting the error I
listed in the title, i.e.,

MOD      src/binding/fortran/use_mpi/mpi.mod-stamp

*src/binding/fortran/use_mpi/mpi.f90:8:9:*


    8 |     USE PMPI_BASE

      |         *1*

*Fatal Error:* Cannot open module file '*pmpi_base.mod*' for reading at
*(1)*: No such file or directory

**Comment by hzhou** [comment]
You may have caught a brief window in our git history that this was broken. Could you refresh your git repository -- `git pull` or rerun `git clone` to a new empty directory -- and retry the whole process (`git submodule update --init`, `./autogen.sh`, `./configure`, `make`)?

**Comment by githubweather** [comment]
I redid everything - git clone'd to a clean directory, "git submodule
update --init", ./autogen.sh, ./configure, make, but am still seeing that
same error.

**Comment by lancelotnd** [comment]
I am getting the same error when building from source mpich-4.2.0b1 (beta release)

**Comment by hzhou** [comment]
@githubweather Thank you for your patience. @lancelotnd Thank you for your report confirming the issue.

Could you try patch `src/binding/fortran/use_mpi/Makefile.mk` with https://github.com/pmodels/mpich/pull/6828, then rerun `./autogen.sh`?

**Comment by githubweather** [comment]
I did a quick diff of configure.ac in the tree I pulled originally with
what is in the tree now and they are identical.  Similar situation for
src/binding/fortran/use_mpi/Makefile.mk.  Are there patches I need to
apply?  I am not clear what to do next.

**Comment by hzhou** [comment]
@githubweather Yes, please manually patch `src/binding/fortran/use_mpi/Makefile.mk` as in https://github.com/pmodels/mpich/pull/6828/files, then re-run `./augtogen.sh`.
