### ISSUE TITLE
Name publishing and port names under CH4:UCX

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6831]
Name publishing with ch4:ucx seems to be broken in current main branch, I'm getting truncated port names

Don't you have to add the support for "port_name_size" via info to all routines that involve a port name string? Or did you , and I just failed to figured that out in your original PR?

Maybe only `MPI_Lookup_name` needs the "port_name_size" hint. The other routines that only read the port name (close, publish, and unpublish) can get away by checking whether the character at MPI_MAX_PORT_NAME(=512) is the null terminator to decide whether to keep reading the buffer. `MPI_Close_port` doesn't even have an info hint!

**Comment by hzhou** [comment]
Yes, we neglected `MPI_Lookup_name`.  Only `MPI_lookup_name` is an issue since it writes into a user-provided buffer with assumed size.  Other commands can use an internal max limit.
