### ISSUE TITLE
MPI_Group_translate_ranks and others are wrong under specific circumstances in ch-4 device

### ISSUE THREAD

**Issue by cppkhartna** [pmodels/mpich#6832]
**Description**

For some versions of MPICH, notably from 4.0 and above (ch-4 device), MPI_Group_translate_ranks function behaves wrongfully when interconnecting separately launched processes into one intracommunicator.

The code used to connect processes launched from separate mpirun's is similar to [example.](https://mpi.deino.net/mpi_functions/MPI_Comm_connect.html)

The wrong picture of ranks distribution is:

![wrong_ranks](https://github.com/pmodels/mpich/assets/1138997/d9ce4713-70e2-4e04-a160-4368b5684f3d)

The right ranks (ch-3 device example) should be 0,1,2,3,4, (blank or MPI_UNDEFINED) in all cases except for the last one:

![right_ranks](https://github.com/pmodels/mpich/assets/1138997/12a46f33-9b87-404c-b30d-d9a495a923bf)

Legend:
- v1 are ranks of group before merge and v2 is a translation of v1 into newgroup of merged comm;
- v3 are ranks of newgroup after merge and v4 is a translation of v3 into old group of old comm.

**Blocking nature of the problem**
Most of group-specific functions fail to work, either hanging indefinitely, or crashing with an assert error (in debug mode):
> (cdst) != MPI_UNDEFINED

Due to MPIR_Group_translate_ranks_impl being used to get a correct rank of local group peer in order to communicate during Allreduce_group, the problem also affects MPI_Comm_split, MPI_Com_create, etc.

**Problem explanation**
During latest switch from ch-3 device to ch-4 device, AV-Table replaced VCRT virtual-connections table. Commit #09be7d08 from Aug 2, 2021, broke ch-4 device compatibility with src/mpi/group/group_impl.c be extending lpid format to uint64_t to accomodate dynamic processes AV-table if (avtid) overflow, thus leaving group implementation with incorrect int (int32_t) lpid representation. This leads to omitting higher bits in MPIR_Group_translate_ranks_impl and others, which are, ironically, avtid.

<img width="605" alt="mpid" src="https://github.com/pmodels/mpich/assets/1138997/35cfbb42-53e0-4e0e-90ef-3bed83e4e8c4">

When lpid is 0 and avtid is changing (i.e. in case of dynamic processes, either spawn or joined/accept-connect/merged), the int32_t lpid is yielding wrong results. A simple arithmetic test to illustrate this:

<img width="472" alt="lpid" src="https://github.com/pmodels/mpich/assets/1138997/47ee1267-dacd-4014-a171-971a526c21c5">

In MPIR_Group_translate_ranks_impl, for example, gp2->lrank_to_lpid[0].lpid is uint64_t and gets converted to lpid_offset which is int32_t and is truncated:
[L480](https://github.com/pmodels/mpich/blob/main/src/mpi/group/group_impl.c#L480)

Next, all zeroes and undefined stuff get searched through to find the index of first lpid, which is rather random after wrong conversion, and the result of translate ranks is garbage.

**Solution**
Patching group_impl.c (see further pull request).

**Comment by hzhou** [comment]
Fixed by #6833
