### ISSUE TITLE
fortran: Add MPI_REAL2 and MPI_COMPLEX4

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6849]
Add `MPI_REAL2` and `MPI_COMPLEX4`. They should always be in `mpi.h`, but defined to `MPI_DATATYPE_NULL` if not supported by the compiler or Fortran bindings are disabled.

Followup of https://github.com/pmodels/mpich/issues/6780#issuecomment-1797984336.

**Comment by hzhou** [comment]
@dalcinl maybe you can give #6851 a try? It doesn't a c correspondence, so it may break if it is used in reduction.

**Comment by hzhou** [comment]
My impression was `MPI_REAL2` was not standard. Do we know when it is added to the standard?

**Comment by dalcinl** [comment]
> @dalcinl maybe you can give #6851 a try? 

mpi4py builds just fine and works in [GHA](https://github.com/mpi4py/mpi4py-testing/actions/runs/7233164339),  but these builds run with Fortran disabled. Anyway, gfortran does not support real*2, so I don't have an easy way to test the full actual thing right now.

> It doesn't a c correspondence, so it may break if it is used in reduction.

Yes, of course. Maybe the closed C type would any IEEE binary16 implementation supported by the compiler, like GCC's `_Float16` (although without `real*2` in gfortran this is a bit pointless).

> My impression was `MPI_REAL2` was not standard. Do we know when it is added to the standard?

`MPI_REAL2` appeared very long time ago in MPI-2.1, and `MPI_COMPLEX4` in MPI-2.2. This is what I see from the respective std documents, without checking the errata documents.

**Comment by dalcinl** [comment]
Is there anything left from promote this PR out of the draft state?
