### ISSUE TITLE
ABI: `MPI_THREAD_XXX` are enum values, cannot be used within the C preprocessor. 

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6875]
From the ABI `mpi.h`:

```c
...
enum {
    // Environmental inquiry keys and Predefined Attribute Keys
    // Threads Constants
    // These values are monotonic; i.e., SINGLE < FUNNELED < SERIALIZED < MULTIPLE.
    MPI_THREAD_SINGLE     = 0,
    MPI_THREAD_FUNNELED   = 1,
    MPI_THREAD_SERIALIZED = 2,
    MPI_THREAD_MULTIPLE   = 7, // in case we need other threading levels below M
...
}
...
```

In MPICH sources, there are places where these constants are used in preprocessor directives, for example:
In `src/mpi/init/init_impl.c`
```c
int MPIR_Is_thread_main_impl(int *flag)
{
#if MPICH_THREAD_LEVEL <= MPI_THREAD_FUNNELED || ! defined(MPICH_IS_THREADED)
    {
        *flag = TRUE;
    }
#else
    {
        MPID_Thread_id_t my_thread_id;

        MPID_Thread_self(&my_thread_id);
        MPID_Thread_same(&MPIR_ThreadInfo.main_thread, &my_thread_id, flag);
    }
#endif
    return MPI_SUCCESS;
}
```
Therefore, any instance of `MPI_THREAD_XXX` within the preprocessor is considered undefined and then take a value of 0 when used in expressions (at least with GCC).

I'm not sure what the proper fix for this is. 

1. For the time being, perhaps you could stash something like the following somewhere in in `mpiimpl.h`. 
   ```c
   #ifdef BUILD_MPI_ABI
   #define MPI_THREAD_SINGLE  0
   ...
   #defne  MPI_THREAD_MULTIPLE  7
   #endif
   ```
* Or maybe fix the generation of `mpi_abi_internal.h` to special case the `MPI_THREAD_XXX` enum constants and make them preprocessor constants.

PS: This issue was original reported here https://github.com/pmodels/mpich/pull/6872#issuecomment-1898625690, but I guess the comment went unnoticed.

**Comment by hzhou** [comment]
> * Or maybe fix the generation of `mpi_abi_internal.h` to special case the `MPI_THREAD_XXX` enum constants and make them preprocessor constants.

I am leaning toward this.

**Comment by hzhou** [comment]
> > * Or maybe fix the generation of `mpi_abi_internal.h` to special case the `MPI_THREAD_XXX` enum constants and make them preprocessor constants.
> 

I am leaning toward this. We want the option to eliminate threading check at compile time to really not to hurt `MPI_THREAD_SINGLE` performance.
