### ISSUE TITLE
MPICHLIB_LDFLAGS not supported?

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6904]
I attempted to use `MPICHLIB_LDFLAGS="-Wl,--as-needed"` with an UCX build to avoid shared library overlinking in `mpichversion` and `mpivars` (the UCX libraries should not be DT_NEEDED in these executables ). 
However, things did not work as expected. Maybe I'm missing something, and there is some other hiccup explaining why the UCX shared libraries got injected as dependencies in `mpichversion` and `mpivars`.

In any case, `configure.ac` does not seems to support `MPICHLIB_LDFLAGS` at all.  I'm not an autotools expert, so I'm not quite sure how to implement it or how hard it would be. It would be nice to have this support in place for next release.

PS: I'm working on producing binary distributions of MPICH as Python wheels, such that users can `pip install mpich` in both Linux and macOS. I'm also considering `ch4:ofi` and `ch4:ucx` alternatives. UCX is giving me a bit of a hard time, mainly related to the fact that the embedded option build UCX shared libraries.

**Comment by raffenet** [comment]
MPICHLIB_LDFLAGS was removed back in 4d93cefa8f2fb06fdc47d8f73ed46c3623b8dfd6, but I'm not sure I agree with the reasoning in the commit message. I'd be open to adding support back.

**Comment by hzhou** [comment]
UCX doesn't support embedded build, so we always build it the same way as an external install.

Does setting `LDFLAGS` work?

**Comment by dalcinl** [comment]
Irrespective of my build endeavors... How would users set LDFLAGS that should be used for the building the libraries but that you DO NOT want in the compiler wrappers? Therefore, I'm advocating for `MPICHLIB_LDFLAGS`. Does it make sense?

**Comment by hzhou** [comment]
I don't think we currently add `LDFLAGS` to `WRAPPER_LDFLAGS`. Could you verify?

**Comment by dalcinl** [comment]
> I don't think we currently add `LDFLAGS` to `WRAPPER_LDFLAGS`. Could you verify?

I can, but if that is indeed the case, then maybe that's another nit to address?

**Comment by dalcinl** [comment]
Just checked, and LDFLAGS is indeed added to compiler wrappers.

```
$ grep as-needed $(command -v mpicc)
final_ldflags=" -Wl,--as-needed"
    final_ldflags="${final_ldflags} -Wl,--as-needed"
```

**Comment by hzhou** [comment]
@raffenet Should we restore `MPICHLIB_LDFLAGS`?

**Comment by raffenet** [comment]
> @raffenet Should we restore `MPICHLIB_LDFLAGS`?

I think so. I'm undecided about `MPICHLIB_LIBS`. Is there any use-case for that?

**Comment by hzhou** [comment]
> > @raffenet Should we restore `MPICHLIB_LDFLAGS`?
> 
> I think so. I'm undecided about `MPICHLIB_LIBS`. Is there any use-case for that?

I would like to add that just for symmetry reasons. It doesn't hurt users if they don't use it.

**Comment by hzhou** [comment]
> Just checked, and LDFLAGS is indeed added to compiler wrappers.
> 
> ```
> $ grep as-needed $(command -v mpicc)
> final_ldflags=" -Wl,--as-needed"
>     final_ldflags="${final_ldflags} -Wl,--as-needed"
> ```

@dalcinl This is for the case when interlibrary dependency is not supported by the linker, in which case we need add LDFLAGS that are needed for resolve MPICH internal dependency during compiling user programs. Unfortunately, there is no way of tell which parts of LDFLAGS are needed, so we have to add all. If `MPICHLIB_LDFLAGS` are needed for linking `libmpi`, then those flags are likely also needed to build user programs. Thus if we support `MPICHLIB_LDFLAGS` or `MPICHLIB_LIBS`, both will be merged with `LDFLAGS` and `LIBS` as long as MPICH is concerned. I guess it can be useful for user build systems when they need build multiple packages.

**Comment by dalcinl** [comment]
>  If `MPICHLIB_LDFLAGS` are needed for linking `libmpi`, then those flags are likely also needed to build user programs.

There are flags that may be needed only when building shared libraries, eg. `-Wl,--as-needed`, or special link (shared) libraries that get listed as NEEDED in libmpi.so. There are also link-time-optimization (LTO) flags that you may want to apply to the library, but not necessarily to every user problem.

**Comment by hzhou** [comment]
> > If `MPICHLIB_LDFLAGS` are needed for linking `libmpi`, then those flags are likely also needed to build user programs.
> 
> There are flags that may be needed only when building shared libraries, eg. `-Wl,--as-needed`, or special link (shared) libraries that get listed as NEEDED in libmpi.so. There are also link-time-optimization (LTO) flags that you may want to apply to the library, but not necessarily to every user problem.

How can we tell which flags are needed and which are not needed?

**Comment by hzhou** [comment]
`CFLAGS` are used only for compiling source code. All the compiling of MPICH is done during building MPICH, they are not needed to compile user code. `LDFLAGS` are for linking. If e.g. `libmpi.so` depend on `libsth.so` and the linker does not support interlib dependency, then we need carry the `LDFLAGS` when we link user program in order to find `libsth.so`.

**Comment by dalcinl** [comment]
I have to separate objections to your argument:

* Not every linker flag is related to handling interlib dependencies. For example, you may want to add linker flags that affect the object code -> shared object generation for libmpi.so, but that you do not want or are even inappropriate for let say building an executable with mpicc. 
* If you have a linker and system that do support interlib deps properly, like Linux or Darwin, then why not allowing users to take advantage of that to build libmpi.so exactly as they want/need? Packagers and distributor may find the feature quite useful to customize and workaround issues.

Maybe I'm being naive and I'm asking too much because I missing some important point about how autotools and libtool operate. All I'm asking for is for the possibility of allowing users to specify linker flags that are used to produce libmpi.so, but at the same time these flags do not end up being added to mpicc. If this is technically difficult and not worth the development time, then let's stop here and forget about it. However, it that is relatively easy to implement, this feature may prove handy for power users, sysadmin, packagers, etc that have to deal with the usual mess of producing binaries for other users.

**Comment by hzhou** [comment]
> * Not every linker flag is related to handling interlib dependencies. For example, you may want to add linker flags that affect the object code -> shared object generation for libmpi.so, but that you do not want or are even inappropriate for let say building an executable with mpicc.

Agreed. But we can't tell. I guess we can differentiate `LDFLAGS` and `MPICHLIB_LDFLAGS` so that `MPICHLIB_LDFLAGS` never goes into wrapper scripts.
> 
> * If you have a linker and system that do support interlib deps properly, like Linux or Darwin, then why not allowing users to take advantage of that to build libmpi.so exactly as they want/need? Packagers and distributor may find the feature quite useful to customize and workaround issues.

If interlib deps are supported, `LDFLAGS` does not go into `mpicc`.

**Comment by hzhou** [comment]
Consider this issue is fixed by https://github.com/pmodels/mpich/pull/6932
