### ISSUE TITLE
build: Build embedded libfabric as a shared library

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6905]
Would it be possible to add a configure option to build the embedded libfabric as a shared library (just like what is done with UCX as default)?

PS: I'm working on producing binary distributions of MPICH as Python wheels, such that users can `pip install mpich` in both Linux and macOS. I'm considering a `ch4:ofi` option where librabric is built as a shared library and installed alongside the MPI library, allowing users to override libfabric via `LD_LIBRARY_PATH` (at least on Linux).

**Comment by raffenet** [comment]
Actually I was mistake. `--disable-static` doesn't work as I expected. We can add a configure switch to enable this behavior, though.

**Comment by dalcinl** [comment]
> `--disable-static` doesn't work as I expected.

Just to confirm, this option is just meant to NOT build the MPICH static libraries, right? I'm my particular use case, I was already passing `--disable-static`. By the way, without passing that option, I had troubles building the 4.1.2 tarball on Linux aarch64 (linker failed with symbol relocation errors).

**Comment by hzhou** [comment]
Let's see if #6912 does the trick.

**Comment by hzhou** [comment]
Labeled as `wontfix`. See discussion in https://github.com/pmodels/mpich/pull/6912

**Comment by hzhou** [comment]
Without `--enable-embedded`, the symbols from libfabric will be exposed through libmpi.so. This may cause user issues when there is a system libfabric with conflict versions from the embedded versions.

**Comment by dalcinl** [comment]
Well, that's kind of my whole point, that is, to have a default, embedded libfabric.so alongside libmpi.so such that libfabric can be overridden via LD_LIBRARY_PATH with a (same version or newer) libfabric installed elsewhere. I'm not saying that MPICH should default to this kind of builds, but rather allow power users and binary distributors to make such builds possible.  In should add that I'm using `-Wl,-rpath,$ORIGIN` such that libmpi.so will load the libfabric.so residing in the same directory via the DT_RUNPATH entry in the ELF binary.

I'm still a bit puzzled about the resistance for this request. Moreover, as far as I know, you guys cannot embed UCX, so the UCX netmod uses the UCX shared libraries, and similar concerns apply regarding system UCX libraries. Or there is something more profound going on that I'm still not realizing?

**Comment by hzhou** [comment]
First, if you want to install libfabric as libfabric.so, why not build libfabric separately as a dependency and use `--with-libfabric=[path]` pointing to it?

We are not properly embedding ucx is an unfortunate state and compromise. It is not an intention. Again, it is recommended to build ucx separately as a dependency.

**Comment by dalcinl** [comment]
Well, there are a few reasons I want MPICH building librabric for me: use a consistent set of `CFLAGS` in all binaries, make it easier to do `make install DESTDIR=/some/staging/path`, and ultimately simplify all the fragile non-futureproof mess I have to do to ensure the result does not have hardwired paths to the build directories. Both MPICH and Open MPI make things a bit harder than usual, due to their insistence on leaking build-time information (paths, cflags, etc) into the resulting binaries.

My ultimate goal is reproducible builds (the same environment at different times and build paths produce the same binaries) that are also relocatable (unpack a zipfile/tarball run straight away without having to set ad-hoc environ vars by default) and without information leaks related to the original build directories and environment. All this requires a combination of environment variables, patching in between configure and make, special compiler and linker flags, and postprocesing with strip/patchelf/install_name_tool.

**Comment by hzhou** [comment]
Okay, I guess you want an option to build libfabric and ucx using the embedded copy but build as external library? We can add that option.

**Comment by dalcinl** [comment]
> I guess you want an option to build libfabric and ucx using the embedded copy but build as external library?

Exactly! Moreover, after all the previous work you did (e.g. fixing visibility), I believe the implementation of this option should be trivial, just a matter of not passing `--enable-embedded` in the subconfigure invocation. I'm not good at all with autotools stuff, otherwise I would have proposed a patch to make my intention clear from the beginning.
