### ISSUE TITLE
errhan: Issue with error handling

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6931]
Consider the following C reproducer:

```C
#include <assert.h>
#include <stdio.h>
#include <mpi.h>

int delete_fn(MPI_Comm comm, int k, void *v, void *xs)
{
  return MPI_ERR_UNKNOWN;
}

int main(int argc, char *argv[])
{
  int ierr, errcls;
  MPI_Init(&argc, &argv);
  MPI_Comm_set_errhandler(MPI_COMM_SELF, MPI_ERRORS_RETURN);
  MPI_Comm_set_errhandler(MPI_COMM_WORLD, MPI_ERRORS_RETURN);

  int keyval;
  MPI_Comm_create_keyval(MPI_COMM_NULL_COPY_FN, delete_fn, &keyval, NULL);
  MPI_Comm_set_attr(MPI_COMM_SELF, keyval, NULL);
  ierr = MPI_Comm_delete_attr(MPI_COMM_SELF, keyval);
  MPI_Error_class(ierr, &errcls);
  MPI_Comm_free_keyval(&keyval);
  printf ("%d %d %d\n", ierr, errcls, MPI_ERR_UNKNOWN);

  for (int i = 0; i<65; i++) {
    void *val; int flag;
    ierr = MPI_Type_get_attr(MPI_INT, MPI_KEYVAL_INVALID, &val, &flag);
    MPI_Error_class(ierr, &errcls);
    printf ("%d %d %d\n", ierr, errcls, MPI_ERR_KEYVAL);
  }
  
  MPI_Finalize();
  return 0;
}
```

If you build and run, you should see the following output:
```
$ mpicc tmp-attr.c
$ ./a.out 
13 13 13
1011526960 48 48
1012575536 48 48
...
1007332656 48 48
1008381232 48 48
1009429808 48 48
13 13 48
1011526960 48 48
```
The second to last line (and iterations multiples of 64 if I loop more)  is obviously wrong. The error handling machinery is a bit involved, so it is not immediately obvious to me where things are being messed up.

PS: I want to submit a PR improving the handling or attributes, but this issue is breaking mpi4py test suite and so far I'm stuck.

**Comment by dalcinl** [comment]
After quite a bit of time figuring out what was going out, I was about to submit the exact same fix. Now at least I know how exactly the machinery works. Thanks anyway!

**Comment by hzhou** [comment]
> After quite a bit of time figuring out what was going out, I was about to submit the exact same fix. Now at least I know how exactly the machinery works. Thanks anyway!

That's good! There will be bugs waiting for you in the future :)
