### ISSUE TITLE
Multiple MPI_Test invocations on the same MPI_Request object are not thread-safe

### ISSUE THREAD

**Issue by JiakunYan** [pmodels/mpich#6937]
All the discussion here assumes that we initialize MPI with `MPI_THREAD_MULTIPLE`.

If we have a code like this
```
MPI_Request g_request;

void init() {
    // Run by the main thread
    post_recv(&g_request);
}

void thread_fn() {
    // Run by multiple threads
    MPI_Status status;
    int flag;
    MPI_Test(&g_request, &flag, &status);
    if (flag && !is_empty_status(status)) {
        // We got the message!
        ....
        post_recv(&g_request);
    }
}
```
There is one pre-post `MPI_Irecv` with the global `g_request`. All worker threads are polling the `g_request` and whoever got it first will process the message and repost the `MPI_Irecv`.

According to the MPI Specification 4.1, this code is a valid MPI code, because
1. All MPI functions should be thread-safe under `MPI_THREAD_MULTIPLE`.
2. `MPI_Test` with a `MPI_REQUEST_NULL` as input should return `flag=1` and `status=empty`.
3. `MPI_Test` with a non-null request as input should either
  a. return `flag=0` and the request is not modified.
  b. return `flag=1` and the request is set to `MPI_REQUEST_NULL`.

However, with the current MPICH implementation, we will actually encounter a data race due to the following code:
https://github.com/pmodels/mpich/blob/dcfb18c1e3aee07350d2ce5c6aa2eb579ed07822/src/binding/c/request_api.txt#L284
https://github.com/pmodels/mpich/blob/dcfb18c1e3aee07350d2ce5c6aa2eb579ed07822/src/binding/c/request_api.txt#L285
MPICH first frees the internal request object and then sets the request to `MPI_REQUEST_NULL`.

~~I think a correct implementation should first set the request to `MPI_REQUEST_NULL` and then free the internal request object, so that other thread will not see a non-null but already freed request.~~

Do I have a misunderstanding of the MPI specification, or does MPICH's implementation conflict with the specification? If it is the latter case, is it possible to have an efficient thread-safe implementation, or do we need to update the specification?

**Comment by JiakunYan** [comment]
I think OpenMPI (at least its UCX backend) had the correct way
https://github.com/open-mpi/ompi/blob/a25dd5f3a2512c20f3f18286f7fc977b59433c7c/ompi/mca/pml/ucx/pml_ucx_request.c#L28

**Comment by JiakunYan** [comment]
Okay, after some more thinking, simply reversing the order of free and set does not resolve this data race. I start to doubt whether there is a way to make it thread-safe without using locks.

**Comment by JiakunYan** [comment]
Sorry, I missed this part of the specification. Thanks!

**Comment by lauffr** [comment]
> A program in which two threads block, waiting on the same request, is erroneous. Similarly, the same request cannot appear in the array of requests of two concurrent MPI_{WAIT|TEST}{ANY|SOME|ALL} calls.

The first sentence is about two threads blocking, but MPI_Test is a non-blocking call, and the second sentence is about array of requests so I feel like the specification does not make it clear whether or not calling MPI_Test concurrently on the same request should be safe or not. I would assume it's not, as it would definitely require locking, but the specification does need clarification in my opinion.

**Comment by hzhou** [comment]
It's not about concurrent execution, but concurrent ownerships. Imagine two threads are testing on the same request, and assume they are serialized via locking. The first one completed and set the request to `MPI_REQUEST_NULL`. What happens to the second test? Effectively, the second one is calling `MPI_Test` on an invalid request handle.

The nature of the completion call -- deterministic or deterministic -- requires sole ownership.
