### ISSUE TITLE
how do i make libtool substitute -shared for -Wl,-shared

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6942]
i worked https://github.com/llvm/llvm-project/issues/84900 manually by editing `libtool` to replace `-shared` with `-Wl,-shared`.  what's the `configure` hack to achieve this?

thanks.

**Comment by raffenet** [comment]
We maintain a bunch of libtool patches in `maint/patches/optional/confdb/`, that get applied during `autogen.sh`. We have this one already, so I'm surprised it doesn't just work. What version of llvm is this so I can try it out on one of our systems?
```
--- libtool.m4~ 2019-11-08 13:59:39.000000000 -0600
+++ libtool.m4  2019-11-11 15:34:57.000000000 -0600
@@ -4736,6 +4736,12 @@
        _LT_TAGVAR(lt_prog_compiler_pic, $1)='-KPIC'
        _LT_TAGVAR(lt_prog_compiler_static, $1)='-static'
         ;;
+      # flang / f18
+      flang* | f18*)
+       _LT_TAGVAR(lt_prog_compiler_wl, $1)='-Wl,'
+       _LT_TAGVAR(lt_prog_compiler_pic, $1)='-fPIC'
+       _LT_TAGVAR(lt_prog_compiler_static, $1)='-static'
+        ;;
       # icc used to be incompatible with GCC.
       # ICC 10 doesn't accept -KPIC any more.
       icc* | ifort*)
```

**Comment by jeffhammond** [comment]
the LLVM issue was fixed already, but i didn't know it, so it's not important to hack libtool anymore.
