### ISSUE TITLE
Can't build on lustre

### ISSUE THREAD

**Issue by zeus-cht** [pmodels/mpich#6945]
When I run `./configure --prefix=install_path --with-file-system=lustre`, it prints "checking configured file systems... testfs lustre", but there is an error in file `/src/mpi/romio/adio/ad_lustre/ad_lustre_hints.c`: "ADIOI_Direct_read not declared". And I found that the `ROMIO_LUSTRE` was not defined in the file `/src/mpi/romio/adio/include/romioconf.h`: 
``` c
/* Define for ROMIO with LUSTRE */
// #undef ROMIO_LUSTRE
```
 Then I modified the file:
``` c
/* Define for ROMIO with LUSTRE */
// #undef ROMIO_LUSTRE
#define ROMIO_LUSTRE 1
```
Then the `make && make install` succeeds.
I wonder why this happen? And will my method of modifying `/src/mpi/romio/adio/include/romioconf.h` cause any problems?
other info:
The command `df -T install_path` returns lustre in the "TYPE" colum.

**Comment by hzhou** [comment]
Could you share `src/mpi/romio/config.log`?

**Comment by zeus-cht** [comment]
> Could you share `src/mpi/romio/config.log`?

yes, the file is: 
[config.log](https://github.com/pmodels/mpich/files/14618987/config.log)

**Comment by hzhou** [comment]
`ROMIO_LUSTRE` is defined by configure as shown in config.log (line 3879). I think you must somehow have a inconsistency during the build process. I am not sure of the exact cause, but it is not uncommon issue with autotools.

If you encounter this issue persistently after building from a clean source tree, comment, and we'll follow up.

**Comment by zeus-cht** [comment]
> `ROMIO_LUSTRE` is defined by configure as shown in config.log (line 3879). I think you must somehow have a inconsistency during the build process. I am not sure of the exact cause, but it is not uncommon issue with autotools.
> 
> If you encounter this issue persistently after building from a clean source tree, comment, and we'll follow up.

Okay, Thanks for your help!
