### ISSUE TITLE
Subcommunicators

### ISSUE THREAD

**Issue by tks2004** [pmodels/mpich#6957]
Is it good to use MPI_GROUP_INCL or MPI_COMM_SPLIT to create sub communicators. How does it differ.

**Comment by hzhou** [comment]
`MPI_Group_incl` is a local function, it creates a group structure on your local process. You can later create the communicator via `MPI_Comm_create_group` to create the communicator. You need make sure the groups are on all participating processes are consistent.

`MPI_Comm_split` is a collective. It creates the sub-communicator in one step. I recommend the latter unless you want the flexibility of using groups.

**Comment by tks2004** [comment]
Could you please elaborate on the "You need make sure the groups are on all participating processes are consistent." Does this mean sometimes there can be inconsistence with the participating processes

**Comment by tks2004** [comment]
Thanks!
