### ISSUE TITLE
`man MPI_Type_vector_c` is not available

### ISSUE THREAD

**Issue by sthibaul** [pmodels/mpich#6973]
`man MPI_Type_vector` brings to a manpage shared by `MPI_Type_vector` and `MPI_Type_vector_c`, but `man MPI_Type_vector_c` does not bring a manpage. mpich should e.g. install a symlink between the two.

And similar for all the other `_c` variants

**Comment by hzhou** [comment]
Thank you, @sthibaul, for reporting the issue.

[TODO notes for maintainers]
Alisas man pages are created in `maint/alias-mancnst`. We should grep all `man1` pages with `_c` entries and create alias man pages for them.

Also, we need update `maint/createhtmlindex` to create index entries for `_c` routines.
