### ISSUE TITLE
info: Freeing/modifying `MPI_INFO_ENV`

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#6981]
`MPI_INFO_ENV` is a predefined info object, yet MPICH does not complain if users try free it with `MPI_Win_free`.
After the free call, the object apparently becomes deallocated, an trying to use it lead to a segfault:

```python
>>> from mpi4py import MPI
>>> dict(MPI.INFO_ENV)
{'num_nics': '1', 'num_close_nics': '1'}
>>> MPI.INFO_ENV.Free()
>>> dict(MPI.INFO_ENV)
Segmentation fault (core dumped)
```

I don't think this behavior is correct, `MPI_INFO_ENV` should be treated as most predefined handles, that is, attempts to free it should fail. Moreover, I would even argue that it should be readonly: attempts to add/remove/change key/values should also error, but that's less of a concern to me for now.

**Comment by raffenet** [comment]
I agree it should be read-only. I created https://github.com/mpi-forum/mpi-issues/issues/815 along those lines. Didn't think to try freeing it, though. This should be an error, IMO.
