### ISSUE TITLE
MPI_Waitany through MPI_f08 does not return MPI_UNDEFINED

### ISSUE THREAD

**Issue by hakostra** [pmodels/mpich#6989]
This issue is the same as issue #6402 but using MPI_f08 instead of the MPI module in Fortran.

The reproducer program from the original bug report can be easily converted to using "MPI_f08" to show the bug:

```
PROGRAM test_waitany
    USE MPI_f08

    IMPLICIT NONE (type, external)

    INTEGER :: idx = 0
    INTEGER :: nreqs = 0
    TYPE(MPI_request), DIMENSION(:), POINTER :: recvreqs=> NULL()

    CALL MPI_Init()
    CALL MPI_Waitany(nreqs, recvreqs, idx, MPI_STATUS_IGNORE)
    WRITE(*,*) 'index = ', idx , 'MPI_UNDEFINED = ', MPI_UNDEFINED
    CALL MPI_Finalize()
END PROGRAM
```
The output of the program is as in the original bug still:

```
index =  -32765 MPI_UNDEFINED =  -32766
```
The (generated) MPI_f08 binding in `f08ts.f90` for `MPI_Waitany` contains the code:

```
    IF (c_associated(c_loc(status), c_loc(MPI_STATUS_IGNORE))) THEN
        ierror_c = MPIR_Waitany_c(count, array_of_requests%MPI_VAL, indx_c, &
                                  MPIR_F08_get_MPI_STATUS_IGNORE_c())
    ELSE
        ierror_c = MPIR_Waitany_c(count, array_of_requests%MPI_VAL, indx_c, c_loc(status))
    END IF
    
    indx = indx_c + 1
```
and it is clear that the `indx = indx_c + 1` is unconditionally applied also in case of `MPI_UNDEFIEND`. This means that code that depend on `MPI_Waitany` returning `MPI_UNDEFINED` will not work.

The same problem seems to apply to MPI_Testany used through MPI_f08.

**Comment by raffenet** [comment]
Hm, we fixed this in the `mpif.h` binding (f376c9fb146a398d96e260bb94d6eb7efce3b673) but must have overlooked `mpi_f08`. Thanks for the report.
