### ISSUE TITLE
ABI File Errhandler broken

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#7003]
cf. https://github.com/mpi4py/mpi4py-testing/actions/runs/9039938318/job/24843498645

```python
from mpi4py import MPI

file = MPI.File.Open(MPI.COMM_SELF, "/dev/null")

def errhandler_fn(fh, ierr):
    assert fh == file, f"{file.handle=} {fh.handle=}"

eh = MPI.File.Create_errhandler(errhandler_fn)
file.Set_errhandler(eh)
file.Call_errhandler(MPI.SUCCESS)
```

```console
$ python test-eh.py
Traceback (most recent call last):
  File "src/mpi4py/MPI.src/errhimpl.pxi", line 44, in mpi4py.MPI.__pyx_fuse_3errhdl_call_mpi
    registry[index](pyhandle, errcode)
  File "/home/dalcinl/Devel/mpi4py/test-eh.py", line 6, in errhandler_fn
    assert fh == file, f"{file.handle=} {fh.handle=}"
           ^^^^^^^^^^
AssertionError: file.handle=94541399181280 fh.handle=579061728
Fatal Python error: exception in user-defined error handler function
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by dalcinl** [comment]
@raffenet @hzhou @jeffhammond The [mpi4py ABI tests](https://github.com/mpi4py/mpi4py-testing/actions/workflows/abi.yml) have been broken for about a month. Please confirm whether MPICH is committed to have the ABI variant in a working state, or whether that is no longer a priority. If the MPICH team does not have bandwidth to keep things in a working state, please let me know and then I'll disable my MPICH+ABI tests and stop caring until new notice.

**Comment by hzhou** [comment]
@dalcinl Please continue caring about the project. If this doesn't get fixed by the end of this week, please ping us again.

**Comment by hzhou** [comment]
@dalcinl Do you have instructions on how to build mpi4py with ABI?

**Comment by dalcinl** [comment]
> @dalcinl Do you have instructions on how to build mpi4py with ABI?

The following should be all what you need:
```
export MPICC=mpicc_abi
```
