### ISSUE TITLE
Fail to compile with gcc-14 on M1 Macbook

### ISSUE THREAD

**Issue by wgropp** [pmodels/mpich#7014]
My build of MPICH 4.2.1 failed with 

`  CC       src/libfabric_la-hmem.lo
../../../mpich-4.2.1/modules/libfabric/src/hmem.c: In function 'ofi_async_copy_hmem_iov_buf':
../../../mpich-4.2.1/modules/libfabric/src/hmem.c:216:45: error: passing argument 3 of 'ofi_iov_bytes_to_copy' from incompatible pointer type [-Wincompatible-pointer-types]
  216 |                                             &hmem_iov_offset, &hmem_buf);
      |                                             ^~~~~~~~~~~~~~~~
      |                                             |
      |                                             uint64_t * {aka long long unsigned int *}
In file included from ../../../mpich-4.2.1/modules/libfabric/src/hmem.c:41:
../../../mpich-4.2.1/modules/libfabric/include/ofi_iov.h:87:47: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}
   87 |                         size_t *size, size_t *offset, char **copy_buf)
      |                                       ~~~~~~~~^~~~~~
../../../mpich-4.2.1/modules/libfabric/src/hmem.c: In function 'ofi_copy_hmem_iov_buf':
../../../mpich-4.2.1/modules/libfabric/src/hmem.c:252:45: error: passing argument 3 of 'ofi_iov_bytes_to_copy' from incompatible pointer type [-Wincompatible-pointer-types]
  252 |                                             &hmem_iov_offset, &hmem_buf);
      |                                             ^~~~~~~~~~~~~~~~
      |                                             |
      |                                             uint64_t * {aka long long unsigned int *}
../../../mpich-4.2.1/modules/libfabric/include/ofi_iov.h:87:47: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}
   87 |                         size_t *size, size_t *offset, char **copy_buf)
      |                                       ~~~~~~~~^~~~~~
../../../mpich-4.2.1/modules/libfabric/src/hmem.c: In function 'ofi_copy_mr_iov':
../../../mpich-4.2.1/modules/libfabric/src/hmem.c:282:61: error: passing argument 3 of 'ofi_iov_bytes_to_copy' from incompatible pointer type [-Wincompatible-pointer-types]
  282 |                 len = ofi_iov_bytes_to_copy(&iov[i], &size, &offset, &hmem_buf);
      |                                                             ^~~~~~~
      |                                                             |
      |                                                             uint64_t * {aka long long unsigned int *}
../../../mpich-4.2.1/modules/libfabric/include/ofi_iov.h:87:47: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}
   87 |                         size_t *size, size_t *offset, char **copy_buf)
      |                                       ~~~~~~~~^~~~~~
make[3]: *** [src/libfabric_la-hmem.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
%`

This looks like a simple error in declaring the type of offset. I've attached my make and config log files. gcc-14 and gfortran were installed with "brew install gcc".

[make.log](https://github.com/pmodels/mpich/files/15474977/make.log)
[config.log](https://github.com/pmodels/mpich/files/15474978/config.log)

**Comment by hzhou** [comment]
Yeah, it's frustrating that `gcc` chooses the pedantic rule that `long long` is not the same type as `long` despite both being 64-bit for most systems today.  Here it is complaining the "incompatibility" between `uint64_t` and `size_t`, which I personally would avoid but libfabric folks loves to use ... :) 

Anyway, I think the solution is to patch the embedded libfabric Makefile so it do not treat this warning as error.

**Comment by wgropp** [comment]
That's a short term solution (which I'm fine with). But long long is not the same type as long (even in most systems make them 64 bits), and good code won't assume otherwise. If the code is expecting size_t to be 64 bits, then it should use uint64_t everywhere. Otherwise, it should probably only use size_t.  I agree that it should not use both.

**Comment by wgropp** [comment]
It may need `-fpermissive` and/or `-Wno-error=incompatible-pointer-types` in more recent versions of gcc.  I manually added both to modules/libfabric/Makefile and (with lots of warning messages) the compile proceeded.

**Comment by hzhou** [comment]
Just to add to the annoyance -- `uint64_t` is `unsigned long` on Linux but `unsigned long long` on Mac. So whether it warns depends on which system you are building.

**Comment by raffenet** [comment]
I submitted https://github.com/ofiwg/libfabric/pull/10096 to upstream. I'll give it a few days to see if it gets approval before cherry-picking to our embedded module. Definitely want a fix for this in 4.2.2.
