### ISSUE TITLE
libmpi dependency libs not added to mpicc

### ISSUE THREAD

**Issue by natshineman** [pmodels/mpich#7048]
When building MPICH with external dependencies, these are not being correctly added to the mpicc wrapper. 

It looks like the lines of the Makefile that source the .la file were removed in this commit: f3e092ab690dbfad6a79830540b429e0987a700d

If that was intentional, is there a different method that is supposed to be in place? In all of my builds `final_libs` ends up blank and I have unresolved symbols.

**Comment by hzhou** [comment]
The external dependencies are not needed in the wrapper if inter-library dependency is supported by the dynamic linker. `configure` is supposed to check that and set `@INTERLIB_DEPS@`.

**Comment by hzhou** [comment]
Indeed the sourcing of libtool was broken in https://github.com/pmodels/mpich/commit/f3e092ab690dbfad6a79830540b429e0987a700d. It is now fixed in https://github.com/pmodels/mpich/pull/7090
