### ISSUE TITLE
ROMIO: Crash writing to GPFS filesystem with latest 4.2.2 version

### ISSUE THREAD

**Issue by martinjotte** [pmodels/mpich#7068]
With mpich-4.2.2, all of my MPI codes now crash when performing parallel writes to GPFS file systems.

It looks like a number of variables in ad_gpfs_aggrs.c were changed to MPI_Count from int, but in two places where memory is allocated with ADIOI_Calloc, int is still being using instead of MPI_Count as the size of the variables. The first is around line 465, *count_my_req_per_proc_ptr = ADIOI_Calloc(nprocs, sizeof(int)), and the second is around line 685, count_others_req_per_proc = ADIOI_Malloc(nprocs * sizeof(int)).

Fixing these two bugs allows the code run again. I have also attached my diff that fixes this issue.

[ad_gpfs_aggrs.patch](https://github.com/user-attachments/files/16257532/ad_gpfs_aggrs.patch)

**Comment by roblatham00** [comment]
thanks for testing and the patch.   I will get this fix in and also take a look if there are any other places I made a similar mistake.
