### ISSUE TITLE
mpiexec -path flag not working (v.4.2.0)

### ISSUE THREAD

**Issue by Darptolus** [pmodels/mpich#7086]
The argument `-path`  outputs ` unrecognized argument path`

`mpiexec -path "/absolute/path/to/executable/" ./myprogram` is not working 

HYDRA build details:
    Version:                                 4.2.0

The argument `-path` is described in https://www.mpich.org/static/docs/v3.0.x/www1/mpiexec.html

**Comment by hzhou** [comment]
Hmm, the man page was broken. The `-path` option were no longer supported. You may use `mpiexec -h` to see all the options hydra accepts. You can use the `-wdir` option to set the working directory. Or you can set the path simply by setting environment variable `PATH`.

**Comment by raffenet** [comment]
`-path` is stipulated by the MPI Standard. It is supported in calls to `MPI_COMM_SPAWN` etc. Hydra should support it. It just looks like it never did for some reason.
