### ISSUE TITLE
Manpages of `MPI_Finalize` and `MPI_Init_thread` not available in v4.2.2

### ISSUE THREAD

**Issue by giordano** [pmodels/mpich#7089]
I'm not sure whether this is the right place where to report this, but here we go: man pages of `MPI_Finalize` and `MPI_Init_thread` aren't available in v4.2.2:

* https://www.mpich.org/static/docs/v4.2.2/www3/MPI_Finalize.html
* https://www.mpich.org/static/docs/v4.2.2/www3/MPI_Init_thread.html

For comparison, these pages exist for v4.0.3:

* https://www.mpich.org/static/docs/v4.0.3/www3/MPI_Finalize.html
* https://www.mpich.org/static/docs/v4.0.3/www3/MPI_Init_thread.html

**Comment by hzhou** [comment]
Hmm, looks like an regress since v4.1

**Comment by hzhou** [comment]
PR #7107 should fix the man page generations.

I also copied the missing pages to the v4.1 and v4.2 at mpich.org website docs.
