### ISSUE TITLE
mpi_f08: MPI_ISENDRECV crashes with non-contiguous send buffer

### ISSUE THREAD

**Issue by gcorbin** [pmodels/mpich#7098]
## Description
A call such as this

```
       use :: mpi_f08
       integer :: field(ny,nx)

        call MPI_Isendrecv(field(ny - 1, :), nx, MPI_INTEGER, south, 0, &
                          &field(1, :), nx, MPI_INTEGER, north, 0, &
                          &comm, req)
        call MPI_Wait(req, MPI_STATUS_IGNORE)
```
, where the  non-contiguous array slices `field(ny-1,:)` and `field(1,:)` are passed directly to `MPI_Isendrecv`,
crashes in the `MPI_Wait` with a failed assertion:

```
Assertion failed in file src/mpid/common/sched/mpidu_sched.c at line 495: (((dtp_)))->ref_count >= 0
```

I tried several other possibilities:
- Copy send data to a contiguous buffer before the call -> program works
- Copy recv data from a contiguous buffer after the call -> same crash
- Use blocking Sendrecv -> program works
- Use separate Isend and Irecv -> program works

## System info
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
mpich 4.0

## Data
Contains test program and output of configure
[reproducer.tar.gz](https://github.com/user-attachments/files/16636715/reproducer.tar.gz)

**Comment by hzhou** [comment]
Thanks for catching the bug. Hopefully, #7106 fixes it.
