### ISSUE TITLE
Backtrace not showing during hang

### ISSUE THREAD

**Issue by hkbai** [pmodels/mpich#7102]
Hello.

We are interested in showing backtrack when an application hangs merged in PR #7084, but were unsuccessful in getting the stack dump to show. Please let us know if we're doing something wrong.

### Steps to reproduce:
1. git checkout 77dfd9e083546ce0b5c9018cb7f203c5832d3886
2. ./autogen.sh
3. ./configure -C --prefix $PREFIX/install --enable-g=progress --with-ch4-max-vcis=64 --enable-thread-cs=per-vci --enable-ofi-domain --enable-izem-queue --with-zm-prefix=yes --enable-timer-type=linux86_cycle --enable-static --enable-shared --enable-timing=runtime --enable-error-messages=yes --enable-fast=all,O3,avx --enable-g=all --enable-error-checking=no --disable-opencl --enable-threads=multiple --enable-ch4-mt=runtime --with-device=ch4:ofi --with-libfabric=embedded --with-ch4-shmmods=posix,gpudirect --with-ze=/usr CC=icx CXX=icpx FC=ifort
4. make && make install
5. $PREFIX/bin/mpicc -qopenmp -o t t.c
6. MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=1 $PREFIX/bin/mpiexec ./t

> cat t.c (from PR)
```
#include <mpi.h>
#include <stdio.h>

int main()
{
  MPI_Init(0, 0);

  MPI_Comm comm = MPI_COMM_WORLD;
  int rank, size;
  MPI_Comm_rank(comm, &rank);

  int t;
  if (rank == 0)
      MPI_Recv(&t, 1, MPI_INT, 1, 0, comm, MPI_STATUS_IGNORE);

  MPI_Barrier(comm);

  MPI_Finalize();
return 0;
}
```

### Expected Output
stack dump

### Actual Output
Hangs with no stack dump

**Comment by hzhou** [comment]
You need add `--enable-g=progress` or `--enable-g=all,progress`.  `progress` is not included in `all` because it is a special purpose option.

**Comment by hkbai** [comment]
Hi, --enable-g=progress was passed during the configure step.

```
> ./mpichversion
MPICH Version:      4.3.0a1
MPICH Release date: unreleased development copy
MPICH ABI:          0:0:0
MPICH Device:       ch4:ofi
MPICH configure:    --prefix $PREFIX/install --enable-g=progress --with-ch4-max-vcis=64 --enable-thread-cs=per-vci --enable-ofi-domain --enable-izem-queue --with-zm-prefix=yes --enable-timer-type=linux86_cycle --enable-static --enable-shared --enable-timing=runtime --enable-error-messages=yes --enable-fast=all,O3,avx --enable-g=all --enable-error-checking=no --disable-opencl --enable-threads=multiple --enable-ch4-mt=runtime --with-device=ch4:ofi --with-libfabric=embedded --with-ch4-shmmods=posix,gpudirect --with-ze=/usr CC=icx CXX=icpx FC=ifort F77=ifort
MPICH CC:           icx    -DNDEBUG -DNVALGRIND -mavx -g
MPICH CXX:          icpx   -DNDEBUG -DNVALGRIND -g
MPICH F77:          ifort   -g -O3
MPICH FC:           ifort   -g -O3
MPICH features:     threadcomm
```

**Comment by hzhou** [comment]
I think the later `--enable-g=all` overwrites the earlier `--enable-g=progress`. Please try `--enable-g=all,progress` (and make sure there isn't another other `--enable-g` options.

**Comment by hkbai** [comment]
Ahh I see. Yes, passing it together as --enable-g=all,progress works. Thank you.
