### ISSUE TITLE
Manpages of most `*_c` functions not available in v4.2.2

### ISSUE THREAD

**Issue by giordano** [pmodels/mpich#7116]
Similar to #7089, the manpages of most `*_c` functions aren't available in v4.2.2, compare

* https://www.mpich.org/static/docs/v4.2.2/www3/MPI_Accumulate_c.html
* https://www.mpich.org/static/docs/v4.2.2/www3/MPI_Allgather_c.html

vs

* https://www.mpich.org/static/docs/v4.0.3/www3/MPI_Accumulate_c.html
* https://www.mpich.org/static/docs/v4.0.3/www3/MPI_Allgather_c.html

Full list of missing manpages:

* `MPI_Accumulate_c`
* `MPI_Allgather_c`
* `MPI_Allgather_init_c`
* `MPI_Allgatherv_c`
* `MPI_Allgatherv_init_c`
* `MPI_Allreduce_c`
* `MPI_Allreduce_init_c`
* `MPI_Alltoall_c`
* `MPI_Alltoall_init_c`
* `MPI_Alltoallv_c`
* `MPI_Alltoallv_init_c`
* `MPI_Alltoallw_c`
* `MPI_Alltoallw_init_c`
* `MPI_Bcast_c`
* `MPI_Bcast_init_c`
* `MPI_Bsend_c`
* `MPI_Bsend_init_c`
* `MPI_Buffer_attach_c`
* `MPI_Buffer_detach_c`
* `MPI_Exscan_c`
* `MPI_Exscan_init_c`
* `MPI_Gather_c`
* `MPI_Gather_init_c`
* `MPI_Gatherv_c`
* `MPI_Gatherv_init_c`
* `MPI_Get_accumulate_c`
* `MPI_Get_c`
* `MPI_Get_count_c`
* `MPI_Get_elements_c`
* `MPI_Iallgather_c`
* `MPI_Iallgatherv_c`
* `MPI_Iallreduce_c`
* `MPI_Ialltoall_c`
* `MPI_Ialltoallv_c`
* `MPI_Ialltoallw_c`
* `MPI_Ibcast_c`
* `MPI_Ibsend_c`
* `MPI_Iexscan_c`
* `MPI_Igather_c`
* `MPI_Igatherv_c`
* `MPI_Imrecv_c`
* `MPI_Ineighbor_allgather_c`
* `MPI_Ineighbor_allgatherv_c`
* `MPI_Ineighbor_alltoall_c`
* `MPI_Ineighbor_alltoallv_c`
* `MPI_Ineighbor_alltoallw_c`
* `MPI_Irecv_c`
* `MPI_Ireduce_c`
* `MPI_Ireduce_scatter_block_c`
* `MPI_Ireduce_scatter_c`
* `MPI_Irsend_c`
* `MPI_Iscan_c`
* `MPI_Iscatter_c`
* `MPI_Iscatterv_c`
* `MPI_Isend_c`
* `MPI_Isendrecv_c`
* `MPI_Isendrecv_replace_c`
* `MPI_Issend_c`
* `MPI_Mrecv_c`
* `MPI_Neighbor_allgather_c`
* `MPI_Neighbor_allgather_init_c`
* `MPI_Neighbor_allgatherv_c`
* `MPI_Neighbor_allgatherv_init_c`
* `MPI_Neighbor_alltoall_c`
* `MPI_Neighbor_alltoall_init_c`
* `MPI_Neighbor_alltoallv_c`
* `MPI_Neighbor_alltoallv_init_c`
* `MPI_Neighbor_alltoallw_c`
* `MPI_Neighbor_alltoallw_init_c`
* `MPI_Op_create_c`
* `MPI_Pack_c`
* `MPI_Pack_external_c`
* `MPI_Pack_external_size_c`
* `MPI_Pack_size_c`
* `MPI_Put_c`
* `MPI_Raccumulate_c`
* `MPI_Recv_c`
* `MPI_Recv_init_c`
* `MPI_Reduce_c`
* `MPI_Reduce_init_c`
* `MPI_Reduce_local_c`
* `MPI_Reduce_scatter_block_c`
* `MPI_Reduce_scatter_block_init_c`
* `MPI_Reduce_scatter_c`
* `MPI_Reduce_scatter_init_c`
* `MPI_Rget_accumulate_c`
* `MPI_Rget_c`
* `MPI_Rput_c`
* `MPI_Rsend_c`
* `MPI_Rsend_init_c`
* `MPI_Scan_c`
* `MPI_Scan_init_c`
* `MPI_Scatter_c`
* `MPI_Scatter_init_c`
* `MPI_Scatterv_c`
* `MPI_Scatterv_init_c`
* `MPI_Send_c`
* `MPI_Send_init_c`
* `MPI_Sendrecv_c`
* `MPI_Sendrecv_replace_c`
* `MPI_Ssend_c`
* `MPI_Ssend_init_c`
* `MPI_Type_contiguous_c`
* `MPI_Type_create_darray_c`
* `MPI_Type_create_hindexed_block_c`
* `MPI_Type_create_hindexed_c`
* `MPI_Type_create_hvector_c`
* `MPI_Type_create_indexed_block_c`
* `MPI_Type_create_resized_c`
* `MPI_Type_create_struct_c`
* `MPI_Type_create_subarray_c`
* `MPI_Type_get_contents_c`
* `MPI_Type_get_envelope_c`
* `MPI_Type_get_extent_c`
* `MPI_Type_get_true_extent_c`
* `MPI_Type_indexed_c`
* `MPI_Type_size_c`
* `MPI_Type_vector_c`
* `MPI_Unpack_c`
* `MPI_Unpack_external_c`
* `MPI_Win_allocate_c`
* `MPI_Win_allocate_shared_c`
* `MPI_Win_create_c`
* `MPI_Win_shared_query_c`

**Comment by giordano** [comment]
Actually, this is probably a duplicate of #6973, just fixed in #7112, but the v4.2.2 website hasn't been updated yet?

**Comment by raffenet** [comment]
> Actually, this is probably a duplicate of #6973, just fixed in #7112, but the v4.2.2 website hasn't been updated yet?

No, not yet. We will cherry-pick the fix back to the 4.2.x branch and update the website either then or at the 4.2.3 release in October.

**Comment by raffenet** [comment]
Actually on a closer look, the HTML docs need the same aliasing that was done for the manpages. Will have to do another PR to fix.

**Comment by hzhou** [comment]
> Actually on a closer look, the HTML docs need the same aliasing that was done for the manpages. Will have to do another PR to fix.

I'll work on it.
