### ISSUE TITLE
romio: Question about MPIX_Type_iov

### ISSUE THREAD

**Issue by wkliao** [pmodels/mpich#7163]
I notice the following statement from the [Change log of 4.2 release](https://github.com/pmodels/mpich/blob/main/CHANGES).
```
# Experimental datatype functions MPIX_Type_iov_len and MPIX_Type_Iov
```
My question is are they still experimental? Also, is there a configure situation that would disable use of MPIX_Type_Iov?

The reason I ask is ROMIO is using these APIs to flatten a derived datatype since MPICH version 4.1. Before then, ROMIO used its own implementation. ROMIO uses `#ifdef HAVE_MPIX_TYPE_IOV` to determine which one to use. See [flatten.c](https://github.com/pmodels/mpich/blob/cd026027b30f293faedcc813388954387d1b990c/src/mpi/romio/adio/common/flatten.c#L65)

If there is still a possibility that MPIX_Type_Iov is not enabled, then
the ROMIO's own datatype flattening codes need to be fixed, as I found a bug in it. Otherwise, ROMIO's flattening codes can be safely removed...?

**Comment by hzhou** [comment]
All `MPIX_` functions are always "experimental" :) .

When ROMIO is being build outside MPICH, then those APIs won't be available.

Please submit the issue or fix. We'll still fix the code as long as it is not deleted.

**Comment by wkliao** [comment]
So, if ROMIO is built within MPICH, then will `MPIX_` functions be always used, no matter the systems or how configure options are used?

**Comment by hzhou** [comment]
> So, if ROMIO is built within MPICH, then will `MPIX_` functions be always used, no matter the systems or how configure options are used?

That's right.

**Comment by wkliao** [comment]
In that case, I wonder how would a fix to ROMIO's own `ADIOI_Flatten()` be tested? Is any of MPICH CI testing older versions, say 4.0.3, which does not have MPIX_ functions?

**Comment by hzhou** [comment]
Yeah, it is not covered in our current CI. We could/should add a CI job to test building ROMIO with e.g. OpenMPI -- add to TODOs.

**Comment by hzhou** [comment]
For now, we rely on contributor and reviewers' manual testing ;)
