### ISSUE TITLE
GitHub: Add missing v4.2.3 release page

### ISSUE THREAD

**Issue by EwoutH** [pmodels/mpich#7170]
On https://github.com/pmodels/mpich/releases a release page is missing for the [v4.2.3](https://github.com/pmodels/mpich/releases/tag/v4.2.3) tag.

**Comment by raffenet** [comment]
Thank you for pointing it out. Just added https://github.com/pmodels/mpich/releases/tag/v4.2.3.

**Comment by EwoutH** [comment]
Thanks!
