### ISSUE TITLE
Cannot build CH4 with both OFI and UCX channels

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#7185]
Is `--with-device=ch4:ofi,ucx` supposed to work?

```console
./configure --with-device=ch4:ofi,ucx ...
make
...
src/mpid/ch4/netmod/ucx/ucx_am.c: In function ‘MPIDI_UCX_am_nbx_handler’:
src/mpid/ch4/netmod/ucx/ucx_am.c:109:17: error: implicit declaration of function ‘MPIDI_UCX_do_am_recv’; did you mean ‘MPIDIG_do_irecv’? [-Wimplicit-function-declaration]
  109 |                 MPIDI_UCX_do_am_recv(rreq);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 MPIDIG_do_irecv
```

I also trying adding `--disable-ch4-netmod-inline` to the `./configure` invocation , but that didn't make it either.
Am I missing something?

PS: I'm reviewing locally how things would work in conda-forge after https://github.com/conda-forge/mpich-feedstock/pull/100. Lools like in there the option `--with-device=ch4:ofi,ucx` works fine. But I cannot make it work in my local Fedora 40 workstation.

**Comment by raffenet** [comment]
We were also seeing this but only as a warning in our nightly build, so it slipped thru. Just submitted a fix.

**Comment by dalcinl** [comment]
I see, you are likely using an older GCC version than the one I have on my Fedora 40.
Maybe you could update you nightly builds to include `-Werror -Wimplicit-function-declaration` in `CFLAGS`?

In any case, thanks for the prompt fix. I'll try to apply your patch to the conda-forge build.
