### ISSUE TITLE
MPI_Comm_spawn not working in MPICH 4.3.0b1 (ch4:ucx)

### ISSUE THREAD

**Issue by Petter-Programs** [pmodels/mpich#7230]
Version of MPICH in use: 4.3.0b1, from git clone:
```
commit d1b04e8ae12e33f62544fae5593b4eb2d7f70d81 (HEAD -> 4.3.x, tag: v4.3.0b1, origin/4.3.x)
Merge: 942f9bb1b 0dff75865
Author: Hui Zhou <hzhou321@anl.gov>
Date:   Fri Nov 15 13:36:17 2024 -0600
```
System information:
```
Operating system/version: Red Hat Enterprise Server; Linux 5.14.x (EL9-based distribution)
Computer hardware: Intel Sapphire Rapids 8480
Network type: NDR200
```

Hi,

I am trying to use the MPI_Comm_spawn functionality of MPICH 4.3.0b1 (with UCX), but I cannot seem to get it to work. There seems to be nothing wrong with the installation; it works for other programs and the ``make check`` test suite passes. In the 4.2.1 version of MPICH, I have no issue doing spawns. In this version, it always crashes.

My reproducer code is below; one program (hello_world_mpi.c) simply prints out "Hello world!" and the other (simple_spawn.c) simply launches this program.

Here's hello_world_mpi.c:
```
#include <mpi.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    MPI_Init(&argc, &argv);

    printf("Hello world!\n");

    MPI_Finalize();

    return EXIT_SUCCESS;
}
```

And here's simple_spawn.c
```
#include <mpi.h>
#include <stdlib.h>
#include <stdio.h>

#define ROOT 0
#define MAX_PROCS 1

int main(int argc, char *argv[])
{
    MPI_Init(&argc, &argv);

    MPI_Comm inter_comm;

    int errors[MAX_PROCS];

    MPI_Comm_spawn("./hello_world_mpi", MPI_ARGV_NULL, MAX_PROCS, MPI_INFO_NULL, ROOT, MPI_COMM_WORLD, &inter_comm, errors);

    MPI_Finalize();

    return EXIT_SUCCESS;
}
```

Here's the exact error I am getting, when launched through ```mpiexec.hydra -np 1 ./simple_spawn``` (but also through Slurm's srun):
```
Abort(806450191) on node 0 (rank 0 in comm 0): Fatal error in internal_Comm_spawn: Other MPI error, error stack:
internal_Comm_spawn(101)....: MPI_Comm_spawn(command=./hello_world_mpi, argv=(nil), maxprocs=1, MPI_INFO_NULL, 0, MPI_COMM_WORLD, intercomm=0x7fff5c9c0858, array_of_errcodes=0x7fff5c9c0854) failed
MPID_Comm_spawn_multiple(88): Error in spawn call
```

With MPICH 4.2.1, I get the expected:
```Hello world!```

Let me know if there's any more information you need.

**Comment by hzhou** [comment]
I suspect this is due to UCX address exceeding `MPID_MAX_PORT_NAME`, which is currently hard-coded at `1024`. But let's try get a better error messages. Could you try this patch: https://github.com/pmodels/mpich/pull/7231 ?

**Comment by siserte** [comment]
After applying that patch #7231 I got this error when reproducing the issue:

```
Abort(605123599) on node 0 (rank 0 in comm 0): Fatal error in internal_Comm_spawn: Other MPI error, error stack:
internal_Comm_spawn(101)....: MPI_Comm_spawn(command=./hello_world_mpi, argv=(nil), maxprocs=1, MPI_INFO_NULL, 0, MPI_COMM_WORLD, intercomm=0x7ffc354db7bc, array_of_errcodes=0x7ffc354db7b8) failed
MPID_Comm_spawn_multiple(86):
MPID_Open_port(243).........: no space for port_name tag
```

**Comment by hzhou** [comment]
Thanks @siserte !  It confirms the issue was due to UCX address exceeding `MPID_MAX_PORT_NAME`. I pushed another commit in #7231 to expand the limit. Could you retry that PR?

**Comment by siserte** [comment]
@hzhou this is what I get now :(

```
Abort(201946127) on node 0 (rank 0 in comm 0): Fatal error in internal_Comm_spawn: Other MPI error, error stack:
internal_Comm_spawn(101)....: MPI_Comm_spawn(command=./hello_world_mpi, argv=(nil), maxprocs=1, MPI_INFO_NULL, 0, MPI_COMM_WORLD, intercomm=0x7fff1ee7f50c, array_of_errcodes=0x7fff1ee7f508) failed
MPID_Comm_spawn_multiple(86):

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 845963 RUNNING AT glogin2
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

```

**Comment by hzhou** [comment]
My bad. I had a typo. I just fixed it. Could you try https://github.com/pmodels/mpich/pull/7231 again?

**Comment by siserte** [comment]
Now it works! Thanks :)

**Comment by Petter-Programs** [comment]
I can confirm that the reproducer works for me as well with this new patch. Cheers!
