### ISSUE TITLE
`--without-ze` does not propagate `--disable-levelzero` to embedded hwloc's configure script

### ISSUE THREAD

**Issue by haampie** [pmodels/mpich#7233]
`--without-ze` is insufficient to disable level zero support when embedded hwloc is used.

mpich's configure script passes `--without-ze` on to hwloc, but the flag should be `--disable-levelzero`.

**Comment by raffenet** [comment]
Should be fixed in https://github.com/pmodels/mpich/pull/7191 which will be included in 4.3.0.

**Comment by haampie** [comment]
Thanks, I should have checked better.
